### ISSUE TITLE
transmat_  doesn't sum to 1.0

### ISSUE THREAD

**Issue by naghmehghanooni** [hmmlearn/hmmlearn#101]
Hello, 

I am using hmmlearn package version 0.2.1. I want to cluster some 2d sequences. I have a transition matrix which sums to 1.0 (0 for some cells of matrix, but at the end they all sum to 1.0) but when I fit the data I get a value error that the transition matrix doesn't sum to 1.0.

```python
model = hmm.GaussianHMM(n_components=70, covariance_type="full", n_iter=100, params="st", init_params="st")
```

I want to give my initial transition matrix to the model and I want the model to change it (as you can see in the above code). But the model changes it in a way that it is not sum to 1.0 anymore. 
Does anyone know what might be wrong? 
This is the Value Error. The matrix in return is not complete. But you can see it doesn't sum to 1.0 anymore as my initial transition matrix. 

```
File "build/bdist.linux-x86_64/egg/hmmlearn/base.py", line 524, in _check
ValueError: rows of transmat_ must sum to 1.0 (got [ 1.          1.          1.          1.          1.          1.          1.
  1.          1.          1.          1.          1.          1.          1.
  1.          1.          1.          1.          1.          1.          1.
  1.          1.          1.          1.          1.          1.          1.
  1.          1.          1.          1.          1.          1.          1.
  1.          1.          1.          1.          1.          1.          1.
  1.          1.          1.          1.          1.          1.          1.
  1.          1.          1.          1.          1.          1.          1.
  1.          1.          1.          1.          1.          1.          1.
  1.          1.          1.          0.66666667  0.66666667  0.66666667
```

Thanks in advance,

**Comment by superbobry** [comment]
Could you attach the transition matrix you're using?

**Comment by naghmehghanooni** [comment]
transMat = np.zeros((70, 70))
for i, j in itertools.product(range(len(transMat)), range(len(transMat))):
    if i == 0:
        if j == i or j == i+1 or j == i+10 or j == i+1+10:
            transMat[i, j] = 1.0/4.0
    elif i == 9:
        if j == i or j == i-1 or j == i+10 or j == i-1+10:
            transMat[i, j] = 1.0/4.0
    elif i == 60:
        if j == i or j == i+1 or j == i-10 or j == i+1-10:
            transMat[i, j] = 1.0/4.0
    elif i == 69:
        if j == i or j == i-1 or j == i-10 or j == i-1-10:
            transMat[i, j] = 1.0/4.0
    elif i == 1 or i == 2 or i == 3 or i == 4 or i == 5 or i == 6 or i == 7 or i == 8\
        or i == 61 or i == 62 or i == 63 or i == 64 or i == 65:
        if j == i-1 or j == i or j == i+1 or j == i+10 or j == i-1+10 or j == i+1+10\
                or j == i-10 or j == i-1-10 or j == i+1-10:
            transMat[i, j] = 1.0/6.0
    elif i == 10 or i == 20 or i == 30 or i == 40 or i == 50 or i == 60:
        if j == i or j == i+1 or j == i-10 or j == i+10 or j == i+1+10 or j == i+1-10:
            transMat[i, j] = 1.0/6.0
    elif i == 19 or i == 29 or i == 39 or i == 49 or i == 59:
        if j == i or j == i-1 or j == i-10 or j == i+10 or j == i-1+10 or j == i-1-10:
            transMat[i, j] = 1.0/6.0
    else:
        if j == i-1 or j == i or j == i+1 or j == i+10 or j == i-1+10 or j == i+1+10\
                or j == i-7 or j == i-1-10 or j == i+1-10:
            transMat[i, j] = 1.0/9.0

**Comment by superbobry** [comment]
The rows of `transMat` do not sum to 1:

```
>>> transMat.sum(axis=1)
[ 1.          1.          1.          1.          1.          1.          1.
  1.          1.          1.          1.          1.          1.          1.
  1.          1.          1.          1.          1.          1.          1.
  1.          1.          1.          1.          1.          1.          1.
  1.          1.          1.          1.          1.          1.          1.
  1.          1.          1.          1.          1.          1.          1.
  1.          1.          1.          1.          1.          1.          1.
  1.          1.          1.          1.          1.          1.          1.
  1.          1.          1.          1.          1.          1.          1.
  1.          1.          1.          0.66666667  0.66666667  0.66666667
  1.        ]
```

**Comment by naghmehghanooni** [comment]
Okay, thank you. 
But I fixed the problem and I'm sure now the rows of transMat sum to 1 and I still have the problem: 
This is the transMat: 
transMat = np.zeros((70, 70))
for i, j in itertools.product(range(len(transMat)), range(len(transMat))):
    if i == 0:
        if j == i or j == i+1 or j == i+10 or j == i+1+10:
            transMat[i, j] = 1.0/4.0
    elif i == 9:
        if j == i or j == i-1 or j == i+10 or j == i-1+10:
            transMat[i, j] = 1.0/4.0
    elif i == 60:
        if j == i or j == i+1 or j == i-10 or j == i+1-10:
            transMat[i, j] = 1.0/4.0
    elif i == 69:
        if j == i or j == i-1 or j == i-10 or j == i-1-10:
            transMat[i, j] = 1.0/4.0
    elif i == 1 or i == 2 or i == 3 or i == 4 or i == 5 or i == 6 or i == 7 or i == 8\
        or i == 61 or i == 62 or i == 63 or i == 64 or i == 65 or i == 66 or i == 67 or i == 68:
        if j == i-1 or j == i or j == i+1 or j == i+10 or j == i-10:
            transMat[i, j] = 0.17
        if j == i-1+10 or j == i+1+10 or j == i-1-10 or j == i+1-10:
            transMat[i, j] = 0.16
    elif i == 10 or i == 20 or i == 30 or i == 40 or i == 50 or i == 60:
        if j == i or j == i+1 or j == i-10 or j == i+10:
            transMat[i, j] = 0.17
        if j == i+1+10 or j == i+1-10:
            transMat[i, j] = 0.16
    elif i == 19 or i == 29 or i == 39 or i == 49 or i == 59:
        if j == i or j == i-1 or j == i-10 or j == i+10:
            transMat[i, j] = 0.17
        if j == i-1+10 or j == i-1-10:
            transMat[i, j] = 0.16
    else:
        if j == i-1 or j == i+1 or j == i+10 or j == i-1+10 or j == i+1+10\
                or j == i-7 or j == i-1-10 or j == i+1-10:
            transMat[i, j] = 0.11
        if j == i:
            transMat[i, j] = 0.12

But I get the error again: 

/usr/local/lib/python2.7/dist-packages/hmmlearn-0.2.1-py2.7-linux-x86_64.egg/hmmlearn/base.py:459: RuntimeWarning: divide by zero encountered in log
/usr/local/lib/python2.7/dist-packages/hmmlearn-0.2.1-py2.7-linux-x86_64.egg/hmmlearn/base.py:460: RuntimeWarning: divide by zero encountered in log
/usr/local/lib/python2.7/dist-packages/hmmlearn-0.2.1-py2.7-linux-x86_64.egg/hmmlearn/base.py:468: RuntimeWarning: divide by zero encountered in log
/usr/local/lib/python2.7/dist-packages/hmmlearn-0.2.1-py2.7-linux-x86_64.egg/hmmlearn/base.py:469: RuntimeWarning: divide by zero encountered in log
/usr/local/lib/python2.7/dist-packages/hmmlearn-0.2.1-py2.7-linux-x86_64.egg/hmmlearn/base.py:624: RuntimeWarning: divide by zero encountered in log
/usr/lib/python2.7/dist-packages/scipy/misc/common.py:88: RuntimeWarning: invalid value encountered in subtract
  out = log(sum(exp(a - a_max), axis=0))
Traceback (most recent call last):
  File "/home/ghanooni/PycharmProjects1/test1/conthmm.py", line 206, in <module>
    hiddenState = model.predict(arr, [len(arr)])
  File "build/bdist.linux-x86_64/egg/hmmlearn/base.py", line 334, in predict
  File "build/bdist.linux-x86_64/egg/hmmlearn/base.py", line 294, in decode
  File "build/bdist.linux-x86_64/egg/hmmlearn/hmm.py", line 165, in _check
    
  File "build/bdist.linux-x86_64/egg/hmmlearn/base.py", line 524, in _check
ValueError: rows of transmat_ must sum to 1.0 (got [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  1.  0.  0.  0.  0.  0.
  0.  0.  0.  0.  1.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.])
Exception AttributeError: "'NoneType' object has no attribute 'path'" in <function _remove at 0x7fa83f008668> ignored

**Comment by naghmehghanooni** [comment]
@superbobry do you have any idea why this is happening?

**Comment by aubreyli** [comment]
when compute the posteriors during the model fitting, if the elements in gamma have very large difference, it's possible the one is normalized to 1 and the other is normalized to 0, so no wonder
we encountered divide by ZERO warning if the start probability is 0.

For example, here are two elements in gamma

`[ -9.37793995e+02  -1.80005478e+10]`

After normalize, they became

`[  0.00000000e+00  -1.80005469e+10]`

And finally, np.exp(log_gamma) returns

`[ 1.  0.]`

Anyway, I think we should tolerate this case, let me submit a patch to see if it works on your side

**Comment by superbobry** [comment]
The patch by @aubreyli is now in master. Please update and let us know if it helped.

**Comment by vett93** [comment]
Hello,

I downloaded the latest 0.2.1 from the Master on April 20, 2016. I am having similar problems. When n_components is small, it runs fine. But when it is larger, I get the following error message:

hidden_states=mymodel.predict(arr)
  File "build/bdist.linux-x86_64/egg/hmmlearn/base.py", line 334, in predict
  File "build/bdist.linux-x86_64/egg/hmmlearn/base.py", line 294, in decode
  File "build/bdist.linux-x86_64/egg/hmmlearn/hmm.py", line 165, in _check
  File "build/bdist.linux-x86_64/egg/hmmlearn/base.py", line 524, in _check
ValueError: rows of transmat_ must sum to 1.0 (got [ 1.  1.  1.  1.  1.  1.  1.  1.  0.  1.  1.  1.  1.  1.  1.])

Let me start a new issue reporting the problem I run int.

**Comment by superbobry** [comment]
Closing the issue in favour of #110.
