### ISSUE TITLE
HMM used for Bayesian Knowledge Tracing

### ISSUE THREAD

**Issue by qintaozhang** [hmmlearn/hmmlearn#106]
Need suggestions on HMM used for BKT :)  I used multinomialHMM here

As we know BKT (Bayesian Knowledge tracing) is essentially a two-state HMM but has its specials. 

1) If we define two states as learned and not-learned. The transaction matrix is defined as :[ [ 1-forget, forget],[learn, 1-learn]]. Here comes the first special point: we have to force forget=0, meaning never be learned to not-learned or in other words, never forget

2) Suppose the observations have also two states , right or wrong, We can define our emission matrix as following [[1- slip, slip],[guess, 1-guess]]. Here comes the second special point: we empirically force guess<0.3 and slip<0.1.

My question is how to setup these limitations in HMMlearn? I know by default, all three matrix will be trained. 

Second question is how to change training starting point? I know EM method is typically local optimization, so we need to randomize starting point but I didn't find where to input those numbers. 

Thanks, Qintao

**Comment by superbobry** [comment]
Hi Qintao,

> [...] we have to force forget=0, meaning never be learned to not-learned or in other words, never forget.

This can be done by zeroing the `forget` state in the transition matrix and dropping `"t"` in `init_params`:

```python
model = hmm.MultinomialHMM(init_params="se")
model.transmat_ = [[1, 0], [0.5, 0.5]]  # The second row can be arbitrary.
```

> [...] we empirically force guess<0.3 and slip<0.1.

I'm not immediately sure how to enforce these in EM. One thing you can do is override the [`_do_mstep`](http://hmmlearn.readthedocs.org/en/latest/api.html#hmmlearn.base._BaseHMM._do_mstep) method of `MultinomialHMM` and simply clip the corresponding entries in `emissionprob_`. Note that HMMs are prone to "label switching", thus you don't really know which row is `guess` and which is `slip`. 

> Second question is how to change training starting point?

Just set the attributes manually prior to calling `fit` and omit the corresponding letters in `init_params`. See [tutorial](http://hmmlearn.readthedocs.org/en/latest/tutorial.html#building-hmm-and-generating-samples) for details.

**Comment by qintaozhang** [comment]
Thanks for your quick reply.  I just did a quick test with your suggestions.

1) the "forget" can be successfully set to 0
2) The _do_mstep override is a kind of issue actually :) If the label switch can not prevented, how can I distinguished trained results because I eventually need to know prior, Probability of learn, slip and guess. 3) init_params works fine. Thanks

I know people used Matlab to do HMM training. Though I didn't try by myself yet, I just wonder how they can solve the problem 2.

Best wishes,

Qintao

**Comment by superbobry** [comment]
> Though I didn't try by myself yet, I just wonder how they can solve the problem 2.

Usually, you need to have domain knowledge about the parameters of the model to be able to label them.  For instance, `forget > learn` or `slip > guess`. 

Sorry I can't be any more specific than that.
