### ISSUE TITLE
What are the differences between GaussianHMM and GMMHMM?

### ISSUE THREAD

**Issue by vett93** [hmmlearn/hmmlearn#111]
From the Tutorial, it states GMMHMM as HMM with Gaussian mixture emissions. What do "mixture emissions" mean?

**Comment by superbobry** [comment]
Hi, "mixture emissions" means that conditioned on the state, the observations are modeled as a sample from a finite Gaussian mixture (as opposed to a single Gaussian in `GaussianHMM`).

**Comment by vett93** [comment]
Thanks, superbobry.
