### ISSUE TITLE
Some doc links to source are broken

### ISSUE THREAD

**Issue by anntzer** [hmmlearn/hmmlearn#112]
e.g. the `[source]` link at http://hmmlearn.readthedocs.org/en/latest/api.html#hmmlearn.hmm.GMMHMM.decode (which targets https://github.com/checkouts/latest/doc/build/bdist.linux-x86_64/egg/hmmlearn/base.py#L262-L315).

**Comment by superbobry** [comment]
Thanks, fixed in b8391fc7f6b77e78fca06dcade8db4fdd0ed56ca.
