### ISSUE TITLE
Testing/Verification for fit()?

### ISSUE THREAD

**Issue by vett93** [hmmlearn/hmmlearn#114]
Can someone please let me know how it was tested and verified that the fit() function works correctly? I input a sequence of time series data to the GaussianHMM model and use the fit() function to obtain the parameters. The results don't look right to me. 

I am going to change the initialization and see if it will improve the results. But it would be good if I can use the same test to verify if it works correctly

**Comment by superbobry** [comment]
Hi, 

yes we do have sample/refit tests, e.g. [`test_gaussian_hmm.py`](https://github.com/hmmlearn/hmmlearn/blob/master/hmmlearn/tests/test_gaussian_hmm.py#L133). I didn't have a chance to look into #110, so it is possible that with a large number of states we run into underflow somewhere.

**Comment by vett93** [comment]
Thanks for the comments, superbobry. 15 Markovian states are not really large numbers. Are you the only one who maintains the code? Thank you.

David

**Comment by superbobry** [comment]
> Are you the only one who maintains the code? 

Yes, mostly, but I do get PRs once in a while :)
