### ISSUE TITLE
no module named hmmlearn

### ISSUE THREAD

**Issue by chitrang6** [hmmlearn/hmmlearn#115]
I have installed hmmlearn on my Mac OS X 10.11using the below command. 

 sudo pip install -U --user hmmlearn

**Comment by superbobry** [comment]
It is possible that `pip` and `python` actually use different interpreters. Try this:

```
$ python -m pip install --user hmmlearn
$ python -c "import hmmlearn"
```

Not that you don't need `sudo` in case of `--user` installs.

**Comment by chitrang6** [comment]
I am still getting the same error.

**Comment by chitrang6** [comment]
Ok I got it working the error was in the PyCharm.
