### ISSUE TITLE
Multinomial HMM -- Custom emission frequency 

### ISSUE THREAD

**Issue by chitrang6** [hmmlearn/hmmlearn#116]
Let's say using the Multinomial HMM class, I am designing a HMM model. I am providing initial probabilities, transition probabilities and the emission probability. Using these model, I am generating a hidden sequence(Z) and the observation sequence(X). Let's say I am giving a observation sequence to this model and I am getting some hidden sequence using the Viterbi Algorithm. How to check the efficiency of this model?

Thank you

**Comment by superbobry** [comment]
Evaluating unsupervised models is tricky and, unfortunately, I'm not aware of an efficiency criteria for Viterbi predictions. 

I mostly work with posterior state probabilities, because they can be used to estimate and control FDR for model predictions (see reference in #25). The method is only applicable if you have a null (binary) hypothesis. E.g. if the states are `{SIGNAL, NOISE}` then the reasonable null hypothesis might be "the true state is NOISE".

**Comment by chitrang6** [comment]
Thank you for your reply. Is there any way to classify the accelerometer gesture data using your multinomial HMM data? If not can you suggest any other open source library to achieve this?

You said you don't have an idea for the unsupervised model. Is there any way to do this for the supervised model?

Thank you,
Chitrang Talaviya

**Comment by superbobry** [comment]
>  Is there any way to classify the accelerometer gesture data using your multinomial HMM data?

I reckon the accelerometer data is continuous, so `GaussianHMM` or `GMMHMM` might be better choices. Anyway, I've never encountered the problem myself, but this seems to be explored in a number of publications ([Witowski et al., 2014] [1]; Nickel and Busch, 2013 [2]).

[1]: http://www.ncbi.nlm.nih.gov/pubmed/25464514
[2]: https://www.fbi.h-da.de/fileadmin/gruppen/FG-IT-Sicherheit/Publikationen/2011/2011_10_Nickel_ICCST.pdf

> Is there any way to do this for the supervised model?

In the supervised setting you're basically doing multilabel classification, so all of the classification metrics are applicable. See e.g. [`sklearn.metrics`](http://scikit-learn.org/stable/modules/model_evaluation.html#classification-metrics).

**Comment by gallupliu** [comment]
Is there any way to classify the accelerometer gesture data using your multinomial HMM data?my data  as follow：
[ 0.04333398 -0.04045627 -0.12045372]
[-0.00642086 -0.2774157  -0.02673739]
[-0.05069528 -0.23678512 -0.08378408]
[-0.16470499 -0.24370246 -0.29795249]
[-0.11216438 -0.07401174  0.06413633]
[-0.04039333 -0.08456876 -0.11298023]
[ 0.11466839 -0.12889097  0.21347354]
[ 0.12612788  0.32214285  0.21465836]
[ 0.73886406  1.13910069  2.30146036]
[ 1.8508436   7.12657781  3.64370733]
[  2.39546209  16.00722001   2.11027302]
[ 4.09336102  9.67173482 -0.86354049]
[ 10.55496476  -7.81579242  -0.40574208]
[  5.82115102 -13.21035562  -2.4879339 ]
[ 1.26957164 -9.00915651 -2.41820546]
[ 2.25561631 -9.04392809 -0.34458632]
[  6.94720297 -14.99570346  -1.72139258]
[ 0.04333398 -0.04045627 -0.12045372]
[-0.00642086 -0.2774157  -0.02673739]
[-0.05069528 -0.23678512 -0.08378408]
[-0.16470499 -0.24370246 -0.29795249]
[-0.11216438 -0.07401174  0.06413633]
[-0.04039333 -0.08456876 -0.11298023]
[ 0.11466839 -0.12889097  0.21347354]
[ 0.12612788  0.32214285  0.21465836]
[ 0.73886406  1.13910069  2.30146036]
[ 1.8508436   7.12657781  3.64370733]
[  2.39546209  16.00722001   2.11027302]
[ 4.09336102  9.67173482 -0.86354049]
[ 10.55496476  -7.81579242  -0.40574208]
[  5.82115102 -13.21035562  -2.4879339 ]
[ 1.26957164 -9.00915651 -2.41820546]
[ 2.25561631 -9.04392809 -0.34458632]
[  6.94720297 -14.99570346  -1.72139258]
[ 6.09528983 -8.79887837 -0.57123609]
[ 1.23158425  5.98897545  0.40297526]
[  1.00576292  10.18543792   2.48186499]
[ 0.14502997  9.46914688  1.92214392]
[ 0.6641174   3.45990895  2.07224025]
[ 0.58340159  1.41640726  1.11847123]
[ 0.32608096  0.37314466  0.81462637]
[ 0.13808211  0.68228845  0.24617202]
[ 0.01525991  0.05679353 -0.38585175]
The data seems to be discrete（Each columns corresponds to X Y Z）, so I don't know which type（GaussianHMM 、 GMMHMM  or MultinomialHMM） should use？ Thank you
