### ISSUE TITLE
Custom Univariate Gaussian Emission

### ISSUE THREAD

**Issue by trinberg** [hmmlearn/hmmlearn#117]
Thanks so much for your package. I'm using the GaussianHMM function and I was wondering if there is a simple way to change the emission distribution to be a univariate Gaussian (1D), rather than a 2-dimensional distribution. In my case, I am studying a process as a function of time that I'm trying to classify into various states that are sampled from different univariate gaussians. Given the number of states in the system, I'd still like the algorithm to infer the best parameters for those univariate distributions.

**Comment by superbobry** [comment]
> [..] I was wondering if there is a simple way to change the emission distribution to be a univariate Gaussian (1D), rather than a 2-dimensional distribution.

Yep, set `covariance_type` to `"diag"` and make sure `X` has shape `(n_samples, 1)`.

**Comment by trinberg** [comment]
Thanks! I probably should have figured that out, but I think I was getting the x shape wrong.
