### ISSUE TITLE
with same input data, why are outputs not identical?

### ISSUE THREAD

**Issue by vett93** [hmmlearn/hmmlearn#119]
Hi,
I am running the GuassianHMM fit function multiple times, and use the same input data each time. The outputs are not identical. 

I want to estimate the mean/SD of 5 Gaussian distributions, as well as the transition probability matrix, of the HMM. With the same input data, the output varies somewhat. For example, the 0th hidden state of one run may be close to the 2nd hidden state of another run. 

Shouldn't the outputs be identical for each run if I use the same input data? Thank you.

David

**Comment by elitcenk** [comment]
Hi David,
GaussianHMM create model with random. İf you add 'random_state' paramater to init function, your output identical.

**Comment by vett93** [comment]
Thanks, Elitcenk. Let me close the issue then.
