### ISSUE TITLE
How to run fit() with various initializations?

### ISSUE THREAD

**Issue by vett93** [hmmlearn/hmmlearn#120]
This issue is different from #119. Is there an example showing how to run fit() with various initializations?

I am trying to validate the results of fit() by the following method. I create a Markov Chain with 5 known states. Each state emits with Gaussian distribution with known mean and standard deviation. The state transition probabilities are also known. I then generate a sequence of random numbers based on this Markov Modulated Gaussian distribution. 

I want to use GaussianHMM.fit() to estimate the parameters of this sequence of random numbers and see if they are close to the original parameters. 

I have conducted such test 10 times. The results are 9 out of 10 runs are close enough. The last run has distinguishably different parameters. 

So I want to change the initialization of the 10th run and see if the result will improve. Thank you.

**Comment by superbobry** [comment]
Yes, this is possible via `init_params`. See the answer in #62 and "Fixing parameters" section in the [tutorial](http://hmmlearn.readthedocs.io/en/latest/tutorial.html#building-hmm-and-generating-samples).
