### ISSUE TITLE
examples/plot_hmm_stock_analysis?

### ISSUE THREAD

**Issue by gliptak** [hmmlearn/hmmlearn#122]
Would there be a paper you could point me to allowing to put in context the stock data example? Thanks

http://hmmlearn.readthedocs.io/en/latest/auto_examples/plot_hmm_stock_analysis.html

**Comment by superbobry** [comment]
Unfortunately, I don't have a reference for this. I think the example might've originated as a simple demonstration of HMMs for time-series data, but I'm not sure.

@lucidfrontier45 I've looked through `scikit-learn` log and it seems [you are the original author](https://github.com/scikit-learn/scikit-learn/commit/dac2e4fe1bb2bc2832a251a67c2d5de997518e3f) of this example. Could you please comment?

**Comment by anntzer** [comment]
The example has been removed in #303 due to the closure of both Yahoo and Google APIs for fetching the data; lack of explanations for the example is probably a good reason too...
