### ISSUE TITLE
Supervised Learning: why not?

### ISSUE THREAD

**Issue by pbrusco** [hmmlearn/hmmlearn#123]
Hi, first of all, thanks for the work on the project, it's very usefull to have an HMM framework in python. 

Regarding the disclaimer on the landing page: "For supervised learning learning of HMMs and similar models see seqlearn." 

What do you think about using the framework for a classification problem with labeled data?. The way I think it could work is by building one HMM per class (trained with the specific class data) and then, when data has to be predicted, compare the scores of each model and select the best. 

For example, in a two class classification problem, something like this: (didn't test it)

```python

from hmmlearn import hmm
import numpy as np

class CustomHMM:
  def __init__(self):
      def build_hmm():
          model = hmm.GMMHMM(n_components=3, n_mix=3, covariance_type="diag", init_params="t")
          model.transmat_ = np.array([[0.5, 0.5, 0.0],
                                      [0.0, 0.5, 0.5],
                                      [0.0, 0.0, 1.0]])
          return model

      self.hmm_0 = build_hmm()
      self.hmm_1 = build_hmm()

  def fit(self, X_train, y_train):
      # X_train shape(n_instances, n_samples)
      labels = set(y_train)
      if len(labels) != 2:
          raise Exception("y_train doesn't contain 2 classes")
      X_0 = X_train[y_train == 0, :]
      X_1 = X_train[y_train == 1, :]

      self.hmm_0.fit(X_0)
      self.hmm_1.fit(X_1)

  def predict(self, X_test):
      res = []
      for x in X_test:
           res.append(0 if self.hmm_0.score(x) > self.hmm_1.score(x) else 1)
      return np.array(res)
```
Then, you can use it:

```python
clf = CustomHMM()
clf.fit(X_train, y_train)
clf.predict(X_test)

**Comment by superbobry** [comment]
Hi, glad you find `hmmlearn` is useful!

> What do you think about using the framework for a classification problem with labeled data?

I think you can do this, if you agree with the assumptions: `y` are iid, `x` are `GMMHMM`.

* `seqlearn` allows you to model the data by a two-state hidden Markov model with some emission distribution. The crucial assumption `seqlearn` does is that the sequence of states the model goes through while generating `X` is known (`y`).
* `CustomHMM` on the other hand, does not assume the Markovian dependence for `y` and does label-specific density estimation instead. This scenario corresponds to supervised learning of a mixture with equal prior component probabilities and HMMs as component distributions.

**Comment by pbrusco** [comment]
Thanks for the reply! One last thing I would like to calculate is the probability of a sample to belong to each class.. that is, `p(x|C0)` and that should be equal to `1 - p(x|C1)`

I think this can be calculated by this equation:
```
p(x|C0) = p(x|Hmm0) / (p(x|Hmm0) + p(x|Hmm1))
p(x|C1) = p(x|Hmm1) / (p(x|Hmm0) + p(x|Hmm1))
```
Assuming two HMMs trained for class 0 and 1.

And if I didn't get it wrong, what the `hmm0.score([x])` function does is to return the `log(p(x|Hmm0))`. 

After some math to avoid overflow errors:

```python
def prob_sample_class_0(x, hmm0, hmm1):
    lp0 = hmm0.score([x])
    lp1 = hmm1.score([x])
    return (math.exp(lp1 - lp0) + 1) ** (-1)
```

Have you tried something like that? 

Thanks again

**Comment by superbobry** [comment]
> And if I didn't get it wrong, what the hmm0.score([x]) function does is to return the log(p(x|Hmm0)).

Yes, it returns log-likelihood of the data under the model.

> Have you tried something like that?

I haven't but your approach makes sense.

There is one thing you could do to make `prob_sample_class_0` more stable --- drop the -1.

```python
from scipy.misc import logsumexp


def prob_sample_class_0(x, hmm0, hmm1):
    lp0 = hmm0.score([x])
    lp1 = hmm1.score([x])
    total = logsumexp([lp0, lp1])
    return np.exp(lp0 - total)
```

**Comment by pbrusco** [comment]
Perfect! Thanks very much!

**Comment by pikulsomesh** [comment]
Hi, 
Can you please state what should be the sample input for X_train, Y_train and X_test?
Please give examples.
Somesh.
