### ISSUE TITLE
Fitting multiple sequences with MultinomialHMM

### ISSUE THREAD

**Issue by Orkat** [hmmlearn/hmmlearn#124]
Hi,

This simple example

```
X1 = [0, 2, 1, 1, 2, 0]
X2 = [0, 5, 2]
X = np.concatenate([X1, X2])
lengths = [len(X1), len(X2)]
hmm.MultinomialHMM(n_components=3).fit(X, lengths)
```

 returns an error :

```
  File "__main__.py", line 38, in test_multinomial_hmm
    hmm.MultinomialHMM(n_components=3).fit(X, lengths)
  File "lib/python3.5/site-packages/hmmlearn/base.py", line 421, in fit
    self._init(X, lengths=lengths)
  File "lib/python3.5/site-packages/hmmlearn/hmm.py", line 377, in _init
    raise ValueError("expected a sample from "
ValueError: expected a sample from a Multinomial distribution.
```

looking at hmm.py line 377, we get :
```
    def _init(self, X, lengths=None):
        if not self._check_input_symbols(X):
            raise ValueError("expected a sample from "
                             "a Multinomial distribution.")
```

originating from :
```
    def _check_input_symbols(self, X):
        """Check if ``X`` is a sample from a Multinomial distribution.
        That is ``X`` should be an array of non-negative integers from
        range ``[min(X), max(X)]``, such that each integer from the range
        occurs in ``X`` at least once.
        For example ``[0, 0, 2, 1, 3, 1, 1]`` is a valid sample from a
        Multinomial distribution, while ``[0, 0, 3, 5, 10]`` is not.
        """
```

Why must every integer in the range [min(X), max(X)] occur in the sequence?

Furthermore, if we change the value of X2 to :
`X2 = [0, 3, 2]`

self._check_input_symbols returns true ( even though the value '1' does not occur in the sequence ), and we get an entirely different error :

```
  File "__main__.py", line 38, in test_multinomial_hmm
    hmm.MultinomialHMM(n_components=3).fit(X, lengths)
  File "lib/python3.5/site-packages/hmmlearn/base.py", line 421, in fit
    self._init(X, lengths=lengths)
  File "lib/python3.5/site-packages/hmmlearn/hmm.py", line 386, in _init
    for i, j in iter_from_X_lengths(X, lengths):
  File "lib/python3.5/site-packages/hmmlearn/utils.py", line 59, in iter_from_X_lengths
    .format(n_samples, lengths))
ValueError: more than 1 samples in lengths array [6, 3]
```

Finally, if the value of X2 is changed to:
`X2 = [0, 1, 2]`

We get the same error as above, even though this sequence should be 'valid'

**Comment by superbobry** [comment]
> Why must every integer in the range [min(X), max(X)] occur in the sequence?

The requirement directly follows from the definition of the Multinomial distribution (see Support on [Wikipedia](https://en.wikipedia.org/wiki/Multinomial_distribution)). If your sample does not conform to this requirement, you could use [`LabelEncoder`](http://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.LabelEncoder.html) from scikit-learn to manually project it in the required range:

```python
>>> from sklearn.preprocessing import LabelEncoder
>>> LabelEncoder().fit_transform([0, 1, 5, 10])
array([0, 1, 2, 3])
```

> We get the same error as above, even though this sequence should be 'valid' [...]

`X` has to be 2D, where the first axis corresponds to samples. This is not mentioned in the docs, sorry. I've created a relevant issue.

```python
>>> hmm.MultinomialHMM(n_components=3).fit(np.atleast_2d(X).T, lengths)
MultinomialHMM(algorithm='viterbi', init_params='ste', n_components=3,
        n_iter=10, params='ste',
        random_state=<mtrand.RandomState object at 0x107be7b88>,
        startprob_prior=1.0, tol=0.01, transmat_prior=1.0, verbose=False)
```

**Comment by Orkat** [comment]
Thanks! That works.

I had misunderstood the error message as implying that both sequences X1 and X2 had to occupy all values in [min(X1), max(X1)] and [min(X2), max(X2)] respectively.

Requiring the concatenated vector X to occupy all values in [min(X), max(X)] does indeed make a lot more sense. Thanks for the tip about [LabelEncoder](http://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.LabelEncoder.html)!

**Comment by mfilej** [comment]
I just came here to ask more or less the same question. Thank you the timely tip! `np.atleast_2d` seems to work well indeed.

Would you say this is also the suggested way to call `fit()` if the input data comes from a generator?

```python
seq = np.fromiter(generator, np.int64)                                                                                        
seq = np.atleast_2d(seq).T
model.fit(seq)
```

(I apologise if this is more about numpy than hmmlearn, but I'm curious to hear your opinion on this.)

**Comment by superbobry** [comment]
> Would you say this is also the suggested way to call fit() if the input data comes from a generator?

There is no API for that at the moment. `fit` can (and usually does) traverse the input multiple times, so it can't accept a generator. Casting a generator to an array using `np.fromiter` looks good to me.

**Comment by suraj2495** [comment]
Hi! Just to clarify, if I am passing multiple sequences using a MultinomialHMM to the fit method as a list with the lengths, I have to transform the ENTIRE list using sklearn's LabelEncoder, or transform each sequence first, and then pass the entire list?
