### ISSUE TITLE
Null Emission

### ISSUE THREAD

**Issue by seribuan** [hmmlearn/hmmlearn#126]
Hello,

I need to implement null emission as implemented in 
http://nl.ijs.si/janes/wp-content/uploads/2014/09/choudhuryothers07.pdf

I also see that it is possible to use custom emission here:
http://hmmlearn.readthedocs.io/en/stable/tutorial.html#implementing-hmms-with-custom-emission-probabilities

Please give me a hint which part of the code that needs to be overriden, I am still new with HMM.

Thanks!

**Comment by superbobry** [comment]
I've skimmed through the paper and it describes an supervised model for word variations (i.e. considering insertions/deletions/substitutions). `hmmlearn` currently does not target supervised learning, so I am not sure it can be applied for your problem.

Could you explain what kind of model you need?

**Comment by seribuan** [comment]
It seems I need to have a model that could emit nothing when transitioning.
For example for the word 'book', it is a left to right HMM that consist of 4 state with order:
b->o->o->k
If I give the word 'bk' as the parameter to the function decode(),
then it should find that:
the first state emits b
the second state emits nothing
the third state emits nothing
and the last state emits k

I am not sure what is the difference between supervised and unsupervised though.

**Comment by superbobry** [comment]
> I am not sure what is the difference between supervised and unsupervised though.

The difference is that in the supervised scenario you know the true sequence of hidden states for training. E.g. for book and the 'bk' input the sequence might be MATCH, DEL, DEL, MATCH.

> It seems I need to have a model that could emit nothing when transitioning.

The model you're describing sounds like a [profile HMM](http://www.biology.wustl.edu/gcg/hmmanalysis.html) for sequence alignment. It requires labeled data, so `hmmlearn` is not applicable here. Take a look at [`pomegranate`](https://github.com/jmschrei/pomegranate) it explains profile HMMs in the "Hidden Markov Models" section of the README.

**Comment by seribuan** [comment]
Thanks, will look into it!
