### ISSUE TITLE
GaussianHMM 、 GMMHMM or MultinomialHMM should use？ 

### ISSUE THREAD

**Issue by gallupliu** [hmmlearn/hmmlearn#127]
Is there any way to classify the accelerometer gesture data using your multinomial HMM data?my data as follow：
[ 0.04333398 -0.04045627 -0.12045372]
[-0.00642086 -0.2774157 -0.02673739]
[-0.05069528 -0.23678512 -0.08378408]
[-0.16470499 -0.24370246 -0.29795249]
[-0.11216438 -0.07401174 0.06413633]
[-0.04039333 -0.08456876 -0.11298023]
[ 0.11466839 -0.12889097 0.21347354]
[ 0.12612788 0.32214285 0.21465836]
[ 0.73886406 1.13910069 2.30146036]
[ 1.8508436 7.12657781 3.64370733]
[ 2.39546209 16.00722001 2.11027302]
[ 4.09336102 9.67173482 -0.86354049]
[ 10.55496476 -7.81579242 -0.40574208]
[ 5.82115102 -13.21035562 -2.4879339 ]
[ 1.26957164 -9.00915651 -2.41820546]
[ 2.25561631 -9.04392809 -0.34458632]
[ 6.94720297 -14.99570346 -1.72139258]
[ 0.04333398 -0.04045627 -0.12045372]
[-0.00642086 -0.2774157 -0.02673739]
[-0.05069528 -0.23678512 -0.08378408]
[-0.16470499 -0.24370246 -0.29795249]
[-0.11216438 -0.07401174 0.06413633]
[-0.04039333 -0.08456876 -0.11298023]
[ 0.11466839 -0.12889097 0.21347354]
[ 0.12612788 0.32214285 0.21465836]
[ 0.73886406 1.13910069 2.30146036]
[ 1.8508436 7.12657781 3.64370733]
[ 2.39546209 16.00722001 2.11027302]
[ 4.09336102 9.67173482 -0.86354049]
[ 10.55496476 -7.81579242 -0.40574208]
[ 5.82115102 -13.21035562 -2.4879339 ]
[ 1.26957164 -9.00915651 -2.41820546]
[ 2.25561631 -9.04392809 -0.34458632]
[ 6.94720297 -14.99570346 -1.72139258]
[ 6.09528983 -8.79887837 -0.57123609]
[ 1.23158425 5.98897545 0.40297526]
[ 1.00576292 10.18543792 2.48186499]
[ 0.14502997 9.46914688 1.92214392]
[ 0.6641174 3.45990895 2.07224025]
[ 0.58340159 1.41640726 1.11847123]
[ 0.32608096 0.37314466 0.81462637]
[ 0.13808211 0.68228845 0.24617202]
[ 0.01525991 0.05679353 -0.38585175]
The data seems to be discrete（Each columns corresponds to X Y Z）, so I don't know which type（GaussianHMM 、 GMMHMM or MultinomialHMM） should use？ Thank you

**Comment by superbobry** [comment]
The data is continuous, so the choice is between `GaussianHMM` and `GMMHMM`. Unfortunately, I'm not familiar with gesture recognition, so I can't give a more specific advice here.

**Comment by gallupliu** [comment]
Yes ，I really want to do this, I want to get the parameters, the parameters to the forward algorithm, and then run on Android via JNI in C++ ， Do you have any tips？Thanks！

**Comment by chitrang6** [comment]
Hello This link may be helpful to you. I was trying to do same thing using Hidden Markov model for Gesture recognition using the hmmlearn python library. But as I was having some other stuff at school, O was not able to complete. I will also share one PDF for this approach. 

http://teyvoniathomas.com/index.php/projects/79-gest-recog-hmm-imu.html

**Comment by chitrang6** [comment]
http://nealsun.com/?works=gesture-recognition-using-hidden-markov-models

**Comment by gallupliu** [comment]
Thank you, I found that you later use the MATLAB to achieve, can you share the code？

**Comment by chitrang6** [comment]
Actually I am haven't implemented this thing yet. I was suppose to implement this. I have started working on it using the hmmlearn python library which is developed by superbobry. But there was a limitation in this python HMM libraray. We need some modification in this python library to have that feature.

**Comment by superbobry** [comment]
> But there was a limitation in this python HMM libraray. We need some modification in this python library to have that feature.

Could you elaborate a bit on the limitations you've encountered?

**Comment by anntzer** [comment]
The issue tracker is not the place to learn about HMMs, there are better resources elsewhere.
