### ISSUE TITLE
Fitting multiple time series

### ISSUE THREAD

**Issue by hedgy123** [hmmlearn/hmmlearn#128]
Hi,

   I have a bunch of time series obtained from approximately 100 sensors (all measuring different quantities but for the same process).  Can the GaussianHMM handle this case or is it limited to univariate time series, like in the Yahoo stock example?  

   You did say in the documentation that there is a way to input "multiple sequences" into the code by concatenating them into a single array, but I wasn't sure if by multiple sequences you meant multiple time series, since in the example the two 1D sequences (X1 and X2) are of different length.   Any insight would be appreciated.

**Comment by superbobry** [comment]
Hello, `GaussianHMM` can handle multiple sequences of any (but same) dimension. 

Here's an example:

```python
>>> import numpy as np
>>> from hmmlearn import hmm
>>> X1 = np.random.random((10, 2))  # 2-D
>>> X2 = np.random.random((5, 2))   # must have the same ndim as X1.
>>> X = np.concatenate([X1, X2])
>>> lengths = np.array([len(X1), len(X2)])
>>> hmm.GaussianHMM(n_components=2).fit(X, lenghts)
GaussianHMM(algorithm='viterbi', covariance_type='diag', covars_prior=0.01,
      covars_weight=1, init_params='stmc', means_prior=0, means_weight=0,
      min_covar=0.001, n_components=2, n_iter=10, params='stmc',
      random_state=None, startprob_prior=1.0, tol=0.01, transmat_prior=1.0,
      verbose=False)
```

Hope this helps.

**Comment by Borreguin** [comment]
Hello, 
Thanks for your explanation, I was doing similar as you explain. However when I fit my model, I have some warning messages like:

> DeprecationWarning: Function log_multivariate_normal_density is deprecated; The function log_multivariate_normal_density is deprecated in 0.18 and will be removed in 0.20. warnings.warn(msg, category=DeprecationWarning)

 What I could do in order to solve this issue?

Best,
Roberto

**Comment by eshouppe** [comment]
In the BaseHMM class, the observation data is described as `X : array-like, shape (n_samples, n_features)`. I assume that means a vector of observations are allowed at each step in time.  However this seems in conflict with the multiple sequence example used in your answer above. In the below code snippet I used your example but made the sequences of equal lengths. This model yields a hidden state sequence of length 20.
```
>>> import numpy as np
>>> from hmmlearn import hmm
>>> X1 = np.random.random((10,1))
>>> X2 = np.random.random((10,1))
>>> X = np.concatenate([X1,X2])
>>> lengthsX = np.array([len(X1), len(X2)])
>>> modelX = hmm.GaussianHMM(n_components=2).fit(X, lengthsX)
>>> modelX.predict(X, lengthsX)
array([0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0])
```
But if instead I concatenate along the other axis so there is an observation vector at each time step, the model yields a hidden state sequence of length 10.
```
>>> Y = np.concatenate([X1,X2], axis=1)
>>> lengthsY = [10]
>>> modelY = hmm.GaussianHMM(n_components=2).fit(Y, lengthsY)
>>> modelY.predict(Y, lengthsY)
array([0, 1, 0, 0, 0, 1, 1, 0, 0, 0])
```
So two questions. 
A) If the API expects X to be shape `(n_samples, n_features)`, why does your go-to example stack features along the vertical axis?
B) What purpose does the `lengths` parameter serve if it does not delineate the multiple sequences? I assume that if it did, the above two examples would yield the exact decoded hidden state sequence.

**Comment by svdc** [comment]
@eshouppe 
A) `n_samples` is the total amount of (possibly unrelated) observations -- it is not a single time-series per se. He stacked two time-series vertically, with length 10 and 5 respectively, so `n_samples` is 15.
B) It does have that purpose. See [base.py](https://github.com/hmmlearn/hmmlearn/blob/master/hmmlearn/base.py) and the definition of `fit`, as well as [utils.py](https://github.com/hmmlearn/hmmlearn/blob/master/hmmlearn/utils.py) and the definition of `iter_from_X_lengths`.

**Comment by mhrvth** [comment]
@olive1618 

Honestly, I don't get it either. What's the difference between a sequence and a feature? If he has data from multiple sensors, shouldn't they be features? The measurement time series even have the same lengths. Yet they're stacked as sequences in the example.

**Comment by anntzer** [comment]
Thanks @svdc for providing an answer here.
