### ISSUE TITLE
Cannot import name 'hmm'

### ISSUE THREAD

**Issue by epratheeban** [hmmlearn/hmmlearn#129]
It works fine with my Ipyhton Notebook. But when I try to run from terminal. It says` cannot import name hmm` ? 

Do I have any installation problem ?

**Comment by superbobry** [comment]
This can be a result of using a different version of Python for running IPython Notebook and in the terminal. What OS are you using?

**Comment by epratheeban** [comment]
Sorry I made a lame mistake in installation. It is working now .

Thanks
