### ISSUE TITLE
After using gmmhmm or gaussian, how to get its emission？

### ISSUE THREAD

**Issue by gallupliu** [hmmlearn/hmmlearn#130]
After using gmmhmm or gaussian, how to get its emission？
GMMHMM 
monitor_	(ConvergenceMonitor) Monitor object used to check the convergence of EM.
startprob_	(array, shape (n_components, )) Initial state occupation distribution.
transmat_	(array, shape (n_components, n_components)) Matrix of transition probabilities between states.
gmms_	(list of GMM objects, length n_components) GMM emission distributions for each state.
Gaussain：
n_features	(int) Dimensionality of the Gaussian emissions.
monitor_	(ConvergenceMonitor) Monitor object used to check the convergence of EM.
transmat_	(array, shape (n_components, n_components)) Matrix of transition probabilities between states.
startprob_	(array, shape (n_components, )) Initial state occupation distribution.
means_	(array, shape (n_components, n_features)) Mean parameters for each state.
covars_	(array) Covariance parameters for each state. The shape depends on covariance_type:: (n_

**Comment by superbobry** [comment]
Hi, could you clarify what do you mean by emissions? The hidden states or a random sample from the model?

**Comment by gallupliu** [comment]
Thank you for your reply. I mean that hidden states！

**Comment by superbobry** [comment]
You need to call the [`predict`](http://hmmlearn.readthedocs.io/en/latest/api.html#hmmlearn.base._BaseHMM.predict) method on a fitted model.

**Comment by gallupliu** [comment]
I need transmat and emassion with forward algorithm to loglike in C++ ， Do you have any tips？

**Comment by gallupliu** [comment]
I get this error when using MultinomialHMM:  "expected a sample from a Multinomial distribution". my data format as fellow:
[[-1.  1.  1. ...,  1. -3.  1.]
 [-2.  1. -1. ..., -1. -1. -2.]
 [-1. -1. -1. ..., -2. -1. -1.]
 ..., 
 [ 1.  1. -2. ..., -2. -2. -2.]
 [-1. -3. -3. ..., -2. -4. -2.]
 [-2. -2. -3. ...,  2.  5.  2.]]

it is n x 75 ，n represents a sequence of numbers ，75 represents a size of sequence

**Comment by superbobry** [comment]
> I need transmat and emassion with forward algorithm to loglike in C++

Do you mead you need to write the algorithm from scratch in C++ or you need to pass the parameters estimated in Python to C++?

> I get this error when using MultinomialHMM: "expected a sample from a Multinomial distribution". 

See issue #74.

**Comment by gallupliu** [comment]
Yes ，I really want to do this, I want to get the parameters, and then run on Android via JNI in C++ ， Do you have any tips？Thanks！

**Comment by superbobry** [comment]
Well, HMMs aren't hard to implement, so I guess it might be easier to do training in C++ as well.

**Comment by gallupliu** [comment]
Thanks ，I  have a try
