### ISSUE TITLE
Online documentation

### ISSUE THREAD

**Issue by jwkvam** [hmmlearn/hmmlearn#14]
Unless I missed it, would be nice not needing to build the docs myself to view them.

**Comment by superbobry** [comment]
You haven't, `hmmlearn` doesn't currently have online docs, but I'm working on making them available.

**Comment by superbobry** [comment]
I've uploaded the docs to GH pages: http://hmmlearn.github.io/hmmlearn. The are far from perfect at the moment, but I'm planning to improve them.

**Comment by jwkvam** [comment]
That's great, thanks!
