### ISSUE TITLE
Is there any simple way to build a model if both the observation sequence list and the hidden state sequence list are given?

### ISSUE THREAD

**Issue by songjun54cm** [hmmlearn/hmmlearn#142]
Given the observation sequence list as :
X = [ [x11, x12, x13, ...],
         [x21, x22, x23, ...].
         ......]
and the corresponding hidden state sequence list as :
S = [ [s11, s12, s13, ...],
         [s21, s22, s23, ...],
         ......]
Is there any simple API can be used to make a model using X and S ?

**Comment by superbobry** [comment]
There is no such API `hmmlearn`, but you can use [`seqlearn`](https://github.com/larsmans/seqlearn) which implements supervised learning of HMMs.
