### ISSUE TITLE
how can I decode sequentially

### ISSUE THREAD

**Issue by chanansh** [hmmlearn/hmmlearn#144]
say I get a a single emission per time and I would like to have a probability for the state (with some lag so that the viterbi converges). Is that possible? Does the package supports sequential decoding rather than batch decoding? In HMM language this is called "filtering". see https://en.wikipedia.org/wiki/Forward_algorithm

**Comment by superbobry** [comment]
Hi @chanansh, support for sequential decoding is lacking at the moment, although it shouldn't be hard to implement in the MAP case.

A similar question was asked on SO recently, so I guess I'd [link to it](http://stackoverflow.com/questions/39388890/error-in-model-prediction-using-hmmlearn) as well.

**Comment by azuric** [comment]
just my two cents but you can still do the incremental (sequential decoding but you need to perform batch by appending the new vector each time, I have checked and the result is the same as if you had trained on one set run predict on another except for the first couple of values since the algo needs to 'settle down'

**Comment by superbobry** [comment]
Hi @azuric, thanks for the hint!

> [...] results will not be exactly the same though.

Yep, that is exactly what worries me. The values on the batch boundaries might end up being mispredicted.

**Comment by azuric** [comment]
Doesn't this mean that hmm viterbi decoding using batch will achieve results that can never be guaranteed using sequential decoding? You can only estimate the probability of the next current state using transitional probabilities right?

**Comment by zarzen** [comment]
Why decode only give one state?
I think it should be a sequence for each input data.
