### ISSUE TITLE
Baum-Welch Decoder Not Implemented

### ISSUE THREAD

**Issue by romainecarter** [hmmlearn/hmmlearn#145]
Hi, 
Is the baum-welch decoder available? I did a quick search of the repository and could not find any reference to Baum-Welch; I'm curious because the below example throws an error. 

`model2 = hmm.MultinomialHMM(n_components=2, n_iter=10, algorithm='Baum-Welch').fit(X)
`

**Comment by superbobry** [comment]
Hi Romaine, what do you mean by the Baum-Welch decoder? The two decoders implemented are `"viterbi"` for the [Viterbi algorithm](https://en.wikipedia.org/wiki/Viterbi_algorithm) and `"map"` for maximum-aposteriori decoding.

The estimation method `MultinomialHMM.fit` is indeed a slight variation of the original Baum-Welch algorithm with the only difference being in the use of priors for the parameters.

**Comment by romainecarter** [comment]
Thanks, I did not realize that the fit function Implements Baum-Welch. Your answer cleared it up for me.
