### ISSUE TITLE
Possible to initialize GMMHMM with given GMMs and perform Viterbi decoding afterwards?

### ISSUE THREAD

**Issue by ben314** [hmmlearn/hmmlearn#147]
Hey guys,

I have some trained GMMs, however I did **not** train those GMMs using scikit learn, so I only have them as numpy arrays of means, variances and weights. Is it possible to initialize a GMMHMM with those GMMs and use them to viterbi-decode a sequence of vectors?

Thanks in advance. :)

Best
Benjamin

**Comment by superbobry** [comment]
Yep, that should be doable. Which version of `hmmlearn` are you using?

**Comment by ben314** [comment]
I'm using hmmlearn 0.2.0 :)

**Comment by ben314** [comment]
Oh by the way, I saw that there is a n_mix parameter for the number of mixtures of all GMMs right? What happens if my GMMs do not all have the same amount of mixtures? Will Viterbi decoding still work?

**Comment by superbobry** [comment]
Sorry for the late reply. 

This should be possible, yes. Create a `GMMHMM` and populate the `gmms_` attribute using your `GMM` instances:

```python
model = GMMHMM(n_mix=42)
model.gmms_ = [GMM(...) for i in range(n_mix)]
```

> What happens if my GMMs do not all have the same amount of mixtures? Will Viterbi decoding still work?

Yes, I think it should work.
