### ISSUE TITLE
cannot import name _hmmc

### ISSUE THREAD

**Issue by GovertJaap** [hmmlearn/hmmlearn#149]
So I am trying to get hmmlearn working in Jupyter, and I have come across an error while installing Hmmlearn using `pip`. I have tried this [solution](http://stackoverflow.com/questions/38575860/error-compiling-c-code-for-python-hmmlearn-package), but it didn't work. 

It seems to me that `pip` does install the _hmmc file, but it does so incorrect. instead it has the name 

> _hmmc.cp35-win_amd64

and the file extesion is `.PYD`, instead of `.c`

When I run the code to import it, I get this error :

        ImportError                               Traceback (most recent call last)
        <ipython-input-1-dee84c3d5ff9> in <module>()
              7 import os
              8 from pyAudioAnalysis import audioBasicIO as aB
        ----> 9 from pyAudioAnalysis import audioAnalysis as aA

        C:\Users\gover_000\Documents\GitHub\Emotion-Recognition-Prototype\pyAudioAnalysis\audioAnalysis.py in <module>()
             15 import audioFeatureExtraction as aF
             16 import audioTrainTest as aT
       --->  17 import audioSegmentation as aS
             18 import audioVisualization as aV
             19 import audioBasicIO

        C:\Users\gover_000\Documents\GitHub\Emotion-Recognition-Prototype\pyAudioAnalysis\audioSegmentation.py in <module>()
             16 import sklearn
             17 import sklearn.cluster
        ---> 18 import hmmlearn.hmm
             19 import cPickle
             20 import glob

        C:\Users\gover_000\Anaconda3\envs\python2\lib\site-packages\hmmlearn\hmm.py in <module>()
             19 from sklearn.utils import check_random_state
             20 
        ---> 21 from .base import _BaseHMM
             22 from .utils import iter_from_X_lengths, normalize
             23 

        C:\Users\gover_000\Anaconda3\envs\python2\lib\site-packages\hmmlearn\base.py in <module>()
             11 from sklearn.utils.validation import check_is_fitted
             12 
        ---> 13 from . import _hmmc
             14 from .utils import normalize, log_normalize, iter_from_X_lengths
             15 

        ImportError: cannot import name _hmmc 

don't know why `pip` just doesn't install it correctly, even when I tried to use `--no-cache-dir`

**Comment by superbobry** [comment]
Did you install `hmmlearn` as a wheel of did you build it from source? 

If you aren't sure, reinstall the package and post the installation output here.

**Comment by GovertJaap** [comment]
I am installing it as a wheel: 

`C:\Users\gover_000>pip install hmmlearn`
`Collecting hmmlearn`
 `Using cached hmmlearn-0.2.0-cp35-cp35m-win_amd64.whl`
`Installing collected packages: hmmlearn`
`Successfully installed hmmlearn-0.2.0`

But I think there might be a problem with the versioning, since I am trying to get it running on python 2.7, but my root enviroment is python 3.5

**Comment by GovertJaap** [comment]
So i figured out what the problem was. my active python enviroment was python 3.5, as i was manually transferring the installed files to my enviroment, it failed because i had the wrong version.
I had to change my active python enviroment: using `activate <my_enviroment name>`
after that i could just use `pip` to install it again and it worked this time.
