### ISSUE TITLE
setuptools

### ISSUE THREAD

**Issue by ManuelAllh** [hmmlearn/hmmlearn#15]
Hi,

Is it possible to make hmmlearn available for setuptools?

Best regards,
Manuel

**Comment by superbobry** [comment]
I think you're referring to [PyPI](http://pypi.python.org), right? Sure, I will make a release over the weekend.

**Comment by ManuelAllh** [comment]
Thanks a lot in advance!

**Comment by superbobry** [comment]
Hello, I've made a PyPI [release](https://pypi.python.org/pypi/hmmlearn/0.1.1). Please let me know if it works for you.

**Comment by ManuelAllh** [comment]
Thanks a lot, it works perfectly!

**Comment by superbobry** [comment]
Great, closing the issue.
