### ISSUE TITLE
Startprob

### ISSUE THREAD

**Issue by MarkFuini** [hmmlearn/hmmlearn#150]
Curious as to the implementation details as why passing one sample to the predict_proba method always returns the probability of the startprob_ ?

model.predict_proba(test[0:1])
array([[ 0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.]])

It returns close to the startprob_ regardless of the value of the actual sample.

Thanks!

**Comment by superbobry** [comment]
Hi, Mark! 

The result of `predict_proba` is defined as follows

```
P[t, i] ∝ alpha[t, i] * beta[t, i]
```

where `alpha` and `beta` are computed by the forward-backward algorithms. In the single observation case we can expand that to

```
P[0, i] ∝ alpha[0, i] * beta[0, i]
        = startprob_[i] * emissionprob_[0, i]
```

Therefore, if your `startprob_` resemble `[ 0., 0., 0., 0., 1., 0., 0., 0.]`, then the **unnormalized** `P[0, i]` simply reduces a vector where all entries **except one** are zero. The non-zero entry would have some probability there, which will becomes 1 after normalization. 

Does this make sense?
