### ISSUE TITLE
Divide by zero encountered in log 

### ISSUE THREAD

**Issue by jemmykw** [hmmlearn/hmmlearn#151]
Hello , I download HMMlearn to try training HMM but when it come to train there is a warning

```
MultinomialHMM(algorithm='viterbi', init_params='ste', n_components=7,
        n_iter=50, params='ste',
        random_state=<mtrand.RandomState object at 0x10acd0288>,
        startprob_prior=1.0, tol=0.05, transmat_prior=1.0, verbose=True)
done
         1     -252750.2670             +nan
         2     -209161.1707      +43589.0964
         3     -208699.2674        +461.9033
         4     -207940.0653        +759.2021
         5     -206156.3213       +1783.7440
         6     -201466.4221       +4689.8992
         7     -193360.1122       +8106.3099
         8     -183145.5575      +10214.5547
         9     -168185.4196      +14960.1379
        10     -153344.4520      +14840.9676
        11     -145883.5135       +7460.9385
        12     -141737.7456       +4145.7679
        13     -137739.9243       +3997.8213
        14     -131168.9626       +6570.9617
        15     -127520.4174       +3648.5452
        16     -126778.4003        +742.0171
        17     -126017.8596        +760.5408
        18     -124993.9946       +1023.8649
        19     -123429.1970       +1564.7976
        20     -121325.9365       +2103.2606
        21     -120573.2583        +752.6782
        22     -120229.3897        +343.8686
        23     -119990.3985        +238.9912
        24     -119812.3264        +178.0722
/Users/imedia/anaconda/lib/python3.5/site-packages/hmmlearn-0.2.1-py3.5-macosx-10.6-x86_64.egg/hmmlearn/hmm.py:422: RuntimeWarning: divide by zero encountered in log
  return np.log(self.emissionprob_)[:, np.concatenate(X)].T
        25     -119678.0226        +134.3037
```
and when i try to test it , it have a index error , 

```
Traceback (most recent call last):
  File "/Users/imedia/PycharmProjects/PyCharmWorkplace/src/cf_predict.py", line 78, in <module>
    score_hmm = predict.score(X)
  File "/Users/imedia/anaconda/lib/python3.5/site-packages/hmmlearn-0.2.1-py3.5-macosx-10.6-x86_64.egg/hmmlearn/base.py", line 249, in score
    framelogprob = self._compute_log_likelihood(X[i:j])
  File "/Users/imedia/anaconda/lib/python3.5/site-packages/hmmlearn-0.2.1-py3.5-macosx-10.6-x86_64.egg/hmmlearn/hmm.py", line 439, in _compute_log_likelihood
    return np.log(self.emissionprob_)[:, np.concatenate(X)].T
IndexError: index 29 is out of bounds for axis 1 with size 29
```

can someone help me with this problem
thank you

**Comment by superbobry** [comment]
The warning is fine. It is harmless and has been fixed in the `master` version, which hasn't been released yet.

As for the error, it exactly matches another issue. Closing this one in favour of #154. Is it possible that you share a sample of the data reproducing the `IndexError`?

**Comment by jemmykw** [comment]
[train006.zip](https://github.com/hmmlearn/hmmlearn/files/540964/train006.zip)

hello superbobry, i attach the sample data reproducing the IndexError

thanks

**Comment by superbobry** [comment]
Thanks! However, I can't load the data neither via `pickle` nor `numpy.load`, which format is it in?

**Comment by jemmykw** [comment]
im using  `joblib` as in the tutorial to save the signal
`from sklearn.externals import joblib`

**Comment by superbobry** [comment]
Yep, I've managed to load the models. The archive doesn't have any data, only the models,
 right?

I've tried to fit the HMMs to the samples and worked okay. Could you attach some data reproducing the error?

**Comment by jemmykw** [comment]
[SOMdataset.zip](https://github.com/hmmlearn/hmmlearn/files/544316/SOMdataset.zip)
 that data for training, and when im testing with same data, error out of bond is showing,,

**Comment by superbobry** [comment]
I was able to reproduce the issue and will look into it. Thank you very much!

**Comment by fdabek1** [comment]
@superbobry I am currently using this library and everything was going well until I tried using some new data and I have now encountered this same "divide by zero encountered in log" warning.  Is there a fix for this warning or is it safe to ignore it?
