### ISSUE TITLE
MFCC with HMM

### ISSUE THREAD

**Issue by zarulizham** [hmmlearn/hmmlearn#152]
Hi, I am new to Python and learning algorithm. May I know how to make learning from MFCC output?

Here is my example of MFCC output.

`[[ 10.16348115  11.83078808  12.32813583  11.72925441  10.86806676
    9.02069854   8.19032066   6.22532274   7.36343193   7.89671557
    6.3507426    4.87263271   4.05336033   4.60243864   4.74114591
    4.36045822   4.60110666   4.89981733   5.15295887   5.03894547
    5.83283419   6.34318579   5.6423808    6.42846063   5.70638572
    5.35352784]
 [ 12.04730356  13.09948372  13.61868205  14.2522396   14.38476353
   12.54170743  10.86727736  10.29876982   9.88689996   9.99754236
    9.50433244   8.45680682   8.37608792   8.09342721   7.59267654
    7.30371051   7.27695111   7.04055057   7.24971343   7.23991369
    6.84996184   7.26223856   7.6858424    7.43273312   6.86028006
    6.73406315]]`

MFCC algorithm is fork from [jameslyons](https://github.com/jameslyons/python_speech_features)

If anyone have an idea/steps for me to be done, I thank you in advance.

**Comment by epratheeban** [comment]
@zarulizham  Can you please elaborate what are you trying to learn from the MFCC feature ? What is your ultimate aim of using HMM ?

**Comment by zarulizham** [comment]
Sorry for the late. I'm using HMM for speech recognition to detect whether a single word pronunciation is correct or not.

I'm using 5 words only for the testing. Example
1. Eat
2. Drink
3. Food
4. Dark
5. Car

So I'm will using those 5 words to make training and testing using HMM.

**Comment by superbobry** [comment]
Closing for reasons outlined in #157. Please do not create duplicate issues.
