### ISSUE TITLE
Emission matrix on the GaussianHMM

### ISSUE THREAD

**Issue by guerrajorge** [hmmlearn/hmmlearn#153]
Hello Sergei,

I saw that it is possible to set up the emission probability for the MultinomialHMM. However, just looking at the code I do not see it to possible for the GaussianHMM? is this correct or am I missing something?

**Comment by superbobry** [comment]
Hi, Jorge. It should work exactly the same for `GaussianHMM` except that `GaussianHMM` is parameterized in terms of means and covariances. See *Attributes* section [here](http://hmmlearn.readthedocs.io/en/latest/api.html#gaussianhmm).

**Comment by guerrajorge** [comment]
Oh, I understand. Thank you for the information.
