### ISSUE TITLE
Error using MultinomialHMM

### ISSUE THREAD

**Issue by gan3sh500** [hmmlearn/hmmlearn#154]
I was training multiple Multinomial HMMs to create a classifier. Due to the different classes some symbols only occurred in sequences produced by some HMMs. This causes an error in the Multinomial HMM. Whenever I have symbols from from 0 to n it works fine but if k where 0<k<n is not present in any of the sequences training that particular HMM it fails.
I get the following error:

```
> Traceback (most recent call last):
  File "dhmm.py", line 30, in <module>
    hmm_1 = MultinomialHMM(n_components = 3).fit(train_1, lengths1)
  File "/usr/local/lib/python3.5/dist-packages/hmmlearn/base.py", line 429, in fit
    framelogprob = self._compute_log_likelihood(X[i:j])
  File "/usr/local/lib/python3.5/dist-packages/hmmlearn/hmm.py", line 405, in _compute_log_likelihood
    return np.log(self.emissionprob_)[:, np.concatenate(X)].T
IndexError: index 5 is out of bounds for axis 1 with size 5
```

**Comment by superbobry** [comment]
Interesting, you should've gotten a different error (see [`_check_input_symbols`](https://github.com/hmmlearn/hmmlearn/blob/master/hmmlearn/hmm.py#L448)) in that case.

Could you share a sample of `train_1` which reproduces the issue?

**Comment by gan3sh500** [comment]
array([[3],
       [4],
       [4],
       ..., 
       [3],
       [1],
       [3]])
I pass it as fit(train_1, lengths). I had very similar code to this but with continuous data using GMMHMM and it worked perfectly. Can you tell me how to fix the problem?

**Comment by superbobry** [comment]
Could you save the full array to an NPZ file and attach it here? 

I've failed to reproduce the issue using these 6 elements above:

```python
>>> from hmmlearn.hmm import MultinomialHMM
>>> MultinomialHMM(n_components=3).fit([[3], [4], [4], [3], [1], [3]])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "./hmmlearn/hmmlearn/base.py", line 424, in fit
    self._init(X, lengths=lengths)
  File "./hmmlearn/hmmlearn/hmm.py", line 394, in _init
    raise ValueError("expected a sample from "
ValueError: expected a sample from a Multinomial distribution.
```

**Comment by nachtm** [comment]
Hi @superbobry,

Any update on this, or ideas on a workaround? I'm running into this issue with 0.2.0.

Thanks!

**Comment by tomervia** [comment]
I'm also facing the same problem when training MULTINOMIAL HMM on MULTIPLE SEQUENCES. 
It seems that the same data and code works (as exemplified in the documentation) with continuous data, Gaussian HMM (hmm.GMMHMM); but doesn't work when only changing the model to be a Multinomial HMM. That gives that same Index Error.


` 
X1 = [[1],[2],[2],[2],[2],[4],[2],[4],[2]]
X2 = [[1],[3],[4],[2],[4],[3],[4]]
X = np.concatenate([X1, X2])
lengths = [len(X1), len(X2)]
hmm.MultinomialHMM(n_components=2).fit(X, lengths)  
# this would work: hmm.GMMHMM(n_components=2).fit(X_example, lengths_example)  
`

Getting this error:
`
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-129-34edee5616c2> in <module>()
      5 X_example = np.concatenate([X1_example, X2_example])
      6 lengths_example = [len(X1_example), len(X2_example)]
----> 7 hmm.MultinomialHMM(n_components=2).fit(X_example, lengths_example)

/Users/tomereldor/anaconda2/lib/python2.7/site-packages/hmmlearn/base.pyc in fit(self, X, lengths)
    427             curr_logprob = 0
    428             for i, j in iter_from_X_lengths(X, lengths):
--> 429                 framelogprob = self._compute_log_likelihood(X[i:j])
    430                 logprob, fwdlattice = self._do_forward_pass(framelogprob)
    431                 curr_logprob += logprob

/Users/tomereldor/anaconda2/lib/python2.7/site-packages/hmmlearn/hmm.pyc in _compute_log_likelihood(self, X)
    403 
    404     def _compute_log_likelihood(self, X):
--> 405         return np.log(self.emissionprob_)[:, np.concatenate(X)].T
    406 
    407     def _generate_sample_from_state(self, state, random_state=None):

IndexError: index 4 is out of bounds for axis 1 with size 4
`

How to fix this?

**Comment by SmirkCao** [comment]
try to change your X to zero-based values.
```python
    X1 = np.array([0, 1, 1, 1, 1, 3, 1, 3, 1])
    X2 = np.array([0, 2, 3, 1, 3, 2, 3])
    X = np.concatenate([X1, X2])
    lengths = [len(X1), len(X2)]
    hmm_issue = hmm.MultinomialHMM(n_components=2)
    hmm_issue.fit(X.reshape(-1, 1), lengths)
    logger.info("\n%s" % hmm_issue.emissionprob_)
    logger.info("\n%s" % hmm_issue.startprob_)
    logger.info("\n%s" % hmm_issue.transmat_)
```

The outputs as follows:
```
2018-09-14 21:25:20,598 - __main__ - INFO - 
[[1.00000000e+00 1.14612786e-11 5.63729005e-13 3.38061507e-12]
 [0.00000000e+00 5.00000000e-01 1.42857143e-01 3.57142857e-01]]
2018-09-14 21:25:20,598 - __main__ - INFO - 
[1. 0.]
2018-09-14 21:25:20,598 - __main__ - INFO - 
[[1.36640789e-12 1.00000000e+00]
 [2.33986913e-12 1.00000000e+00]]
```

**Comment by hpathak92** [comment]
I am getting a similar issue. observations is a list
X = np.atleast_2d([observations]).T
model = hmm.MultinomialHMM(n_components = 4)
Z = model.fit(X)

Returns an error:
![image](https://user-images.githubusercontent.com/43105904/69842241-7e01d180-1230-11ea-9b2d-99c6d69b3b2a.png)
