### ISSUE TITLE
Unsure how to use multiple hmmlearn for my data

### ISSUE THREAD

**Issue by kbagalo** [hmmlearn/hmmlearn#155]
Hello Guys,
I have a set of 200 (M) signals,and each signal is divided into N frames of length 16 and overlap 8. I am extracting Hjorth parameters (3) from each frame. I want to fit an HMM on this dataset of mine. Could someone please tell me how the multiple sequence functionality can be used here. I suspect that I am just confusing myself with the notation here.

**Comment by superbobry** [comment]
Could you explain a bit more about the kind of model you have in mind? The models we have in `hmmlearn` do not account for possible overlaps in the samples.

**Comment by kbagalo** [comment]
I have decided on a GMMHMM, since the Hjorth parameters follow that density distribution. A diag cov matrix (time series). Essentially, I am trying to solve a classification problem on the 200 signals, using sequences from each frame of each a signal. Please let me know if my description was enough, or I can go into details.

**Comment by superbobry** [comment]
Sorry, I don't know what Hjorth parameters are, but if you're trying to solve a supervised problem, `hmmlearn` is probably not the best option, since it targets the unsupervised case.
