### ISSUE TITLE
Deprecation warning

### ISSUE THREAD

**Issue by Borreguin** [hmmlearn/hmmlearn#158]
Hello @superbobry ,
I'm using the GaussianHMM model. and is working good. However when I fit my model, I have some warning messages like:

> DeprecationWarning: Function log_multivariate_normal_density is deprecated; The function log_multivariate_normal_density is deprecated in 0.18 and will be removed in 0.20. warnings.warn(msg, category=DeprecationWarning)

What I could do in order to solve this issue?

Best,
Roberto

**Comment by karimpedia** [comment]
If you just want to suppress the warning you can use:

```
imoprt warnings
with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=DeprecationWarning)
        model.fit(X)
```

**Comment by superbobry** [comment]
Hi Roberto. `scikit-learn` developers re-worked the implementation of the Gaussian mixture model and deprecated he contents of `sklearn.gmm` (see scikit-learn/scikit-learn#7012). We would have to address that in the next release. Thanks for pointing this out!

**Comment by superbobry** [comment]
Closing in favour of #175.
