### ISSUE TITLE
py.test --doctest-modules hmmlearn got errors

### ISSUE THREAD

**Issue by YFJiang** [hmmlearn/hmmlearn#159]
Hi:
I run 'py.test --doctest-modules hmmlearn' after installing, i got the errors:
E       AttributeError: 'module' object has no attribute 'broadcast_to'

============================================== 38 failed, 60 passed, 12 xfailed in 6.64 seconds ===============================================

**Comment by superbobry** [comment]
[`np.broadcast_to`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.broadcast_to.html) was added in NumPy 1.10.0, so I think you could "fix" the error by updating NumPy. 

We would reconsider relaxing the version requirements before releasing the current `master`.
