### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by tangabc** [hmmlearn/hmmlearn#16]
When I build the project with: `python setup.py build`, I get the following errors:

```
running build
running build_py
running build_ext
building 'hmmlearn._hmmc' extension
creating build/temp.linux-x86_64-2.7
creating build/temp.linux-x86_64-2.7/hmmlearn
x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/local/lib/python2.7/dist-packages/numpy/core/include -I/usr/include/python2.7 -c hmmlearn/_hmmc.c -o build/temp.linux-x86_64-2.7/hmmlearn/_hmmc.o
x86_64-linux-gnu-gcc: error: hmmlearn/_hmmc.c: No such file or directory
x86_64-linux-gnu-gcc: fatal error: no input files
compilation terminated.
error: command 'x86_64-linux-gnu-gcc' failed with exit status 4
```
The build does not seem to be able to find the `hmmlearn/_hmmc.c` file. Any advice?

**Comment by superbobry** [comment]
Hmm, are you building `master` or PyPI release? Also, you do have Cython installed, right?

**Comment by tangabc** [comment]
I have Cython v0.22 installed.

This error occurs both when I'm building master (python setup.py install)
and PyPI release (pip install hmmlearn).

Let me know if you need more info.

**Comment by superbobry** [comment]
Interesting, I've failed to reproduce the build error in a fresh conda environment. Can you please post complete build output?

Here's mine:

```
running build
running build_py
creating build
creating build/lib.linux-x86_64-2.7
creating build/lib.linux-x86_64-2.7/hmmlearn
copying hmmlearn/hmm.py -> build/lib.linux-x86_64-2.7/hmmlearn
copying hmmlearn/base.py -> build/lib.linux-x86_64-2.7/hmmlearn
copying hmmlearn/__init__.py -> build/lib.linux-x86_64-2.7/hmmlearn
creating build/lib.linux-x86_64-2.7/hmmlearn/utils
copying hmmlearn/utils/fixes.py -> build/lib.linux-x86_64-2.7/hmmlearn/utils
copying hmmlearn/utils/__init__.py -> build/lib.linux-x86_64-2.7/hmmlearn/utils
running build_ext
cythoning hmmlearn/_hmmc.pyx to hmmlearn/_hmmc.c
building 'hmmlearn._hmmc' extension
creating build/temp.linux-x86_64-2.7
creating build/temp.linux-x86_64-2.7/hmmlearn
```

**Comment by tangabc** [comment]
Hi,

Here's a log of what I tried. Perhaps I miss something here.

root@test-pc:/tmp$ uname -a
Linux test-pc 3.13.0-24-generic #46-Ubuntu SMP Thu Apr 10 19:11:08 UTC 2014
x86_64 x86_64 x86_64 GNU/Linux

root@test-pc:/tmp$ cython --version
Cython version 0.22
root@test-pc:/tmp$ git clone https://github.com/hmmlearn/hmmlearn.git
Cloning into 'hmmlearn'...
remote: Counting objects: 365, done.
remote: Total 365 (delta 0), reused 0 (delta 0)
Receiving objects: 100% (365/365), 1.79 MiB | 0 bytes/s, done.
Resolving deltas: 100% (150/150), done.
Checking connectivity... done.
root@test-pc:/tmp$ cd hmmlearn/
root@test-pc:/tmp/hmmlearn$ python setup.py install
running install
Checking .pth file support in /usr/local/lib/python2.7/dist-packages/
/usr/bin/python -E -c pass
TEST PASSED: /usr/local/lib/python2.7/dist-packages/ appears to support
.pth files
running bdist_egg
running egg_info
creating hmmlearn.egg-info
writing requirements to hmmlearn.egg-info/requires.txt
writing hmmlearn.egg-info/PKG-INFO
writing top-level names to hmmlearn.egg-info/top_level.txt
writing dependency_links to hmmlearn.egg-info/dependency_links.txt
writing manifest file 'hmmlearn.egg-info/SOURCES.txt'
reading manifest file 'hmmlearn.egg-info/SOURCES.txt'
writing manifest file 'hmmlearn.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build
creating build/lib.linux-x86_64-2.7
creating build/lib.linux-x86_64-2.7/hmmlearn
copying hmmlearn/__init__.py -> build/lib.linux-x86_64-2.7/hmmlearn
copying hmmlearn/base.py -> build/lib.linux-x86_64-2.7/hmmlearn
copying hmmlearn/hmm.py -> build/lib.linux-x86_64-2.7/hmmlearn
creating build/lib.linux-x86_64-2.7/hmmlearn/utils
copying hmmlearn/utils/__init__.py ->
build/lib.linux-x86_64-2.7/hmmlearn/utils
copying hmmlearn/utils/fixes.py -> build/lib.linux-x86_64-2.7/hmmlearn/utils
running build_ext
building 'hmmlearn._hmmc' extension
creating build/temp.linux-x86_64-2.7
creating build/temp.linux-x86_64-2.7/hmmlearn
x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2
-Wall -Wstrict-prototypes -fPIC
-I/usr/local/lib/python2.7/dist-packages/numpy/core/include
-I/usr/include/python2.7 -c hmmlearn/_hmmc.c -o
build/temp.linux-x86_64-2.7/hmmlearn/_hmmc.o
x86_64-linux-gnu-gcc: error: hmmlearn/_hmmc.c: No such file or directory
x86_64-linux-gnu-gcc: fatal error: no input files
compilation terminated.
error: command 'x86_64-linux-gnu-gcc' failed with exit status 4

root@test-pc:/tmp$ pip install hmmlearn
Downloading/unpacking hmmlearn
  Downloading hmmlearn-0.1.1.tar.gz
  Running setup.py (path:/tmp/pip_build_root/hmmlearn/setup.py) egg_info
for package hmmlearn

Requirement already satisfied (use --upgrade to upgrade): Cython in
/usr/local/lib/python2.7/dist-packages/Cython-0.22-py2.7-linux-x86_64.egg
(from hmmlearn)
Installing collected packages: hmmlearn
  Running setup.py install for hmmlearn
    building 'hmmlearn._hmmc' extension
    x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv
-O2 -Wall -Wstrict-prototypes -fPIC
-I/usr/local/lib/python2.7/dist-packages/numpy/core/include
-I/usr/include/python2.7 -c hmmlearn/_hmmc.c -o
build/temp.linux-x86_64-2.7/hmmlearn/_hmmc.o
    x86_64-linux-gnu-gcc: error: hmmlearn/_hmmc.c: No such file or directory
    x86_64-linux-gnu-gcc: fatal error: no input files
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 4
    Complete output from command /usr/bin/python -c "import setuptools,
tokenize;__file__='/tmp/pip_build_root/hmmlearn/setup.py';exec(compile(getattr(tokenize,
'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))"
install --record /tmp/pip-i8Y5N2-record/install-record.txt
--single-version-externally-managed --compile:
    running install

running build
running build_py
creating build
creating build/lib.linux-x86_64-2.7
creating build/lib.linux-x86_64-2.7/hmmlearn
copying hmmlearn/__init__.py -> build/lib.linux-x86_64-2.7/hmmlearn
copying hmmlearn/base.py -> build/lib.linux-x86_64-2.7/hmmlearn
copying hmmlearn/hmm.py -> build/lib.linux-x86_64-2.7/hmmlearn
creating build/lib.linux-x86_64-2.7/hmmlearn/utils
copying hmmlearn/utils/__init__.py ->
build/lib.linux-x86_64-2.7/hmmlearn/utils
copying hmmlearn/utils/fixes.py -> build/lib.linux-x86_64-2.7/hmmlearn/utils
running build_ext
building 'hmmlearn._hmmc' extension
creating build/temp.linux-x86_64-2.7
creating build/temp.linux-x86_64-2.7/hmmlearn
x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2
-Wall -Wstrict-prototypes -fPIC
-I/usr/local/lib/python2.7/dist-packages/numpy/core/include
-I/usr/include/python2.7 -c hmmlearn/_hmmc.c -o
build/temp.linux-x86_64-2.7/hmmlearn/_hmmc.o
x86_64-linux-gnu-gcc: error: hmmlearn/_hmmc.c: No such file or directory
x86_64-linux-gnu-gcc: fatal error: no input files
compilation terminated.
error: command 'x86_64-linux-gnu-gcc' failed with exit status 4
----------------------------------------
Cleaning up...

**Comment by superbobry** [comment]
Your log seems to be missing the cython call

```
cythoning hmmlearn/_hmmc.pyx to hmmlearn/_hmmc.c
```

I think the ultimate fix might be to just add `_hmmc.c` back to the repository. Can you try the `master` version now?

**Comment by tangabc** [comment]
Perfect. It works now. Thanks.

**Comment by jovesus** [comment]
the release 0.1.1 links to the wrong commit.
instead of
https://github.com/hmmlearn/hmmlearn/commit/d3449a7427c1cab24691752880969ae2b7061c30
should be
https://github.com/hmmlearn/hmmlearn/commit/0ae058edcf058f06ece201ae5758e6e7e92da1c7

**Comment by superbobry** [comment]
Are you sure? I've checked the [PyPi release](https://pypi.python.org/pypi/hmmlearn/0.1.1) and it does not have a `_hmmc.c` added in 0ae058edcf058f06ece201ae5758e6e7e92da1c7.
