### ISSUE TITLE
Import error

### ISSUE THREAD

**Issue by Kameshkk** [hmmlearn/hmmlearn#161]
I have Scikit-learn 0.18, and hmmlearn 0.2.1

When I try to run `from hmmlearn import hmm` , I get this error:

```
ImportError                               Traceback (most recent call last)
<ipython-input-23-8b8c029fb053> in <module>()
----> 1 from hmmlearn import hmm

//anaconda/lib/python2.7/site-packages/hmmlearn/hmm.py in <module>()
     19 from sklearn.utils import check_random_state
     20 
---> 21 from .base import _BaseHMM
     22 from .utils import iter_from_X_lengths, normalize
     23 

//anaconda/lib/python2.7/site-packages/hmmlearn/base.py in <module>()
      8 from scipy.misc import logsumexp
      9 from sklearn.base import BaseEstimator, _pprint
---> 10 from sklearn.utils import check_array, check_random_state
     11 from sklearn.utils.validation import check_is_fitted
     12 

ImportError: cannot import name check_array
```

**Comment by superbobry** [comment]
Hi! Are you sure you using 0.18? I've checked with GitHub, [`check_array`](https://github.com/scikit-learn/scikit-learn/blob/0.18.X/sklearn/utils/__init__.py#L13) is still in `sklearn.utils` in this release.

**Comment by Kameshkk** [comment]
I have scikit-learn 0.18.1 and I can confirm that this line doesn't run:

 ```
from sklearn.utils import check_array
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-2-fcd9175a5040> in <module>()
----> 1 from sklearn.utils import check_array

ImportError: cannot import name check_array
```

However, the following works:  
`from sklearn.utils import check_arrays`

What's the difference between `check_array` and `check_arrays` ?





I think “check_array” is only available for developers. I’m quoting the scikit-learn website:

(http://scikit-learn.org/stable/developers/utilities.html#developers-utils)

"Warning These utilities are meant to be used internally within the scikit-learn package. They are not guaranteed to be stable between versions of scikit-learn. Backports, in particular, will be removed as the scikit-learn dependencies evolve.”

**Comment by superbobry** [comment]
Hmm, could you attach the output of

```python
import sklearn
print(sklearn.__version__)
```

**Comment by Kameshkk** [comment]
Ah! That seems to be the issue!
I had a version of Python from Enthought and for some reason the my Anaconda installation was importing the Canopy version of sklearn. 
I removed Canopy and the import seems to work fine!

Sorry about the confusion.
