### ISSUE TITLE
how to export emission matrix that can be used by external forward algorithm ?

### ISSUE THREAD

**Issue by fulean** [hmmlearn/hmmlearn#163]
I want to export the trans matrix, and emission matrix from hmmlearn , and used as model parameters in forward algorithm written by c++,  it'clear that  "transmat_" attribute is the trans matrix of hiden state ,while 
how to get the so called emission matrix ?  does "means_" attribute of model represent the emission matrix ? thanks !

**Comment by superbobry** [comment]
Hello, the emission matrix can be computed by the (currently internal) `_compute_log_likelihood` method. See its docstring for the details.

**Comment by fulean** [comment]
hi Sergei, I want to get the emission matrix from GaussianHMM , which with shape  (number_of_hiden_state , number_of_observation_state) , and I have read the _compute_log_likelihood method in GaussianHMM ,just invoke log_multivariate_normal_density in sklearn, and return I still can't figure out how to get the emission matrix. could you please give me more tips , thanks a lot !

**Comment by fulean** [comment]
after get emission matrix, it can be used as param B in HMM_forwardAlgorithm in following link:

http://study.marearts.com/2013/02/hmm-forward-algorithm-source-code.html

**Comment by aubreyli** [comment]
_compute_log_likelihood(X) returns log of emission matrix, so emission matrix can be gotten by exp of log_likelihood.

**Comment by fulean** [comment]
in GaussianHMM,  _compute_log_likelihood  equals to log_multivariate_normal_density from sklearn, which return log probabilities of each data point in X under each of the n_components multivariate Gaussian distributions,its shape (n_samples, n_components) ,while emission matrix should be with shape (n_component, n_features) . so emission matrix , ,in my understanding , cannot be gotten by exp of log_likelihood. right ?

**Comment by aubreyli** [comment]
I don't think so. log_multivariate_normal_density() is correct and enough to feed to HMM forward algorithm, which is already included in hmmlearn.

**Comment by fulean** [comment]
hi aubreyli , in my case ,  I want to use the matrices of hmm model parameters in C++ code,  then I can use the model in android system , the c++ forward algorithm only accept the Emission matrix with (n_component,n_features)  shape, n_component is number of hiden state, and n_features is number of possible observation value , my probem is how to get the emission matrix with this shape , and it shouldn't be related to the number of sample data, while  log_multivariate_normal_density returns depend on  number of samples input .

**Comment by fulean** [comment]
please refer to hmmtrain method in matlab toolbox, the 2th element returned by hmmtrain is excactly the one i needed.

**Comment by superbobry** [comment]
The function you've referenced estimates a MultinomialHMM, also part of `hmmlearn`. Are you sure you want `GaussianHMM`?

**Comment by fulean** [comment]
hi superbobry, MultinomialHMM has constrains for sample  'X'  that each integer from the range [min(X), max(X)] occurs in ``X`` at least once, while in my case ,samples don't satisfy this requirement. so I turn to GaussianHMM, but it doesn't support emission matrix , which I needed to apply to c++ forward algorithm. it seems like I have to use matlab instead.

**Comment by superbobry** [comment]
You could map `X` to the required range before passing it to `hmmlearn`. This can be done e.g. via `np.unique`:

```python
>>> np.unique([42, 42, 42, 1, 0, 1], return_inverse=True)
(array([ 0,  1, 42]), array([2, 2, 2, 1, 0, 1]))
```

Here the first array holds all unique values and the second -- transformed `X`. See [this](http://stackoverflow.com/questions/3172509/numpy-convert-categorical-string-arrays-to-an-integer-array) SO discussion for details.

**Comment by fpetric** [comment]
To get back to the original question, what do you need to pass to `_compute_log_likelihood(X)` in order to obtain the log of the emission matrix?

**Comment by superbobry** [comment]
`X` --- a matrix of observations. Note that the `length` argument is not supported by this method. Here's an example:

```python
>>> import numpy as np
>>> from hmmlearn import hmm
>>> X = np.atleast_2d([[1, 2, 0, 0, 1], [2, 0, 1, 1, 2]])
>>> model = hmm.MultinomialHMM(n_components=2).fit(X)
>>> model._compute_log_likelihood(X)
array([[-0.24013362, -2.29753672],
       [-3.70061976, -0.66688017],
       [-1.66723105, -0.9514352 ],
       [-1.66723105, -0.9514352 ],
       [-0.24013362, -2.29753672],
       [-3.70061976, -0.66688017],
       [-1.66723105, -0.9514352 ],
       [-0.24013362, -2.29753672],
       [-0.24013362, -2.29753672],
       [-3.70061976, -0.66688017]])
```

**Comment by fpetric** [comment]
Thanks
