### ISSUE TITLE
A question about prior in multiple sequence HMM

### ISSUE THREAD

**Issue by kaiping** [hmmlearn/hmmlearn#164]
[https://github.com/hmmlearn/hmmlearn/blob/master/hmmlearn/base.py#L643](https://github.com/hmmlearn/hmmlearn/blob/master/hmmlearn/base.py#L643)

In this line, stats['start'] is an accumulation of all sequences, but the prior part is added only once after accumulation. Then the influence of prior will be related to the number of sequences.

I was wondering why the design is like this?

**Comment by superbobry** [comment]
This is common for Bayesian inference: the more data you have, the lower the effect of the prior. 

N.B. `hmmlearn` does maximum aposteriori inference for parameters, that is where the Bayesian part comes in :)

**Comment by kaiping** [comment]
Thank you for your timely reply!
