### ISSUE TITLE
A question on constraints

### ISSUE THREAD

**Issue by Heerpa** [hmmlearn/hmmlearn#166]
Hi,
thanks for the awesome package! In my application I have quite a clear idea about the relationships between transition rates between several states. In some cases I want the emission probabilities of two states to be the same (while the transition rates differ). Is it possible to constrain the HMM such that these conditions will be met? Or is this only possible with supervised implementations?
Thanks
  Heinrich

**Comment by superbobry** [comment]
Hi Heinrich,

Yes this is possible, but is not available in `hmmlearn` out of the box. You'll have to override the M-step (see `_BaseHMM._do_mstep`) and re-update these states manually.
