### ISSUE TITLE
Adaboosting for MultivariateHMM?

### ISSUE THREAD

**Issue by davidlamcm** [hmmlearn/hmmlearn#167]
Hi I am looking to implement adaboosting wiith HMM for a set of multivariate data, i.e. I have a set of time series data with multiple attributes. I have tried the Gaussian HMM of stock data example on the website and seems that HMMlearn can deal with multivariate data. But to do boosting, I need to assign weighting to each data point. May I know does the HMMLearn allow this customization? Otherwise, if I have to implement this one my own, could you point me to the part of the code that calculate the MLE?

Or is it bad idea to apply adaboost on HMM? what do you think?

**Comment by superbobry** [comment]
Hi! As far as I know, boosting is well developed only for the case of supervised learning, while `hmmlearn` targets the unsupervised case. Take a look at [`seqlearn`](https://github.com/larsmans/seqlearn) which implements supervised learning of `MultinomialHMM`.

In general, it is hard to tell apriori whether boosting would give any improvement. The best way to find out is to experiment :)
