### ISSUE TITLE
A row in transmat_ converges to zero and means_ to NaN

### ISSUE THREAD

**Issue by stevenwong** [hmmlearn/hmmlearn#169]
Hi, hmmlearn version 0.2.0. I noticed that sometimes if hmmlearn doesn't trickle into a state, mean_[state] becomes NaN and transmat_[state] becomes zero. An example is given below.

    In [6]: f.hmm
    Out[6]:
    GaussianHMM(algorithm='viterbi', covariance_type='full', covars_prior=0.01,
          covars_weight=1, init_params='stmc', means_prior=0, means_weight=0,
          min_covar=0.001, n_components=5, n_iter=20, params='stmc',
          random_state=None, startprob_prior=1.0, tol=0.01, transmat_prior=1.0,
          verbose=False)

    In [7]: f.hmm.transmat_
    Out[7]:
    array([[  1.12475664e-01,   3.04248336e-01,   2.03045232e-10,
              5.83275999e-01,   0.00000000e+00],
           [  2.88676084e-02,   1.92617799e-01,   2.56359906e-11,
              7.78514593e-01,   0.00000000e+00],
           [  4.12825948e-01,   3.78983316e-01,   2.46398405e-09,
              2.08190734e-01,   0.00000000e+00],
           [  1.28096031e-02,   1.64703359e-01,   3.43378095e-12,
              8.22487038e-01,   0.00000000e+00],
           [  0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
              0.00000000e+00,   0.00000000e+00]])

    In [8]: f.hmm.means_
    Out[8]:
    array([[-0.01016293],
           [ 0.00304074],
           [-0.02592761],
           [ 0.00568082],
           [        nan]])

And I get the following error:

    [2017-01-03 15:23:03,661] [ERROR] array must not contain infs or NaNs
    ---------------------------------------------------------------------------
    ValueError                                Traceback (most recent call last)
    <ipython-input-4-31791a173418> in <module>()

    C:\test.py in hmm()
    --> 739               h = h.fit(seq)

    C:\Users\swong32\AppData\Roaming\Python\Python34\site-packages\hmmlearn\base.py in fit(self, X, lengths)
        427             curr_logprob = 0
        428             for i, j in iter_from_X_lengths(X, lengths):
    --> 429                 framelogprob = self._compute_log_likelihood(X[i:j])
        430                 logprob, fwdlattice = self._do_forward_pass(framelogprob)
        431                 curr_logprob += logprob

    C:\Users\swong32\AppData\Roaming\Python\Python34\site-packages\hmmlearn\hmm.py in _compute_log_likelihood(self, X)
        198     def _compute_log_likelihood(self, X):
        199         return log_multivariate_normal_density(
    --> 200             X, self.means_, self._covars_, self.covariance_type)
        201
        202     def _generate_sample_from_state(self, state, random_state=None):

    C:\Program Files\Anaconda3\envs\py34\lib\site-packages\sklearn\utils\deprecation.py in wrapped(*args, **kwargs)
         69         def wrapped(*args, **kwargs):
         70             warnings.warn(msg, category=DeprecationWarning)
    ---> 71             return fun(*args, **kwargs)
         72
         73         wrapped.__name__ = fun.__name__

    C:\Program Files\Anaconda3\envs\py34\lib\site-packages\sklearn\mixture\gmm.py in
     log_multivariate_normal_density(X, means, covars, covariance_type)
         70         'full': _log_multivariate_normal_density_full}
         71     return log_multivariate_normal_density_dict[covariance_type](
    ---> 72         X, means, covars)
         73
         74

    C:\Program Files\Anaconda3\envs\py34\lib\site-packages\sklearn\mixture\gmm.py in _log_multivariate_normal_density_full(X, means, covars, min_covar)
        720     for c, (mu, cv) in enumerate(zip(means, covars)):
        721         try:
    --> 722             cv_chol = linalg.cholesky(cv, lower=True)
        723         except linalg.LinAlgError:
        724             # The model is most probably stuck in a component with too

    C:\Program Files\Anaconda3\envs\py34\lib\site-packages\scipy\linalg\decomp_cholesky.py in cholesky(a, lower, overwrite_a, check_finite)
         79     """
         80     c, lower = _cholesky(a, lower=lower, overwrite_a=overwrite_a, clean=True,
    ---> 81                             check_finite=check_finite)
         82     return c
         83

    C:\Program Files\Anaconda3\envs\py34\lib\site-packages\scipy\linalg\decomp_cholesky.py in _cholesky(a, lower, overwrite_a, clean, check_finite)
         18
         19     if check_finite:
    ---> 20         a1 = asarray_chkfinite(a)
         21     else:
         22         a1 = asarray(a)

    C:\Program Files\Anaconda3\envs\py34\lib\site-packages\numpy\lib\function_base.py in asarray_chkfinite(a, dtype, order)
       1031     if a.dtype.char in typecodes['AllFloat'] and not np.isfinite(a).all():
       1032         raise ValueError(
    -> 1033             "array must not contain infs or NaNs")
       1034     return a
       1035

    ValueError: array must not contain infs or NaNs

I suspect setting means_[4] to zero will work. I've created a gist to illustrate the above.

[Gist here](https://gist.github.com/stevenwong/fd082f63d68b8f3315588c7b49cad24f)

**Comment by stevenwong** [comment]
I figured this is what I need to change to cater for the case where noise isn't Gaussian and one of the states ends up with NaN mean:

In base.py

    def fit(self, X, lengths=None):
        """Estimate model parameters.

        An initialization step is performed before entering the
        EM algorithm. If you want to avoid this step for a subset of
        the parameters, pass proper ``init_params`` keyword argument
        to estimator's constructor.

        Parameters
        ----------
        X : array-like, shape (n_samples, n_features)
            Feature matrix of individual samples.

        lengths : array-like of integers, shape (n_sequences, )
            Lengths of the individual sequences in ``X``. The sum of
            these should be ``n_samples``.

        Returns
        -------
        self : object
            Returns self.
        """
        X = check_array(X)
        self._init(X, lengths=lengths)
        self._check()

        self.monitor_ = ConvergenceMonitor(self.tol, self.n_iter, self.verbose)
        for iter in range(self.n_iter):
            stats = self._initialize_sufficient_statistics()
            curr_logprob = 0
            for i, j in iter_from_X_lengths(X, lengths):
                framelogprob = self._compute_log_likelihood(X[i:j])
                logprob, fwdlattice = self._do_forward_pass(framelogprob)
                curr_logprob += logprob
                bwdlattice = self._do_backward_pass(framelogprob)
                posteriors = self._compute_posteriors(fwdlattice, bwdlattice)
                self._accumulate_sufficient_statistics(
                    stats, X[i:j], framelogprob, posteriors, fwdlattice,
                    bwdlattice)

            # XXX must be before convergence check, because otherwise
            #     there won't be any updates for the case ``n_iter=1``.
            self._do_mstep(stats)
            self._covars_ = np.nan_to_num(self._covars_)
            self.covars_ = np.nan_to_num(self.covars_)
            self.means_ = np.nan_to_num(self.means_)
            self.transmat_ = normalize(self.transmat_, axis=1)

            self.monitor_.report(curr_logprob)
            if self.monitor_.converged:
                break

        return self

But I end up with this super weird error where the numpy import got mysteriously overwritten.

    [2017-01-04 15:29:47,970] [ERROR] 'NoneType' object has no attribute 'log'
    ---------------------------------------------------------------------------
    AttributeError                            Traceback (most recent call last)
    <ipython-input-4-31791a173418> in <module>()
    ----> 1 hmm.fit(seq)

    C:\Users\swong32\AppData\Roaming\Python\Python34\site-packages\hmmlearn\base.py in fit(self, X, lengths)
        428             for i, j in iter_from_X_lengths(X, lengths):
        429                 framelogprob = self._compute_log_likelihood(X[i:j])
    --> 430                 logprob, fwdlattice = self._do_forward_pass(framelogprob)
        431                 curr_logprob += logprob
        432                 bwdlattice = self._do_backward_pass(framelogprob)

    C:\Users\swong32\AppData\Roaming\Python\Python34\site-packages\hmmlearn\base.py in _do_forward_pass(self, framelogprob)
        463         _hmmc._forward(n_samples, n_components,
        464                        np.log(self.startprob_),
    --> 465                        np.log(self.transmat_),
        466                        framelogprob, fwdlattice)
        467         return logsumexp(fwdlattice[-1]), fwdlattice

    AttributeError: 'NoneType' object has no attribute 'log'

Any ideas?

**Comment by stevenwong** [comment]
I figured out that I need to reset NaNs to 0. So I tried doing this in base.py

    def fit(self, X, lengths=None):
        """Estimate model parameters.

        An initialization step is performed before entering the
        EM algorithm. If you want to avoid this step for a subset of
        the parameters, pass proper ``init_params`` keyword argument
        to estimator's constructor.

        Parameters
        ----------
        X : array-like, shape (n_samples, n_features)
            Feature matrix of individual samples.

        lengths : array-like of integers, shape (n_sequences, )
            Lengths of the individual sequences in ``X``. The sum of
            these should be ``n_samples``.

        Returns
        -------
        self : object
            Returns self.
        """
        X = check_array(X)
        self._init(X, lengths=lengths)
        self._check()

        self.monitor_ = ConvergenceMonitor(self.tol, self.n_iter, self.verbose)
        for iter in range(self.n_iter):
            stats = self._initialize_sufficient_statistics()
            curr_logprob = 0
            for i, j in iter_from_X_lengths(X, lengths):
                framelogprob = self._compute_log_likelihood(X[i:j])
                logprob, fwdlattice = self._do_forward_pass(framelogprob)
                curr_logprob += logprob
                bwdlattice = self._do_backward_pass(framelogprob)
                posteriors = self._compute_posteriors(fwdlattice, bwdlattice)
                self._accumulate_sufficient_statistics(
                    stats, X[i:j], framelogprob, posteriors, fwdlattice,
                    bwdlattice)

            # XXX must be before convergence check, because otherwise
            #     there won't be any updates for the case ``n_iter=1``.
            self._do_mstep(stats)

            # NEW ###
            self._covars_ = np.nan_to_num(self._covars_)
            self.covars_ = np.nan_to_num(self.covars_)
            self.means_ = np.nan_to_num(self.means_)
            normalize(self.transmat_, axis=1)

            self.monitor_.report(curr_logprob)
            if self.monitor_.converged:
                break

        return self

And in utils.py so empty states won't violate transition probabilities sum to 1

    def normalize(a, axis=None):
        """Normalizes the input array so that it sums to 1.

        Parameters
        ----------
        a : array
            Non-normalized input data.

        axis : int
            Dimension along which normalization is performed.

        Notes
        -----
        Modifies the input **inplace**.
        """
        a_sum = a.sum(axis)
        if axis and a.ndim > 1:
            # Make sure we don't divide by zero.
            a[a_sum == 0, :] = 1
            a_sum = a.sum(axis)
        
            a_sum[a_sum == 0] = 1
            shape = list(a.shape)
            shape[axis] = 1
            a_sum.shape = shape

        a /= a_sum

But then I get this error, the covariance matrix looks like this

    [[[  7.29450510e-04]]
     [[  1.02015571e-02]]
     [[  4.53586764e+11]]
     [[  0.00000000e+00]]
     [[  1.56601459e-04]]]

    [2017-01-04 16:40:48,388] [ERROR] component 3 of 'full' covars must be symmetric, positive-definite
    ---------------------------------------------------------------------------
    ValueError                                Traceback (most recent call last)
    <ipython-input-4-79fdf5c77f52> in <module>()
    ----> 1 hmm.predict(seq)

    C:\Users\swong32\AppData\Roaming\Python\Python34\site-packages\hmmlearn\base.py in predict(self, X, lengths)
        332             Labels for each sample from ``X``.
        333         """
    --> 334         _, state_sequence = self.decode(X, lengths)
        335         return state_sequence
        336

    C:\Users\swong32\AppData\Roaming\Python\Python34\site-packages\hmmlearn\base.py in decode(self, X, lengths, algorithm)
        292         """
        293         check_is_fitted(self, "startprob_")
    --> 294         self._check()
        295
        296         algorithm = algorithm or self.algorithm

    C:\Users\swong32\AppData\Roaming\Python\Python34\site-packages\hmmlearn\hmm.py in _check(self)
        173
        174         _validate_covars(self._covars_, self.covariance_type,
    --> 175                          self.n_components)
        176
        177     def _init(self, X, lengths=None):

    C:\Program Files\Anaconda3\envs\py34\lib\site-packages\sklearn\mixture\gmm.py in  _validate_covars(covars, covariance_type, n_components)
        771                     or np.any(linalg.eigvalsh(cv) <= 0)):
        772                 raise ValueError("component %d of 'full' covars must be"
    --> 773                                  "symmetric, positive-definite" % n)
        774     else:
        775         raise ValueError("covariance_type must be one of " +

    ValueError: component 3 of 'full' covars must be symmetric, positive-definite

Any ideas?

**Comment by stevenwong** [comment]
Ok, I was able to fix it by setting the covariance matrices to 1 where it is NaN. I'm sure someone can shed some light on whether this approach is appropriate.

            self._covars_[np.isnan(self._covars_)] = 1
            self.covars_[np.isnan(self.covars_)] = 1

**Comment by superbobry** [comment]
NaNs usually indicate that either you have sever outliers or the model has poor fit to the data. 

Just out of curiosity, could you try this with the master version and lmk if it worked for the same model/data?

**Comment by stevenwong** [comment]
Indeed, I'm training HMMs on a thousand sequences with 5 hidden states. I don't want to look at each manually to see what number of states fit best, so I want it to just train without errors. I noticed that if it can't differentiate between states one tends to dominate (perhaps because the params were randomly initialised) and the other state doesn't get any observations, which is when I start getting NaNs.

**Comment by superbobry** [comment]
You could probably fix the issue by playing with `transmat_prior`. Try setting it to a value >1 to compensate for missing observations, when estimating some entries.

**Comment by idnavid** [comment]
> NaNs usually indicate that either you have severe outliers or the model has poor fit to the data.

This was the case for me. I was able to resolve the issue by finding and removing the outlier. Thanks!
