### ISSUE TITLE
Setting emission probabilities and number of symbols in MultinomialHMM

### ISSUE THREAD

**Issue by hanisaf** [hmmlearn/hmmlearn#17]
I am trying to create a multinomial HMM with 3 states and 2 symbols. Apparently, it is not possible to pass n_symbols nor emissionprob to the constructor. I can use _set_emissionprob after creating the instance but I wonder if there is a more sanctioned way to do it.

```python
n_symbols = 2
n_components = 3
startprob = np.array([0.6, 0.3, 0.1])
transmat = np.array([[0.7, 0.2, 0.1], [0.3, 0.5, 0.2], [0.3, 0.3, 0.4]])
emissionprob  = np.array([[0.1,0.9], [0.5,0.5],[0.9,0.1]])
#this returns an error
model = hmm.MultinomialHMM(n_components=n_components,n_symbols=n_symbols,startprob=startprob,transmat=transmat,emissionprob=emissionprob)
#this works
model = hmm.MultinomialHMM(n_components=n_components,startprob=startprob,transmat=transmat)
model._set_emissionprob(emissionprob)
```

**Comment by superbobry** [comment]
It seems that accepting `n_symbols` via constructor will require another layer of checks during parameter initialization and fitting. This might complicate the code without much benefit for the users. 

As for your example, you don't need to call `_set_emissionprob` directly --- it's just a setter method of the `emissionprobs_` property, so the following should work:
```python
model = hmm.MultinomialHMM(n_components=n_components, startprob=startprob, transmat=transmat)
model.emissionprob_ = emissionprob
```

**Comment by hanisaf** [comment]
Thank you for your prompt answer

**Comment by zachgitt** [comment]
The set of observances seen is often times not the same size as the set of possible observances. It seems the constructor defines n_symbols by taking the number of unique elements in the set of observances. This is problematic in the case where the set of possible observances is larger. I am happy to go in further detail, however, I would like to know if there are any alternatives since n_symbols seems to throw an error.

**Comment by anntzer** [comment]
Please do go into further detail as to what exactly you want to do and what you have tried.
