### ISSUE TITLE
How to fit multiple sequences with GMMHMM

### ISSUE THREAD

**Issue by rockcody** [hmmlearn/hmmlearn#170]
I have servral training sets , and I would like to have one gaussian mixture hmm model to fit them.

Example in the document:
Working with multiple sequences:

X = np.concatenate([X1, X2])
lengths = [len(X1), len(X2)]
hmm.GaussianHMM(n_components=3).fit(X, lengths)  

but when i change GaussianHMM to GMMHMM,
return error:

hmm.GMMHMM(n_components=3).fit(X, lengths)

Traceback (most recent call last):
  File "C:\Users\Cody\workspace\QuickSilver_HMT\hmm_list_sqlite.py", line 141, in hmm_list_pickle
    orderbook_hmm.fit(new_wavelets_coff_array, lengths_list)
  File "build\bdist.win32\egg\hmmlearn\hmm.py", line 998, in fit
    raise ValueError("'lengths' argument is not supported yet")
ValueError: 'lengths' argument is not supported yet

I'd like to know how to fit multiple sequences with  GMMHMM.

thanks!

**Comment by superbobry** [comment]
The master version of `GMMHMM` supports multiple sequences. The expected format is described in section ["Working with multiple sequences"](http://hmmlearn.readthedocs.io/en/latest/tutorial.html#multiple-sequences) of the Tutorial.
