### ISSUE TITLE
Log likelihood in MultinomialHMM using fit method

### ISSUE THREAD

**Issue by Geegee** [hmmlearn/hmmlearn#172]
Hello guys,

Thanks for putting out this package.

In my HMM I have some theoretical considerations, which lead to the fact that the initial transition
matrix should be zero for some of it components. When I'm setting this I get always problems
with the log likelihood when running the fit method, which makes sense, but isn't there a way to do the EM 
algorithm without using log likelihoods? 

Another thing is even when I add some leeway at some point the program breaks I presume because
some parameters are according to the theory converging to zero leading to the same problem. But 
generally I have no idea and would appreciate help.

```
test2 = hmm.MultinomialHMM(n_components=3, verbose=True, n_iter=50, init_params='')
test2.transmat_prior = np.array([[0.8-0.005, 0.2-0.005, 0.01],
                                 [0.01, 0.2-0.005, 0.8-0.005],
                                 [0.2, 0.6, 0.2]])
test2.transmat_ = np.array([[0.8-0.005, 0.2-0.005, 0.01],
                            [0.2, 0.6, 0.2],
                            [0.01, 0.2-0.005, 0.8-0.005]])
test2.startprob_prior = np.array([0.01, 0.01, 0.98])
test2.startprob_ = np.array([0.005, 0.005, 1.0-0.01])
test2.emissionprob_ = np.array([[0.8, 0.2],
                                [0.1, 0.4],
                                [0.1, 0.4]])

test2.n_iter = 100
test2.fit(obs)

```

This outputs:

         1       -1415.8300             +nan
/home/user/.local/lib/python3.4/site-packages/hmmlearn/base.py:459: RuntimeWarning: invalid value encountered in log
  np.log(self.startprob_),

/home/user/.local/lib/python3.4/site-packages/hmmlearn/base.py:468: RuntimeWarning: invalid value encountered in log
  np.log(self.startprob_),

I will append the data that was used in the pickle format:

[observation.npy.tar.gz](https://github.com/hmmlearn/hmmlearn/files/757122/observation.npy.tar.gz)

**Comment by superbobry** [comment]
Hi, you should be able to zero some transition probabilities, this is used e.g. for left-right HMMs. See issue #47 and [this](https://github.com/hmmlearn/hmmlearn/blob/master/hmmlearn/tests/test_gaussian_hmm.py#L202) test.

**Comment by renderit** [comment]
@Geegee Hi, can you share the complete example for `MultinomialHMM`.. In my case, I have a bunch of "buttonStates" (5 to be precise) and I have prior probabilities for a user moving from a Button1 to Button2. Any idea how would I model this?

**Comment by Geegee** [comment]
Hey,

I can send you my code if you like.

For your model you have to give me more information.

Like what are your hidden states and what are your observable states ?

Like the decision from a user to move from one state to another are 
transition

probabilities to my understanding.

Greetings,

Geegee

**Comment by renderit** [comment]
@Geegee Apologies for the late reply.. that'd be great( i guess you can attach here?)
Anyway, my problem is rather simple, and would love your feedback. Essentially, I have these States or "buttons". I have let's say initial probabilities, of a user going from one button to another. After time t1, I want to know which button he "could" be on now(or predict). After every time 't' he presses a some button button, we update the transition matrix and predict the next button. Sounds simple I'm having a hard time incorporating this with the library.. Here's a screenshot for your reference: 
![untitled diagram 1](https://user-images.githubusercontent.com/8347939/27934365-34062c30-625a-11e7-8490-0b38870080f4.png)

**Comment by Geegee** [comment]
I will try to work on it this weekend and refresh my memory a bit more.
For now my concern is that from my understanding of the HMM you need
some Hidden states you get no information from, which interact so to say 
secretely
and you have some states which are visible for you. Typical example a doctor
sees a patient and he shows certain symptoms and based on them you want to
get the actual disease ( which you can't see). I don't understand at 
what point in
your button sequence you don't know which state the user is in and at what
state you get a signal from your user.

It seems to me you don't need a HMM, to make a simple prediction you 
just need
a sample of e.g. 100 users that go from as an example BUTTON 1 to other 
buttons.
If 70 go to BUTTON 4 and 30 got to BUTTON 3 you know that with 70 % 
probability you go
to BUTTON 4 and 30 % you got to BUTTON 3.

If I misunderstood you just let me know :).

Greetings

**Comment by renderit** [comment]
@Geegee Good intuition there! Yes, unfortunately, I don't have enough samples to do this kind of frequentist analysis (  believe me, I'd love to :) ) 
And I agree I don't even need hidden states, it should be a simple graph as shown above. So if i give you a device which has buttons on it. you press a button and then you move on to another, I know some buttons are less probable and some are more.. I want to know a programmatic way to do this. Also, if you press a button right now, good chance you will not use it again.. I know it sounds pretty random but I'd love to give it a try. Any starting points?

**Comment by Zhijing1128** [comment]
Hi @Geegee @superbobry @renderit,

I have a question regarding to the modeling fitting code. In the fitting, does it matter what kind of emission distribution it is? I didn't see in the code that there are different processings for different distributions.

Thanks.
