### ISSUE TITLE
How can I estimate GMM given a state?

### ISSUE THREAD

**Issue by chananshgong** [hmmlearn/hmmlearn#174]
I have labeled data and need to find the GMM given the state. 
In other time segments the state is unknown

**Comment by superbobry** [comment]
Am I right that you want to fit a GMM to the observations labelled with a given state? If yes, this could be done with `GaussianMixture` from scikit-learn.

**Comment by chanansh** [comment]
I actually tried that but it didn't work well because of compatibility issues with the current usage of the old obselete GMM scikit-learn class. Had to use the latter as a temporary work around.

**Comment by anntzer** [comment]
The issue tracker is not the place to learn about HMMs, there are better resources elsewhere.
