### ISSUE TITLE
State shuffled in fitted model

### ISSUE THREAD

**Issue by jingsliu07** [hmmlearn/hmmlearn#177]
I tried to fit an HMM model with simulated data but noticed that the fitted transmit matrix, mean and cov matrices have the states shuffled. Could anyone shed some light on what might be going on? Thanks!

You can regenerate the issue as follows:

```
=================================
import numpy as np
from hmmlearn import hmm

import warnings
warnings.filterwarnings("ignore", category=DeprecationWarning) 

np.random.seed(42)

M_trans = np.array([[0.9, 0.1, 0.0], [0.3, 0.4, 0.3], [0.0, 0.3, 0.7]])
M_start = np.array([0.0, 1.0, 0.0])
mean_emit = np.array([[60.0, 10.0, 0.01], [80.0, 13.0, 0.05], [120.0, 15.0, 0.2]])
cov_emit = np.tile(np.array([[100.0, 9.0, 0.8], [9.0, 1.0, 0.07], [0.8, 0.07, 0.01]]), (3,1,1))

# Simulate outputs
model = hmm.GaussianHMM(n_components=3, covariance_type="full")
model.startprob_ = M_start
model.transmat_ = M_trans
model.means_ = mean_emit
model.covars_ = cov_emit

X, Z = model.sample(500)
X2, Z2 = model.sample(150)

# Estimate parameter:
remodel = hmm.GaussianHMM(n_components=3, covariance_type="full", n_iter=100, params="tmc")
remodel.startprob_ = M_start
X_in = np.concatenate([X, X2])
len_in = [len(X), len(X2)]
          
remodel.fit(X_in, len_in)   
remodel.monitor_.converged
Z_pred1 = remodel.predict(X)   
Z_pred2 = remodel.predict(X2)    

M_trans_fit = remodel.transmat_ 
M_means_fit = remodel.means_ 
M_cov_fit = remodel.covars_
=========================
```
The transition matrix I used to simulate the data is:

State t / State t-1 | S1 | S2 | S3
-|-|-|-
S1 | 0.9 | 0.3 | 0.0
S2 | 0.1 | 0.4 | 0.3
S3 | 0.0 | 0.3 | 0.7

But the estimated transition matrix is:

State t / State t-1 | S1_fit | S2_fit | S3_fit
-|-|-|-
S1_fit | 0.45 | 0.315 | 0.23
S2_fit | 0.32 | 0.68 | 0.0
S3_fit | 0.12 | 0.0 | 0.88

Seems S1 = S3_fit, S2 = S1_fit and S3 = S2_fit.

**Comment by superbobry** [comment]
Hi! `fit` uses random init for all parameters unless you specifically tell it not to do so via `init_parms`. See section "Fixing parameters" of the [tutorial](http://hmmlearn.readthedocs.io/en/latest/tutorial.html).

**Comment by jingsliu07** [comment]
@superbobry Thanks! But I changed the fitting part to the following, still get shuffled results. Am I still not getting the tutorial right?

New fitting code:
```
remodel = hmm.GaussianHMM(n_components=3, covariance_type="full", n_iter=100, params="tmc", init_params = 'tmc')
remodel.startprob_ = M_start
```

New fitted result is:

State t / State t-1 | S1_fit | S2_fit | S3_fit
-|-|-|-
S1_fit | 0.88 | 0.0 | 0.11
S2_fit | 0.0 | 0.68 | 0.32
S3_fit | 0.23 | 0.32 | 0.45

And seems the order is not fixed each time I run it.

**Comment by jingsliu07** [comment]
Ah, assigning prior fixed this. I didn't realize the ordering of the states are interchangeable otherwise.
