### ISSUE TITLE
using GMMHMM problem

### ISSUE THREAD

**Issue by manuel1581** [hmmlearn/hmmlearn#178]
Hi everybody
I'm having troubles using GMMHMM
I have a numpy matrix [n_samples,n_features] which I would to fit into GMMHMM but it seems it doesn´t converge to anything because the transition parameters stay in 0.5 everytime I try to fit the sequence.

Heres the line of code:

model = GMMHMM(n_components=2, n_mix=2 (or more) ,covariance_type="diag", n_iter=1000).fit(my_matrix)

thanks in advance

**Comment by chananshgong** [comment]
n_mix =1 is actually no mixture, so you might try to use GaussianHMM

**Comment by manuel1581** [comment]
Sorry, I'm editing the post, I mistyped. The number of mixtures were more than 1.

**Comment by superbobry** [comment]
0.5 transition probabilities do not necessarily mean the model did not converge. Could you run the fitting with `verbose=True` and post the output here?

Also, try looking at the parameters of the individual components. Are they similar?
