### ISSUE TITLE
python setup.py install returned error

### ISSUE THREAD

**Issue by yelingusa** [hmmlearn/hmmlearn#179]
I am totally new to this hmmlearn and python. While running "python setup.py install" in Anaconda prompt, under window 10 64bit, python3.6, it gives me the following message:

running install
running bdist_egg
running egg_info
writing hmmlearn.egg-info\PKG-INFO
writing dependency_links to hmmlearn.egg-info\dependency_links.txt
writing requirements to hmmlearn.egg-info\requires.txt
writing top-level names to hmmlearn.egg-info\top_level.txt
reading manifest file 'hmmlearn.egg-info\SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'hmmlearn.egg-info\SOURCES.txt'
installing library code to build\bdist.win-amd64\egg
running install_lib
running build_py
running build_ext
No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
building 'hmmlearn._hmmc' extension
error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": http://landinghub.visualstudio.com/visual-opp-build-tools

I had the  MV C++ 2015 redistributable .msi as in the attached file here
![pic](https://cloud.githubusercontent.com/assets/23273961/23329375/164a25c4-fb72-11e6-802d-3698e473a70c.jpg)
what is the actual missing part here? do i need to compile something or change my path?
Any help will be appreciated.

**Comment by superbobry** [comment]
I am no expert when it comes to Windows, but can you make sure you have the C++ compiler installed as suggested in [this](http://stackoverflow.com/questions/38949519/error-while-installing-lxml-through-pip-microsoft-visual-c-14-0-is-required) SO answer.

**Comment by yelingusa** [comment]
I manage to install hmmlearn by finding the latest hmmlearn win 64bit wheel file with cp36 from http://www.lfd.uci.edu/~gohlke/pythonlibs/, and do a 'pip install hmmlearn-*.whl' under Anaconda(3) prompt window.

**Comment by RudyPeng** [comment]
It is helpful,thx.
