### ISSUE TITLE
Traning a HMM

### ISSUE THREAD

**Issue by Sudipta-Paul** [hmmlearn/hmmlearn#180]
Hi,

I am giving an observation sequence as input and trying to find the best possible model parameter. 
following is my code and output.
please let me know if it is the write thing to do what I want to do?
Another thing, what is the default iteration number? (couldn't find in the tutorial)

Regards,
Sudipta 

####################################################
Code:-
---------
from __future__ import division
import sys
import re
import numpy as np
from hmmlearn import hmm

fin=open("./inputs/inputForC_H.txt","r")
print "Name of the file fin: ", fin.name
print "Closed or not : ", fin.closed
print "Opening mode : ", fin.mode
print "Softspace flag : ", fin.softspace

obsList=[]

states = ["S1", "S2"]
n_states = len(states)

observations = ["N", "A", "B", "C"]
n_observations = len(observations)

start_probability = np.array([0.85, 0.15])

transition_probability = np.array([
  [0.3, 0.7],
  [0.1, 0.9]
])

emission_probability = np.array([
  [0.3, 0.3, 0.3, 0.1],
  [0.3, 0.3, 0.3, 0.1]
])

lineCount=1
for line in fin:
    col=line.split()
    if(lineCount >= 9):
       obsList.append(col[3])
    lineCount=lineCount + 1
length=len(obsList)
print "Number of observation:",length
OBS=np.arange(length).reshape(1,length)

for i in range(0,length):
    if(obsList[i]=="N"):
       OBS[0][i]=0
    if(obsList[i]=="A"):
       OBS[0][i]=1
    if(obsList[i]=="B"):
       OBS[0][i]=2
    if(obsList[i]=="C"):

model = hmm.MultinomialHMM(n_components=n_states,n_iter=10)
model.startprob_=start_probability
model.transmat_=transition_probability
model.emissionprob_=emission_probability

bob_says = OBS.T
model = model.fit(bob_says)
logprob, alice_hears = model.decode(bob_says, algorithm="viterbi")
print "Bob says:", ", ".join(map(lambda x: observations[x], bob_says.T[0]))
print "Alice hears:", ", ".join(map(lambda x: states[x], alice_hears))
print "transmission matrix:"
print model.transmat_
print "mission matrix:"
print model.emissionprob_
print "start probability:"
print model.startprob_
#####################################################################

And here is the output:
----------------------------
Number of observation: 462
Bob says: N, N, N, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, N, N, N, B, N, N, N, C, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, B, N, N, N, N, N, N, N, N, N, N, N, B, N, N, N, N, N, N, N, N, N, N, N, B, N, N, N, N, N, N, N, N, N, N, N, B, N, N, N, N, N, N, N, N, N, N, N, N, N, B, N, N, N, N, N, N, N, N, N, N, N, B, N, N, N, N, N, N, N, B, N, N, N, N, N, N, N, N, N, B, N, N, N, N, N, N, N, B, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N
Alice hears: S2, S2, S2, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S1, S2, S2, S2, S2, S2, S2, S2, S2, S2, S2, S2, S2, S2, S2, S2, S2, S2, S2, S2, S2, S2, S2, S2, S2, S2, S2, S2, S2, S2, S2, S2, S2, S2, S2, S2, S2, S2, S2, S2, S2, S2, S2, S2, S2, S2, S2, S2, S2, S2, S2, S2, S2, S2, S2, S2, S2, S2, S2, S2, S2, S2, S2, S2, S2, S2, S2, S2, S2, S2, S2, S2, S2, S2, S2, S2, S2, S2, S2, S2, S2, S2, S2, S2, S2, S2, S2, S2, S2, S2, S2, S2, S2, S2, S2, S2, S2, S2, S2, S2, S2, S2, S2, S2, S2, S2, S2, S2, S2, S2, S2, S2, S2, S2, S2, S2, S2, S2, S2, S2, S2, S2, S2, S2, S2, S2, S2, S2, S2, S2, S2, S2, S2, S2, S2, S2, S2, S2, S2, S2, S2, S2, S2, S2, S2, S2, S2, S2, S2, S2, S2, S2, S2, S2, S2, S2, S2, S2, S2, S2
transmission matrix:
[[ 0.72985906  0.27014094]
 [ 0.29268567  0.70731433]]
mission matrix:
[[ 0.0968945   0.89217472  0.00779986  0.00313092]
 [ 0.57453561  0.38778197  0.03655895  0.00112348]]
start probability:
[ 0.00293658  0.99706342]

**Comment by superbobry** [comment]
Hi Sudipta,

Could you please summarise your code in plain words? This way it would be easier to comment on your approach.

Regarding the number of iterations: `n_iter=10`, you could see it in the [API docs](http://hmmlearn.readthedocs.io/en/latest/api.html#multinomialhmm).
