### ISSUE TITLE
Is there any method to update HMM model dynamically?

### ISSUE THREAD

**Issue by notheory** [hmmlearn/hmmlearn#181]
I wanna use HMM model for quantitative finance. To do this, it's better to update the parameters of the model dynamically as time goes by. When there is a new trading day, there will be one new sample with several features, can I make it to update HMM with this new sample? Or could anyone provide me with some suggestions? Thanks a lot!

**Comment by superbobry** [comment]
I think you are interested in online estimation of HMMs. I've never encountered this in practice, so unfortunately I can't give any specific advice, but in general you could learn the model over mini-batches, using the model from the previous mini-batch as initial approximation for learning over the next mini-batch.
