### ISSUE TITLE
GMMHMM ValueError

### ISSUE THREAD

**Issue by notheory** [hmmlearn/hmmlearn#182]
When I write code following and try to test it,
`gmmhmm = GMMHMM(n_components=5, n_mix=5, covariance_type='diag', n_iter=1000000)
    gmmhmm = gmmhmm.fit(train_X)`

There sometimes exists ValurError
`gmmhmm = gmmhmm.fit(train_X)
 File "D:\Anaconda2\lib\site-packages\hmmlearn\base.py", line 436, in fit 
  bwdlattice)
  File "D:\Anaconda2\lib\site-packages\hmmlearn\hmm.py", line 607, in _accumulate_sufficient_statistics
    raise ValueError
ValueError`

however, sometimes the codes run without any problem (for the same data).
the data is obtained from Internet interface each time the codes run.
I'm confused whether the problem is from hmmlearn package or data interface?
Are there any limitations for parameters of GMMHMM? Thanks a lot!

**Comment by superbobry** [comment]
Are you using the latest `master` or 0.2.0? Could you try manually setting the initial parameter values and passing `init_params=""`, does the `VaueError` still happen?

**Comment by andreaschandra** [comment]
i have the same issue, after i add init_params="" hmm.GMMHMM(), `ValueError` still happen
