### ISSUE TITLE
ValueError: startprob_ must sum to 1.0 (got nan)

### ISSUE THREAD

**Issue by Lila14** [hmmlearn/hmmlearn#186]
from hmmlearn.hmm import GMMHMM
    import numpy as np
    scores = np.loadtxt("scores.txt")
    model = GMMHMM(n_components=3).fit(scores)
    hidden_states = model.predict(scores)

After many deprecation warnings, it produces the following error: 

> File "build/bdist.linux-x86_64/egg/hmmlearn/base.py", line 336, in predict
>  File "build/bdist.linux-x86_64/egg/hmmlearn/base.py", line 296, in decode
 > File "build/bdist.linux-x86_64/egg/hmmlearn/hmm.py", line 713, in _check
 > File "build/bdist.linux-x86_64/egg/hmmlearn/base.py", line 519, in _check
> ValueError: startprob_ must sum to 1.0 (got nan)

My dependencies are all up to date. 

[scores.txt](https://github.com/hmmlearn/hmmlearn/files/848113/scores.txt)

**Comment by jtilahun** [comment]
Hello, I also encountered this issue in the current master branch. I believe that the problem originates from the use of `np.where()` in `_do_mstep()` to update only those entries in `self.startprob_` that are not zero. In `_do_mstep()`, if `self.startprob_prior` is the default value (1.0), and some positions in `stats['start']` contain zero entries, then the same positions in `self.startprob_` will also be set to contain zero entries, and hence will not be updated in future iterations of the EM algorithm. If after many iterations of the algorithm, all positions in `self.startprob_` contain zero entries, then the call to `normalize()` in `_do_mstep()` will result in the division of each entry in `self.startprob_` by the sum of the entries in `self.startprob_`, which is zero. This results in each entry in `self.startprob_` becoming `nan`. Removing the use of `np.where()` in `_do_mstep()` fixed the issue for me.

**Comment by erinversfeld** [comment]
what did you replace np.where() with?

**Comment by jtilahun** [comment]
I replaced [lines 644-645 in hmmlearn/base.py](../blob/be90c5924c8c3f488bc08a9d109e43e2c0a803a7/hmmlearn/base.py#L644-L645) with the line `self.startprob_ = startprob_`.

**Comment by Ayle3125** [comment]
> I replaced [lines 644-645 in hmmlearn/base.py](../blob/be90c5924c8c3f488bc08a9d109e43e2c0a803a7/hmmlearn/base.py#L644-L645) with the line `self.startprob_ = startprob_`.

hi, I face the same problem now, can I ask you how you work it out? I replaced the code but it didn't work. Thx

**Comment by anntzer** [comment]
In the original data provided this is because the system only visits state #2 once, at the last data point, so we fail to compute a meaningful transition probability distribution away from that state.  Likely this should be fixed by getting that distribution according to transmat_prior_.

**Comment by omkarerudkar** [comment]
> In the original data provided this is because the system only visits state #2 once, at the last data point, so we fail to compute a meaningful transition probability distribution away from that state. Likely this should be fixed by getting that distribution according to transmat_prior_.

thanks a ton, it worked. The problem was because of wrong initialization of priors. I removed manually initialized priors and let the library handle it for me.

**Comment by anntzer** [comment]
The original bug is now fixed; a warning is logged at the end of the fit: "Some rows of transmat_ have zero sum because no transition out of the state was ever observed." (200f194)

@danFromTelAviv's issue's is also fixed (f480722).
