### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'means_prior'

### ISSUE THREAD

**Issue by edvinli** [hmmlearn/hmmlearn#187]
I am trying to fit my GMMHMM according to

model = GMMHMM(n_components=3, n_mix=4, covariance_type = 'full', means_prior = means, init_params='stmcw').fit(X,lens)

However, I get the error message as described in the title. 
Further, if I just fit my model as

model = GMMHMM(n_components=3, n_mix=4, covariance_type = 'full').fit(X,lens)

I get the error message:

AttributeError: 'GMMHMM' object has no attribute 'means_'

Am I missing something? I am following the API http://hmmlearn.readthedocs.io/en/latest/api.html#hmmlearn

**Comment by superbobry** [comment]
Hi @edvinli, which version of `hmmlearn` are you using? Could you provide the full stacktrace for the attribute error?

**Comment by edvinli** [comment]
Hi,

I am using version 0.2.0. Well, the only error I get is "AttributeError: 'GMMHMM' object has no attribute 'means_'" when trying to call model.means_

However, I just found out that there is a attribute called gmm_ which is a list of all the GMM for each component (hidden states), and they actually have the means_ attribute which is what I was looking for!

But the main question still remains, how to pass the means_prior argument (the same error appears when trying to set weights prior and covariance prior), with the following traceback:

Traceback (most recent call last):

  File ipython-input-128-5b646282020b, line 1, in module
    model = GMMHMM(n_components=3, n_mix=4, covariance_type = 'full', means_prior = means, init_params='stmcw').fit(X,lens)

TypeError: __init__() got an unexpected keyword argument 'means_prior'

**Comment by superbobry** [comment]
Ah, right. There was no `means_prior` in 0.2.0, see [the API docs](http://hmmlearn.readthedocs.io/en/0.2.0/api.html#hmmlearn.hmm.GMMHMM) for this version.
