### ISSUE TITLE
Can train 3-dim data?

### ISSUE THREAD

**Issue by LeonCgh** [hmmlearn/hmmlearn#190]
I have a 3-data and try to use the hmm, however, i raised an error says it expects data dimension <=2

**Comment by recoveringMathmo** [comment]
When you say 3-data do you mean 1) each emission has three features or 2) each emission is multiple dimensional?

1) your data looks like [[0, 1, 2], [1, 1, 2], ...]]
2) like [[[1, 2], [2, 2]], [[3, 1], [2, 3]], ... ]]]

The first case works, the second case does not. I'm also not sure how you'd go about using HMM's for that type of data.
