### ISSUE TITLE
DeprecationWarning: Function sample_gaussian is deprecated

### ISSUE THREAD

**Issue by ErickTalarico** [hmmlearn/hmmlearn#198]
I am getting the above warning from Ipython, and it's annoying because it repeats far many times at once.

Best regards
Thanks for making your code available

Erick Talarico

**Comment by alexnanchen** [comment]
A similar warning: 

"DeprecationWarning: Function log_multivariate_normal_density is deprecated; The function log_multivariate_normal_density is deprecated in 0.18 and will be removed in 0.20"

Many thanks.

Best regards.

Alexandre Nanchen

**Comment by divinekage** [comment]
How do we augment the usage of GMMHMM to avoid the Warning from coming up?
