### ISSUE TITLE
log likelihood computed incorrectly within _decode_viterbi

### ISSUE THREAD

**Issue by HanGoal** [hmmlearn/hmmlearn#199]
The function _compute_log_likelihood is empty in base.py. This returns empty values when running _BaseHMM using viterbi method. 

    def _decode_viterbi(self, X):
        framelogprob = self._compute_log_likelihood(X)
        return self._do_viterbi_pass(framelogprob)

**Comment by chuston** [comment]
_compute_log_likelihood is defined in the subclasses. E.g. for GaussianHMM, see here: https://github.com/hmmlearn/hmmlearn/blob/master/hmmlearn/base.py#L451

**Comment by superbobry** [comment]
Hi Han, _BaseHMM does not assume any emission distribution and is only meant for subclassing, therefore Viterbi decoding is not applicable.
