### ISSUE TITLE
Why decode()/score() returns a log likelihood value greater than zero?

### ISSUE THREAD

**Issue by airpingu** [hmmlearn/hmmlearn#20]
The log likelihood values returned by ```score()```/```decode()``` is supposed to be a negative value in any ways. Otherwise, I'll de-log it to a probability value greater than 1, which doesn't make sense. Why I always got a positive log likelihood value after calling ```score()```/```decode()```?

**Comment by superbobry** [comment]
The log-likelihood should indeed be negative for discrete emission distributions (e.g. Multinomial), for continuous distributions however it's often not the case. For instance Gaussian p.d.f may yield values greater than 1, see this [post](http://blog.stata.com/2011/02/16/positive-log-likelihood-values-happen/) for a longer explanation.

**Comment by airpingu** [comment]
Thank @superbobry very much. It's great to learn that. Closing this issue.
