### ISSUE TITLE
"n_samples=X should be >= n_clusters=X" Error

### ISSUE THREAD

**Issue by Dim-P** [hmmlearn/hmmlearn#204]
As the title says, while I am using Gaussian Mixture Model emissions, I sometimes get errors such as: `n_samples=31 should be >= n_clusters=32`

Here is the full error report:
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-94-8a7d39921c58> in <module>()
----> 1 model = GMMHMM(n_components=2,n_mix=32, covariance_type="diag", n_iter=100, algorithm="map").fit(x)
      2 print('GMMHMM converged: ',model.monitor_.converged)
      3 #hidden_states = model.predict(x)
      4 #print(hidden_states)
      5 hidden_states = model.decode(x,algorithm="viterbi")

/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/hmmlearn-0.2.1-py3.5-macosx-10.6-intel.egg/hmmlearn/base.py in fit(self, X, lengths)
    422         """
    423         X = check_array(X)
--> 424         self._init(X, lengths=lengths)
    425         self._check()
    426 

/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/hmmlearn-0.2.1-py3.5-macosx-10.6-intel.egg/hmmlearn/hmm.py in _init(self, X, lengths)
    616             kmeans = cluster.KMeans(n_clusters=self.n_mix,
    617                                     random_state=self.random_state)
--> 618             kmeans.fit(X[np.where(labels == label)])
    619             kmeanses.append(kmeans)
    620 

/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/sklearn/cluster/k_means_.py in fit(self, X, y)
    878         """
    879         random_state = check_random_state(self.random_state)
--> 880         X = self._check_fit_data(X)
    881 
    882         self.cluster_centers_, self.labels_, self.inertia_, self.n_iter_ = \

/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/sklearn/cluster/k_means_.py in _check_fit_data(self, X)
    855         if X.shape[0] < self.n_clusters:
    856             raise ValueError("n_samples=%d should be >= n_clusters=%d" % (
--> 857                 X.shape[0], self.n_clusters))
    858         return X
    859 

ValueError: n_samples=31 should be >= n_clusters=32
```

It seems like it is an initialisation problem with the k-means algorithm used from the `sklearn`? I cannot understand however how to fix it.

**Comment by superbobry** [comment]
Hi, no, this is not an initialization problem. In theory you can estimate a 32-component model from 31 observations, but in practice the output would rarely make sense, since in the worst case you'd assign a point to each component (that makes 31 components) and at least one component would always stay uninhibited.

Try decreasing the number of components or adding more data.

**Comment by Dim-P** [comment]
Sorry, your answer was long lost in my emails!

But that's my problem, I was getting this error without using <32 observations (in fact, I think I had hundreds of samples in the sequence when receiving this). Any idea why is that?

I ended up using far less components to make it work always.

**Comment by HiIcy** [comment]
your numbers of train sample is less than your number of cluster that defined

**Comment by emanuelevivoli** [comment]
Maybe you don't apply the transpose to your example matrix.
If you have X referred to h,s,v channels of a 64x64 image (X.shape should be (3, 4096)) , you need X.T (4096, 3) to fit these with kmeans, or other tecniques.
