### ISSUE TITLE
Is it possible to fit n-th order HMM with hmmlearn?

### ISSUE THREAD

**Issue by mt1022** [hmmlearn/hmmlearn#210]
Hi. I want to fit a n-th order HMM model with hmmlearn (where events depend on n previous states). I have read the doc of hmmlearn but could not find related content. Is this feature implemented in hmmlearn?

**Comment by superbobry** [comment]
No, all models in `hmmlearn` are currently of order 1.

**Comment by mt1022** [comment]
That's a pity. Will n-th order HMM be implemented in the future?

**Comment by superbobry** [comment]
I would say this is unlikely precisely because of the limited use-cases for n-th order models.
