### ISSUE TITLE
Invalid predictions (transmat_ not respected)

### ISSUE THREAD

**Issue by kwohlfahrt** [hmmlearn/hmmlearn#214]
As of f66a053e, there is something wrong with model prediction. As far as I can tell, the model `transmat_` is ignored.

The test script below produces impossible predictions, where the state exits the final state (i.e. 0 transition probability to any other state). The first line is the sample, the second is the correct state sequence, and the final line is the predicted state sequence. State 2 has transition probabilities of `0 0 1`, so the state sequence `2 1` should be impossible, but it is still predicted.

```
[ 0.97463307  0.98580524  0.96502726  0.94767963  0.96783919  0.02015515
  0.97280737  1.05605478  1.01784615 -0.01791463  0.02308386  0.0117951
  0.01688058 -0.00290845  0.03611139 -0.03572094 -0.02688102  0.0303838
  0.02761991 -0.00352225]
[0 0 0 0 0 1 0 0 0 2 2 2 2 2 2 2 2 2 2 2]
[0 0 0 0 0 2 0 0 0 1 2 1 2 1 2 1 2 1 2 1]
```

Test script:
```
from hmmlearn import hmm
import numpy as np

np.random.seed(1)

model = hmm.GaussianHMM(
    n_components=3, params='st', init_params='',
)

model.transmat_ = np.array(
    [[0.8, 0.1, 0.1],
     [0.1, 0.9, 0.0],
     [0.0, 0.0, 1.0]]
)
model.means_ = np.array([1.0, 0.0, 0.0]).reshape(-1, 1)
model.covars_ = np.array([0.001, 0.001, 0.001]).reshape(-1, 1)
model.startprob_ = np.array([0.8, 0.1, 0.1])

samples, states = model.sample(20)
prediction = model.predict(samples)

print(samples[:, 0])
print(states)
print(prediction)

np.testing.assert_equal(states, prediction)
```

**Comment by jexner** [comment]
I think the main issue lies in `log_mask_zero` returning 0 for probabilities of 0, which should be -inf. See https://github.com/hmmlearn/hmmlearn/pull/217.
