### ISSUE TITLE
log prob score function

### ISSUE THREAD

**Issue by austinlittle1** [hmmlearn/hmmlearn#220]
It seems like something is wrong when calculating the log probability using the score function OR I could be interpreting the output incorrectly. When I ran this code (in which most of it is literally from the website except the line containing the score function), the logprob is -361.68 which seems highly unlikely given that the sample data was generated from the model. 

import numpy as np
from hmmlearn import hmm
np.random.seed(42)

model = hmm.GaussianHMM(n_components=3, covariance_type="full")
model.startprob_ = np.array([0.6, 0.3, 0.1])
model.transmat_ = np.array([[0.7, 0.2, 0.1],
                            [0.3, 0.5, 0.2],
                            [0.3, 0.3, 0.4]])
model.means_ = np.array([[0.0, 0.0], [3.0, -3.0], [5.0, 10.0]])
model.covars_ = np.tile(np.identity(2), (3, 1, 1))
X, Z = model.sample(100)
logprob = model.score(X)

**Comment by himanData** [comment]
I have the same problem using the score function of hmmlearn. I am interested to know how to interpret that value. I also like to know if there is a function that compute the P(O|HMM)? The exat probability not the log likelihood.

Thanks

**Comment by superbobry** [comment]
The `score` method returns the log-likelihood of the data given the model (i.e. exactly log P(O|HMM)). As for the value, -361.88 looks okay to me. Log-likelihood is unlikely to be exactly 0 for a random sample. You could try doing the same for a simpler model:

```python
>>> from scipy import stats
>>> mvn = stats.multivariate_normal()
>>> X = mvn.rvs(size=100)
>>> mvn.logpdf(X).sum()
-144.15620658097978
```
