### ISSUE TITLE
Handling 0's in emissionprob_

### ISSUE THREAD

**Issue by jmconroy** [hmmlearn/hmmlearn#223]
It seems like that 0's are not tolerated in the Multinomial output emissions and
cause a renormalization:
For example,
(Pdb) model=hmm.MultinomialHMM(n_components=2)

(Pdb) model.emissionprob_=np.array([[1.0, 0],[0,1.0]])
(Pdb) model.emissionprob_
array([[  5.00000000e-01,   1.11022302e-16],
       [  1.11022302e-16,   5.00000000e-01]])

However if the entries are changed so then 0's are replaced with a small number this
renormalization does not happen.   Is this a bug or a feature?

(Pdb) model.emissionprob_=np.array([[1.0e-17, 1.0],[1.0,1.0e-17]])
(Pdb) model.emissionprob_
array([[  1.00000000e-17,   1.00000000e+00],
       [  1.00000000e+00,   1.00000000e-17]])

I think the output of the first case should be 

array([[  1.0   1.11022302e-16],
       [  1.11022302e-16,   1.0 ]])

**Comment by anntzer** [comment]
This no longer happens as of hmmlearn 0.2.2.
