### ISSUE TITLE
hmmlearn GMMHMM Error

### ISSUE THREAD

**Issue by divinekage** [hmmlearn/hmmlearn#225]
Hi, why does the error come up when i do 

`
startprob = np.array([0.6, 0.3, 0.1])
transmat = np.array([[0.7, 0.2, 0.1],
                    [0.3, 0.5, 0.2],
                    [0.3, 0.3, 0.4]])
gmms = [.5, .5, .5]
model = hmm.GMMHMM(n_components=3, n_iter=100, init_params="") # init_params="mcs"
model.startprob_ = startprob
model.transmat_ = transmat
model.gmms_ = gmms

model.fit(np.array([0.6, 0.3, 0.1]))

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-74-e16851f8b966> in <module>()
----> 1 model.fit(np.array([0.6, 0.3, 0.1]))
      2 # model.sample(10)
      3 # model.decode(X)

~\AppData\Local\Continuum\Anaconda3\lib\site-packages\hmmlearn\base.py in fit(self, X, lengths)
    419         """
    420         X = check_array(X)
--> 421         self._init(X, lengths=lengths)
    422         self._check()
    423 

~\AppData\Local\Continuum\Anaconda3\lib\site-packages\hmmlearn\hmm.py in _init(self, X, lengths)
    569 
    570         for g in self.gmms_:
--> 571             g.set_params(init_params=self.init_params, n_iter=0)
    572             g.fit(X)
    573 

AttributeError: 'float' object has no attribute 'set_params'
`

**Comment by lowkeygit** [comment]
I have similar problem. How did you solve it?
