### ISSUE TITLE
Sample spherical GaussianHMM

### ISSUE THREAD

**Issue by Geegee** [hmmlearn/hmmlearn#228]
I'm probably just to stupid to figure out the right input.
I'm following the code given in the tutorial but with an easier 
underlying model ( 3 states with 2 emissions each having a gaussian pdf).
So I was thinking to implement it like this.
For starters I just wanted to create samples:
`
from hmmlearn import hmm

import numpy as np

model = hmm.GaussianHMM(n_components=3, covariance_type="spherical")

model.startprob_ = np.array([0.7, 0.15, 0.15])

model.transmat_ = np.array([[0.85, 0.15, 0.0],
                                               [0.15, 0.7, 0.15], 
                                               [0.0, 0.15, 0.85]])

model.means_ = [-0.2, 0.2, 0.2]

model.covars_ = [0.1, 0.1 , 0.1]

model.sample(100)
`

This gives me the following error 
`
/usr/local/lib/python3.4/dist-packages/sklearn/utils/deprecation.py:70:` DeprecationWarning: Function sample_gaussian is deprecated; The function sample_gaussian is deprecated in 0.18 and will be removed in 0.20. Use numpy.random.multivariate_normal instead.
  warnings.warn(msg, category=DeprecationWarning)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-37-be1ae9f529d1> in <module>()
      3 model.means_ = [-0.2, 0.2, 0.2]
      4 model.covars_ = [0.1, 0.1 , 0.1]
----> 5 model.sample(100)

/usr/local/lib/python3.4/dist-packages/hmmlearn/base.py in sample(self, n_samples, random_state)
    385         state_sequence = [currstate]
    386         X = [self._generate_sample_from_state(
--> 387             currstate, random_state=random_state)]
    388 
    389         for t in range(n_samples - 1):

/usr/local/lib/python3.4/dist-packages/hmmlearn/hmm.py in _generate_sample_from_state(self, state, random_state)
    206             cv = self._covars_[state]
    207         return sample_gaussian(self.means_[state], cv, self.covariance_type,
--> 208                                random_state=random_state)
    209 
    210     def _initialize_sufficient_statistics(self):

/usr/local/lib/python3.4/dist-packages/sklearn/utils/deprecation.py in wrapped(*args, **kwargs)
     69         def wrapped(*args, **kwargs):
     70             warnings.warn(msg, category=DeprecationWarning)
---> 71             return fun(*args, **kwargs)
     72 
     73         wrapped.__name__ = fun.__name__

/usr/local/lib/python3.4/dist-packages/sklearn/mixture/gmm.py in sample_gaussian(mean, covar, covariance_type, n_samples, random_state)
    104     """
    105     rng = check_random_state(random_state)
--> 106     n_dim = len(mean)
    107     rand = rng.randn(n_dim, n_samples)
    108     if n_samples == 1:

TypeError: object of type 'float' has no len()
`

Would be glad for help.

Greetings

Geegee

**Comment by superbobry** [comment]
Fixed in #213.
