### ISSUE TITLE
ImportError: cannot import name _hmmc for macOX

### ISSUE THREAD

**Issue by QWtail** [hmmlearn/hmmlearn#230]
when i try to run plot_hmm_sampling.py in example file using Pycharm on my Mac, the error occurs:
/System/Library/Frameworks/Python.framework/Versions/2.7/bin/python2.7 "/Users/Chris 1/Work/InsiderThreat/Codefiles/Code/Python/hmmlearn-master/examples/plot_hmm_sampling.py"
Traceback (most recent call last):
  File "/Users/Chris 1/Work/InsiderThreat/Codefiles/Code/Python/hmmlearn-master/examples/plot_hmm_sampling.py", line 17, in <module>
    from hmmlearn import hmm
  File "/Users/Chris 1/Work/InsiderThreat/Codefiles/Code/Python/hmmlearn-master/hmmlearn/hmm.py", line 22, in <module>
    from .base import _BaseHMM
  File "/Users/Chris 1/Work/InsiderThreat/Codefiles/Code/Python/hmmlearn-master/hmmlearn/base.py", line 13, in <module>
    from . import _hmmc
ImportError: cannot import name _hmmc

How can i deal with it?? thanks!

**Comment by superbobry** [comment]
How did you install `hmmlearn`?

**Comment by thast** [comment]
Hi @superbobry,
I have the same error on MacOS, but only with Python 3.6, not Python 2.7.

I wanted access to a function not available in the latest PyPi release, so I cloned the repository and ran `python setup.py build_ext --inplace`.

![thibautastic ipython users thibautastic -bash 144x27 2017-10-20 13-12-22](https://user-images.githubusercontent.com/13682747/31840026-60b744f8-b598-11e7-9fbb-c24ae31a413f.png)

**Comment by anntzer** [comment]
Please provide a build log.

**Comment by anntzer** [comment]
Closing for lack of reply; feel free to request a reopen with more info.
