### ISSUE TITLE
Predicting the next observation

### ISSUE THREAD

**Issue by ashishdandekar** [hmmlearn/hmmlearn#232]
I do not know if this is the right place to ask this question; but I want to get a doubt solved. How should I use this library to predict observation?

I trained a `MultinomialHMM` using the data. When I give a sequence of observations as input to `predict` function, it returns me the associated states. Then I can use these states to generate next observation. If I follow maximum likelihood approach in [this](https://stats.stackexchange.com/questions/110049/predict-observation-using-hidden-markov-models) thread, then I run into one problem. I have tried different configuration; but in most of the cases the transition matrix turns out to be mostly diagonal. So, with maximum likelihood approach, I get stuck in the same state with the same observation!

Is there some problem with the training? Is there any function in the library which predicts next _n_ observations?

**Comment by superbobry** [comment]
No, there is no function to predict the next *n* observation.

The shape of the matrix is guided by the data you learn on, so I am afraid you can't do much about the diagonal domination the rest of the transitions. Also, for big enough *n* you would surely see some transitions unless their probability is exactly 0.
