### ISSUE TITLE
ImportError: cannot import name '_hmmc' for windows

### ISSUE THREAD

**Issue by pipi1900** [hmmlearn/hmmlearn#233]
Hi, I'm new to learn hmm model .but there some problems here,I have no way to solve them ,maybe you can give me a hand. thanks.

from hmmlearn import hmm
Traceback (most recent call last):

  File "<ipython-input-66-8b8c029fb053>", line 1, in <module>
    from hmmlearn import hmm

  File "D:\anaconda\lib\site-packages\hmmlearn\hmm.py", line 22, in <module>
    from .base import _BaseHMM

  File "D:\anaconda\lib\site-packages\hmmlearn\base.py", line 13, in <module>
    from . import _hmmc

ImportError: cannot import name '_hmmc'

I had find many ways to solve it from net  ,but setup.py  I didn't find it in the same flow. by the way , my english is poor ,if you don't  understand, please tell me .I will improve my impression as far as possible.
thank you !

**Comment by superbobry** [comment]
How did you install `hmmlearn`?

**Comment by NicolasMontes** [comment]
i have the same error, i intall hmmlearn with pip install hmmlearn

**Comment by anntzer** [comment]
Please provide a build log.

**Comment by anntzer** [comment]
Closing for lack of reply; feel free to request a reopen with more info.
