### ISSUE TITLE
MFCC in non-uniform time instants using multiple utterances alignment

### ISSUE THREAD

**Issue by jgalic** [hmmlearn/hmmlearn#236]
For training SVM classifier I need vectors of the same length. I want to obtain feature vectors in state transitions. Number of states is 15 and dimension of MFCC feature vector is 39. How can I select only feature vectors in state transitions time instants using hmmlearn and viterbi multiple sequence alignment?

**Comment by superbobry** [comment]
@jgalic sorry, I am not qualified to give any advice on MFCC features. You might better off asking on [CV](https://stats.stackexchange.com/) or SO.
