### ISSUE TITLE
missing no_image.png in the doc/image dir

### ISSUE THREAD

**Issue by bboalimoe** [hmmlearn/hmmlearn#24]
~

**Comment by GaelVaroquaux** [comment]
In nilearn, we are now including a version of sphinx-gallery, to avoid
such problems:
http://sphinx-gallery.readthedocs.org/en/latest/

The script that we are using for inclusion can be found here:
https://github.com/nilearn/nilearn/tree/master/doc/sphinxext

**Comment by bboalimoe** [comment]
@GaelVaroquaux what do you mean~ .. the nillearn and the seqlearn are not the same project?~
