### ISSUE TITLE
What is difference between n_mix and n_feature

### ISSUE THREAD

**Issue by NiharikaSinghal** [hmmlearn/hmmlearn#240]
can anyone please clear to me the difference between n_mix and n_feature.

**Comment by superbobry** [comment]
Please refer to the [API docs](http://hmmlearn.readthedocs.io/en/latest/api.html#gmmhmm) for `GMMHMM`. `n_mix` is the number of components in each mixture, `n_features` is the dimensionality of the multivariate normals in each mixture.
