### ISSUE TITLE
Error building hmmlearn on x64 Windows 10 Pro with python 3.6

### ISSUE THREAD

**Issue by John3-16** [hmmlearn/hmmlearn#245]
This is the error command:
`  error: Command "cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IC:\\Users\\john3\\Anaconda3\\envs\\AIND\\lib\\site-packages\\numpy\\core\\include -IC:\Users\john3\Anaconda3\envs\AIND\include -IC:\Users\john3\Anaconda3\envs\AIND\include /Tchmmlearn/_hmmc.c /Fobuild\temp.win-amd64-3.6\Release\hmmlearn/_hmmc.obj -O3" failed with exit status 127`

**Comment by anntzer** [comment]
Are you running this in a shell with msvc actually installed?

**Comment by anntzer** [comment]
Closing from lack of reply; feel free to request a reopen with more info.
