### ISSUE TITLE
Why do we need the startprob_prior?

### ISSUE THREAD

**Issue by tryfonch** [hmmlearn/hmmlearn#246]
What is the purpose of using startprob_prior? If we want to initialize the startprob_ (the π according to theory's notation) we can do it by setting the `model.startprob_`. 

Therefore it seems to be redundant unless it is used for another purpose that I am missing. Can someone please help?

**Comment by superbobry** [comment]
In MAP inference all parameters must have a prior, this includes `startprob_` which a priori is assumed to follow the Dirichlet distribution.
