### ISSUE TITLE
Tagged release for 0.2.1

### ISSUE THREAD

**Issue by mcg1969** [hmmlearn/hmmlearn#247]
It would seem that HMMLearn was given a version bump on [March 2, 2016](https://github.com/hmmlearn/hmmlearn/commit/a07261706510421c02f071d5e5d5a604a24dfffe), but no tag was created nor release built. Is that simply a packaging issue, or is 0.2.1 still in pre-release?

If 0.2.1 truly was released, I'd like to request that a tag be added and a release be created for it. My interest here is building a conda-forge package.

**Comment by mcg1969** [comment]
Actually, I see that [this commit](https://github.com/hmmlearn/hmmlearn/commit/7228c1c3b3f74cf5b3efc2b06269ac0d7d318f18) extends the changelog for 0.2.1, so it seems reasonable to assume there is not a taggable release yet. Is there a timeline or milestone you can share?

**Comment by anntzer** [comment]
0.2.2 is out.
