### ISSUE TITLE
Is predict_proba() giving the emission probabilities?

### ISSUE THREAD

**Issue by tryfonch** [hmmlearn/hmmlearn#248]
Supposing I have a GaussianHMM(n_components = 3) model. After I train it on my X dataset (X array with shape(5,1)). I run the command model.predict_proba(X) and it is giving out a 5 row by 3 column array. 

What exactly is that array showing me? Is it the emission probabilities in other words P(X|S) -where S is the state-?

**Comment by remidomingues** [comment]
Hi tryfonch,

As shown in the [documentation ](http://hmmlearn.readthedocs.io/en/stable/api.html#hmmlearn.hmm.GaussianHMM.predict_proba), predict_proba returns the probability of each sequence under each component, hence the shape (n_samples, n_components).

Although I agree that it could be nice to have a sklearn-like API, with predict_proba unchanged, and score_samples returning the probability of each sequence over the entire model, as this is the case for example in [GMM](http://scikit-learn.org/stable/modules/generated/sklearn.mixture.GaussianMixture.html#sklearn.mixture.GaussianMixture.score_samples).

**Comment by cruyffturn** [comment]
@remidomingues if it's possible can you mathematically define the predict_proba ?

The API states:
> Compute the posterior probability for each state in the model.

There are (num_components)**T hidden states but it is returning only (num_components)*T probabilities.

**Comment by cruyffturn** [comment]
I have found my answer! In my understanding it gives the gamma in https://en.wikipedia.org/w/index.php?title=Baum%E2%80%93Welch_algorithm&section=6#Update.

**Comment by anntzer** [comment]
Thanks @cruyffturn for providing a reference.
