### ISSUE TITLE
Deprecation warning

### ISSUE THREAD

**Issue by apiszcz** [hmmlearn/hmmlearn#250]
(1) The following error is emitted when running the first example in the documentation

lib\sklearn\utils\deprecation.py:77: DeprecationWarning: Function sample_gaussian is deprecated; The function sample_gaussian is deprecated in 0.18 and will be removed in 0.20. Use numpy.random.multivariate_normal instead.

(2)` hmmlearn.__version__` does not appear to be an attribute.

**Comment by brianbolze** [comment]
Similar issue with GMMHMM. Any updates?

**Comment by traddo** [comment]
with warnings.catch_warnings():
        warnings.simplefilter("ignore")
        hmm=GaussianHMM(n_components=n_components,covariance_type=type,n_iter=iter).fit(X)

**Comment by anntzer** [comment]
Closed as of master by #213.
