### ISSUE TITLE
GMMHMM error - is there a bug?

### ISSUE THREAD

**Issue by tryfonch** [hmmlearn/hmmlearn#251]
My version of hmmlearn is 0.3.0b

Why is the following giving an  error? Is there a  #bug?
```
import numpy as np
from hmmlearn import hmm

size = 30
data = np.concatenate((np.random.normal(0,1,size), np.random.normal(5,2,size)))
np.random.shuffle(data)
x = np.reshape(data,(-1,3))

model = hmm.GMMHMM(n_components=4, n_mix=5)
model.fit(x)
```

```
Traceback (most recent call last):

  File "<ipython-input-7-279053d5b019>", line 2, in <module>
    model.fit(x)

  File "C:\Users\tchristopoulos\AppData\Local\Continuum\Anaconda2\envs\py36env\lib\site-packages\hmmlearn\base.py", line 425, in fit
    self._init(X, lengths=lengths)

  File "C:\Users\tchristopoulos\AppData\Local\Continuum\Anaconda2\envs\py36env\lib\site-packages\hmmlearn\hmm.py", line 608, in _init
    kmeans.fit(X[np.where(labels == label)])

  File "C:\Users\tchristopoulos\AppData\Local\Continuum\Anaconda2\envs\py36env\lib\site-packages\sklearn\cluster\k_means_.py", line 884, in fit
    X = self._check_fit_data(X)

  File "C:\Users\tchristopoulos\AppData\Local\Continuum\Anaconda2\envs\py36env\lib\site-packages\sklearn\cluster\k_means_.py", line 861, in _check_fit_data
    X.shape[0], self.n_clusters))

ValueError: n_samples=2 should be >= n_clusters=5
```

**Comment by flxbe** [comment]
Before starting to fit the data, `n_components` initial clusters for the different states are created. Each cluster will then be further separated into `n_mix` clusters to get a first estimate of the parameters for each gaussian.

It seems like one of the initial clusters only ends up with 2 samples, while at least 5 are required for the second level clustering. It looks like a bug to me. The clustering should acount for a lower bound of members per cluster.

I do not have a lot of experience with clustering, and [`sklearn.cluster.KMeans`](http://scikit-learn.org/stable/modules/generated/sklearn.cluster.KMeans.html) does not include an option for such a lower bound. Intuitively, the clustering should be separated into two steps:

1. Find the `min_cluster_size` nearest neighbours and assign them to each center.
2. Assign the rest of the datapoints using kmeans.

Ideally, this would only differ from the origianl kmeans result if the lower bound constraint is violated. Maybe such a solution already exists?

**Comment by tryfonch** [comment]
@flxbe Thanks! Looks like a bug for me as well

**Comment by ArjunWhabi** [comment]
Is there a solution to this bug ? I'm having the same error.
ValueError: n_samples=2 should be >= n_clusters=5
