### ISSUE TITLE
GMMHMM installed with pip does not work. (version 0.2.0)

### ISSUE THREAD

**Issue by labodyn** [hmmlearn/hmmlearn#253]
pip install only supports version 0.2.0, not the current 0.2.1. The GMMHMM class doesn't learn the correct transmat in version 0.2.0 using the fit() method. This is a result of a lack symmetry breaking in the _init method, leading to the GMM's not being able to diverge in parameter values.

A quick and dirty fix for version 0.2.0 could be made by adding some noise to the inits:
```
import random

    def _init(self, X, lengths=None):
            super(GMMHMM, self)._init(X, lengths=lengths)
            for g in self.gmms_:
                g.set_params(init_params=self.init_params, n_iter=0)
                g.fit(X)
                # add 10% noise
                g.means_ = g.means_ * (0.9 + 0.2 * random.random())
                g.covars_ = g.covars_ * (0.9 + 0.2 * random.random())
```

**Comment by anntzer** [comment]
A complete rewrite went in in #107 (not released yet).  Please test against master.
