### ISSUE TITLE
Python 3 compatibility

### ISSUE THREAD

**Issue by Adamtaranto** [hmmlearn/hmmlearn#259]
Any plans for a Python 3 friendly release?

**Comment by ruffsl** [comment]
Python 2 will soon be EOL. 
(1 Year 9 Months 11 Days 7 ...)
https://pythonclock.org/

**Comment by andreaschandra** [comment]
any update on this?

**Comment by anntzer** [comment]
0.2 is already Py3(<3.7) compatible, master is also compatible with Py3.
