### ISSUE TITLE
Training HMM with same data predicts different hidden states

### ISSUE THREAD

**Issue by grantathon** [hmmlearn/hmmlearn#271]
I'm currently working on training an HMM using hmmlearn, but whenever I train a particular model with the same training data, the predicted hidden states sometimes differ between trainings.

For example, if I train an HMM for two hidden states and extract the predicted hidden states based on the training data, I might get something like this:

![hiddenstate1](https://user-images.githubusercontent.com/4745152/36351374-1fdab710-14a9-11e8-8737-3770bd79d18f.png)

Now let's say I train another HMM with the same exact parameters and training data, but this time the hidden states are predicted to look something like this:

![hiddenstate2](https://user-images.githubusercontent.com/4745152/36351376-2c9beaf0-14a9-11e8-927c-c0871d62e546.png)

Now the models are both able to detect correctly the change of states, but I want the actual labels of the states (e.g., 0 or 1) to be the same between both models. How can I achieve this using hmmlearn?

I also posted this [here](https://stats.stackexchange.com/questions/329149/training-hmm-with-same-data-predicts-different-hidden-states).

**Comment by maxmouchet** [comment]
The EM algorithm [1] used to learn the HMM parameters only finds a local minima of the likelihood function, which depends of its initialization. By default the parameters are initialized randomly.  

You can either set the seed `np.random.seed(XXX)` or pass some initial values (see [Fixing Parameters](http://hmmlearn.readthedocs.io/en/latest/tutorial.html#training-hmm-parameters-and-inferring-the-hidden-states).


[1] https://en.wikipedia.org/wiki/Baum–Welch_algorithm

**Comment by grantathon** [comment]
Thanks for your help @maxmouchet! So you're saying that if I set the seed `np.random.seed(XXX)`, the labels of the hidden states will stay consistent between training of different models with the same number of hidden states?

**Comment by maxmouchet** [comment]
It should!
