### ISSUE TITLE
Which model to use when

### ISSUE THREAD

**Issue by foobar8675** [hmmlearn/hmmlearn#279]
Not an issue, apologies in advance. I was just wondering if there is an explanation of which of the 3  models to use when?

-Hidden Markov Model with Gaussian emissions.
-Hidden Markov Model with Gaussian mixture emissions.
-Hidden Markov Model with multinomial (discrete) emissions

**Comment by anntzer** [comment]
The issue tracker is not the place to learn about HMMs, there are better resources elsewhere.
