### ISSUE TITLE
Error install hmmlearn

### ISSUE THREAD

**Issue by vibhuti16** [hmmlearn/hmmlearn#281]
I am having the following error instaling hmmlean. 

Collecting hmmlearn
  Using cached https://files.pythonhosted.org/packages/dd/9e/6822b0cb04660f897cffb0ef39020423b342548803015f9b6e7dffeed2a8/hmmlearn-0.2.0.tar.gz
Building wheels for collected packages: hmmlearn
  Running setup.py bdist_wheel for hmmlearn ... error
  Complete output from command c:\users\vibhuti\anaconda3\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\Vibhuti\\AppData\\Local\\Temp\\pip-install-e43n98hp\\hmmlearn\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d C:\Users\Vibhuti\AppData\Local\Temp\pip-wheel-r0ict432 --python-tag cp36:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.6
  creating build\lib.win-amd64-3.6\hmmlearn
  copying hmmlearn\base.py -> build\lib.win-amd64-3.6\hmmlearn
  copying hmmlearn\hmm.py -> build\lib.win-amd64-3.6\hmmlearn
  copying hmmlearn\utils.py -> build\lib.win-amd64-3.6\hmmlearn
  copying hmmlearn\__init__.py -> build\lib.win-amd64-3.6\hmmlearn
  creating build\lib.win-amd64-3.6\hmmlearn\tests
  copying hmmlearn\tests\test_base.py -> build\lib.win-amd64-3.6\hmmlearn\tests
  copying hmmlearn\tests\test_gaussian_hmm.py -> build\lib.win-amd64-3.6\hmmlearn\tests
  copying hmmlearn\tests\test_gmm_hmm.py -> build\lib.win-amd64-3.6\hmmlearn\tests
  copying hmmlearn\tests\test_multinomial_hmm.py -> build\lib.win-amd64-3.6\hmmlearn\tests
  copying hmmlearn\tests\test_utils.py -> build\lib.win-amd64-3.6\hmmlearn\tests
  copying hmmlearn\tests\__init__.py -> build\lib.win-amd64-3.6\hmmlearn\tests
  running build_ext
  No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
  building 'hmmlearn._hmmc' extension
  creating build\temp.win-amd64-3.6
  creating build\temp.win-amd64-3.6\Release
  creating build\temp.win-amd64-3.6\Release\hmmlearn
  cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MT -Ic:\\users\\vibhuti\\anaconda3\\lib\\site-packages\\numpy\\core\\include -Ic:\users\vibhuti\anaconda3\include -Ic:\users\vibhuti\anaconda3\include /Tchmmlearn/_hmmc.c /Fobuild\temp.win-amd64-3.6\Release\hmmlearn/_hmmc.obj -O3

  error: Command "cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MT -Ic:\\users\\vibhuti\\anaconda3\\lib\\site-packages\\numpy\\core\\include -Ic:\users\vibhuti\anaconda3\include -Ic:\users\vibhuti\anaconda3\include /Tchmmlearn/_hmmc.c /Fobuild\temp.win-amd64-3.6\Release\hmmlearn/_hmmc.obj -O3" failed with exit status 127

  ----------------------------------------
  Failed building wheel for hmmlearn
  Running setup.py clean for hmmlearn
Failed to build hmmlearn
Installing collected packages: hmmlearn
  Running setup.py install for hmmlearn ... error
    Complete output from command c:\users\vibhuti\anaconda3\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\Vibhuti\\AppData\\Local\\Temp\\pip-install-e43n98hp\\hmmlearn\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\Vibhuti\AppData\Local\Temp\pip-record-jzs40nue\install-record.txt --single-version-externally-managed --compile --user --prefix=:
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.6
    creating build\lib.win-amd64-3.6\hmmlearn
    copying hmmlearn\base.py -> build\lib.win-amd64-3.6\hmmlearn
    copying hmmlearn\hmm.py -> build\lib.win-amd64-3.6\hmmlearn
    copying hmmlearn\utils.py -> build\lib.win-amd64-3.6\hmmlearn
    copying hmmlearn\__init__.py -> build\lib.win-amd64-3.6\hmmlearn
    creating build\lib.win-amd64-3.6\hmmlearn\tests
    copying hmmlearn\tests\test_base.py -> build\lib.win-amd64-3.6\hmmlearn\tests
    copying hmmlearn\tests\test_gaussian_hmm.py -> build\lib.win-amd64-3.6\hmmlearn\tests
    copying hmmlearn\tests\test_gmm_hmm.py -> build\lib.win-amd64-3.6\hmmlearn\tests
    copying hmmlearn\tests\test_multinomial_hmm.py -> build\lib.win-amd64-3.6\hmmlearn\tests
    copying hmmlearn\tests\test_utils.py -> build\lib.win-amd64-3.6\hmmlearn\tests
    copying hmmlearn\tests\__init__.py -> build\lib.win-amd64-3.6\hmmlearn\tests
    running build_ext
    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
    building 'hmmlearn._hmmc' extension
    creating build\temp.win-amd64-3.6
    creating build\temp.win-amd64-3.6\Release
    creating build\temp.win-amd64-3.6\Release\hmmlearn
    cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MT -Ic:\\users\\vibhuti\\anaconda3\\lib\\site-packages\\numpy\\core\\include -Ic:\users\vibhuti\anaconda3\include -Ic:\users\vibhuti\anaconda3\include /Tchmmlearn/_hmmc.c /Fobuild\temp.win-amd64-3.6\Release\hmmlearn/_hmmc.obj -O3

    error: Command "cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MT -Ic:\\users\\vibhuti\\anaconda3\\lib\\site-packages\\numpy\\core\\include -Ic:\users\vibhuti\anaconda3\include -Ic:\users\vibhuti\anaconda3\include /Tchmmlearn/_hmmc.c /Fobuild\temp.win-amd64-3.6\Release\hmmlearn/_hmmc.obj -O3" failed with exit status 127

**Comment by renatopaschoalim** [comment]
Thank you so much. Now is working \o/
I gonna share your solution.
