### ISSUE TITLE
How to git start probability vector π and a transition probability matrix A

### ISSUE THREAD

**Issue by asd3427** [hmmlearn/hmmlearn#282]
Hello I am a student who recently learned that HMM needs to use python to complete an HMM model training, but I have a problem that my data is str type I do not know how to get start probability vector π and a transition probability matrix A. How can I solve this problem? Does the function inside hmmlearn help me solve this problem? I uploaded my data. Please help me.
Sorry for my poor English.......
[hmmData.txt](https://github.com/hmmlearn/hmmlearn/files/2054464/hmmData.txt)

**Comment by erfan-ghadery** [comment]
You should convert your text data to bag of words. for doing this , use gensim library.

**Comment by anntzer** [comment]
The issue tracker is not the place to learn about HMMs, there are better resources elsewhere.
