### ISSUE TITLE
gmmHmm valueError

### ISSUE THREAD

**Issue by sm-jalali-f** [hmmlearn/hmmlearn#283]
I use gmmhmm such as below:
```
model = hmm.GMMHMM(algorithm='viterbi', covars_prior=0.01, n_components=3,init_params="",
                       n_iter=1000, n_mix=2, random_state=None, startprob_prior=1.0, tol=0.01,
                       transmat_prior=1.0, verbose=True)
```
but it crashed. 
error:
`File "/home/mohamad/.local/lib/python3.5/site-packages/hmmlearn/hmm.py", line 607, in _accumulate_sufficient_statistics
    raise ValueError
ValueError`

but when i decrease the number of input data, this error not occured.
what's the problem? how am i solve it?

**Comment by anntzer** [comment]
GMMHMM was fully rewritten in #107 (master only); please request a reopen if this is still a problem.
