### ISSUE TITLE
Performing Predictions

### ISSUE THREAD

**Issue by StupidSushi** [hmmlearn/hmmlearn#286]
Dear all,
I have a function f(t) for which I want to predict futures value. Basically, it is the very same issue as described in 
http://hmmlearn.readthedocs.io/en/latest/auto_examples/plot_hmm_stock_analysis.html#sphx-glr-auto-examples-plot-hmm-stock-analysis-py

In this tutorial it is not explained, how to predict future observation values. There are also already other threads referring to the very same question. As far as I got it, I need to look at the transition matrix from my last data point t, to deduce in which hidden states I will be a t+1. But how can I conclude from the hidden states t+1 the observed values at t+1? I think the answer to this question is straight forward and it is quite dumb that I dont see it, but the explanations of google and Co do not really help me :( And the publications I read about stock exchange prediction are somehow not very clear for me in that part.

Cheers

**Comment by anntzer** [comment]
The issue tracker is not the place to learn about HMMs, there are better resources elsewhere.
