### ISSUE TITLE
GMMHMM model not accepting 'lengths' parameter

### ISSUE THREAD

**Issue by DefinitelyArnav** [hmmlearn/hmmlearn#287]
I've the latest hmmlearn version installed: 0.2.1
But I'm unable to pass 'lengths' parameter in my fit function while implementing a GMMHMM model.
Here's the code: 
    #hmmlearn version 0.2.1

    #HMM Models
    from hmmlearn import hmm
    model_anger = hmm.GMMHMM(n_components=1,n_mix=2, covariance_type="diag", 
    n_iter=1000).fit(anger,lengths=lengths_anger)

This gives me the following error:
    `ValueError: 'lengths' argument is not supported yet`
Note that my hmmlearn is already in its latest version.

But the same parameters work fine on Gaussianhmm model.
Can someone guide me on how can I model gmmhmm with multiple fitting sequences?

**Comment by anntzer** [comment]
This was fixed in https://github.com/hmmlearn/hmmlearn/commit/fa6bc1f.
