### ISSUE TITLE
Documentation link to source code broken

### ISSUE THREAD

**Issue by 1kastner** [hmmlearn/hmmlearn#288]
Hi there,

first of all thanks for this awesome library and the great documentation! When I wanted to look into the source code coming from the [documentation](http://hmmlearn.readthedocs.io/en/stable/api.html#hmmlearn.hmm.MultinomialHMM) via the link called "source", I saw that sadly a small problem sneaked in. It linked me e.g. to https://github.com/checkouts/stable/doc/build/bdist.linux-x86_64/egg/hmmlearn/base.py#L317-L335 but there was nothing. I gues this is because we are in the build folder here. If this could be fixed, that'd be great! Thank you a lot in advance!

**Comment by anntzer** [comment]
This appears to be fixed as of now.  Feel free to reping if this is still a problem.

**Comment by 1kastner** [comment]
Cool thank you!
