### ISSUE TITLE
Error running example

### ISSUE THREAD

**Issue by wendeldr** [hmmlearn/hmmlearn#291]
Hey folks, I am having a issue running your example code from your documentation.  Your example Plot_hmm_sampling shows the plot with the components scattered:
![scattered](https://user-images.githubusercontent.com/6619733/42383473-4d1a9ca4-8105-11e8-9bc2-9d544bcf7863.png)

Mine is showing the components separated but the points are linear:
![linear](https://user-images.githubusercontent.com/6619733/42383333-ed79a07e-8104-11e8-8017-dce7327c710d.png)

All I've done is download and run the code.  Is there something wrong with the example or image on the website?  Or is this just a visual problem?

I'm using Python 3.6.5 (v3.6.5:f59c0932b4) and installed hmmlearn with pip

**Comment by anntzer** [comment]
I can't reproduce as of master.  Please request a reopen if you can reproduce this **with master**, including your versions of numpy and scikit-learn.
