### ISSUE TITLE
ImportError: cannot import name '_hmmc'

### ISSUE THREAD

**Issue by manitadayon** [hmmlearn/hmmlearn#292]
I am trying to use the hmm library in Python using this website 

https://github.com/hmmlearn/hmmlearn

and install the package using the following:

pip install -U --user hmmlearn

however when I try to use it I get following error:

ImportError: cannot import name '_hmmc'

I don't understand what this thread saying since I am still new to Python terminologies.

**Comment by superbobry** [comment]
Please provide:
* OS
* Python version
* C/C++ compiler version
* full output of `pip install`,
* and the traceback of the `ImportError`

**Comment by manitadayon** [comment]
Thanks for responding. **My operating system** is Window 10 Home

**Python**: Python 3.6. I am using Jupyter Notebook from Anaconda

**C/C++ Compiler** I am not sure what version (Running it from Matlab Console )
it seems I have Microsoft Visual Studio version 14.0 (2015 Professional)

**full output of pip_install:**


$ python setup.py install
running install
running bdist_egg
running egg_info
writing hmmlearn.egg-info\PKG-INFO
writing dependency_links to hmmlearn.egg-info\dependency_links.txt
writing requirements to hmmlearn.egg-info\requires.txt
writing top-level names to hmmlearn.egg-info\top_level.txt
reading manifest file 'hmmlearn.egg-info\SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'hmmlearn.egg-info\SOURCES.txt'
installing library code to build\bdist.win32\egg
running install_lib
running build_py
running build_ext
No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
creating build\bdist.win32\egg
creating build\bdist.win32\egg\hmmlearn
copying build\lib.win32-3.6\hmmlearn\base.py -> build\bdist.win32\egg\hmmlearn
copying build\lib.win32-3.6\hmmlearn\hmm.py -> build\bdist.win32\egg\hmmlearn
copying build\lib.win32-3.6\hmmlearn\stats.py -> build\bdist.win32\egg\hmmlearn
creating build\bdist.win32\egg\hmmlearn\tests
copying build\lib.win32-3.6\hmmlearn\tests\conftest.py -> build\bdist.win32\egg\hmmlearn\tests
copying build\lib.win32-3.6\hmmlearn\tests\test_base.py -> build\bdist.win32\egg\hmmlearn\tests
copying build\lib.win32-3.6\hmmlearn\tests\test_gaussian_hmm.py -> build\bdist.win32\egg\hmmlearn\tests
copying build\lib.win32-3.6\hmmlearn\tests\test_gmm_hmm.py -> build\bdist.win32\egg\hmmlearn\tests
copying build\lib.win32-3.6\hmmlearn\tests\test_gmm_hmm_new.py -> build\bdist.win32\egg\hmmlearn\tests
copying build\lib.win32-3.6\hmmlearn\tests\test_multinomial_hmm.py -> build\bdist.win32\egg\hmmlearn\tests
copying build\lib.win32-3.6\hmmlearn\tests\test_utils.py -> build\bdist.win32\egg\hmmlearn\tests
copying build\lib.win32-3.6\hmmlearn\tests\__init__.py -> build\bdist.win32\egg\hmmlearn\tests
copying build\lib.win32-3.6\hmmlearn\utils.py -> build\bdist.win32\egg\hmmlearn
copying build\lib.win32-3.6\hmmlearn\_hmmc.cp36-win32.pyd -> build\bdist.win32\egg\hmmlearn
copying build\lib.win32-3.6\hmmlearn\__init__.py -> build\bdist.win32\egg\hmmlearn
byte-compiling build\bdist.win32\egg\hmmlearn\base.py to base.cpython-36.pyc
byte-compiling build\bdist.win32\egg\hmmlearn\hmm.py to hmm.cpython-36.pyc
byte-compiling build\bdist.win32\egg\hmmlearn\stats.py to stats.cpython-36.pyc
byte-compiling build\bdist.win32\egg\hmmlearn\tests\conftest.py to conftest.cpython-36.pyc
byte-compiling build\bdist.win32\egg\hmmlearn\tests\test_base.py to test_base.cpython-36.pyc
byte-compiling build\bdist.win32\egg\hmmlearn\tests\test_gaussian_hmm.py to test_gaussian_hmm.cpython-36.pyc
byte-compiling build\bdist.win32\egg\hmmlearn\tests\test_gmm_hmm.py to test_gmm_hmm.cpython-36.pyc
byte-compiling build\bdist.win32\egg\hmmlearn\tests\test_gmm_hmm_new.py to test_gmm_hmm_new.cpython-36.pyc
byte-compiling build\bdist.win32\egg\hmmlearn\tests\test_multinomial_hmm.py to test_multinomial_hmm.cpython-36.pyc
byte-compiling build\bdist.win32\egg\hmmlearn\tests\test_utils.py to test_utils.cpython-36.pyc
byte-compiling build\bdist.win32\egg\hmmlearn\tests\__init__.py to __init__.cpython-36.pyc
byte-compiling build\bdist.win32\egg\hmmlearn\utils.py to utils.cpython-36.pyc
byte-compiling build\bdist.win32\egg\hmmlearn\__init__.py to __init__.cpython-36.pyc
creating stub loader for hmmlearn\_hmmc.cp36-win32.pyd
byte-compiling build\bdist.win32\egg\hmmlearn\_hmmc.py to _hmmc.cpython-36.pyc
creating build\bdist.win32\egg\EGG-INFO
copying hmmlearn.egg-info\PKG-INFO -> build\bdist.win32\egg\EGG-INFO
copying hmmlearn.egg-info\SOURCES.txt -> build\bdist.win32\egg\EGG-INFO
copying hmmlearn.egg-info\dependency_links.txt -> build\bdist.win32\egg\EGG-INFO
copying hmmlearn.egg-info\requires.txt -> build\bdist.win32\egg\EGG-INFO
copying hmmlearn.egg-info\top_level.txt -> build\bdist.win32\egg\EGG-INFO
writing build\bdist.win32\egg\EGG-INFO\native_libs.txt
zip_safe flag not set; analyzing archive contents...
hmmlearn.__pycache__._hmmc.cpython-36: module references __file__
creating 'dist\hmmlearn-0.2.1-py3.6-win32.egg' and adding 'build\bdist.win32\egg' to it
removing 'build\bdist.win32\egg' (and everything under it)
Processing hmmlearn-0.2.1-py3.6-win32.egg
removing 'c:\users\manie\downloads\python\lib\site-packages\hmmlearn-0.2.1-py3.6-win32.egg' (and everything under it)
creating c:\users\manie\downloads\python\lib\site-packages\hmmlearn-0.2.1-py3.6-win32.egg
Extracting hmmlearn-0.2.1-py3.6-win32.egg to c:\users\manie\downloads\python\lib\site-packages
hmmlearn 0.2.1 is already the active version in easy-install.pth

Installed c:\users\manie\downloads\python\lib\site-packages\hmmlearn-0.2.1-py3.6-win32.egg
Processing dependencies for hmmlearn==0.2.1
Searching for scikit-learn==0.19.1
Best match: scikit-learn 0.19.1
Adding scikit-learn 0.19.1 to easy-install.pth file

Using c:\users\manie\downloads\python\lib\site-packages
Searching for numpy==1.14.1
Best match: numpy 1.14.1
Adding numpy 1.14.1 to easy-install.pth file

Using c:\users\manie\downloads\python\lib\site-packages
Finished processing dependencies for hmmlearn==0.2.1


**Running following example** 
import numpy as np
from hmmlearn import hmm
np.random.seed(42)

model = hmm.GaussianHMM(n_components=3, covariance_type="full")
model.startprob_ = np.array([0.6, 0.3, 0.1])
model.transmat_ = np.array([[0.7, 0.2, 0.1],
...                             [0.3, 0.5, 0.2],
...                             [0.3, 0.3, 0.4]])
model.means_ = np.array([[0.0, 0.0], [3.0, -3.0], [5.0, 10.0]])
model.covars_ = np.tile(np.identity(2), (3, 1, 1))
X, Z = model.sample(100)


**The error output is as follow:**

ImportError                               Traceback (most recent call last)
<ipython-input-1-12b44993707e> in <module>()
      1 import numpy as np
----> 2 from hmmlearn import hmm
      3 np.random.seed(42)
      4 
      5 model = hmm.GaussianHMM(n_components=3, covariance_type="full")

~\AppData\Roaming\Python\Python36\site-packages\hmmlearn\hmm.py in <module>()
     19 from sklearn.utils import check_random_state
     20 
---> 21 from .base import _BaseHMM
     22 from .utils import iter_from_X_lengths, normalize
     23 

~\AppData\Roaming\Python\Python36\site-packages\hmmlearn\base.py in <module>()
     11 from sklearn.utils.validation import check_is_fitted
     12 
---> 13 from . import _hmmc
     14 from .utils import normalize, log_normalize, iter_from_X_lengths
     15 

ImportError: cannot import name '_hmmc'

**Comment by manitadayon** [comment]
Thanks for responding. My operating system is Window 10 Home

Python: Python 3.6. I am using Jupyter Notebook from Anaconda

C/C++ Compiler I am not sure what version (Running it from Matlab Console )
it seems I have Microsoft Visual Studio version 14.0 (2015 Professional)

full output of pip_install:

$ python setup.py install
running install
running bdist_egg
running egg_info
writing hmmlearn.egg-info\PKG-INFO
writing dependency_links to hmmlearn.egg-info\dependency_links.txt
writing requirements to hmmlearn.egg-info\requires.txt
writing top-level names to hmmlearn.egg-info\top_level.txt
reading manifest file 'hmmlearn.egg-info\SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'hmmlearn.egg-info\SOURCES.txt'
installing library code to build\bdist.win32\egg
running install_lib
running build_py
running build_ext
No module named 'numpy.distutils.msvccompiler' in numpy.distutils; trying from distutils
creating build\bdist.win32\egg
creating build\bdist.win32\egg\hmmlearn
copying build\lib.win32-3.6\hmmlearn\base.py -> build\bdist.win32\egg\hmmlearn
copying build\lib.win32-3.6\hmmlearn\hmm.py -> build\bdist.win32\egg\hmmlearn
copying build\lib.win32-3.6\hmmlearn\stats.py -> build\bdist.win32\egg\hmmlearn
creating build\bdist.win32\egg\hmmlearn\tests
copying build\lib.win32-3.6\hmmlearn\tests\conftest.py -> build\bdist.win32\egg\hmmlearn\tests
copying build\lib.win32-3.6\hmmlearn\tests\test_base.py -> build\bdist.win32\egg\hmmlearn\tests
copying build\lib.win32-3.6\hmmlearn\tests\test_gaussian_hmm.py -> build\bdist.win32\egg\hmmlearn\tests
copying build\lib.win32-3.6\hmmlearn\tests\test_gmm_hmm.py -> build\bdist.win32\egg\hmmlearn\tests
copying build\lib.win32-3.6\hmmlearn\tests\test_gmm_hmm_new.py -> build\bdist.win32\egg\hmmlearn\tests
copying build\lib.win32-3.6\hmmlearn\tests\test_multinomial_hmm.py -> build\bdist.win32\egg\hmmlearn\tests
copying build\lib.win32-3.6\hmmlearn\tests\test_utils.py -> build\bdist.win32\egg\hmmlearn\tests
copying build\lib.win32-3.6\hmmlearn\tests_init.py -> build\bdist.win32\egg\hmmlearn\tests
copying build\lib.win32-3.6\hmmlearn\utils.py -> build\bdist.win32\egg\hmmlearn
copying build\lib.win32-3.6\hmmlearn_hmmc.cp36-win32.pyd -> build\bdist.win32\egg\hmmlearn
copying build\lib.win32-3.6\hmmlearn_init_.py -> build\bdist.win32\egg\hmmlearn
byte-compiling build\bdist.win32\egg\hmmlearn\base.py to base.cpython-36.pyc
byte-compiling build\bdist.win32\egg\hmmlearn\hmm.py to hmm.cpython-36.pyc
byte-compiling build\bdist.win32\egg\hmmlearn\stats.py to stats.cpython-36.pyc
byte-compiling build\bdist.win32\egg\hmmlearn\tests\conftest.py to conftest.cpython-36.pyc
byte-compiling build\bdist.win32\egg\hmmlearn\tests\test_base.py to test_base.cpython-36.pyc
byte-compiling build\bdist.win32\egg\hmmlearn\tests\test_gaussian_hmm.py to test_gaussian_hmm.cpython-36.pyc
byte-compiling build\bdist.win32\egg\hmmlearn\tests\test_gmm_hmm.py to test_gmm_hmm.cpython-36.pyc
byte-compiling build\bdist.win32\egg\hmmlearn\tests\test_gmm_hmm_new.py to test_gmm_hmm_new.cpython-36.pyc
byte-compiling build\bdist.win32\egg\hmmlearn\tests\test_multinomial_hmm.py to test_multinomial_hmm.cpython-36.pyc
byte-compiling build\bdist.win32\egg\hmmlearn\tests\test_utils.py to test_utils.cpython-36.pyc
byte-compiling build\bdist.win32\egg\hmmlearn\tests_init_.py to init.cpython-36.pyc
byte-compiling build\bdist.win32\egg\hmmlearn\utils.py to utils.cpython-36.pyc
byte-compiling build\bdist.win32\egg\hmmlearn_init_.py to init.cpython-36.pyc
creating stub loader for hmmlearn_hmmc.cp36-win32.pyd
byte-compiling build\bdist.win32\egg\hmmlearn_hmmc.py to _hmmc.cpython-36.pyc
creating build\bdist.win32\egg\EGG-INFO
copying hmmlearn.egg-info\PKG-INFO -> build\bdist.win32\egg\EGG-INFO
copying hmmlearn.egg-info\SOURCES.txt -> build\bdist.win32\egg\EGG-INFO
copying hmmlearn.egg-info\dependency_links.txt -> build\bdist.win32\egg\EGG-INFO
copying hmmlearn.egg-info\requires.txt -> build\bdist.win32\egg\EGG-INFO
copying hmmlearn.egg-info\top_level.txt -> build\bdist.win32\egg\EGG-INFO
writing build\bdist.win32\egg\EGG-INFO\native_libs.txt
zip_safe flag not set; analyzing archive contents...
hmmlearn.pycache._hmmc.cpython-36: module references file
creating 'dist\hmmlearn-0.2.1-py3.6-win32.egg' and adding 'build\bdist.win32\egg' to it
removing 'build\bdist.win32\egg' (and everything under it)
Processing hmmlearn-0.2.1-py3.6-win32.egg
removing 'c:\users\manie\downloads\python\lib\site-packages\hmmlearn-0.2.1-py3.6-win32.egg' (and everything under it)
creating c:\users\manie\downloads\python\lib\site-packages\hmmlearn-0.2.1-py3.6-win32.egg
Extracting hmmlearn-0.2.1-py3.6-win32.egg to c:\users\manie\downloads\python\lib\site-packages
hmmlearn 0.2.1 is already the active version in easy-install.pth

Installed c:\users\manie\downloads\python\lib\site-packages\hmmlearn-0.2.1-py3.6-win32.egg
Processing dependencies for hmmlearn==0.2.1
Searching for scikit-learn==0.19.1
Best match: scikit-learn 0.19.1
Adding scikit-learn 0.19.1 to easy-install.pth file

Using c:\users\manie\downloads\python\lib\site-packages
Searching for numpy==1.14.1
Best match: numpy 1.14.1
Adding numpy 1.14.1 to easy-install.pth file

Using c:\users\manie\downloads\python\lib\site-packages
Finished processing dependencies for hmmlearn==0.2.1

Running following example
import numpy as np
from hmmlearn import hmm
np.random.seed(42)

model = hmm.GaussianHMM(n_components=3, covariance_type="full")
model.startprob_ = np.array([0.6, 0.3, 0.1])
model.transmat_ = np.array([[0.7, 0.2, 0.1],
... [0.3, 0.5, 0.2],
... [0.3, 0.3, 0.4]])
model.means_ = np.array([[0.0, 0.0], [3.0, -3.0], [5.0, 10.0]])
model.covars_ = np.tile(np.identity(2), (3, 1, 1))
X, Z = model.sample(100)

The error output is as follow:

ImportError Traceback (most recent call last)
 in ()
1 import numpy as np
----> 2 from hmmlearn import hmm
3 np.random.seed(42)
4
5 model = hmm.GaussianHMM(n_components=3, covariance_type="full")

~\AppData\Roaming\Python\Python36\site-packages\hmmlearn\hmm.py in ()
19 from sklearn.utils import check_random_state
20
---> 21 from .base import _BaseHMM
22 from .utils import iter_from_X_lengths, normalize
23

~\AppData\Roaming\Python\Python36\site-packages\hmmlearn\base.py in ()
11 from sklearn.utils.validation import check_is_fitted
12
---> 13 from . import _hmmc
14 from .utils import normalize, log_normalize, iter_from_X_lengths
15

ImportError: cannot import name '_hmmc'

    On Friday, July 13, 2018, 1:57:24 AM PDT, Sergei Lebedev <notifications@github.com> wrote:  
 
 
Please provide:
   
   - OS
   - Python version
   - C/C++ compiler version
   - full output of pip install,
   - and the traceback of the ImportError

**Comment by manitadayon** [comment]
Why nobody is responding here ? It has been while I have posted the necessary information.
How did you write a package that you do not know how to debug it

**Comment by manitadayon** [comment]
@GaelVaroquaux , @metterlein, @khronosplus
@ldesmetepm
Can any of you guys help me regarding to this problem ?

**Comment by manitadayon** [comment]
No it is not fair and I stopped using Python package for that, however what is the point of writing a package that has a lot of bugs. 

If the program is free it does not mean that no one should care about validity of its package. I read that statement that in case there is a problem do not contact the author before , but I thought at least somebody is responsible for this mess.

**Comment by anmolsahoo25** [comment]
A package that has 1092 stars is definitely not a program with a 'lot' of bugs. I do understand your concern that someone 'should' maintain it, but that isn't a valid demand in the OSS community. 

I sense a lot of ire in your comments. Unfortunately, your expected view of the community cannot be matched by the hmmlearn contributors. So, in case my pull request goes through and you can use the package, well and good. Otherwise there is nothing stopping you from moving on.
