### ISSUE TITLE
ImportError cannot import name _hmmc

### ISSUE THREAD

**Issue by StevenLOL** [hmmlearn/hmmlearn#3]
nosetests...

```
E.E
======================================================================
ERROR: Failure: ImportError (cannot import name _hmmc)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/nose/loader.py", line 414, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/local/lib/python2.7/dist-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/local/lib/python2.7/dist-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/steven/t42/hmmlearn/hmmlearn/hmm.py", line 26, in <module>
    from . import _hmmc
ImportError: cannot import name _hmmc

======================================================================
ERROR: Failure: ImportError (cannot import name _hmmc)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/nose/loader.py", line 414, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/local/lib/python2.7/dist-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/local/lib/python2.7/dist-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/steven/t42/hmmlearn/hmmlearn/tests/test_hmm.py", line 14, in <module>
    from hmmlearn import hmm
  File "/home/steven/t42/hmmlearn/hmmlearn/hmm.py", line 26, in <module>
    from . import _hmmc
ImportError: cannot import name _hmmc

----------------------------------------------------------------------
Ran 3 tests in 0.315s

FAILED (errors=2)
```

**Comment by lu-jian-dong** [comment]
1、make clean
2、make all
3、python setup.py install 
so that can deal with the problem

**Comment by wggbullet** [comment]
@superbobry  
Can you give me some help too ? I am getting the same error 'ImportError: cannot import name _hmmc'.

I don't see anywhere in setup.py that I can add the line to make it work (I saw it in other posts that you provided a one line code that fix the problem). In addition, I don't have admin permission on this Windows machine, so is that something that caused this problem actually? When I ran 'pip install -U --user hmmlearn' I got the following error.

Could not fetch URL https://pypi.python.org/simple/hmmlearn/: There was a problem confirming the ssl certificate: [SSL:
CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590) - skipping
Requirement already up-to-date: hmmlearn in c:\anaconda240\lib\site-packages\hmmlearn-0.2.1-py2.7-win-amd64.egg
Could not fetch URL https://pypi.python.org/simple/numpy/: There was a problem confirming the ssl certificate: [SSL: CER
TIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590) - skipping
Requirement already up-to-date: numpy in c:\anaconda240\lib\site-packages (from hmmlearn)
Could not fetch URL https://pypi.python.org/simple/scikit-learn/: There was a problem confirming the ssl certificate: [S
SL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590) - skipping
Requirement already up-to-date: scikit-learn>=0.16 in c:\anaconda240\lib\site-packages (from hmmlearn)
