### ISSUE TITLE
Build issue on Windows 7

### ISSUE THREAD

**Issue by gjwo** [hmmlearn/hmmlearn#30]
An error occurred in the hmmlearn build step of nilmtk 
building 'hmmlearn._hmmc' extension
error:Mircosoft visual c++ 10.0 is required (unable to find vcvarsall.bat)

full transcription below

![image](https://cloud.githubusercontent.com/assets/12109990/7610133/6db579ac-f972-11e4-9fe7-b1227be31e7b.png)

I appear to have the 2010 and 2012 redistributables installed for both 32 & 64 bit see below

image
![image](https://cloud.githubusercontent.com/assets/12109990/7610144/7a186f06-f972-11e4-9b54-b2c7f854377a.png)

vcvarsall.bat is not present on my PC

Am I missing another install or is this a build error?

originally posted here on nilmtk issue 386

**Comment by superbobry** [comment]
Hello, thank you for reporting this. I'm not a Windows user myself, but quick googling led me to a [similar issue](http://stackoverflow.com/a/27672491) on SO. Can you please try the suggested solution and let me know if it worked for you?

**Comment by gjwo** [comment]
That didn't work but having tried several versions of Microsoft visual C++ redistributable, uninstalled them all and installed Microsoft Visual c++ 2010 Express, this seemed to work better but I think there is now a different issue see below
![image](https://cloud.githubusercontent.com/assets/12109990/7655890/b3b31042-fb1e-11e4-9d57-04cb30199840.png)

**Comment by gjwo** [comment]
didn't mean  to close!

**Comment by gjwo** [comment]
Results using python 2.7 rather than 3.4
$ cd hmmlearn

GJWood@GJWOOD-XPS ~/hmmlearn (master)
$ python setup.py install
running install
running bdist_egg
running egg_info
writing hmmlearn.egg-info\PKG-INFO
writing top-level names to hmmlearn.egg-info\top_level.txt
writing dependency_links to hmmlearn.egg-info\dependency_links.txt
reading manifest file 'hmmlearn.egg-info\SOURCES.txt'
writing manifest file 'hmmlearn.egg-info\SOURCES.txt'
installing library code to build\bdist.win-amd64\egg
running install_lib
running build_py
running build_ext
building 'hmmlearn._hmmc' extension
creating build\temp.win-amd64-2.7
creating build\temp.win-amd64-2.7\Release
creating build\temp.win-amd64-2.7\Release\hmmlearn
C:\Users\GJWood\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.
0\VC\Bin\amd64\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -Ic:\Users\GJWood\Ana
conda\lib\site-packages\numpy\core\include -Ic:\Users\GJWood\Anaconda\include -I
c:\Users\GJWood\Anaconda\PC /Tchmmlearn/_hmmc.c /Fobuild\temp.win-amd64-2.7\Rele
ase\hmmlearn/_hmmc.obj
_hmmc.c
c:\users\gjwood\anaconda\lib\site-packages\numpy\core\include\numpy\npy_1_7_depr
ecated_api.h(12) : Warning Msg: Using deprecated NumPy API, disable it by #defin
ing NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION
hmmlearn/_hmmc.c(2266) : warning C4244: '+=' : conversion from 'Py_ssize_t' to '
int', possible loss of data
hmmlearn/_hmmc.c(2269) : warning C4244: '+=' : conversion from 'Py_ssize_t' to '
long', possible loss of data
hmmlearn/_hmmc.c(2270) : warning C4244: '+=' : conversion from 'Py_ssize_t' to '
int', possible loss of data
hmmlearn/_hmmc.c(2273) : warning C4244: '+=' : conversion from 'Py_ssize_t' to '
long', possible loss of data
hmmlearn/_hmmc.c(2274) : warning C4244: '+=' : conversion from 'Py_ssize_t' to '
int', possible loss of data
hmmlearn/_hmmc.c(2320) : warning C4244: '+=' : conversion from 'Py_ssize_t' to '
long', possible loss of data
hmmlearn/_hmmc.c(2321) : warning C4244: '+=' : conversion from 'Py_ssize_t' to '
int', possible loss of data
hmmlearn/_hmmc.c(2324) : warning C4244: '+=' : conversion from 'Py_ssize_t' to '
int', possible loss of data
hmmlearn/_hmmc.c(2325) : warning C4244: '+=' : conversion from 'Py_ssize_t' to '
int', possible loss of data
hmmlearn/_hmmc.c(2327) : warning C4244: '+=' : conversion from 'Py_ssize_t' to '
int', possible loss of data
hmmlearn/_hmmc.c(2342) : warning C4244: '+=' : conversion from 'Py_ssize_t' to '
int', possible loss of data
hmmlearn/_hmmc.c(2343) : warning C4244: '+=' : conversion from 'Py_ssize_t' to '
int', possible loss of data
hmmlearn/_hmmc.c(2346) : warning C4244: '+=' : conversion from 'Py_ssize_t' to '
int', possible loss of data
hmmlearn/_hmmc.c(2347) : warning C4244: '+=' : conversion from 'Py_ssize_t' to '
int', possible loss of data
hmmlearn/_hmmc.c(2677) : warning C4244: '+=' : conversion from 'Py_ssize_t' to '
long', possible loss of data
hmmlearn/_hmmc.c(2678) : warning C4244: '+=' : conversion from 'Py_ssize_t' to '
int', possible loss of data
hmmlearn/_hmmc.c(2723) : warning C4244: '+=' : conversion from 'Py_ssize_t' to '
int', possible loss of data
hmmlearn/_hmmc.c(2724) : warning C4244: '+=' : conversion from 'Py_ssize_t' to '
int', possible loss of data
hmmlearn/_hmmc.c(2727) : warning C4244: '+=' : conversion from 'Py_ssize_t' to '
long', possible loss of data
hmmlearn/_hmmc.c(2728) : warning C4244: '+=' : conversion from 'Py_ssize_t' to '
int', possible loss of data
hmmlearn/_hmmc.c(2739) : warning C4244: '+=' : conversion from 'Py_ssize_t' to '
long', possible loss of data
hmmlearn/_hmmc.c(2740) : warning C4244: '+=' : conversion from 'Py_ssize_t' to '
int', possible loss of data
hmmlearn/_hmmc.c(2750) : warning C4244: '+=' : conversion from 'Py_ssize_t' to '
int', possible loss of data
hmmlearn/_hmmc.c(2765) : warning C4244: '+=' : conversion from 'Py_ssize_t' to '
int', possible loss of data
hmmlearn/_hmmc.c(2766) : warning C4244: '+=' : conversion from 'Py_ssize_t' to '
int', possible loss of data
hmmlearn/_hmmc.c(3081) : warning C4244: '+=' : conversion from 'Py_ssize_t' to '
int', possible loss of data
hmmlearn/_hmmc.c(3082) : warning C4244: '+=' : conversion from 'Py_ssize_t' to '
int', possible loss of data
hmmlearn/_hmmc.c(3085) : warning C4244: '+=' : conversion from 'Py_ssize_t' to '
int', possible loss of data
hmmlearn/_hmmc.c(3086) : warning C4244: '+=' : conversion from 'Py_ssize_t' to '
int', possible loss of data
hmmlearn/_hmmc.c(3097) : warning C4244: '+=' : conversion from 'Py_ssize_t' to '
long', possible loss of data
hmmlearn/_hmmc.c(3098) : warning C4244: '+=' : conversion from 'Py_ssize_t' to '
int', possible loss of data
hmmlearn/_hmmc.c(3109) : warning C4244: '+=' : conversion from 'Py_ssize_t' to '
long', possible loss of data
hmmlearn/_hmmc.c(3110) : warning C4244: '+=' : conversion from 'Py_ssize_t' to '
int', possible loss of data
hmmlearn/_hmmc.c(3122) : warning C4244: '+=' : conversion from 'Py_ssize_t' to '
int', possible loss of data
hmmlearn/_hmmc.c(3123) : warning C4244: '+=' : conversion from 'Py_ssize_t' to '
int', possible loss of data
hmmlearn/_hmmc.c(3124) : warning C4244: '+=' : conversion from 'Py_ssize_t' to '
int', possible loss of data
hmmlearn/_hmmc.c(3642) : warning C4244: '+=' : conversion from 'Py_ssize_t' to '
long', possible loss of data
hmmlearn/_hmmc.c(3654) : warning C4244: '+=' : conversion from 'Py_ssize_t' to '
long', possible loss of data
hmmlearn/_hmmc.c(3655) : warning C4244: '+=' : conversion from 'Py_ssize_t' to '
int', possible loss of data
hmmlearn/_hmmc.c(3702) : warning C4244: '+=' : conversion from 'Py_ssize_t' to '
long', possible loss of data
hmmlearn/_hmmc.c(3766) : warning C4244: '+=' : conversion from 'Py_ssize_t' to '
int', possible loss of data
C:\Users\GJWood\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.
0\VC\Bin\amd64\link.exe /DLL /nologo /INCREMENTAL:NO /LIBPATH:c:\Users\GJWood\An
aconda\libs /LIBPATH:c:\Users\GJWood\Anaconda\PCbuild\amd64 /EXPORT:init_hmmc bu
ild\temp.win-amd64-2.7\Release\hmmlearn/_hmmc.obj /OUT:build\lib.win-amd64-2.7\h
mmlearn\_hmmc.pyd /IMPLIB:build\temp.win-amd64-2.7\Release\hmmlearn\_hmmc.lib /M
ANIFESTFILE:build\temp.win-amd64-2.7\Release\hmmlearn\_hmmc.pyd.manifest
_hmmc.obj : warning LNK4197: export 'init_hmmc' specified multiple times; using
first specification
   Creating library build\temp.win-amd64-2.7\Release\hmmlearn\_hmmc.lib and obje
ct build\temp.win-amd64-2.7\Release\hmmlearn\_hmmc.exp
creating build\bdist.win-amd64
creating build\bdist.win-amd64\egg
creating build\bdist.win-amd64\egg\hmmlearn
copying build\lib.win-amd64-2.7\hmmlearn\base.py -> build\bdist.win-amd64\egg\hm
mlearn
copying build\lib.win-amd64-2.7\hmmlearn\hmm.py -> build\bdist.win-amd64\egg\hmm
learn
copying build\lib.win-amd64-2.7\hmmlearn\utils.py -> build\bdist.win-amd64\egg\h
mmlearn
copying build\lib.win-amd64-2.7\hmmlearn\_hmmc.pyd -> build\bdist.win-amd64\egg\
hmmlearn
copying build\lib.win-amd64-2.7\hmmlearn\__init__.py -> build\bdist.win-amd64\eg
g\hmmlearn
byte-compiling build\bdist.win-amd64\egg\hmmlearn\base.py to base.pyc
byte-compiling build\bdist.win-amd64\egg\hmmlearn\hmm.py to hmm.pyc
byte-compiling build\bdist.win-amd64\egg\hmmlearn\utils.py to utils.pyc
byte-compiling build\bdist.win-amd64\egg\hmmlearn\__init__.py to __init__.pyc
creating stub loader for hmmlearn\_hmmc.pyd
byte-compiling build\bdist.win-amd64\egg\hmmlearn\_hmmc.py to _hmmc.pyc
creating build\bdist.win-amd64\egg\EGG-INFO
copying hmmlearn.egg-info\PKG-INFO -> build\bdist.win-amd64\egg\EGG-INFO
copying hmmlearn.egg-info\SOURCES.txt -> build\bdist.win-amd64\egg\EGG-INFO
copying hmmlearn.egg-info\dependency_links.txt -> build\bdist.win-amd64\egg\EGG-
INFO
copying hmmlearn.egg-info\top_level.txt -> build\bdist.win-amd64\egg\EGG-INFO
writing build\bdist.win-amd64\egg\EGG-INFO\native_libs.txt
zip_safe flag not set; analyzing archive contents...
creating dist
creating 'dist\hmmlearn-0.1.1-py2.7-win-amd64.egg' and adding 'build\bdist.win-a
md64\egg' to it
removing 'build\bdist.win-amd64\egg' (and everything under it)
Processing hmmlearn-0.1.1-py2.7-win-amd64.egg
Copying hmmlearn-0.1.1-py2.7-win-amd64.egg to c:\users\gjwood\anaconda\lib\site-
packages
Adding hmmlearn 0.1.1 to easy-install.pth file

Installed c:\users\gjwood\anaconda\lib\site-packages\hmmlearn-0.1.1-py2.7-win-am
d64.egg
Processing dependencies for hmmlearn==0.1.1
Finished processing dependencies for hmmlearn==0.1.1

**Comment by superbobry** [comment]
Interesting, so for older Python version everything seems to work. 

I don't have a Windows machine available, so I'll try to reproduce the issue with 3.4 on AppVeyor.

**Comment by superbobry** [comment]
Hello! the latest version of `hmmlearn` seems to build fine on AppVeyor with Python3.4.1. Can you please try building it and let me know if it works.

**Comment by soupault** [comment]
@superbobry what MSVC++ version did you use for Python 3.4?
There is no reference for 3.4 here: https://github.com/cython/cython/wiki/CythonExtensionsOnWindows#using-windows-sdk-cc-compiler-works-for-all-python-versions , but some guesses are given at https://matthew-brett.github.io/pydagogue/python_msvc.html

**Comment by superbobry** [comment]
I'm not familiar at all with the Windows ecosystem, but the AppVeyor [build log for Python3.4.1](https://ci.appveyor.com/project/superbobry/hmmlearn/build/59/job/ns5o2614p6e9q7pd) suggests that MSVC10 is used.

**Comment by soupault** [comment]
@superbobry same here. Thank you very much for the link! Prepared .whl seems to be working on my platform.
