### ISSUE TITLE
HMM with different lengths sequences

### ISSUE THREAD

**Issue by fastluca** [hmmlearn/hmmlearn#300]
Hello,
I read the documentation, but I'm not sure about how to implement the goal of my experimentation.
I have a dataset composed by a sequence of events and the timestamp in which the event occurs. Each sequence has different length. 
The goal is to build a model from the dataset and to classify the sequences themself in two classes.
This is my code:
``` 
sequence_map = __load_df(file)
#Keys are id, values are the sequence of observations, each one with different length.

    x = []
    lengths = []

    for values in sequence_map.values():
        x.append(values)
        lengths.append(len(values))

    x = np.concatenate(x)

    model = hmm.GaussianHMM(n_components=2, n_iter=1000, covariance_type="full").fit(x, lengths=lengths)
```
Having the model, how I could classify each sequence in my dataset?
Thank you in advance.

**Comment by anntzer** [comment]
The issue tracker is not the place to learn about HMMs, there are better resources elsewhere.
