### ISSUE TITLE
hmmlearn 0.2.1 not in pip?

### ISSUE THREAD

**Issue by jgreenemi** [hmmlearn/hmmlearn#305]
Can the latest version of this be made available in pip? Looks like hmmlearn 0.2.0 is no longer compatible with dependency scikit-learn 0.20.0 as the name of sklearn.mixture.GMM has changed to sklearn.mixture.GaussianMixture, so the version of hmmlearn available in pip could use updating. Had to use an older version of scikit-learn to get it up and running.

**Comment by anntzer** [comment]
I'll put it there "soon".

**Comment by jgreenemi** [comment]
Excellent, thank you!

**Comment by anntzer** [comment]
0.2.1 has been released on PyPI.
It is a source-only release only intended to fix compatibility issues with Py3.7 and sklearn 0.20.

**Comment by jgreenemi** [comment]
Wonderful, thank you!
