### ISSUE TITLE
Which HMM to use for discrete emissions with custom probabilities on each symbol?

### ISSUE THREAD

**Issue by blake5634** [hmmlearn/hmmlearn#310]
I'm trying to run HMM.learn() on an HMM with a large number of sequences using multinomialHMM() class. 
  Previous issues cited the error: "ValueError: expected a sample from a Multinomial distribution"  (hmm.py line 377).   My question is, is multinomial the correct HMM subclass to use if I want to specify the probability to see each emission (discrete symbol as an integer) in each state?   In other words, are we restricted to a true multinomail distribution?  

If as a simple example, if my symbols are 0-255 integers, and for state 5 I have uniform(10-20), is multinomial appropriate through setting emissionprobs_???

Thanks

**Comment by blake5634** [comment]
Additional thoughts:  a response to an earlier Issue  highlighted that having all values present in an observation sequence is a requirement for this but I don't see how any probability distribution could guarantee that all emission symbols would be generated on a given run.    What am I missing here?

**Comment by anntzer** [comment]
I agree that the error seems spurious.  Can you point to the other issue?

**Comment by blake5634** [comment]
Issue #124 gets into this issue but did not resolve it (for me at least).

**Comment by anntzer** [comment]
I would consider a PR fixing the issue.
However, as the README says

> Note: this package has currently no maintainer. Nobody will answer questions. In particular, the person who is making this code available on Github will not answer questions, fix bugs, or maintain the package in any way.

**Comment by blake5634** [comment]
Thanks - I'm curious about "no maintainer" since there have been 14 commits since 1-Sept-18.

**Comment by anntzer** [comment]
Well, I spent some time to move the package from "completely broken (doesn't import) with the latest sklearn because sklearn changed their API" to "the old functionality is still working".

**Comment by blake5634** [comment]
Definitely appreciated!!     I've simply commented out that "check" step but I'm running simulations now to see if resulting behavior is valid/sensible.

**Comment by anntzer** [comment]
I think this is now fixed as of master (you can set the n_features attribute on the model).  Please ping for reopen if issues remain.
