### ISSUE TITLE
Setting restrictions to transition matrix in Hmmlearn

### ISSUE THREAD

**Issue by egertteesaar** [hmmlearn/hmmlearn#316]
Hello!
I am working with medicine data, especially with people who have cancer. 
Let's say that I have some  1) pre-operation observations, 2) operation and 3) post-operation observations (and also possible 4) relapse to pre-operation observations ). I would like to omit hidden states to each of these categories. 
The problem is the following. I'd like to set restrictions to transition matrix so it wouldn't be possible to jump from pre-operation states straight to post-operation states ( and vice versa), without them going through "operation" state (or "relapse" state respectively)  first.
So, in a word, I would like to learn transition and emission matrix, where I know that some values are 0 (probabilities of going to pre-op to post-op states) and would like to learn the non-zero probabilities which I don't know. 
Could it be done with the current implementation of hmmlearn or if not, is there an easy way to add it somehow?

**Comment by alegonz** [comment]
Hello, 

I believe you can initialize the model with a transition matrix where the components of the forbidden transitions are set to zero. As per the documentation:

> The transition probability matrix need not to be ergodic. For instance, a left-right HMM can be defined as follows:

```
lr = hmm.GaussianHMM(n_components=3, covariance_type="diag",
                     init_params="cm", params="cmt")
lr.startprob_ = np.array([1.0, 0.0, 0.0])
lr.transmat_ = np.array([[0.5, 0.5, 0.0],
                         [0.0, 0.5, 0.5],
                         [0.0, 0.0, 1.0]])
```

Cheers

**Comment by blake5634** [comment]
Furthermore, the baum Welch algorithm used by .fit() will not change a 0.0 value  so you can think of that initial zero as a constraint on the learning process.

**Comment by egertteesaar** [comment]
Thanks for the proposed solutions! These do the trick.
