### ISSUE TITLE
Use error codes for _check_input_symbols()

### ISSUE THREAD

**Issue by alkemir** [hmmlearn/hmmlearn#318]
The current implementation returns False on the four error kinds currently detected.
This means that when one of the error condition happens, the same error is raised for
all of them. From the users perspective, this is obscure, and it would be more helpful
to know which error is contained on the data.

I propose to return an error code which can be used to provide a more meaningful error
for each case.

Or even, to raise the error where all information about it is available
(_check_input_symbols() ), but I am unsure whether this conforms to best practices, as
testing code would need to handle errors.

**Comment by anntzer** [comment]
I'm fine with changing that, but the check is likely wrong to start with as argued in https://github.com/hmmlearn/hmmlearn/issues/310, so I'd rather get *that* correctly fixed before improving error messages.

**Comment by anntzer** [comment]
This was mostly fixed in https://github.com/hmmlearn/hmmlearn/commit/1b5b557ce381e8bfdb6af9a5ffe5561df326a312#diff-2288c5d38e59bd54894a0c7272e5cf71R455.
