### ISSUE TITLE
Example of HMMGaussian with emission matrix

### ISSUE THREAD

**Issue by rbpisupati** [hmmlearn/hmmlearn#319]
Hi, 

I just started playing around the hmmlearn package GaussianHMM. Does someone have an example to initialize HMM with given emission and transition probability matrices? It is not entirely clear in the manual (https://hmmlearn.readthedocs.io/en/latest/tutorial.html#implementing-hmms-with-custom-emission-probabilities)

Thanks in advance, 
Rahul

**Comment by anntzer** [comment]
You can directly set the means_, covars_, and transmat_ attributes on the hmm object and then exclude them from init_params and/or params.
