### ISSUE TITLE
Pip version is outdated

### ISSUE THREAD

**Issue by oxinabox** [hmmlearn/hmmlearn#32]
Hi,
The version of hmmlearn which one gets from installing with `pip install hmmlearn`,
is quiet out of date, and several fixed issues have been hitting me.

Namely the lack of monitoring (which I guess isn't fully implemented?),

and the lack of https://github.com/hmmlearn/hmmlearn/commit/0747df111ecd9221b235aa4b970baaa766d44b2d

A new release should be made.
and the __version__ should also be incremented.

(I am currently using master, installed from source, but for the good of all of us...)

**Comment by superbobry** [comment]
Hello, the one thing that is currently stopping me from making a release is non-sklearnish interfaces (see #29 for discussion), once I change them, I'll release the new version.

**Comment by oxinabox** [comment]
Thanks.
And Monitoring will work for all types of HMMs?

**Comment by superbobry** [comment]
If you mean for all emission distributions then yes, it should.

**Comment by dalexander** [comment]
I'm also quite eager for the release of a new version.  The issues #33 and #47 in 0.1.1 make it quite unusable for me.

**Comment by superbobry** [comment]
You're right. I think I'll go ahead and release 0.2.0 this weekend and then 0.2.1 with documentation updates and (hopefully not) bugfixes.

**Comment by achalddave** [comment]
Any updates on this? Looking forward to it :)

**Comment by superbobry** [comment]
Not at the moment, unfortunately, I've discovered more issues with `GMMHMM` (see 2b05895). So now the goal is to make it work before the release.

**Comment by achalddave** [comment]
I see... It would be neat if you could push some version after https://github.com/hmmlearn/hmmlearn/commit/0181eb7bdaa252468ba3ff99a8e9416e7b0d236d, since the API is a bit different since that change changes user-facing things and leaves the pip version out of sync with the readthedocs. Anyway, I understand if that's not possible - I've installed the HEAD version for now.

**Comment by superbobry** [comment]
I've decided to go ahead and release 0.2.0. We'll fix the `GMMHMM` bug in the following version.
