### ISSUE TITLE
ImportError: cannot import name '_validate_covars'

### ISSUE THREAD

**Issue by mohammad1kharjo** [hmmlearn/hmmlearn#322]
I don't know why, but when i run a hmmlearn example i get this error. I modified the files according to [this thread](https://github.com/hmmlearn/hmmlearn/commit/510ae05c38ff046f00641712187b279cc498fd0a#diff-224ff9d9c3624d4c7454eea72cb9d9b5R106). Can anyone help me?

**Comment by anntzer** [comment]
Please indicate how you installed hmmlearn, and the output of `pip list`.

**Comment by mohammad1kharjo** [comment]
I'm using PyCharm and I installed hmmlearn using its pip inside the app. `pip list` output in windows cmd:
beautifulsoup4            4.5.3
cycler                    0.10.0
decorator                 4.3.0
Django                    1.9.9
django-admin-bootstrapped 2.5.7
django-extra-views        0.8.0
django-nose               1.4.4
django-polymorphic        1.0
hmmlearn                  0.2.1
kiwisolver                1.0.1
matplotlib                3.0.2
networkx                  2.2
nose                      1.3.7
numpy                     1.15.4
olefile                   0.44
pbr                       1.10.0
pep8                      1.7.0
Pillow                    4.0.0
pip                       18.1
pyparsing                 2.3.0
python-dateutil           2.7.5
scikit-learn              0.20.1
scipy                     1.2.0
setuptools                40.6.3
six                       1.10.0
stevedore                 1.20.0
virtualenv                15.0.3
virtualenv-clone          0.2.6
virtualenvwrapper         4.7.2
waitress                  1.0.1
WebOb                     1.7.1
WebTest                   2.0.23

**Comment by mohammad1kharjo** [comment]
I dug into it and found that '_validate_covars' is missing from the sikitlearn library.

**Comment by anntzer** [comment]
Please uninstall and reinstall hmmlearn.

**Comment by anntzer** [comment]
Closing for lack of additional info.
