### ISSUE TITLE
ImportError: cannot import name 'distribute_covar_matrix_to_match_covariance_type'

### ISSUE THREAD

**Issue by markusMM** [hmmlearn/hmmlearn#328]
Hello devs,
I had a bad error in:

`from sklearn.mixture import (`

it said:

`ImportError: cannot import name 'distribute_covar_matrix_to_match_covariance_type'`

It seems this module has been moved?

Best regards,
Markus

**Comment by anntzer** [comment]
please use hmmlearn 0.2.1
