### ISSUE TITLE
MultinomialHMM.score_samples uses inconsistent input shape (or more likely docs are wrong)

### ISSUE THREAD

**Issue by rubenvereecken** [hmmlearn/hmmlearn#329]
I think this issue may be somewhat related: #125. I finally figured it out thanks to #70.

[The docs for `MultinomialHMM.score_samples`](https://hmmlearn.readthedocs.io/en/latest/api.html#hmmlearn.hmm.MultinomialHMM.score_samples) state that the input format is `(n_samples, n_features)`. As such, I had one-hot encoded my observations to fit the 2D format. `n_features` is simply the cardinality of the set of observations. However, that's not how that method actually works. It expects a `(n_samples, 1)` vector of labels, which I figured out thanks to #70. 

Since there is no active maintainer, I'm mainly leaving this here for others with similar problems.

**Comment by DaehanKim** [comment]
Thanks a lot. This solved my problem too.

**Comment by anntzer** [comment]
Thanks for bumping this.  I have now fixed the docs with the correct shape and an additional note (https://hmmlearn.readthedocs.io/en/latest/api.html#hmmlearn.hmm.MultinomialHMM.score_samples).
