### ISSUE TITLE
Problem on Decoded State Sequence.

### ISSUE THREAD

**Issue by JeffreyDLN** [hmmlearn/hmmlearn#330]
I'm currently using HMMLearn 0.2.1. The state sequence from  decode( ) and predict ( ) did not follow its startprob_ and transmat_. I mean that after training an left-to-right HMM, the model has its startprob_ and transmat_ which are proper to provide the state sequence for left-to-right HMM patterns. However, the decoded state sequence derived from .decode( ) or .predict( ) is not a correct left-to-right HMM pattern that I expected. Please see the result of model.startprob_, model.transmat_ and decoded state sequence. 

I attempted to implement left-to-right HMM. I trained 4 sequences of 16x8 (n_sample x n_feature) and tested with one sequence (16x8).

Please help me to figure it out. Are there something wrong with my code? Many Thanks!
[train.xlsx](https://github.com/hmmlearn/hmmlearn/files/2903360/train.xlsx)
[test.xlsx](https://github.com/hmmlearn/hmmlearn/files/2903362/test.xlsx)

################################################################
import pandas as pd
from pandas import ExcelWriter
from pandas import ExcelFile

import numpy as np
from hmmlearn import hmm

#feature for training
df = pd.read_excel('train.xlsx', sheetname='Sheet1',header=None)
f = df.as_matrix() 
lengthsF = np.array([16,16,16,16])

#feature for test
dft = pd.read_excel('test.xlsx',sheetname='Sheet1',header=None)
ft = dft.as_matrix()
lengthsFT = np.array([16])

model = hmm.GaussianHMM(n_components=3,covariance_type="diag",n_iter=100,tol=0.001,init_params='mc',params='tmc')

#Initial parameter before training
model.startprob_ = np.array([1.0, 0.0, 0.0])
model.transmat_ = np.array([[0.5, 0.5, 0.0],[0.0, 0.5, 0.5],[0.0, 0.0, 1.0]])

model.fit(f, lengthsF);

lp, tseq = model.decode(ft,algorithm="viterbi");
#tseq = model.predict(ft)

print (' ')
print ('##### Start Prob #####')
print (model.startprob_);
print (' ')
print ('##### Transition Matrix #####')
print (model.transmat_);
print (' ')
print ('##### Decoded Sequence #####')
print (tseq);
print (' ')
print(model.monitor_)
###############################################################

Result
##### Start Prob #####
[ 1.  0.  0.]

##### Transition Matrix #####
[[ 0.86206043  0.13793957  0.        ]
 [ 0.                  0.66307478  0.33692522]
 [ 0.                  0.                  1.        ]]

##### Decoded Sequence #####
[1 1 1 1 1 0 0 2 2 0 0 0 0 1 2 0]

ConvergenceMonitor(history=[-565.70528992330674, -565.70474202073285], iter=8,
          n_iter=100, tol=0.001, verbose=False)

**Comment by anntzer** [comment]
I don't know what you mean by "The hidden state sequence from decode( ) and predict ( ) did not follow its startprob_ and transmat_".
Perhaps you want to set the `params` kwarg appropriately.

**Comment by JeffreyDLN** [comment]
@anntzer Thank you very much for your kind reply :0)

I meant that after training an left-to-right HMM, the model has its startprob_ and transmat_ which are proper to provide the state sequence for left-to-right HMM patterns. However, the decoded state sequence derived from .decode( ) or .predict( ) is not a correct left-to-right HMM pattern that I expected. Please see the result of model.startprob_, model.transmat_ and decoded state sequence. 

About params kwarg setting, I followed API reference for fixing startprob_ to force the HMM starting at its first state. Also, I initialized the transmat_ to force the HMM to be left-to-right state transition.

**Comment by anntzer** [comment]
Oh, I see.  When I run it locally the result is correctly left-to-right.  Can you make sure to install 0.2.1 from the PyPI release?  (There are some other versions reporting themselves as 0.2.1 lying around, but they're not actually 0.2.1...)

**Comment by JeffreyDLN** [comment]
I installed HMMlearn thru anaconda and it claims to be 0.2.1 version. Before that, I attempted to install 0.2.1 from the PyPI but unsuccessful. Could you please give me the link for HMMlearn installation guide?

**Comment by JeffreyDLN** [comment]
I see the PyPI installation guide.  Which python version I should use?

**Comment by anntzer** [comment]
`conda remove hmmlearn`
`pip install --upgrade hmmlearn==0.2.1`
please post any error message

**Comment by anntzer** [comment]
py 3.6 or 3.7 though it should not matter

**Comment by JeffreyDLN** [comment]
After installing a MS build tool, It works. :0)
Thank you so...................... much for your kindness. Bless you!
