### ISSUE TITLE
A suggestion about the name "MultinomialHMM"

### ISSUE THREAD

**Issue by zhaoyanthu** [hmmlearn/hmmlearn#335]
This is my personal opinion. I think the name "MultinomialHMM" is not an appropriate name. Why not just call it "DiscreteHMM"? When I first saw "MultinomialHMM", I thought the emission probability supports a general [Multinomial distribution](https://en.wikipedia.org/wiki/Multinomial_distribution).

**Comment by blake5634** [comment]
+1

**Comment by anntzer** [comment]
The distribution implemented by MultinomialHMM is actually a multinomial, isn't it?

**Comment by wkopp** [comment]
It is a categorical distribution that is implemented in MultinomialHMM, which is a special case of a multinomial [Categorical distribution](https://en.wikipedia.org/wiki/Categorical_distribution). I would agree to renaming it. Maybe to CategoricalHMM?

**Comment by anntzer** [comment]
Oh, I see, this is correct.  I'm fine with renaming to CategoricalHMM.

**Comment by anntzer** [comment]
Closed by #432.
