### ISSUE TITLE
Selecting number of observations in multinomial HMM

### ISSUE THREAD

**Issue by FerusAndBeyond** [hmmlearn/hmmlearn#336]
I don't know if I've missed something but is it not possible to set the number of unique observations in a multinomial HMM? It seems like it infers it from the training data but if the training data doesn't contain an observation that then appears in the test data everything breaks.

**Comment by blake5634** [comment]
This is related to #310  
I wound up having to comment out line 385+-  in hmm.py

**Comment by li924579** [comment]
I meet the problem you met before and did you solve the problem? or use other lib? @blake5634

**Comment by blake5634** [comment]
Commenting out line 385 in hmm.py did solve the problem. (and didn't seem to cause any other problems)

**Comment by li924579** [comment]
I used the same method but cause another problem.
For the example
states = ["Rainy", "Sunny"]
observations = ["walk", "shop", "clean"]
X = np.array([[0, 0, 2, 2, 0, 0],[0, 0, 2, 2, 0, 0],[0, 2, 0, 2, 0, 0]])
model.fit(X)
An index error occured : IndexError: index 2 is out of bounds for axis 1 with size 2
It seems that a sequence contains all the possible observations must exit
May be I have to find another lib :(

**Comment by hb925822** [comment]
发自我的华为手机ever value in range  [min(X),max(X)],must occur in array X which is the input param of fit function. -------- 原始邮件 --------主题：Re: [hmmlearn/hmmlearn] Selecting number of observations in multinomial HMM (#336)发件人：吴尔立 收件人：hmmlearn/hmmlearn 抄送：Subscribed I used the same method but cause another problem.
For the example
states = ["Rainy", "Sunny"]
observations = ["walk", "shop", "clean"]
X = np.array([[0, 0, 2, 2, 0, 0],[0, 0, 2, 2, 0, 0],[0, 2, 0, 2, 0, 0]])
model.fit(X)
An index error occured : IndexError: index 2 is out of bounds for axis 1 with size 2
It seems that a sequence contains all the possible observations must exit
May be I have to find another lib :(

**Comment by anntzer** [comment]
I think this is now fixed as of master (you can set the n_features attribute on the model).  Please ping for reopen if issues remain.
