### ISSUE TITLE
Fitting data to hsmmlearn model

### ISSUE THREAD

**Issue by manasa001** [hmmlearn/hmmlearn#339]
We are working on device failure detection using syslogs and trying to use HSMM Model for the same .We have built training data for Error sequences and another with Errorfree sequences. We want to build a HSMM model for both Error and Error free data using the hsmmlearn module.In the example model demonstrated in the git, model is trained on only the sample data based out of Gaussian distribution, but we require the HSMM model to be trained on our Error and Error free data.Kindly help in understanding of how to fit hsmmlearn model for our training data(Error and Error Free data) and do predictions.

**Comment by anntzer** [comment]
sorry, I have no bandwidth to teach you how to use a hmm.
