### ISSUE TITLE
Tuple of observations as 1 input observation      

### ISSUE THREAD

**Issue by egertteesaar** [hmmlearn/hmmlearn#340]
Is there a way to give a tuple or a list of observations as 1 observation into MultinomialHMM?

I have this data where there are usually multiple discrete observations for each day but I'd like to describe them with just one hidden state. Can it be done?

**Comment by anntzer** [comment]
No, but I think this is basically the problem at https://github.com/hmmlearn/hmmlearn/issues/335: MultinomialHMM is not really a multinomial HMM but really a categorical one.
