### ISSUE TITLE
ValueError: Buffer dtype mismatch, expected 'dtype_t' but got 'float'

### ISSUE THREAD

**Issue by yogagm** [hmmlearn/hmmlearn#341]
Hello,

I try to setup the init_params in GHMM,  however when I fit, this error keeps occuring 'ValueError: Buffer dtype mismatch, expected 'dtype_t' but got 'float'', is this bug? Does anyone here experience the same error? Please share your solution. Thank you.

**Comment by anntzer** [comment]
Please provide a way to reproduce the issue.

**Comment by yogagm** [comment]
I found the solution, thank you

**Comment by BertramSun** [comment]
@yogagm How did you solve it?
