### ISSUE TITLE
Peek into the future in the prediction.

### ISSUE THREAD

**Issue by sloparev** [hmmlearn/hmmlearn#345]
I try to understand how to work prediction in this code (file "_hmmc.pyx"):

def _viterbi(...)

        for t in range(n_samples - 2, -1, -1):
            for i in range(n_components):
                work_buffer[i] = (viterbi_lattice[t, i] + log_transmat[i, where_from])
            state_sequence[t] = where_from = _argmax(work_buffer)

To calculate predict in iteretion"t" we use information from iteretion "t+1", is it correct?

**Comment by anntzer** [comment]
yes.  please see the references at https://hmmlearn.readthedocs.io/en/latest/tutorial.html.
