### ISSUE TITLE
correct format of X for HMM classification and regression 

### ISSUE THREAD

**Issue by Dazzid** [hmmlearn/hmmlearn#347]
I have a very simple question. I have recordings of 9 different gestures using gyroscope, accelerometer and magnetometer (IMU) device (3 axis gyroscope, 3 axis accelerometer, 4 axis rotation-quaternion). 
That means my data has 10 features, gestures trials made of 150 samples. All of them normalized (-1.0, 1.0) 
What is the correct format of the X, in the case of classification of those 9 gestures, I don't really understand how to pass in the matrix, how to define which batch of data corresponds to which gesture?
I don't have nither the probabilistic transition between the gestures, it is necessary? Because the real case is that any gesture can be followed by any other gesture, all probabilities are 0.111. What I want to do is a likelihood estimation of new gestures.

**Comment by anntzer** [comment]
sorry, I have no bandwidth to teach you how to use a hmm.
