### ISSUE TITLE
Minor issue in docs

### ISSUE THREAD

**Issue by cstarkjp** [hmmlearn/hmmlearn#349]
In the tutorial, where it says "calculate the likelihood of the data": this is incorrect phrasing. It should read either "calculate the likelihood of the model parameters given the data" or "calculate the probability of the data given the model parameters". There is no such thing as data likelihood.

**Comment by anntzer** [comment]
I agree. Can you open a PR to fix it? Thanks.

**Comment by anntzer** [comment]
closed by #350, thanks.
