### ISSUE TITLE
underflow in the sklearn.mixture.GMM module

### ISSUE THREAD

**Issue by georgid** [hmmlearn/hmmlearn#35]
I have been writing a duration-explicit HMM  https://github.com/georgid/HMMDuration
I am using the sklearn.mixture.GMM module in my observation model. I found out that it does not guarantee to avoid the issue of underflow as mentioned here: https://github.com/scikit-learn/scikit-learn/pull/538

FYI:
The issue of underflow can be solved by adding min float constant in  logsumexp(arr, axis=0) from utils/extmath.py
I did solve it by adding these lines to logsumexp(arr, axis=0)

import sys
MINIMAL_PROB = sys.float_info.min
old_settings = np.seterr( under='raise')
    try:
        a = np.exp(arr - vmax)
    except FloatingPointError:
        old_settings = np.seterr( under='ignore')
        a = np.exp(arr - vmax)
        a[a==0] = MINIMAL_PROB
Who cares to add this in the official release?

**Comment by superbobry** [comment]
Thank you, I'll definitely include your fix in the next `hmmlearn` release.

**Comment by andybrnr** [comment]
quick question: I've patched the code as georgid suggested, but still get a failed test:

>>>>>

>python setup.py build_ext
 --inplace && nosetests
running build_ext
copying build\lib.win-amd64-2.7\hmmlearn\_hmmc.pyd -> hmmlearn
........C:\Anaconda3\envs\python2.7\lib\site-packages\sklearn\utils\extmath.py:3
48: RuntimeWarning: invalid value encountered in subtract
  a = np.exp(arr - vmax)
F..............SSS...S...S......................................
======================================================================
FAIL: test_hmm_score_samples_consistent_with_gmm (test_base.TestBaseHMM)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\andrewb\Documents\GitHub\hmmlearn\hmmlearn\tests\test_base.py",
 line 128, in test_hmm_score_samples_consistent_with_gmm
    assert_array_almost_equal(hmmposteriors.sum(axis=1), np.ones(nobs))
  File "C:\Anaconda3\envs\python2.7\lib\site-packages\numpy\testing\utils.py", l
ine 842, in assert_array_almost_equal
    precision=decimal)
  File "C:\Anaconda3\envs\python2.7\lib\site-packages\numpy\testing\utils.py", l
ine 628, in assert_array_compare
    chk_same_position(x_isnan, y_isnan, hasval='nan')
  File "C:\Anaconda3\envs\python2.7\lib\site-packages\numpy\testing\utils.py", l
ine 608, in chk_same_position
    raise AssertionError(msg)
AssertionError:
Arrays are not almost equal to 6 decimals

x and y nan location mismatch:
 x: array([  1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,  nan])
 y: array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])
>>  raise AssertionError('\nArrays are not almost equal to 6 decimals\n\nx and y
 nan location mismatch:\n x: array([  1.,   1.,   1.,   1.,   1.,   1.,   1.,
1.,   1.,  nan])\n y: array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])'
)


----------------------------------------------------------------------
Ran 72 tests in 2.389s

FAILED (SKIP=5, failures=1)

<<<<<

not quite sure what's flowing through here, this seems distinct to the underflow issue? 

Thanks for the work on rescuing the orphaned HMMM functionality from scikit-learn and making it sustainable, I'll try to contribute in the future.

**Comment by superbobry** [comment]
Hello @georgid! Thank you for reporting the issue with `GMM`. Are you suggesting to add the epsilon fix to the `logsumexp` used in `hmmlearn` to make it more robust to underflow or you have an example of the underflow in the current version of `hmmlearn`?

@andybrnr can you please post the version of NumPy, SciPy and scikit-learn you're using. Thanks in advance.

**Comment by andybrnr** [comment]
Sure, running Anaconda 3.15.1 under Win7x64 with 64-bit versions of python2.7 and python3.4. Can't quite get it to install with python3.4, as I'm still troubleshooting compiler dependencies (had mingw gcc compilers installed, but need to make it work with Visual Studio Express, not quite sorted yet). Install of hmmlearn under python 2.7, numpy 1.9.2, scikit-learn 0.16.1, scipy 0.16.0 works, but I get underflow errors as mentioned by @georgid during tests (though tests still pass?). I had this sorted by applying his patch to the utils/extmath.py file in sklearn, but wondered if it was causing other problems, so I reverted the changes; examples still fail. Hope that's helpful, let me know if you want further info.

**Comment by andybrnr** [comment]
I sorted out the compiler issues and got it built for python3.4; interestingly, the example works fine in this case, tests look good. Not sure what's breaking under python2.7, but at least I have a working version.

**Comment by superbobry** [comment]
@georgid have you considered merging your library into `hmmlearn`? Explicit duration HMMs might be a good addition to the model we have already.

**Comment by georgid** [comment]
@superbobry  I am interested to integrate it so that others may use my code, but I dont see how. 
I developed my tool on top of https://github.com/guyz/HMM

if you care to help,
 give me some ideas to save me time figuring out and I can give it a try

**Comment by superbobry** [comment]
A good way to start might be to re-implement GMMHMM (see #78 for motivation). We can then think about integrating different sample weighting schemes, which your library has as well. 

Does this sound good?
