### ISSUE TITLE
Unstable hidden states when retraining with more data points !

### ISSUE THREAD

**Issue by vortexounet** [hmmlearn/hmmlearn#351]
The problem I found is that if I train data points from 0--to-->1000 (then decode these observations so I have 1000 hidden states, for example the 1st 400 are state A and the last 600 are state B ) then train a new model with data points from 0--to-->1200 (then decode these 1200, I have the first 400 are state B, and the last 800 are state A)... so the problem here is how to fix the first 400 data points to not switch from state A to state B at each training model.

Thank you

**Comment by Bingo-W** [comment]
I think the reason is the k-means. The initialization of the model is using the k-means to init the emitting matrix. So the states will be initialized randomly.

**Comment by jetychill** [comment]
@vortexounet I'm having a very similar problem with the GaussianHMM model 
here is some pseudo code 
`print(len(data))
500
predictions = hm.predict(data)
print(predictions)
 np.array([0,0,0,0,0,1,1,1,1,1....n])

lb =0 
rolling_preds = []
#creating a low bound variable
#and predicting on a rolling window basis, which i assume i would need to do in online systems
for i in range(30,len(data)):
   rolling_preds.append(hm.predict(data[lb:i+1])[-1])
   lb = lb+1

#here i have created a window size of 30 and for each iteration the window is being shifted by 1 
#after discarding the first 30 values of the batch predictions 
preds = preds[30:]
len(rolling_preds) == len(preds)
True

##I Would get vastly different results 
##Could anybody explain why is this happening
`

**Comment by jetychill** [comment]
> I think the reason is the k-means. The initialization of the model is using the k-means to init the emitting matrix. So the states will be initialized randomly.

Is this the case even after setting a random seed on the model initialization?

**Comment by anntzer** [comment]
The Viterbi algorithm does not guarantee that later points do not affect earlier points (even ignoring random seeding issues).  In fact it is a feature of the algorithm that the entire trajectory influences the final result.
