### ISSUE TITLE
unable to install hmmlearn on macOS with pip

### ISSUE THREAD

**Issue by fowly** [hmmlearn/hmmlearn#353]
I tried to install hmmlearn on my Mac running macOS Catalina 10.15 beta with 'pip install --upgrade --user hmmlearn' but failed

It returned **_'Failed building wheel for hmmlearn_**', below are all the logs:

Collecting hmmlearn
  Using cached https://files.pythonhosted.org/packages/d7/c5/91b43156b193d180ed94069269bcf88d3c7c6e54514a8482050fa9995e10/hmmlearn-0.2.2.tar.gz
Requirement already satisfied, skipping upgrade: numpy>=1.10 in /usr/local/lib/python2.7/site-packages (from hmmlearn) (1.16.5)
Requirement already satisfied, skipping upgrade: scikit-learn>=0.16 in /usr/local/lib/python2.7/site-packages (from hmmlearn) (0.20.4)
Requirement already satisfied, skipping upgrade: scipy>=0.13.3 in /usr/local/lib/python2.7/site-packages (from scikit-learn>=0.16->hmmlearn) (1.2.2)
Building wheels for collected packages: hmmlearn
  Building wheel for hmmlearn (setup.py) ... error
  Complete output from command /usr/local/opt/python@2/bin/python2.7 -u -c "import setuptools, tokenize;__file__='/private/var/folders/m6/y322v0816rj7vxmc7652xq000000gn/T/pip-install-PgA_Dc/hmmlearn/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /private/var/folders/m6/y322v0816rj7vxmc7652xq000000gn/T/pip-wheel-Iy9xtE --python-tag cp27:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.macosx-10.14-x86_64-2.7
  creating build/lib.macosx-10.14-x86_64-2.7/hmmlearn
  copying lib/hmmlearn/_version.py -> build/lib.macosx-10.14-x86_64-2.7/hmmlearn
  copying lib/hmmlearn/__init__.py -> build/lib.macosx-10.14-x86_64-2.7/hmmlearn
  copying lib/hmmlearn/utils.py -> build/lib.macosx-10.14-x86_64-2.7/hmmlearn
  copying lib/hmmlearn/stats.py -> build/lib.macosx-10.14-x86_64-2.7/hmmlearn
  copying lib/hmmlearn/base.py -> build/lib.macosx-10.14-x86_64-2.7/hmmlearn
  copying lib/hmmlearn/_utils.py -> build/lib.macosx-10.14-x86_64-2.7/hmmlearn
  copying lib/hmmlearn/hmm.py -> build/lib.macosx-10.14-x86_64-2.7/hmmlearn
  creating build/lib.macosx-10.14-x86_64-2.7/hmmlearn/tests
  copying lib/hmmlearn/tests/test_multinomial_hmm.py -> build/lib.macosx-10.14-x86_64-2.7/hmmlearn/tests
  copying lib/hmmlearn/tests/test_utils.py -> build/lib.macosx-10.14-x86_64-2.7/hmmlearn/tests
  copying lib/hmmlearn/tests/conftest.py -> build/lib.macosx-10.14-x86_64-2.7/hmmlearn/tests
  copying lib/hmmlearn/tests/test_gmm_hmm.py -> build/lib.macosx-10.14-x86_64-2.7/hmmlearn/tests
  copying lib/hmmlearn/tests/__init__.py -> build/lib.macosx-10.14-x86_64-2.7/hmmlearn/tests
  copying lib/hmmlearn/tests/test_gmm_hmm_new.py -> build/lib.macosx-10.14-x86_64-2.7/hmmlearn/tests
  copying lib/hmmlearn/tests/test_gaussian_hmm.py -> build/lib.macosx-10.14-x86_64-2.7/hmmlearn/tests
  copying lib/hmmlearn/tests/test_base.py -> build/lib.macosx-10.14-x86_64-2.7/hmmlearn/tests
  running build_ext
  xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
  error: Command "clang -fno-strict-aliasing -fno-common -dynamic -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/Tk.framework/Versions/8.5/Headers -DNDEBUG -g -fwrapv -O3 -Wall -l/usr/local/Cellar/openssl/1.0.2r/include -I/usr/local/lib/python2.7/site-packages/numpy/core/include -I/usr/local/include -I/usr/local/opt/openssl/include -I/usr/local/opt/sqlite/include -I/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c lib/hmmlearn/_hmmc.c -o build/temp.macosx-10.14-x86_64-2.7/lib/hmmlearn/_hmmc.o" failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for hmmlearn
  Running setup.py clean for hmmlearn
Failed to build hmmlearn
Installing collected packages: hmmlearn
  Running setup.py install for hmmlearn ... error
    Complete output from command /usr/local/opt/python@2/bin/python2.7 -u -c "import setuptools, tokenize;__file__='/private/var/folders/m6/y322v0816rj7vxmc7652xq000000gn/T/pip-install-PgA_Dc/hmmlearn/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/m6/y322v0816rj7vxmc7652xq000000gn/T/pip-record-2_CIvp/install-record.txt --single-version-externally-managed --compile --user --prefix=:
    running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-10.14-x86_64-2.7
    creating build/lib.macosx-10.14-x86_64-2.7/hmmlearn
    copying lib/hmmlearn/_version.py -> build/lib.macosx-10.14-x86_64-2.7/hmmlearn
    copying lib/hmmlearn/__init__.py -> build/lib.macosx-10.14-x86_64-2.7/hmmlearn
    copying lib/hmmlearn/utils.py -> build/lib.macosx-10.14-x86_64-2.7/hmmlearn
    copying lib/hmmlearn/stats.py -> build/lib.macosx-10.14-x86_64-2.7/hmmlearn
    copying lib/hmmlearn/base.py -> build/lib.macosx-10.14-x86_64-2.7/hmmlearn
    copying lib/hmmlearn/_utils.py -> build/lib.macosx-10.14-x86_64-2.7/hmmlearn
    copying lib/hmmlearn/hmm.py -> build/lib.macosx-10.14-x86_64-2.7/hmmlearn
    creating build/lib.macosx-10.14-x86_64-2.7/hmmlearn/tests
    copying lib/hmmlearn/tests/test_multinomial_hmm.py -> build/lib.macosx-10.14-x86_64-2.7/hmmlearn/tests
    copying lib/hmmlearn/tests/test_utils.py -> build/lib.macosx-10.14-x86_64-2.7/hmmlearn/tests
    copying lib/hmmlearn/tests/conftest.py -> build/lib.macosx-10.14-x86_64-2.7/hmmlearn/tests
    copying lib/hmmlearn/tests/test_gmm_hmm.py -> build/lib.macosx-10.14-x86_64-2.7/hmmlearn/tests
    copying lib/hmmlearn/tests/__init__.py -> build/lib.macosx-10.14-x86_64-2.7/hmmlearn/tests
    copying lib/hmmlearn/tests/test_gmm_hmm_new.py -> build/lib.macosx-10.14-x86_64-2.7/hmmlearn/tests
    copying lib/hmmlearn/tests/test_gaussian_hmm.py -> build/lib.macosx-10.14-x86_64-2.7/hmmlearn/tests
    copying lib/hmmlearn/tests/test_base.py -> build/lib.macosx-10.14-x86_64-2.7/hmmlearn/tests
    running build_ext
    xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
    error: Command "clang -fno-strict-aliasing -fno-common -dynamic -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/Tk.framework/Versions/8.5/Headers -DNDEBUG -g -fwrapv -O3 -Wall -l/usr/local/Cellar/openssl/1.0.2r/include -I/usr/local/lib/python2.7/site-packages/numpy/core/include -I/usr/local/include -I/usr/local/opt/openssl/include -I/usr/local/opt/sqlite/include -I/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c lib/hmmlearn/_hmmc.c -o build/temp.macosx-10.14-x86_64-2.7/lib/hmmlearn/_hmmc.o" failed with exit status 1
    
    ----------------------------------------
Command "/usr/local/opt/python@2/bin/python2.7 -u -c "import setuptools, tokenize;__file__='/private/var/folders/m6/y322v0816rj7vxmc7652xq000000gn/T/pip-install-PgA_Dc/hmmlearn/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/m6/y322v0816rj7vxmc7652xq000000gn/T/pip-record-2_CIvp/install-record.txt --single-version-externally-managed --compile --user --prefix=" failed with error code 1 in /private/var/folders/m6/y322v0816rj7vxmc7652xq000000gn/T/pip-install-PgA_Dc/hmmlearn/

Is there any solutions for macOS? I've saw some suggestions for windows users like download the .whl files for windows but that didn't work for me. Thx!

**Comment by yuritpinheiro** [comment]
I have a similar error.
I am using Ubuntu 18.04
The log:
Collecting hmmlearn (from auto-hmm==0.1)
  Using cached https://files.pythonhosted.org/packages/d7/c5/91b43156b193d180ed94069269bcf88d3c7c6e54514a8482050fa9995e10/hmmlearn-0.2.2.tar.gz
Collecting pytz>=2017.2 (from pandas->auto-hmm==0.1)
  WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='pypi.org', port=443): Read timed out. (read timeout=15)",)': /simple/pytz/
  Using cached https://files.pythonhosted.org/packages/87/76/46d697698a143e05f77bec5a526bf4e56a0be61d63425b68f4ba553b51f2/pytz-2019.2-py2.py3-none-any.whl
Collecting python-dateutil>=2.6.1 (from pandas->auto-hmm==0.1)
  Using cached https://files.pythonhosted.org/packages/41/17/c62faccbfbd163c7f57f3844689e3a78bae1f403648a6afb1d0866d87fbb/python_dateutil-2.8.0-py2.py3-none-any.whl
Collecting cycler>=0.10 (from matplotlib->auto-hmm==0.1)
  Using cached https://files.pythonhosted.org/packages/f7/d2/e07d3ebb2bd7af696440ce7e754c59dd546ffe1bbe732c8ab68b9c834e61/cycler-0.10.0-py2.py3-none-any.whl
Collecting kiwisolver>=1.0.1 (from matplotlib->auto-hmm==0.1)
  Using cached https://files.pythonhosted.org/packages/f8/a1/5742b56282449b1c0968197f63eae486eca2c35dcd334bab75ad524e0de1/kiwisolver-1.1.0-cp36-cp36m-manylinux1_x86_64.whl
Collecting pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 (from matplotlib->auto-hmm==0.1)
  Using cached https://files.pythonhosted.org/packages/11/fa/0160cd525c62d7abd076a070ff02b2b94de589f1a9789774f17d7c54058e/pyparsing-2.4.2-py2.py3-none-any.whl
Collecting isort<5,>=4.2.5 (from pylint->auto-hmm==0.1)
  Using cached https://files.pythonhosted.org/packages/e5/b0/c121fd1fa3419ea9bfd55c7f9c4fedfec5143208d8c7ad3ce3db6c623c21/isort-4.3.21-py2.py3-none-any.whl
Collecting astroid<3,>=2.2.0 (from pylint->auto-hmm==0.1)
  Using cached https://files.pythonhosted.org/packages/d5/ad/7221a62a2dbce5c3b8c57fd18e1052c7331adc19b3f27f1561aa6e620db2/astroid-2.2.5-py3-none-any.whl
Collecting mccabe<0.7,>=0.6 (from pylint->auto-hmm==0.1)
  Using cached https://files.pythonhosted.org/packages/87/89/479dc97e18549e21354893e4ee4ef36db1d237534982482c3681ee6e7b57/mccabe-0.6.1-py2.py3-none-any.whl
Collecting scikit-learn>=0.16 (from hmmlearn->auto-hmm==0.1)
  WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out. (read timeout=15)",)': /packages/a0/c5/d2238762d780dde84a20b8c761f563fe882b88c5a5fb03c056547c442a19/scikit_learn-0.21.3-cp36-cp36m-manylinux1_x86_64.whl
  Downloading https://files.pythonhosted.org/packages/a0/c5/d2238762d780dde84a20b8c761f563fe882b88c5a5fb03c056547c442a19/scikit_learn-0.21.3-cp36-cp36m-manylinux1_x86_64.whl (6.7MB)
     |████████████████████████████████| 6.7MB 5.8MB/s 
Collecting six>=1.5 (from python-dateutil>=2.6.1->pandas->auto-hmm==0.1)
  Using cached https://files.pythonhosted.org/packages/73/fb/00a976f728d0d1fecfe898238ce23f502a721c0ac0ecfedb80e0d88c64e9/six-1.12.0-py2.py3-none-any.whl
Requirement already satisfied: setuptools in ./venv/lib/python3.6/site-packages (from kiwisolver>=1.0.1->matplotlib->auto-hmm==0.1) (41.2.0)
Collecting lazy-object-proxy (from astroid<3,>=2.2.0->pylint->auto-hmm==0.1)
  Using cached https://files.pythonhosted.org/packages/0e/26/534a6d32572a9dbca11619321535c0a7ab34688545d9d67c2c204b9e3a3d/lazy_object_proxy-1.4.2-cp36-cp36m-manylinux1_x86_64.whl
Collecting typed-ast>=1.3.0; implementation_name == "cpython" (from astroid<3,>=2.2.0->pylint->auto-hmm==0.1)
  Using cached https://files.pythonhosted.org/packages/31/d3/9d1802c161626d0278bafb1ffb32f76b9d01e123881bbf9d91e8ccf28e18/typed_ast-1.4.0-cp36-cp36m-manylinux1_x86_64.whl
Collecting wrapt (from astroid<3,>=2.2.0->pylint->auto-hmm==0.1)
Collecting joblib>=0.11 (from scikit-learn>=0.16->hmmlearn->auto-hmm==0.1)
  Downloading https://files.pythonhosted.org/packages/cd/c1/50a758e8247561e58cb87305b1e90b171b8c767b15b12a1734001f41d356/joblib-0.13.2-py2.py3-none-any.whl (278kB)
     |████████████████████████████████| 286kB 6.0MB/s 
Collecting scipy>=0.17.0 (from scikit-learn>=0.16->hmmlearn->auto-hmm==0.1)
  Downloading https://files.pythonhosted.org/packages/29/50/a552a5aff252ae915f522e44642bb49a7b7b31677f9580cfd11bcc869976/scipy-1.3.1-cp36-cp36m-manylinux1_x86_64.whl (25.2MB)
     |████████████████████████████████| 25.2MB 3.6MB/s 
Building wheels for collected packages: hmmlearn
  Building wheel for hmmlearn (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/yuri/Documentos/Projetos/auto_hmm/venv/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ucum0ju6/hmmlearn/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ucum0ju6/hmmlearn/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-agfz8319 --python-tag cp36
       cwd: /tmp/pip-install-ucum0ju6/hmmlearn/
  Complete output (28 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.6
  creating build/lib.linux-x86_64-3.6/hmmlearn
  copying lib/hmmlearn/stats.py -> build/lib.linux-x86_64-3.6/hmmlearn
  copying lib/hmmlearn/base.py -> build/lib.linux-x86_64-3.6/hmmlearn
  copying lib/hmmlearn/hmm.py -> build/lib.linux-x86_64-3.6/hmmlearn
  copying lib/hmmlearn/__init__.py -> build/lib.linux-x86_64-3.6/hmmlearn
  copying lib/hmmlearn/_version.py -> build/lib.linux-x86_64-3.6/hmmlearn
  copying lib/hmmlearn/utils.py -> build/lib.linux-x86_64-3.6/hmmlearn
  copying lib/hmmlearn/_utils.py -> build/lib.linux-x86_64-3.6/hmmlearn
  creating build/lib.linux-x86_64-3.6/hmmlearn/tests
  copying lib/hmmlearn/tests/test_gmm_hmm.py -> build/lib.linux-x86_64-3.6/hmmlearn/tests
  copying lib/hmmlearn/tests/test_utils.py -> build/lib.linux-x86_64-3.6/hmmlearn/tests
  copying lib/hmmlearn/tests/test_gaussian_hmm.py -> build/lib.linux-x86_64-3.6/hmmlearn/tests
  copying lib/hmmlearn/tests/__init__.py -> build/lib.linux-x86_64-3.6/hmmlearn/tests
  copying lib/hmmlearn/tests/test_gmm_hmm_new.py -> build/lib.linux-x86_64-3.6/hmmlearn/tests
  copying lib/hmmlearn/tests/test_multinomial_hmm.py -> build/lib.linux-x86_64-3.6/hmmlearn/tests
  copying lib/hmmlearn/tests/test_base.py -> build/lib.linux-x86_64-3.6/hmmlearn/tests
  copying lib/hmmlearn/tests/conftest.py -> build/lib.linux-x86_64-3.6/hmmlearn/tests
  running build_ext
  lib/hmmlearn/_hmmc.c:17:10: fatal error: Python.h: Arquivo ou diretório inexistente
   #include "Python.h"
            ^~~~~~~~~~
  compilation terminated.
  error: Command "x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/tmp/pip-install-ucum0ju6/hmmlearn/.eggs/numpy-1.17.2-py3.6-linux-x86_64.egg/numpy/core/include -I/usr/include/python3.6m -I/home/yuri/Documentos/Projetos/auto_hmm/venv/include/python3.6m -c lib/hmmlearn/_hmmc.c -o build/temp.linux-x86_64-3.6/lib/hmmlearn/_hmmc.o" failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for hmmlearn
  Running setup.py clean for hmmlearn
Failed to build hmmlearn
Installing collected packages: numpy, pytz, six, python-dateutil, pandas, cycler, kiwisolver, pyparsing, matplotlib, rope, isort, lazy-object-proxy, typed-ast, wrapt, astroid, mccabe, pylint, joblib, scipy, scikit-learn, hmmlearn, auto-hmm
  Running setup.py install for hmmlearn ... error
    ERROR: Command errored out with exit status 1:
     command: /home/yuri/Documentos/Projetos/auto_hmm/venv/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ucum0ju6/hmmlearn/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ucum0ju6/hmmlearn/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-911rro_f/install-record.txt --single-version-externally-managed --compile --install-headers /home/yuri/Documentos/Projetos/auto_hmm/venv/include/site/python3.6/hmmlearn
         cwd: /tmp/pip-install-ucum0ju6/hmmlearn/
    Complete output (28 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.6
    creating build/lib.linux-x86_64-3.6/hmmlearn
    copying lib/hmmlearn/stats.py -> build/lib.linux-x86_64-3.6/hmmlearn
    copying lib/hmmlearn/base.py -> build/lib.linux-x86_64-3.6/hmmlearn
    copying lib/hmmlearn/hmm.py -> build/lib.linux-x86_64-3.6/hmmlearn
    copying lib/hmmlearn/__init__.py -> build/lib.linux-x86_64-3.6/hmmlearn
    copying lib/hmmlearn/_version.py -> build/lib.linux-x86_64-3.6/hmmlearn
    copying lib/hmmlearn/utils.py -> build/lib.linux-x86_64-3.6/hmmlearn
    copying lib/hmmlearn/_utils.py -> build/lib.linux-x86_64-3.6/hmmlearn
    creating build/lib.linux-x86_64-3.6/hmmlearn/tests
    copying lib/hmmlearn/tests/test_gmm_hmm.py -> build/lib.linux-x86_64-3.6/hmmlearn/tests
    copying lib/hmmlearn/tests/test_utils.py -> build/lib.linux-x86_64-3.6/hmmlearn/tests
    copying lib/hmmlearn/tests/test_gaussian_hmm.py -> build/lib.linux-x86_64-3.6/hmmlearn/tests
    copying lib/hmmlearn/tests/__init__.py -> build/lib.linux-x86_64-3.6/hmmlearn/tests
    copying lib/hmmlearn/tests/test_gmm_hmm_new.py -> build/lib.linux-x86_64-3.6/hmmlearn/tests
    copying lib/hmmlearn/tests/test_multinomial_hmm.py -> build/lib.linux-x86_64-3.6/hmmlearn/tests
    copying lib/hmmlearn/tests/test_base.py -> build/lib.linux-x86_64-3.6/hmmlearn/tests
    copying lib/hmmlearn/tests/conftest.py -> build/lib.linux-x86_64-3.6/hmmlearn/tests
    running build_ext
    lib/hmmlearn/_hmmc.c:17:10: fatal error: Python.h: Arquivo ou diretório inexistente
     #include "Python.h"
              ^~~~~~~~~~
    compilation terminated.
    error: Command "x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/home/yuri/Documentos/Projetos/auto_hmm/venv/lib/python3.6/site-packages/numpy/core/include -I/usr/include/python3.6m -I/home/yuri/Documentos/Projetos/auto_hmm/venv/include/python3.6m -c lib/hmmlearn/_hmmc.c -o build/temp.linux-x86_64-3.6/lib/hmmlearn/_hmmc.o" failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/yuri/Documentos/Projetos/auto_hmm/venv/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ucum0ju6/hmmlearn/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ucum0ju6/hmmlearn/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-911rro_f/install-record.txt --single-version-externally-managed --compile --install-headers /home/yuri/Documentos/Projetos/auto_hmm/venv/include/site/python3.6/hmmlearn Check the logs for full command output.

**Comment by anntzer** [comment]
@fowly please google for "invalid active developer path", there's plenty of responses.
@yuritpinheiro https://stackoverflow.com/questions/16454129/python-h-header-file-missing-on-mac-os-x-10-6 or similar.
