### ISSUE TITLE
Future leakage in model.predict()

### ISSUE THREAD

**Issue by alex7088** [hmmlearn/hmmlearn#355]
I am trying to use hidden states as input features to train another model. I was surprised to find that I can’t really reproduce those results that I received on the test.
It turned out that the predict method sets the hidden state looking into the future. It is easy to check.
if we compare the predicted states (let there be 2) and the real last ones, if we follow the observations by the window and take the last predicted state.
a1 = list(df['hmm'])
a2 = list(df['delta_3'])
for i in range(len(a1)-100,len(a1)):
    result=hmm_model.predict(np.array(a2[i-900:i+1]).reshape(-1,1))[-1]
    print(a1[i],result)
0 0
0 0
1 0
1 1
1 1
1 0
1 1
1 1
1 1
1 1
0 1
0 0
0 0

The first column is predict () for the whole sample. The second column is what happens if we do not know the future.
It can be clearly seen that the predict method looks one step ahead.

My question: how to get predict() without future leak

**Comment by anntzer** [comment]
Yes, the Viterbi algorithm, which is implemented by hmmlearn, performs state prediction by considering the whole sequence at once, and hence the future does matter.  This is a feature of it, not a bug.
