### ISSUE TITLE
ValueError: expected a sample from a Multinomial distribution.

### ISSUE THREAD

**Issue by YatinBhutani95** [hmmlearn/hmmlearn#356]
Hello, i'm trying  to fit MultinomialHmm model.
The data is stored into a column of a pandas, but when i passed the column to the fit() this error is occured: ValueError: expected a sample from a Multinomial distribution.

How can i solve it?

**Comment by hpathak92** [comment]
Hi Yatin
Were you able to solve this issue?

**Comment by YatinBhutani95** [comment]
> Hi @YatinBhutani95
> Were you able to solve this issue?

Hi, yes i've solved the problem.
Fit want a multinomial distribution, that means in the column passed to the function must contain all the possibilities of the observations.
Example:
In my case the observations were 5 and in the column I had to have all the possibilities starting from 0
