### ISSUE TITLE
hmmlearn 0.1.1 requires a function from one its dependencies (Cython.Distutils) in setup.py, and thus cannot be installed

### ISSUE THREAD

**Issue by ernstki** [hmmlearn/hmmlearn#357]
Line 13 of `setup.py` included with `hmmlearn` 0.1.1 is

```python
from Cython.Distutils import build_ext
```

and yet `Cython` is stated as a dependency within `setup.py`.

This creates a chicken-and-egg problem where you can't actually just _install_ `hmmlearn` without also knowing that it has two hard dependencies (numpy and Cython), which `setup.py` is normally supposed to take care of.

Maybe it's no big deal if you understand what the stack trace is telling you, and with a bit of searching, you can determine that **[the solution](https://stackoverflow.com/a/26687525/785213) is to just `pip install cython` and try again.**

None of that is inherently obvious to a biologist or geneticist who just wants to use some package that has a dependency on `hmmlearn` at 0.1.1, because half of the bioinformatics packages out there are stuck at Python 2.7.x right now.

As hmmlearn 0.1.1 is no longer the current version, and the 0.2.x series only supports Python 3.x, I am assuming this issue will not be resolved. I'm only documenting it here for posterity, in case someone else runs into this error.

**Comment by anntzer** [comment]
Actually 0.2.x still supports Py2, and should not exhibit this issue.
