### ISSUE TITLE
Algorithm for model estimation in MultinomialHMM

### ISSUE THREAD

**Issue by mohammeddanishkhan** [hmmlearn/hmmlearn#359]
Hey all,

This is not an issue, but a question.
I am using MultinomialHMM for model estimation. The documentation does not mention as to which algorithm is being used here for estimation of model (eg: Baum-Welch). So any information regarding algorithm used for model estimation would be great help.

The task that I am implementing here is; given only observation sequence and no. of states estimate the model i.e estimate **start probability** matrix, **transition probability** matrix, **emission probability** matrix. 
Here is a sample code
import numpy as np
from hmmlearn import hmm

model=MultinomialHMM(n_components=2) # model has 2 states

X = np.array([[0,1,0]]) #observation sequence
model.fit(X) #fit the model over the observation sequence

model.decode([0,1,0]) #decode the observed sequence
#print the model parameters
print(model.transmat_) #estimated transition matrix
print(model.startprob_) #estimated start probability
print(model.emissionprob_) #estimated observation matrix or emission matrix

Also, I would appreciate if it could be confirmed that I am correctly invoking the library for model estimation. If any issue/better way to implement it, please point it out.

**Comment by anntzer** [comment]
The algorithms used are listed in https://hmmlearn.readthedocs.io/en/latest/tutorial.html.
