### ISSUE TITLE
No explicit dependency on setuptools 

### ISSUE THREAD

**Issue by igorabr** [hmmlearn/hmmlearn#360]
I've got "ImportError: setuptools>=36.2 is required" when tried to install hmmlearn together with other packages from requirements.txt. 

Setup.py includes the following lines:
```
if LooseVersion(setuptools.__version__) < "36.2":
    raise ImportError("setuptools>=36.2 is required")
```
but (after installing setuptools manually and then hmmtools) "pip show" doesn't show that setuptools is required by hmmlearn:

```
c:\code>pip show setuptools
Name: setuptools
Version: 41.6.0
Summary: Easily download, build, install, upgrade, and uninstall Python packages
Home-page: https://github.com/pypa/setuptools
Author: Python Packaging Authority
Author-email: distutils-sig@python.org
License: UNKNOWN
Location: c:\program files\python35\lib\site-packages
Requires:
Required-by: pipenv, protobuf, kiwisolver, ipython
```

**Comment by anntzer** [comment]
It is a setup-time dependency, not a runtime one.

**Comment by igorabr** [comment]
@anntzer, my diagnosis may be wrong, but I still couldn't get hmmlearn installed from requirements.txt and had to explicitly install setuptools before "pip install -r requirements.txt". Something should be wrong.

**Comment by anntzer** [comment]
There is no requirements.txt file in the repo?
