### ISSUE TITLE
Can't able to install in mac

### ISSUE THREAD

**Issue by MurugeshMarvel** [hmmlearn/hmmlearn#362]
I tried to install using pip comman in python3 env, got xcrun error. 
![Screenshot 2019-11-11 at 12 41 26 PM](https://user-images.githubusercontent.com/9530814/68568084-988e2980-0480-11ea-85eb-4a95f79480f1.png)

**Comment by anntzer** [comment]
See e.g. https://stackoverflow.com/questions/52522565/git-is-not-working-after-macos-update-xcrun-error-invalid-active-developer-pa https://apple.stackexchange.com/questions/254380/why-am-i-getting-an-invalid-active-developer-path-when-attempting-to-use-git-a or various other pages you can find by googling for the error.
