### ISSUE TITLE
return value problem: _logsumexp(dtype_t[:] X)

### ISSUE THREAD

**Issue by 1173710126** [hmmlearn/hmmlearn#363]
a problem when reading the code below:

`    
cdef dtype_t X_max = _max(X)
    if isinf(X_max):
        return -INFINITY
`
why it return -1 * INFINITY instead of INFINITY, because I think log(exp(X1)+exp(X2)+...) = X_max, when X_max is INFINITY 

thanks

**Comment by anntzer** [comment]
I think the idea is to cater for the case X_max = -inf, not the case X_max = +inf.  Do you have a case that would trigger the latter?

**Comment by 1173710126** [comment]
no，I just read the code and don‘t understand, thanks for your answer
