### ISSUE TITLE
use pip install hmmlearn

### ISSUE THREAD

**Issue by smithCoderLeo** [hmmlearn/hmmlearn#366]
while i use `pip install --upgrade --user hmmlearn`，some errors occured that i cannot install successfully

finally i use this method ：
i download hmmlearn from https://www.lfd.uci.edu/~gohlke/pythonlibs/#hmmlearn
and use then use `pip install (The location of the file) /hmmlearn‑0.2.1‑cp36‑cp36m‑win_amd64.whl`

**Comment by anntzer** [comment]
Glad to hear it works now.
