### ISSUE TITLE
Can not install in python3.8.0

### ISSUE THREAD

**Issue by Lynch4u** [hmmlearn/hmmlearn#367]
Whl : hmmlearn‑0.2.2‑cp38‑cp38‑win_amd64.whl,  form : https://www.lfd.uci.edu/~gohlke/pythonlibs/#hmmlearn

Is this whl can not install in python3.8.0 ,centos7.7 ?

''ERROR: hmmlearn-0.2.2-cp38-cp38-win_amd64.whl is not a supported wheel on this platform.
''

**Comment by anntzer** [comment]
That's a windows wheel.

**Comment by Lynch4u** [comment]
> That's a windows wheel.

OH..My fault..
