### ISSUE TITLE
For the update of sklearn 0.22

### ISSUE THREAD

**Issue by EdisonLeeeee** [hmmlearn/hmmlearn#368]
As sklearn is updated to version 0.22, some API have changed and warnings will occur during using `model.fit()`, e.g., `check_is_fitted` :

```
Passing attributes to check_is_fitted is deprecated and will be removed in 0.23. The attributes argument is ignored.
```
I solve this warnings by change
```python
check_is_fitted(self, "transmat_")
```
into
```python
check_is_fitted(self)
```
but I don;t know  if it's going to be a problem.

**Comment by anntzer** [comment]
This is fixed as of master by https://github.com/hmmlearn/hmmlearn/commit/cb2ad0c1e1c9ef85fe2c28ce1ca47b8740acc6c3, thanks for the notice, will make a new release "soon".

**Comment by anntzer** [comment]
Looks like a test is failing on OSX, but I can't test that locally (it passes fine on Linux and Windows): https://dev.azure.com/anntzer/hmmlearn/_build/results?buildId=172&view=logs
I would appreciate if anyone with access to a mac could have a look at it.

**Comment by anntzer** [comment]
I'll keep this open in case anyone with a mac can help with the packaging.

**Comment by anntzer** [comment]
0.2.3 has been released.
