### ISSUE TITLE
install failed

### ISSUE THREAD

**Issue by wmtxt** [hmmlearn/hmmlearn#369]
The install process is filed and the follow code is the error dispaly. Plese help me!!!
ERROR: Command errored out with exit status 1:
     command: /usr/bin/python2.7 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-Cn4NSr/hmmlearn/setup.py'"'"'; __file__='"'"'/tmp/pip-install-Cn4NSr/hmmlearn/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-Cn4NSr/hmmlearn/pip-egg-info
         cwd: /tmp/pip-install-Cn4NSr/hmmlearn/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-Cn4NSr/hmmlearn/setup.py", line 18, in <module>
        raise ImportError("setuptools>=36.2 is required")
    ImportError: setuptools>=36.2 is required
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by anntzer** [comment]
That's what it says: "setuptools>=36.2 is required."
