### ISSUE TITLE
Looking for help with macOS testing

### ISSUE THREAD

**Issue by anntzer** [hmmlearn/hmmlearn#370]
I am planning to make a new release of hmmlearn for compatibility with sklearn 0.22.
I added testing on macOS and will (try to) build wheels as well, but it appears that the macOS tests are failing (https://dev.azure.com/anntzer/hmmlearn/_build/results?buildId=172&view=logs).  I cannot repro the failures locally and don't have access to a mac, so any help would be welcome.

Edit: the failing test is test_gmm_hmm_new.py::TestGMMHMMWithTiedCovars::test_fit_zero_variance; I xfailed it for the time being on macOS.

**Comment by MBrouns** [comment]
I tried to reproduce this test failure but was unable. My system runs

- Python 3.7
- OSX 10.15.2

**Comment by anntzer** [comment]
Thanks for having a look!

**Comment by dantheman0207** [comment]
I'm able to work on this. How would I go about replicating this error? I can no longer see the build logs on azure as they've expired.

**Comment by anntzer** [comment]
I pushed a new commit removing the xfail to get a new azure log, but looks like macOS fixed itself in the meantime (https://dev.azure.com/anntzer/hmmlearn/_build/results?buildId=222&view=results), so I'll close the issue.  Thanks for volunteering to help; I'll keep your names in case this happens again, so that no good deed goes unpunished, though ;-)

**Comment by anntzer** [comment]
Actually, that got "fixed" when I accidentally inactivated a chunk of code that was necessary (https://github.com/hmmlearn/hmmlearn/issues/404).  I restored that chunk, so now the issue is present again :/

**Comment by anntzer** [comment]
Fixed by properly handling zero-weight components in GMMHMM.
