### ISSUE TITLE
Interpreting Transition Probability Matrix 

### ISSUE THREAD

**Issue by cmp1** [hmmlearn/hmmlearn#373]
## I am requesting a new feature

This library is currently not under active development.  Large-scale features
are unlikely to be added unless accompanied with a PR, which will be considered
by the maintainers to the best of their ability.

I currently have a 3 component GaussianHMM fitted to a single sequence of time series data. I am trying to predict the state at t+1. 

My question is whether there is an inbuilt function that I am missing, or would I have to calculate this by hand? if the latter, then the transmat_ function returns an n x n matrix of the transition probabilities....are these ordered numerically in terms of n components? 

Thank you!

**Comment by anntzer** [comment]
no. yes. no.
