### ISSUE TITLE
GMMHMM using Multiple Sequences

### ISSUE THREAD

**Issue by SainiNidhi** [hmmlearn/hmmlearn#377]
Hello,

When I use GaussianHMM with multiple sequences it works fine. I train and test my models.
However, when I use GMMHMM with multiple sequences it trains but it runs only for two iterations. 
It also shows monitor_.converged TRUE which I think is not possible.

GMMHMM(n_components=5, n_mix = 3, n_iter=10, covariance_type='tied', algorithm="map", verbose=True)
When I test, it show me error:
ValueError: Covariance of state #0 is not positive definite

I have tried with a single sequence(with the same dataset) it works fine as well.

**Comment by wxy117** [comment]
Same problem here.

`hmm.GMMHMM(n_components=3, verbose=True, n_iter=500,tol=0.1).fit(X, lengths)`

`         1        -304.4300             +nan
         2        -228.0815         +76.3485
         3       -7275.3321       -7047.2506`

**Comment by yujianll** [comment]
Have you solved the problem? I also have the same issue.

1     -661742.0333             +nan
2     -696210.6074      -34468.5741

**Comment by fcostin** [comment]
A couple of different symptoms related to GMMHMM are mentioned in this issue:

1. attempting to train GMMHMM with multiple sequences halts after a small number of iterations and claims to have converged (perhaps showing that the objective function is decreasing between EM iterations, which is not meant to happen); and
2. ValueError: Covariance of state #0 is not positive definite

The first symptom, mentioned here by three users, was also reported in https://github.com/hmmlearn/hmmlearn/issues/410 with a self-contained example that is able to reproduce the issue.

A patch has been merged that fixes the GMMHMM multi sequence convergence problem reported in https://github.com/hmmlearn/hmmlearn/issues/410 (see https://github.com/hmmlearn/hmmlearn/pull/417 ) . It is plausible that this patch fixes some or all of the GMMHMM multi-sequence problems reported in this issue, but it is not possible to confirm without self contained reproducible examples.

**Comment by anntzer** [comment]
@fcostin has kindly provided a fix to fit multiple sequences using GMMHMM, which was previously not supported.  This is now released as hmmlearn 0.2.6.  Please consider upgrading to it, and reopen the issue if your problem is still present.
