### ISSUE TITLE
Computing the model likelihood using Forward-Backward algorithm

### ISSUE THREAD

**Issue by timsainb** [hmmlearn/hmmlearn#378]
I would like to compute the model likelihood given the model parameters and observed data using the Forward-Backward algorithm. 

The documentation states:

> There are three fundamental problems for HMMs:
> 
> 1. Given the model parameters and observed data, estimate the optimal sequence of hidden states.
> **2. Given the model parameters and observed data, calculate the model likelihood.**
> 3. Given just the observed data, estimate the model parameters.
> 
> **The first and the second problem can be solved by the dynamic programming algorithms known as the Viterbi algorithm and the Forward-Backward algorithm, respectively**. The last one can be solved by an iterative Expectation-Maximization (EM) algorithm, known as the Baum-Welch algorithm.

I looked through the documentation, API, and issues, but could not find the relevant function.

Thanks!

**Comment by anntzer** [comment]
https://hmmlearn.readthedocs.io/en/latest/api.html#hmmlearn.hmm.MultinomialHMM.score may be what you want?

**Comment by timsainb** [comment]
Thanks for the quick rely @anntzer !

Isn't this the probability of the data given the model (𝑃(𝑂|𝜃)), rather than the likelihood of the model given the data (𝐿(𝜃|𝑂))? 

E.g. if I want to compare models on the basis of AIC, I would calculate the AIC as - 2log(𝐿)+2𝐾.

**Comment by anntzer** [comment]
Are these not equal by definition of the likelihood? (https://en.wikipedia.org/wiki/Likelihood_function#Continuous_probability_distribution)

**Comment by timsainb** [comment]
Yes! Thank you for clearing that up.
