### ISSUE TITLE
Extend the sample method: sampling after several observants

### ISSUE THREAD

**Issue by Freakwill** [hmmlearn/hmmlearn#379]
I want to sample with HMM after several observants, for example:
I have obtained a HMM model, and observed some samples (denoted as O1 O2... On-1), now generate the following sample(s) (On), formally, calculate the prob P(On| O1 O2...On-1, theta) where O1 O2... On-1 and theta (params of the model) are known. The api might be designed as `model.sample(n_samples=10, random_state=0, observants=[...])`.

**Comment by owenshen24** [comment]
I think `predict_proba(observations)[-1]` will give you the state distribution after having seen all of your observations. 
From there, you can probably build out a simple function to do the sampling based on that distribution. The easiest way might be to overwrite `startprob_prior`?

**Comment by Freakwill** [comment]
> I think `predict_proba(observations)[-1]` will give you the state distribution after having seen all of your observations.
> From there, you can probably build out a simple function to do the sampling based on that distribution. The easiest way might be to overwrite `startprob_prior`?

Thank you for your reply. More complicated case is, to define a method `model.sample(n_samples=10, random_state=0, observants={})` to produce a sequence with known observants at any position, where parameter `observants` is a dict of index-number pair, such as {1: O1, 3: O3, 5:O5}, and it would produce O2 O4 O6 O7...
