### ISSUE TITLE
Cross-Validation  - Continuous training

### ISSUE THREAD

**Issue by fpgdesa** [hmmlearn/hmmlearn#384]
Hi! I need to implement 10 fold cross-validation to select best model parameters. My doubt is about continuous training. During loop through the 10 folds, is correct to keep the same model object performing the parameters updating?

Like this:

          
          for train_index, test_index in kf.split(matrix):
                   
                    X_train, X_test = matrix[train_index], matrix[test_index]        
                                
                    try:
                        model_cv.train_model(X_train)                        
                    except:
                        print("Fit Training Error")

**Comment by owenshen24** [comment]
I think the right thing to do is to instantiate a new model each time.
If you look in the code, [`fit`](https://github.com/hmmlearn/hmmlearn/blob/e8721266ea2795515bc6747f5da735636735dbee/lib/hmmlearn/base.py#L481) will call `_do_m_step`, which in all 3 of the implementations of the HMM, appears to be modifying the existing model's parameters.

**Comment by owenshen24** [comment]
Sorry, my previous answer was incorrect.

I believe it's fine to use the same model, as when you call `fit`, the model will re-estimate the model parameters from scratch each time.

I ran some tests by calling `fit` several times through a loop and verified that the score was around the same each time on the trained sequence.

**Comment by anntzer** [comment]
I agree with the response above.
