### ISSUE TITLE
why params='tmc' doesn't work?

### ISSUE THREAD

**Issue by HYuanggg** [hmmlearn/hmmlearn#386]
model=hmm.GaussianHMM(n_components=3,covariance_type='full',params='tmc',n_iter=100)
model.startprob_ = np.array([0., 0., 1.])

I set params='tmc' because I want startprob_ to be fixed. But after fit, startprob_ always changes to [0.33,0.33,0.33].

What did I do wrong?

**Comment by anntzer** [comment]
You also need to exclude 's' from init_params.
