### ISSUE TITLE
AttributeError: '_BaseHMM' object has no attribute '_get_n_fit_scalars_per_param'

### ISSUE THREAD

**Issue by HYDesmondLiu** [hmmlearn/hmmlearn#387]
**Question:**
   I tried to use the BaseHMM to fit a model with a sequence of observations.
I used the example in tutorial to fit, however there is an AttributeError complaining 
"**__BaseHMM object has no attribute '_get_n_fit_scalars_per_param_**' "
   How do I fix this? And my target observation matrix is ~60K by 21 and the length of sequence is 21, how do I set the **_lengths_** in bi and **_score_**?

**Environment:**
CentOS Linux release 7.7.1908 (Core)
Python 3.6.8 :: Anaconda custom (64-bit)
hmmlearn==0.2.3.post4+g70f6194

```
import numpy as np
from hmmlearn import hmm
n = 3
iteration = 100
model = hmm._BaseHMM(n_components = n, 
                     n_iter = iteration,
                     algorithm = 'viterbi',
                     init_params = '',
                     tol = 0.001,
                     params = ''
)
X1 = [[0.5], [1.0], [-1.0], [0.42], [0.24]]
X2 = [[2.4], [4.2], [0.5], [-0.24]]
X = np.concatenate([X1, X2])
lengths = [len(X1), len(X2)]
model.fit(X, lengths)
   
```

**Error Message**
```
Traceback (most recent call last):
  File "test.py", line 16, in <module>
    model.fit(X, lengths)
  File "/home/hliu/.local/lib/python3.6/site-packages/hmmlearn/base.py", line 462, in fit
    self._init(X, lengths=lengths)
  File "/home/hliu/.local/lib/python3.6/site-packages/hmmlearn/base.py", line 547, in _init
    n_fit_scalars_per_param = self._get_n_fit_scalars_per_param()
AttributeError: '_BaseHMM' object has no attribute '_get_n_fit_scalars_per_param'
```

**Comment by owenshen24** [comment]
I think the BaseHMM class isn't supposed to be instantiated by itself; in the code, it seems to be missing methods that the other HMM classes provide when they subclass it. Do you get the same error if you use MultinomialHMM or GausianHMM?

**Comment by anntzer** [comment]
@owenshen24 correctly addressed the question.
