### ISSUE TITLE
HMM topology with minimum duration

### ISSUE THREAD

**Issue by priscilla-amorim** [hmmlearn/hmmlearn#392]
Hi! I'm currently implementing a diarization system (ICSI-09) with hmmlearn, which is almost complete, but I'm facing an issue that I hope someone can help me with.

In the description of the system, the authors stress the need to force the HMM topology to remain in the same state for a minimum duration. They do that including in each state of this HMM a several sub-states that share the same GMM pdf (figure).

The hsmmlearn library has this functionality, but I was wondering if it can also be implemented with hmmlearn (which I found much more stable).

![topology](https://user-images.githubusercontent.com/24230866/91467233-b50c1e80-e866-11ea-8067-fe475b77a1e1.png)

**Comment by poypoyan** [comment]
You need to "force" the initialization of the transition matrix. To do this, you set `init_params=='cmsw'` for GMMHMM (basically all parameters **except** `t`, the transition matrix). Then you need to define the transition matrix of your own. In the EM algorithm (`.fit()`), if a probability parameter is zero, the updated probability will still be zero. For example, we have this code (GaussianHMM in this case):
```
M = hmm.GaussianHMM(3, covariance_type='diag', init_params='cms')
M.transmat_ = np.array([[0.5, 0.0, 0.5],
                        [0.4, 0.3, 0.3],
                        [0.0, 0.4, 0.6]])
M.fit(obs)
```
After the fitting, of course the entries of `M.transmat_` will be modified, except for the zero entries (sample output below).

![image](https://user-images.githubusercontent.com/64708703/96472433-09c68700-1263-11eb-9457-f2cfc8d68353.png)

In your case, treat the sub-states as states too, except that you force the transition probability of sub-state '1' up to 'S-1' to the next sub-state only (like `[0.0, 0.0, ..., 1.0, ..., 0.0]`); for the 'last' sub-state (sub-state 'S' in your figure), there should only be non-zero transition probabilities for itself and the 'initial' sub-states (sub-state '1' in your figure).

Hope this helps.

**Comment by anntzer** [comment]
I think @poypoyan address the question.  (Thanks!)
