### ISSUE TITLE
modify HMM to IO-HMM

### ISSUE THREAD

**Issue by aminzadenoori** [hmmlearn/hmmlearn#393]
Hello,
I want to use HMM learn code to modify it and make it possible to be able to train IO-HMM in which the transition probabilities are dependant on inputs. Can you guide me on how can I solve this problem?
thank you
## I am requesting a new feature
This library is currently not under active development.  Large-scale features
are unlikely to be added unless accompanied with a PR, which will be considered
by the maintainers to the best of their ability.

## I am reporting a bug

If you are reporting a bug, please

- Make sure that it occurs with the latest release of hmmlearn (per
  https://pypi.org/project/hmmlearn/).
- Provide a short, self-contained, correct example (http://sscce.org/).
  Maintainers must be able to reproduce the issue **by copy-pasting your
  example in a new, empty file/console/notebook**.  Avoid including data files
  as much as possible; if they are absolutely necessary, they must be in csv or
  npy format, and code for loading the file must be included in the example.

Issues not reproducible with the latest release of hmmlearn or without a short,
self-contained, correct example **will be closed**.

**Comment by anntzer** [comment]
No.

(Also, as noted in the issue template: This library is currently not under active development. Large-scale features are unlikely to be added unless accompanied with a PR, which will be considered by the maintainers to the best of their ability.)
