### ISSUE TITLE
[BUG] Log probability of state sequence returned by .decode() disagrees with manual check

### ISSUE THREAD

**Issue by b2jia** [hmmlearn/hmmlearn#394]
For an emission ```X```, ```_BaseHMM.decode(X)```, returns ```logprob``` - log probability of the produced state sequence and ```state_sequence``` - labels for each sample from X obtained via a given decoder algorithm.

Easy enough, I just wanted double check the logprob and I computed the log sum of probabilities from my starting prob, transition matrix, and emission matrix. I found that the discrepancy between my hand calculation and ```decode()``` is quite large:

```
log_prob, states = model.decode(X, algorithm='viterbi')

### my check ###
num_states = 9
start_prob = 1/7
trans_hat = np.log(start_prob) # starting probability
emit_hat = np.log(emit_mat[states[0], 0]) + np.log(emit_mat[states[-1], num_states-1])

for i in range(1, len(states)-1):
    trans_hat += np.log(trans_mat[states[i], states[i+1]])
    emit_hat += np.log(emit_mat[states[i], i])

log_prob_hat = trans_hat + emit_hat

print(log_prob_hat)
print(log_prob)

>>> -6.074828603620871
>>> -6.3176377335486125
```

Not sure if anyone else can reproduce this error (?). If possible, I can attach my emission and transition matrix below ( I don't see an option to attach files). I wonder if there's a bug in ```decode()```? At the moment I no longer trust the output of ```decode()```.

**Comment by anntzer** [comment]
Did you solve the issue?

**Comment by b2jia** [comment]
Yes, in the end I realized it was both a (1) off-by-one indexing error (2) number of significant digits displayed by numpy.
