### ISSUE TITLE
Question: How to catch "Degenerate mixture covariance" messages

### ISSUE THREAD

**Issue by vawalker** [hmmlearn/hmmlearn#395]
My understanding is that the "degenerate mixture covariance" message occurs when there is no state change in the observed sequence. This message does not seem to be caught by a simple warnings.catch_warnings() filter. Is there a way to catch it and therefore enable additional reporting (e.g., which sequence triggered it when multiple are processed in parallel)?

**Comment by anntzer** [comment]
The warnings are emitted by the logging machinery (https://docs.python.org/3/library/logging.html), so you can silence them e.g. with
```python
logging.getLogger("hmmlearn").setLevel("CRITICAL")
```
or install your own filters (https://docs.python.org/3/library/logging.html#filter-objects) or handlers (https://docs.python.org/3/library/logging.html#handler-objects) to process them as desired.
