### ISSUE TITLE
Different number of Gaussians per state

### ISSUE THREAD

**Issue by priscilla-amorim** [hmmlearn/hmmlearn#397]
Hello! I wondered if it is possible to train an HMM with a different number of GMMs in each state. Like 4 Gaussians in the first state, 6 in the second, 4 again in the third and etc.

I've already tried to accomplish this by training the GMMs for each state separately, getting the emissions pdf of each state, and passing these to build an HMM. It works only if all the GMMs have the same number of Gaussians. If anyone has a solution to this problem, or maybe a hint, I really appreciate your answer.

Thanks

**Comment by anntzer** [comment]
I believe that you should be able to force that by creating a HMM with a number of gaussians equal to the max number you want, and then in some states pre-set the weight of some gaussians to zero (once a weight is at zero it will stay there throughout the training), effectively decreasing the number of gaussians for that state.
