### ISSUE TITLE
Comparing similarity matrices with dtw and with softdtw

### ISSUE THREAD

**Issue by yesidospitiamedina** [hmmlearn/hmmlearn#398]
Hello, 

I don't understand why when I use dtw to calculate the similarity matrix between all the series, and compare it to the similarity matrix that applies soft-dtw I get different degrees of similarity by changing the order in which the series are more similar.

You could give me some idea of why in one case I have a similarity order between the series, and in the other case the order changes. The change is not very significant, but almost always the first two series more similar with respect to the series I analyze are exchanged position. 

Thank you very much. 
Yesid

**Comment by yesidospitiamedina** [comment]
![Captura de Pantalla 2020-12-21 a la(s) 4 19 08 p  m](https://user-images.githubusercontent.com/16143027/102823138-508e4580-43a8-11eb-9fc3-0570ebaec113.png)

I attach the comparison of two similarity matrices with dtw and with softdtw.

**Comment by anntzer** [comment]
This seems a question about dtw and not hmmlearn?
