### ISSUE TITLE
extra_compile_args=["-O3"]

### ISSUE THREAD

**Issue by anntzer** [hmmlearn/hmmlearn#40]
On Windows (conda/gcc), the default compilation switch is "-O", which yields a much slower extension module than what can be obtained after compiling with "-O3".  I would thus suggest adding `extra_compile_args=["-O3"]` to the `setup.py` so that this is used by default.
Not sure whether this would affect those using the MSVC compiler though.

**Comment by superbobry** [comment]
Thank you for the suggestion. AFAIK AppVeyor uses MSVC, so we can make sure nothing breaks with `O3` once I get the buildscript right :)

**Comment by anntzer** [comment]
You just have to add `extra_compile_args=["-O3"]` to the call to `Extension` :)
To be honest I'd suggest not shipping the generated C and instead relying on cythonize to have it generated at build time, but that's more a personal preference I guess.

**Comment by superbobry** [comment]
> To be honest I'd suggest not shipping the generated C and instead relying on cythonize to have it generated at build time, but that's more a personal preference I guess.
I'm trying to follow scikit-learn convention here. However switching to wheels for the PyPI release might make this convention irrelevant.
