### ISSUE TITLE
will it work for multivariate time series

### ISSUE THREAD

**Issue by Sandy4321** [hmmlearn/hmmlearn#400]
great code thanks
may you clarify : 
will it work for multivariate time series
1 
  where all values are continues values 
2
or  even will it work for multivariate time series where values are mixture of continues  and categorical values
for example 2 dimensions have continues values and 3 dimensions are categorical values

    color        weight     gender  height  age  
1    black       56              m          160    34
2    white       77              f            170    54
3    yellow      87             m          167     43
4    white       55             m            198    72
5   white       88              f            176     32

**Comment by anntzer** [comment]
yes
yes
no
