### ISSUE TITLE
Variable time intervals in hmmlearn

### ISSUE THREAD

**Issue by pawij** [hmmlearn/hmmlearn#401]
Has there been any work at any stage on incorporating variable time intervals into hmmlearn? It seems that only fixed time intervals are currently accepted by the code, as it requires only the number of observations per sequence, and not the number of time steps.

**Comment by anntzer** [comment]
No.

(Also, as noted in the issue template: This library is currently not under active development. Large-scale features are unlikely to be added unless accompanied with a PR, which will be considered by the maintainers to the best of their ability.)
