### ISSUE TITLE
Full Likelihood History

### ISSUE THREAD

**Issue by anneborcherding** [hmmlearn/hmmlearn#402]
Hi everyone,

as far as I understood, it is not possible to receive the whole history of likelihoods during the training in a variable of the ConvergenceMonitor. Currently, it is only possible to receive the information on stderr. 

Since I think it would be interesting to follow the training process of the HMM graphically, this information would be nice to have in a variable.

I see two different possibilities to implement this:

1. Implement it directly into the `report` method of `ConvergenceMonitor`
2. Create an example for users to implement their own ConvergenceMonitor.

Which one would you prefer? I could create an PR for the preferred solution.

**Comment by anntzer** [comment]
Seems reasonable.  I would suggest just changing the `history` attribute into a full list of logprobs (with a API change notice).  Likely the memory cost is negligible compared to the training data itself, for example.

**Comment by anntzer** [comment]
Closed by #403.
