### ISSUE TITLE
ValueError: startprob_ must sum to 1.0 (got nan)

### ISSUE THREAD

**Issue by zhqu1148980644** [hmmlearn/hmmlearn#408]
## I am reporting a bug

The specified `model.startprob_` has a sum to 1 but still get the error.

If you are reporting a bug, please

- Make sure that it occurs with the latest release of hmmlearn (per
  https://pypi.org/project/hmmlearn/).
- Provide a short, self-contained, correct example (http://sscce.org/).
  Maintainers must be able to reproduce the issue **by copy-pasting your
  example in a new, empty file/console/notebook**.  Avoid including data files
  as much as possible; if they are absolutely necessary, they must be in csv or
  npy format, and code for loading the file must be included in the example.

Issues not reproducible with the latest release of hmmlearn or without a short,
self-contained, correct example **will be closed**.

**Comment by anntzer** [comment]
> Issues not reproducible with the latest release of hmmlearn or without a short,
self-contained, correct example will be closed.
