### ISSUE TITLE
Microsoft Visual C++ 9.0 is required

### ISSUE THREAD

**Issue by malzantot** [hmmlearn/hmmlearn#41]
Hello,

I am trying to get setup "hmmlearn" on windows 7. However, I get the following error message
`error: Microsoft Visual C++ 9.0 is required`, I don't have visual c++ installed, but I have already cygwin g++ , How can I configure the installer to make use of it ?

**Comment by superbobry** [comment]
Hello. Unfortunately I'm not familiar with the Python ecosystem on Windows. I think you need to install the [Visual Studio compiler for Python](https://www.microsoft.com/en-us/download/details.aspx?id=44266).
