### ISSUE TITLE
is it possible to extract the probability of each component of the mixture?

### ISSUE THREAD

**Issue by sdedeo** [hmmlearn/hmmlearn#411]
Hello, super-appreciative about the creation of this package!!

A question: is it possible, for the GMMHMM case, to extract the probability of each mixture component when reconstructing a time series?

i.e., right now, log_probs tells us, given an HMM, and a sample sequence, what the probability of being in each state is, at each point in the sequence.

But the model also includes a step where, once you're in a particular state, you sample from one of the mixture components with some probability. In an ordinary GMM, we can also figure out the probability that a particular observation was drawn from each of the mixture components.

It is possible to extract this? Presumably, you would have, for each point in the sequence, an n_components x n_mix matrix. This would tell you the *joint* probability that you drew from, say Hidden State 1, Mixture Component 1.

This may be hidden somewhere in the code itself; I think EM/Viterbi will estimate this as part of the reconstruction anyway...

**Comment by alexrockhill** [comment]
I think you're just asking about the `model.weights_` parameter. You can take the probability of being in a state (from `model.predict_proba`) and then the likelihood for each mixture within that state would just be `model.weights[idx]` where `idx` is the index of the state.

**Comment by simon-dedeo** [comment]
Hey, thank you! Will try…
