### ISSUE TITLE
Add support to release aarch64 wheels

### ISSUE THREAD

**Issue by odidev** [hmmlearn/hmmlearn#412]
Problem
---------
On aarch64, ‘pip install hmmlearn’ builds the wheels from source code and then installs it. It requires the user to have a development environment installed on his system. Also, it takes some time to build the wheels than downloading and extracting the wheels from pypi.

Resolution
-----------
On aarch64, ‘pip install hmmlearn’ should download the wheels from pypi

@anntzer Please let me know your interest in releasing aarch64 wheels. I can help in this.

**Comment by anntzer** [comment]
Closed by #413.
