### ISSUE TITLE
Get evaluation score from new state added state sequence or Get prediction (next observation)

### ISSUE THREAD

**Issue by youngminpark2559** [hmmlearn/hmmlearn#415]
Hi. I have a question on my test.

I trained hidden markov model and I got state like [1,2,3,4] from specific observation, say, [20,21,23,22]
And I added new state at the end of above state sequence like [1,2,3,4,4] based on transition probability which says highest likely state from state4 is state4.

And I'd like to calculate evaluation score by using score() with multiple observations sequence, for example,
observation1 = [20,21,23,22,24]  --> evaluation score : s1
observation2 = [20,21,23,22,25]  --> evaluation score : s2
observation3 = [20,21,23,22,26]  --> evaluation score : s3
Note that 24, 25, 26 are added values at the end of each list as prediction candidates.

And I will get the highest evaluation score (i.e. s3) and I'll use that observation sequence as my prediction ( [20,21,23,22,26] )

But how I can setup new state sequence like [1,2,3,4,4] into my trained model?  

---
EDIT  

It seems like I had misunderstanding on how to calculate likelihood of multiple observation sequences to find best observation sequence storing new latest value.  

With my experiment, I have yearly measured 5 sequential body weight values data like [18,20,21,23,22]  
And I want to find best value at 6th year  
To do this, according to do this link https://stats.stackexchange.com/a/110096
can I do just like below?  
```
evaluation_score_list=[]
ranged_new_values=[17,18,19,20,21,22,23,24]
for one_value in ranged_new_values:
  new_observation=[20,21,23,22,one_value]    
  evaluation_score=trained_hmm.score(new_observation)
  evaluation_score_list.append(evaluation_score)

max_value_index=np.argmax(evaluation_score_list)
optimal_predicted_value_at_6th_year=ranged_new_values[max_value_index]
```

**Comment by anntzer** [comment]
Sorry, I cannot recommend you on the best way to use HMMs.
