### ISSUE TITLE
incremental learning of hmm

### ISSUE THREAD

**Issue by Freakwill** [hmmlearn/hmmlearn#418]
It  could implement incremental learning for `hmmlearn`, by setting simply a new argument `warm_start=True` as in scikit-learn. Following uncompleted code is my idea. When warm_start=True, we need not initialize the model for learning stages.

```
def fit():
...
        if not self.warm_start:
            self._init(X, lengths=lengths)
       else:
            self.partial_fit()
...
```

**Comment by anntzer** [comment]
That's just `init_params=""`?

**Comment by Freakwill** [comment]
> That's just `init_params=""`?

Yes. but The parameters should be initialized at least one time. So,
