### ISSUE TITLE
Why not initialize startprob_, transmat_ with Dirichlet distribution

### ISSUE THREAD

**Issue by Freakwill** [hmmlearn/hmmlearn#419]
We have set startprob_prior, transmat_prior, so why not initialize startprob_, transmat_ with Dirichlet distribution,  just calling`numpy.random.dirichlet`?

**Comment by anntzer** [comment]
This certainly seems like a reasonable feature to add (currently the initialization is using uniform startprob and transmat afaict), feel free to open a PR.
