### ISSUE TITLE
error on example

### ISSUE THREAD

**Issue by andyyuan78** [hmmlearn/hmmlearn#42]
```
ubgpu@ubgpu:~/github/hmmlearn$ sudo python setup.py build_ext --inplace && nosetests
running build_ext
copying build/lib.linux-x86_64-2.7/hmmlearn/_hmmc.so -> hmmlearn
Traceback (most recent call last):
  File "/usr/local/bin/nosetests", line 4, in <module>
    import re
  File "/usr/lib/python3.4/re.py", line 324, in <module>
    import copyreg
  File "/usr/local/lib/python2.7/dist-packages/copyreg/__init__.py", line 7, in <module>
    raise ImportError('This package should not be accessible on Python 3. '
ImportError: This package should not be accessible on Python 3. Either you are trying to run from the python-future src folder or your installation of python-future is corrupted.
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 53, in apport_excepthook
    if not enabled():
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 24, in enabled
    import re
  File "/usr/lib/python3.4/re.py", line 324, in <module>
    import copyreg
  File "/usr/local/lib/python2.7/dist-packages/copyreg/__init__.py", line 7, in <module>
    raise ImportError('This package should not be accessible on Python 3. '
ImportError: This package should not be accessible on Python 3. Either you are trying to run from the python-future src folder or your installation of python-future is corrupted.

Original exception was:
Traceback (most recent call last):
  File "/usr/local/bin/nosetests", line 4, in <module>
    import re
  File "/usr/lib/python3.4/re.py", line 324, in <module>
    import copyreg
  File "/usr/local/lib/python2.7/dist-packages/copyreg/__init__.py", line 7, in <module>
    raise ImportError('This package should not be accessible on Python 3. '
ImportError: This package should not be accessible on Python 3. Either you are trying to run from the python-future src folder or your installation of python-future is corrupted.
ubgpu@ubgpu:~/github/hmmlearn$ 
```

**Comment by superbobry** [comment]
Can you please check the master version and let me know if it works for you?

**Comment by andybrnr** [comment]
I'm still working to try and get hmmlearn working under the Anaconda distribution on Win7. I've pulled the latest version of the master, and it seems to build/install ok, but the model fitting breaks down somewhere. It seems to pass the tests when building (though console output says it skips 5 of the 72 tests, not sure what the deal is there). Example 1 works just fine (as expected since there's no fit, just specify the model), but Example two fails during fitting; unclear where since NaNs are generated at some point and then propagate, but aren't caught until the check at the end. Any suggestions for how I should go about tracking this down?

**Comment by superbobry** [comment]
This might be related to #35. 

I'm currently trying to make AppVeyor run tests (and examples) on Windows, so hopefully I'll be able to reproduce the issue there.

**Comment by superbobry** [comment]
The exception is unlikely to be caused by `hmmlearn`. I think you might want to check your Python installation for conflicts. The traceback suggests that you have both Python2.7 and Python3.4 packages in your `PYTHONPATH` when running tests.

**Comment by andyyuan78** [comment]
just urn it seperately

ubgpu@ubgpu:~/github/hmmlearn$ python setup.py build_ext 
running build_ext
ubgpu@ubgpu:~/github/hmmlearn$ 
ubgpu@ubgpu:~/github/hmmlearn$ python setup.py build_ext --inplace
running build_ext
copying build/lib.linux-x86_64-2.7/hmmlearn/_hmmc.so -> hmmlearn
ubgpu@ubgpu:~/github/hmmlearn$ 

ubgpu@ubgpu:~/github/hmmlearn$ sudo python setup.py build_ext nosetests
running build_ext
running nosetests
running egg_info
writing hmmlearn.egg-info/PKG-INFO
writing top-level names to hmmlearn.egg-info/top_level.txt
writing dependency_links to hmmlearn.egg-info/dependency_links.txt
writing pbr to hmmlearn.egg-info/pbr.json
reading manifest file 'hmmlearn.egg-info/SOURCES.txt'
writing manifest file 'hmmlearn.egg-info/SOURCES.txt'
running build_ext
copying build/lib.linux-x86_64-2.7/hmmlearn/_hmmc.so -> hmmlearn
.......................SSS../usr/local/lib/python2.7/dist-packages/sklearn/utils/extmath.py:337: RuntimeWarning: underflow encountered in exp
  out = np.log(np.sum(np.exp(arr - vmax), axis=0))
/usr/local/lib/python2.7/dist-packages/sklearn/mixture/gmm.py:321: RuntimeWarning: underflow encountered in exp
  responsibilities = np.exp(lpr - logprob[:, np.newaxis])
/home/ubgpu/github/hmmlearn/hmmlearn/base.py:206: RuntimeWarning: underflow encountered in exp
  posteriors[i:j] = np.exp(gamma.T - logsumexp(gamma, axis=1)).T
.S...S..../home/ubgpu/github/hmmlearn/hmmlearn/base.py:419: RuntimeWarning: underflow encountered in exp
  posteriors = np.exp(gamma.T - logsumexp(gamma, axis=1)).T
/home/ubgpu/github/hmmlearn/hmmlearn/base.py:506: RuntimeWarning: underflow encountered in exp
  stats['trans'] += np.exp(logsumexp(lneta, axis=0))
........../home/ubgpu/github/hmmlearn/hmmlearn/hmm.py:224: RuntimeWarning: underflow encountered in multiply
  stats['obs*obs.T'][c] += posteriors[t, c] * obsobsT
........................
----------------------------------------------------------------------
Ran 72 tests in 4.256s

OK (SKIP=5)
ubgpu@ubgpu:~/github/hmmlearn$
