### ISSUE TITLE
HMM Learn Librayr: Error: ValueError : n_samples= 1 should be > = n_clusters=2.

### ISSUE THREAD

**Issue by aaravsawlani** [hmmlearn/hmmlearn#420]
Hello, 
I am looking to use the HMM Learn library to analyze stock data. I am getting an error in my code when trying to use the HMM library. Below is the error itself, an explanation of my code, and the code I've written. Note that with the explanation of the code and the comments in it, it should be fairly easy to understand the logic itself.

```Error: ValueError : n_samples= 1 should be > = n_clusters=2.```

Code explanation: There are two parts of the code. OnInitialize, and OnBarUpdate. OnInitialize is called only once at the beginning of the program, and OnBarUpdate is called each time a new data point is ingested. The code ingests only daily data. In the OnInitialize function, a series of empty global lists and global arrays are created. In the OnBarUpdate function, closing prices, daily returns (+ or -) are appended to these lists and arrays. Then, a GaussianHMM model is fitted to a 2D array, with one column being a zero-based index, and the other daily return data. Note that certain functions (DataTotalCount(), DataClose(0), DataClose(1)), are native to the back testing platform being used, and are only used to retrieve data.

The error is generated by the line 

```model = GaussianHMM(n_components = 2, covariance_type = "full", n_iter = 1000).fit(model_array)```

```
import numpy as np 
import sklearn as sk 
import pandas as pd 
from hmmlearn.hmm import GaussianHMM

def OnInitialize(self,BeginDate,EndDate):


    # OnInitialize Content

    self._BeginDate = BeginDate
    self._EndDate = EndDate

    ## create close price "indicator". it isn't actually an indicator, but it is called that. really just gives you list of close prices to do calculations with
    close = IndicatorCLOSE(self, SymbolIndex())
    self.closes = []
    self.percent_change = []
    self.pct_change_arr = np.array([])
    self.index_array = np.array([])
    self.counter = 0
    self.closes_array = np.array([])

def OnBarUpdate(self, symbolIndex, dataSeries, completedBars):

    # OnBarUpdate Content

    ## check if we have enough data to work with
    if DataTotalCount() < 2:
        return

    ## add close prices to a global list. not used in HMM, but may need for later analysis.
    self.closes.append(DataClose(0))

    ## calculate this bar's percent change
    this_bar_percent_change = (DataClose(0) - DataClose(1))/DataClose(1)

    ## add this bar's percent change to a global list
    self.percent_change.append(this_bar_percent_change)

    ## append numerical values to index array, will be used as first column of array for HMM model
    self.index_array = np.append(self.index_array, self.counter)
    self.counter += 1

    ## add pct change values to np array
    self.pct_change_arr = np.append(self.pct_change_arr, this_bar_percent_change)

    ## create a 2d array using column_stack out of the index array and the returns column
    model_array = np.column_stack((self.index_array, self.pct_change_arr))

    ## create the Gaussian HMM model on the array of day-to-day percent changes of SPY
    model = GaussianHMM(n_components = 2, covariance_type = "full", n_iter = 1000).fit(model_array)


```

How do I fix this error? What am I doing wrong?

**Comment by anntzer** [comment]
The example is not reproducible.
