### ISSUE TITLE
Guassian HMM: A single score is provided when evaluating a feature matrix

### ISSUE THREAD

**Issue by Ravisik** [hmmlearn/hmmlearn#421]
HI!

I just starded to use hmmlearn. For now I just want to fit HMM on a feature matrix, and then predict score for test samples.

I just found that the score given by the model change if I provide a single sample or a whole feature matrix. Here is a snippet code:
```

remodel = hmm.GaussianHMM(n_components=8, covariance_type="spherical", n_iter=100)
remodel.fit(X_train)

print(remodel.score(X_test[0, :].reshape(1, -1)))
print(remodel.score(X_test[1, :].reshape(1, -1)))
print(remodel.score(X_test))
```

The output I have: 

```
-11.91380933179357
-22.909557303728665
-126.79719391548582
```

Since my feature matrix X_test is of size N_sample x N_features, (similarly to X_train), I excpected to have on output of size N_samples.

Am I doing something wrong ?

Thanks in advance,
Flo

**Comment by fcostin** [comment]
The single scalar value returned by `score` is the log probability of the input _sequence_ of samples. 

To get estimates of the hidden state corresponding to each observed sample in the input sequence, you may want to instead call https://hmmlearn.readthedocs.io/en/stable/api.html#hmmlearn.base._BaseHMM.score_samples or https://hmmlearn.readthedocs.io/en/stable/api.html#hmmlearn.base._BaseHMM.decode

**Comment by anntzer** [comment]
Thanks @fcostin for addressing the question.
