### ISSUE TITLE
Question about overriding `BaseHMM._compute_log_likelihood`

### ISSUE THREAD

**Issue by josepablog** [hmmlearn/hmmlearn#422]
The documentation of `computer_log_likehood` simply says that methods that override the `BaseHMM` class must:
> Compute per-component log probability under the model

I think this description is ambiguous, because I can interpret it as two things:  
1. The full model posterior log probability i.e.,  p(output=o|sequence, state=s) for each state s
2.  the emission log probability, i.e., p(output=o|state=s) for each state s

I believe it's option 2. Can you please confirm?

**Comment by anntzer** [comment]
I pushed a new wording.
