### ISSUE TITLE
MultinomialHMM: unable to set n_features explicitly  

### ISSUE THREAD

**Issue by sbhTWR** [hmmlearn/hmmlearn#423]
**Brief overview:** 
In MultinomialHMM, the number of observable states or symbols, (represented by non-negative integers) are set automatically using the observed data `X` in the following manner (`hmm.py`, in function `_check_and_set_n_features`):
```python        
        if hasattr(self, "n_features"):
            if self.n_features - 1 < X.max():
                raise ValueError(
                    "Largest symbol is {} but the model only emits "
                    "symbols up to {}"
                    .format(X.max(), self.n_features - 1))
        self.n_features = X.max() + 1
```

Note the last line which sets the value of `self.n_features` to `X.max() + 1`, irrespective of whether `self.n_features` was set or not. This does not allow a user to explicitly set the number of observable states to more than what has been observed in the data `X`.

**Minimal example to illustrate the issue:**
```python
import numpy as np
from hmmlearn import hmm

n_symbols = 5
n_components = 3

startprob = np.array([0.6, 0.3, 0.1])
transmat = np.array([[0.7, 0.2, 0.1], [0.3, 0.5, 0.2], [0.3, 0.3, 0.4]])
emissionprob  = np.array([[0.1, 0.9, 0.5, 0.2, 0.6], 
                        [0.5, 0.5, 0.1, 0.8, 0.4],
                        [0.9, 0.1, 0.3, 0.8, 0.4]])

observed_sequence = [2, 1, 3, 3, 2, 0, 1, 3]
X = np.array([observed_sequence]).T

model = hmm.MultinomialHMM(n_components = n_components, n_iter=100, init_params='')
model.startprob_ = startprob
model.transmat_ = transmat
model.emissionprob_ = emissionprob
model.n_features = n_symbols

model.fit(X)
```
Output:
```shell
ValueError: emissionprob_ must have shape (n_components, n_features)
```

Note that in the above example, emission probabilities are of shape `(3, 5)`. So the set of possible observed (emitted) states are: `{0, 1, 2, 3, 4}` (5 symbols). But in the observed data, only the following observed states have appeared: `{0, 1, 2, 3}`. So `self.n_features` is set to `X.max()+1 = 4`. Thus, the following check in `MultinomialHMM_check()` fails:

```python
        n_features = getattr(self, "n_features", self.emissionprob_.shape[1])
        if self.emissionprob_.shape != (self.n_components, n_features):
            raise ValueError(
                "emissionprob_ must have shape (n_components, n_features)")
        else:
            self.n_features = n_features
```
If we add the observed state `4` to `observed_sequence` in the above example, the code works.

**Simple way of allowing explicit setting of `n_features`:**
Just add a return statement if `n_features` has been set already like so:

```python
        if hasattr(self, "n_features"):
            if self.n_features - 1 < X.max():
                raise ValueError(
                    "Largest symbol is {} but the model only emits "
                    "symbols up to {}"
                    .format(X.max(), self.n_features - 1))
            return # add return statement here if n_features has been set
        self.n_features = X.max() + 1
```

**Comment by anntzer** [comment]
Good catch, fixed.

**Comment by Priestley72** [comment]
Good catch, fixed.
