### ISSUE TITLE
log likelihood is positive from score() in GaussianHMM()

### ISSUE THREAD

**Issue by jayshah15028** [hmmlearn/hmmlearn#425]
I am using GaussianHMM and fitting the model with some samples and trying to look at the log likelihood of those samples from the fitted model. It gives positive log likelihood, (like [here](https://github.com/hmmlearn/hmmlearn/issues/188)), which cannot be possible. Below is the code. This is a simple example for recreating the effect of what I observe in my application (I admit that it is not the best way to sample observations from the initial model and fit the model with same samples, nevertheless the log likelihood should always be <= 0). Unfortunately, I cannot share my real code. 

I am trying to debug this and will edit this post if/when I find the bug. Meanwhile, can someone please confirm whether this is an actual bug? Thanks.

```
import numpy as np
from hmmlearn import hmm


startprob = np.array([0.18,0.54,0.28])
transmat = np.array([[0.27,0.54,0.19],
                      [0.15,0.48,0.37],
                      [0.8,0.18,0.02]])
means = np.array([[3,7,0.54,-1.6],[2.5,2.6,-0.79,-4.78],[1.4,6.54,0.52,1.45]])

covars = np.tile(np.eye(4),(3,1,1))
model = hmm.GaussianHMM(n_components=3,covariance_type='full',n_iter=100,tol=0.01,init_params='',algorithm='viterbi')
model.startprob_ = startprob
model.transmat_ = transmat
model.means_ = means
model.n_features = means.shape[1]  #to avoid the n_features error
model.covars_ = covars
obs_seq,_ = model.sample(13)  # sampling from the unfitted model
model = model.fit(obs_seq)      # fitting the model
prob = model.score(obs_seq)    # this is positive (should be non-positive)
```

**Comment by anntzer** [comment]
log-probability-densities can be greater than zero.
