### ISSUE TITLE
why do model.decode(obs_seq)[0] and model.score(obs_seq) compute differently?

### ISSUE THREAD

**Issue by pancratm** [hmmlearn/hmmlearn#430]
I have a question. The result of predicting the hidden state is consistent, but the probability score of prediction is different, where model.decode() is consistent with the result of manually computed Viterbi algorithm.
The following code:

```
obs_seq = np.array([[0,1,0,1,0]]).T
logprob,path = model.decode(obs_seq,algorithm='viterbi')
print(np.e**logprob)
print(path)
print(model.predict(obs_seq))
print(np.e**model.score(obs_seq))
```
The print results:

0.0028811999999999996
[0 0 0 0 0]
[0 0 0 0 0]
0.005507310400000001

Thanks.

**Comment by anntzer** [comment]
The likelihood of a sequence observation (p(O|lambda), in Rabiner's notation) is not the same as the likelihood of the Viterbi sequence (p(Q|O,lambda)).
