### ISSUE TITLE
How to save and load Markov model.

### ISSUE THREAD

**Issue by HenryBao91** [hmmlearn/hmmlearn#445]
## I have a question

The maintainers cannot offer advice regarding the use of hmmlearn or of hidden
Markov models in general.  Consider asking on a general forum, e.g.
https://stats.stackexchange.com/.

**Comment by HenryBao91** [comment]
I train a Markov model with hmmlean, code like this: 
```model = hmm.MultinomialHMM(n_components=n_states, n_iter=20, tol=0.01)```

Now, I want to save the model and load this model online for predicting an user's action sequence. It seems there is no any method to save and load model.

**Comment by anntzer** [comment]
The approach is the same as for sklearn: use pickle, as documented at https://scikit-learn.org/stable/modules/model_persistence.html
