### ISSUE TITLE
Is that possible to retrain the model with new dataset?

### ISSUE THREAD

**Issue by Wapiti08** [hmmlearn/hmmlearn#449]
## I am requesting a new feature

I have a request to retrain the pretrained model with new dataset with fit function. In the meantime, I would like to add more weights to the new data. Is that possible to achieve that goal？Thanks

**Comment by anntzer** [comment]
No, you have to retrain from scratch (perhaps using the old train as initialization).

**Comment by Wapiti08** [comment]
Okay. I get that. Thanks
