### ISSUE TITLE
Implementation argument is not working

### ISSUE THREAD

**Issue by gao462** [hmmlearn/hmmlearn#452]
I can not specify implementation argument when initialize MultinomialHMM.
```python
import hmmlearn
from hmmlearn import hmm
print(hmmlearn.__version__)
hmm.MultinomialHMM(n_components=2, startprob_prior=1.0, transmat_prior=1.0, algorithm="viterbi", random_state=None, n_iter=10, tol=0.0, verbose=False, params="te", init_params="ste", implementation="scaling")
```

It gives error message.
```bash
0.2.6
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: __init__() got an unexpected keyword argument 'implementation'
```

**Comment by blckmaxima** [comment]
Hello - It looks like the implementation keyword is only available in the main branch on github, and not part of an official release yet on pypi.  Can you try installing the latest from the `main` branch?

@anntzer How much work is a new release?
