### ISSUE TITLE
How to train HMM model with an irregular matrix dataset ?

### ISSUE THREAD

**Issue by HenryBao91** [hmmlearn/hmmlearn#453]
It's easy to use `hmmlearn` to train a HMM model,  eg:
```
feature = np.array([
   [1,2,3],
   [2,3,1]
])
model = hmm.MultinomialHMM(... )
model.fit(feature)
# then predict
observer = [2,3,5]
score = model.score(np.array(observer))
```

The First questions:
But if my dataset is an irregular matrix , how to train the model? Because there maybe different length of sequence array of users, such as my train dataset below:
```
feature = [
   [1,2,3],
   [3,6,3,1],
   [2,3,1],
   [3,5,2,2,7]
]
```

The Second questions:
How to compare or compute two sequences with different length which is abnormal when there is a hmm model,for example:
```
observer_1 = [0,0,1]    # an abnormal seqence
observer_2 = [1,2,3,3,2,4]    # an normal seqence
```
Because the method of HMM is loglikehood, I think the score of observer_2 will be less than observer_1. But observer_1 is abnormal. Or in the other words, observer_1  will be computed with score is '-inf' ? I'm not sure about that.

## I have a question

The maintainers cannot offer advice regarding the use of hmmlearn or of hidden
Markov models in general.  Consider asking on a general forum, e.g.
https://stats.stackexchange.com/.

**Comment by blckmaxima** [comment]
The first question - 
Format your data as a single array, and create an array of the lengths of each sequence.
```
lengths = np.asarray([len(x) for x in feature])
feature = np.concatenate(feature)[:, None]

model.fit(Xfeature, lengths=lengths)
```

The Second Question:
Looking at the likelihood of each sequence under the trained model is a great idea to start. Whether the score will be `-inf` or a large negative number, will be model dependent.

**Comment by HenryBao91** [comment]
> 

Thanks for your relay very much！
I get the idea from your answer about the first question.
But I'm still confused whether my method is right about another.
My observer-state is [0,1,2,3,4,5,6]
'6' is a very less action obverse-state and '2', '4'  is a very common action and '5' is often.
I use my train data to compute the 'start_prob' , the 'trans_prob' and set for the model , the 'emssion-prob' is set by model fit, lke this:
```
startprob = [0.005, 0.004, 0.331, 0.002, 0.617, 0.038, 0.004]
transmat = [[0.001, ......],....]  #  an matrix ,shape is (6, 6) , because numbers of my obversers is 6.

model = hmm.MultinomialHMM(
            ...
            params='e',
            init_params='e'
        )
model.startprob_ = startprob
model.transmat_ = transmat

model.fit(feature)
```

My online verify like this:
```
obs_1 = [4,2,4,4,2,2,4,2,2,2,4,2,4,2,4,2,2,4,2,4,2,2,4,2,4,2,4,4,2,2,4,2,2,2,4,2,2,2,2,4,2,2,2,4,2,4,2,2,2,4,2,2,2,2,4,2,2,4,2,4,2,2,2,4,2,2,4,2,2,2,4,2,4,2,4,2,2,4,2,2,4,2,2,2,4,2,2,2,2,4,2,2,4,2,2,2,2]
score = model.score(np.array(obs_1).reshape(-1, 1))
print(score)
# score: -68.289

obs_2 = [4,4,4,2,4,4,4,4,2,4,2,4,2,4,2,4,4,2,4,2,2,4,2,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,4,4,4,2,2,4,4,4,4,2,4,4,2,4,2,2,4,4,2,4,2,4,2,4,2,4,4,4,2,4,4,4,4,4,4,4,4,4,4]
score = model.score(np.array(obs_2).reshape(-1, 1))
print(score)
# score: -80.896

obs_3= [0,4,6,1,4,6,4,2,0]
score = model.score(np.array(obs_3).reshape(-1, 1))
print(score)
# score: -36.358
```

For my case , obs_1 and obs_2  are normal sequence , obs_3 is an abnormal sequnce .So,  I  hope obs_3 get a very low score which is more lowwer than obs_1 or obs_2.

Is there any wrong with my method ?  
I'm looking forward to your reply！
