### ISSUE TITLE
Issue with the result of taking the log probability of a dataset using score().

### ISSUE THREAD

**Issue by roblen001** [hmmlearn/hmmlearn#454]
Hello,

My dataset has N timesteps which compose the row and C features which compose the columns. I have fit a hidden Markov model to my data to get the states at the different timepoints of the data. This was done by running model = hmm.GaussianHMM(n_components, n_iter=1000).fit(input_data), where input_data is my CxN matrix. I had assumed that this step was done properly.

My next step was to calculate the probability that another dataset of the size CxN could be generated by this particular model i.e. finding the log_probability of the new data set given the fitted model. Prior to doing this, I began playing around with the package to figure out how this could be done. I came across the function model.score(). I decided to test it by inputting my original dataset to the function i.e. model.score(input_data). This gave me a very large negative value (-24720) implying that the model does not fit the data well. The confusion arises because I would expect to get a high log probability value since the data that was used to fit the model is the same data I used to get the log probability, therefore the model should fit the data perfectly no? 

I am wondering if my issue is in my understanding of the statistics of what I am doing, if my error is in the implementation of the package or if the package has a bug?

Thank you

**Comment by blckmaxima** [comment]
Hello - 
If you train your model, and pass the parameter `verbose=True`, you will see the log likelihood of your data printed at each iteration.  You can then compare this value with calling `model.score(input_data)`, and they should be nearly the same.  

Good Luck!

**Comment by alexrockhill** [comment]
Just to add a small comment, if you have a dataset with a large `N`, then even if the model fits very well, the most likely path is going to be very unlikely because it is one of very, very many paths. As far as I know, that's just an unavoidable part of HMMs. Referring to this PR https://github.com/hmmlearn/hmmlearn/pull/458 which explains it a bit, the perfect the simulated data is generated with a log-likelihood score of `Generated score: -26230.575868403906` and the best fit of a model is 
`Best score: -26229.493976575788` (which is actually slightly greater meaning that the model is overfit to the validation data). The other randomly initialized models have scores of

```
Model #0	Score: -26229.971622596466
Model #1	Score: -26390.227666980343
Model #2	Score: -26376.08494741456
Model #3	Score: -26281.17258583047
Model #4	Score: -26299.01851006042
Model #5	Score: -26236.137373939324
Model #6	Score: -26230.974703921915
Model #7	Score: -26261.19219260834
Model #8	Score: -26297.411183031192
Model #9	Score: -26253.6509061982
Model #10	Score: -26314.971591730027
Model #11	Score: -26330.63705489777
Model #12	Score: -26233.953794150075
Model #13	Score: -26410.827080382856
Model #14	Score: -26232.586361190213
Model #15	Score: -26234.54549170027
Model #16	Score: -26314.34883468753
Model #17	Score: -26293.540648513397
Model #18	Score: -26394.936525414483
Model #19	Score: -26283.727600048238
Model #20	Score: -26304.723449933692
Model #21	Score: -26342.915792746473
Model #22	Score: -26234.559567276618
Model #23	Score: -26278.85891661995
Model #24	Score: -26235.874751645504
Model #25	Score: -26269.369332609396
Model #26	Score: -26242.02291323223
Model #27	Score: -26239.596594358107
Model #28	Score: -26381.77942708548
Model #29	Score: -26278.04936373218
Model #30	Score: -26245.238032886635
Model #31	Score: -26263.38580985463
Model #32	Score: -26304.427057671204
Model #33	Score: -26288.05315734987
Model #34	Score: -26358.330236887607
Model #35	Score: -26237.761489361714
Model #36	Score: -26241.214906960202
Model #37	Score: -26382.39509154031
Model #38	Score: -26230.12804931548
Model #39	Score: -26318.83476029897
Model #40	Score: -26383.848848259528
Model #41	Score: -26230.381311183104
Model #42	Score: -26229.493976575788
Model #43	Score: -26272.36630515497
Model #44	Score: -26240.102054412087
Model #45	Score: -26379.313843906697
Model #46	Score: -26277.921502252204
Model #47	Score: -26256.52567883814
Model #48	Score: -26231.95247530414
Model #49	Score: -26263.98009119551
```

which are more negative and so worse. To my understanding, this is typical for training HMMs.

**Comment by anntzer** [comment]
Thanks @blckmaxima @alexrockhill for putting in some explanations :)
