### ISSUE TITLE
Different run gives different result? 

### ISSUE THREAD

**Issue by shiyuangu** [hmmlearn/hmmlearn#46]
Hi I am using GMMHMM and notice that different run gives different result. This is how I called GMMHMM  :

    model = GMMHMM(n_components = n_states, n_mix=2, covariance_type="diag", n_iter=1000,random_state = 4, thresh = 1e-3)
    model.fit(z_in)    # z_in is the same for different run. 
    model.score(y)   # y is the same for different run 

What might cause  different result in different run? Is there a way I can fix this?
Also, EM process might encounter local minimum. Is restart implement in GMMHMM.fix(..)? 
Thank you.

**Comment by superbobry** [comment]
Hello. Different results might be due to different starting points which in turn can be explained by the random nature of KMeans++ (used to initialize the parameters of `GMM`). So yes in general you should run EM multiple times. 

This feature isn't implemented in `hmmlearn` at the moment.
