### ISSUE TITLE
Report issues on implementing classic viterbi algorithms with emission probabilities known

### ISSUE THREAD

**Issue by SamUnimelb** [hmmlearn/hmmlearn#462]
## I am requesting a new feature

I'm trying to implement the classic case study offered by Wikipedia at: https://en.wikipedia.org/wiki/Viterbi_algorithm#Example, but using the standard hmm.MultinomialHMM class (not the demonstrated implementation there). According to this case, I've implemented the codes as below:

```
import hmmlearn.hmm as hmm
import numpy as np

startprob = np.array([0.6,0.4]) # Healthy - 0.6, Fever - 0.4

# transmission of states btw healthy and fever
transmat = np.array([[0.7,0.3],[0.6,0.4]])

# Emission states between healthy-fever and "normal, dizzy and cold"
emitmat = np.array([[0.1,0.4,0.5],[0.6,0.3,0.1]]) 

h = hmm.MultinomialHMM(n_components=2, 
     startprob_prior=startprob,transmat_prior=transmat)
h.emissionprob_ = emitmat
# Don't know how to implement fit here and how to show the probability values
h.predict([[0,1,2]])
```
Then according to his case study a patient reported "normal, cold and dizzy" for 3 days and my observation should be "healthy, healthy and fever". But seems the predicted state "healthy, healthy and fever" (and others) can't be implemented using the standard hmm. MultinomialHMM (as I've posted this issue on stackoverflow and nobody can answer it for 3 days, nor do I find any useful statements on this problem in hmmlearn documentation).  The issue here really is MultinomialHMM required me to fit some data but here really no data is to be fit since the model is already complete. 

I've tried to search for other implementations, the one at: https://github.com/jason2506/PythonHMM looks similar to my needs. And its "model" class can be indeed replaced by the standard hmmlearn.hmm models. But its "train" and "evaluation" methods seem have no corresponding implementations on the standard hmmlearn. So I would strongly suggest to add new features to implement this kind of problems instead of wild implementations going everywhere but stay far from the standard version. 

Thanks.

**Comment by anntzer** [comment]
You need to set `h.startprob_ = startprob` and `h.transmat_ = transmat` to get a complete model and then `predict()` will work, but your matrices are incorrectly implemented too.
