### ISSUE TITLE
pre-set n_features for MultinomialHMM

### ISSUE THREAD

**Issue by gusye1234** [hmmlearn/hmmlearn#464]
## I am requesting a new feature or a question

One potential problem with using `MultinomialHMM` is that the training `X` for `model.fit` may not include all discrete labels, which may cause errors while predicting.  
Maybe there is a trivial solution for the unseen labels?  For example, pre-set the `n_features` and left the unseen labels' parameters zero?

**Comment by anntzer** [comment]
Setting `model.n_features = <some number>` should work (as of hmmlearn 0.2.7), doesn't it?

**Comment by gusye1234** [comment]
You're right😁. That would do the tricks.
