### ISSUE TITLE
[ENH] Add a uniform prior option

### ISSUE THREAD

**Issue by alexrockhill** [hmmlearn/hmmlearn#469]
Related to https://github.com/hmmlearn/hmmlearn/pull/468. We enforce a gamma prior based on the method of moments fit to the parameters from the training data (`X`). This is consistent with the other HMMs which choose the best prior for you. In the Poission case, it might make sense to have a uniform prior as an option for faster convergence when one or more of the states has a waiting time very different from the mean waiting time of the distribution. This would be a very different API though with something like `lambdas_prior_dist='gamma'` by default with the option of setting to `uniform`. The parameters for the prior would then have to be passed in using `lambdas_prior` and `lambdas_weight` where if they were extra as in the uniform case, they would be ignored. Another option would be to allow a boolean `uniform_prior` keyword argument that would use the uniform prior. That's more backward compatible but less extensible. Interested to know what you think @anntzer and @blckmaxima. Maybe this is just a theoretical issue but I did have to increase `n_iters` for the PoissonHMM example to get convergence.

**Comment by anntzer** [comment]
I don't claim any expertise here (usually I just retry a couple of times to see if I can get a better convergence...), but (unless there are strong principled reasons why two different init methods should be considered) I would just stick to one initialization method and let the end user manually set a starting point (and switch off init_params) if they want to do it in another way.  IOW I don't think it's really worth complexifying the API for that(?)

**Comment by alexrockhill** [comment]
I think the main issue is that there are no arguments that you can pass to avoid the prior, it's coded unavoidably here for example:

```
if 'l' in self.params:
    # Based on: Hyvönen & Tolonen, "Bayesian Inference 2019"
    # section 3.2
    # https://vioshyvo.github.io/Bayesian_inference
    alphas, betas = self.lambdas_prior, self.lambdas_weight
    n = stats['nsamples']
    kappas = betas / (betas + n)
    y_bar = stats['obs'] / stats['post'][:, None]
    self.lambdas_ = kappas * (alphas / betas) + (1 - kappas) * y_bar
```

You can pass a different `lambdas_prior` and `lamdas_weight` but it's still enforcing a gamma distribution prior. This is the case for all the HMMs also.

**Comment by alexrockhill** [comment]
Here are the inverse gamma and inverse Wishart distributions for the `GaussianHMM` covariance for another example.

```
if 'c' in self.params:
    covars_prior = self.covars_prior
    covars_weight = self.covars_weight
    meandiff = self.means_ - means_prior

    if self.covariance_type in ('spherical', 'diag'):
        c_n = (means_weight * meandiff**2
               + stats['obs**2']
               - 2 * self.means_ * stats['obs']
               + self.means_**2 * denom)
        c_d = max(covars_weight - 1, 0) + denom
        self._covars_ = (covars_prior + c_n) / np.maximum(c_d, 1e-5)
        if self.covariance_type == 'spherical':
            self._covars_ = np.tile(self._covars_.mean(1)[:, None],
                                    (1, self._covars_.shape[1]))
    elif self.covariance_type in ('tied', 'full'):
        c_n = np.empty((self.n_components, self.n_features,
                        self.n_features))
        for c in range(self.n_components):
            obsmean = np.outer(stats['obs'][c], self.means_[c])
            c_n[c] = (means_weight * np.outer(meandiff[c],
                                              meandiff[c])
                      + stats['obs*obs.T'][c]
                      - obsmean - obsmean.T
                      + np.outer(self.means_[c], self.means_[c])
                      * stats['post'][c])
        cvweight = max(covars_weight - self.n_features, 0)
        if self.covariance_type == 'tied':
            self._covars_ = ((covars_prior + c_n.sum(axis=0)) /
                             (cvweight + stats['post'].sum()))
        elif self.covariance_type == 'full':
            self._covars_ = ((covars_prior + c_n) /
                             (cvweight + stats['post'][:, None, None]))
```

It is probably the case that these are super helpful for preventing the covariances from blowing up/being unstable in training but it's a bit complicated relative to a uniform prior. As I'm writing this, maybe I should just run some tests to see what effect a uniform prior has in this case as well. I might not get to that right away though.

**Comment by anntzer** [comment]
Ah, I see.  Unless I'm mistaken, lambdas_weight=0 effectively makes the prior uniform (perhaps that should be the default?), and likewise covars_prior=0, covars_weight=(any value<=1) also does so for GaussianHMM (and it's *nearly* the default values, I guess covars_prior=1e-2 is useful to prevent things from blowing up as you say?)

Let's decide on this before making a new release.

**Comment by alexrockhill** [comment]
Ah good point, I need check but if the location/beta parameter for a gamma distribution is 0, does that flatten the distribution completely? There is an alpha / beta in the code so I think that would blow up. In the covariance with the inverse gamma, I don't think setting the weight to zero is essentially no prior either but let me check.

**Comment by alexrockhill** [comment]
I think here: https://github.com/hmmlearn/hmmlearn/blob/main/lib/hmmlearn/hmm.py#L1022-L1028 if `covars_prior` or `covars_weight` or both are 0, then you still enforce the gamma prior that is non-uniform.

Maybe this should just be a bug fix and for the reason I mentioned about different states having different waiting times, the best option may be a uniform prior rather than enforcing this gamma prior just in the PoissonHMM.

The covariances are a bit more complicated of a case because they are less directly tied to the difference in states (i.e. states are mostly defined by the difference in their means).

**Comment by anntzer** [comment]
re: alpha/beta: I guess you need to rewrite
```python
n = stats['nsamples']
kappas = betas / (betas + n)
y_bar = stats['obs'] / stats['post'][:, None]
self.lambdas_ = kappas * (alphas / betas) + (1 - kappas) * y_bar
```
to something like
```python
...
self.lambdas_ = alphas / (betas + n) + n / (betas + n) * y_bar
```
which is equivalent, perhaps slightly less elegant (becase the kappa & 1-kappa weights disappear, perhaps keep mentionning that form in a comment?) but will work even if betas = 0. 

re: covariances: can you remind me the formula for the uniform prior case?

**Comment by alexrockhill** [comment]
That looks like a reasonable solution. I think like in here before it got changed, https://github.com/hmmlearn/hmmlearn/pull/465, you just take the `obs` / `post` to enforce a uniform prior.

**Comment by alexrockhill** [comment]
A colleague of mine mentioned the implementation by this group https://github.com/lindermanlab/ssm. I didn't see how it was implemented right away, I'll have to check later but I thought others might be interested and it's nice to see what other observation models have been implemented elsewhere.
