### ISSUE TITLE
update documentation to mention PoissonHMM

### ISSUE THREAD

**Issue by murphyk** [hmmlearn/hmmlearn#479]
https://hmmlearn.readthedocs.io/en/latest/tutorial.html#available-models does not mention [PoissonHMM](https://github.com/hmmlearn/hmmlearn/blob/main/lib/hmmlearn/hmm.py#L1249)

**Comment by alexrockhill** [comment]
Good catch! Would you have a minute to do a PR to add this?

**Comment by anntzer** [comment]
Closed by #499.
