### ISSUE TITLE
Floating Pointer Errors to clear during calls to log()

### ISSUE THREAD

**Issue by blckmaxima** [hmmlearn/hmmlearn#480]
## I am requesting a new feature

This is a feature request to track the question:  When computing `log` of `probabilities` in `_src/hmmc.cpp`, what floating point errors do we want to clear for?  

History:

1. In [`lib/hmmlearn/utils.py:log_mask_zero`,](https://github.com/hmmlearn/hmmlearn/blob/main/lib/hmmlearn/utils.py#L77) we ignore errors related to divided by zero.
2. [A pull request to move this to C++](https://github.com/hmmlearn/hmmlearn/pull/478)  copied this behavior.

However, we may want to copy [this code from numpy](https://github.com/numpy/numpy/blob/54c2c1ebd290c2cc2faa6f6272f4b04fd0c1eea5/numpy/core/src/npymath/ieee754.c.src#L619) and clear more errors.

**Comment by anntzer** [comment]
Based on empirical investigation I think log() can only throw "division by zero" (log(0)) or "invalid value" (log(negative)), but EM should never ever make any of the entries of the fitted matrices negative, so let's assume that if that ever happens it is a legitimate error and thus let's not suppress anything else.
