### ISSUE TITLE
AttributeError: module 'hmmlearn.hmm' has no attribute 'CategoricalHMM'   hmmlearn 0.2.7

### ISSUE THREAD

**Issue by ningjingzhiwei** [hmmlearn/hmmlearn#486]
It happens the error "AttributeError: module 'hmmlearn.hmm' has no attribute 'CategoricalHMM'" in the line
“gen_model = hmm.CategoricalHMM(n_components=2, random_state=99)”

does anyone know how to fix it?

**Comment by anntzer** [comment]
This is not in a released version of hmmlearn yet.
