### ISSUE TITLE
no CategoricalHMM in hmmlearn0.2.7

### ISSUE THREAD

**Issue by jamesYu365** [hmmlearn/hmmlearn#487]
## I am reporting a bug
When I import CategoricalHMM from hmmlearn
```python
gen_model = hmm.CategoricalHMM(n_components=2, random_state=99)
```
I got this:
```python
Traceback (most recent call last):

  File "I:\Anaconda\envs\graph\lib\site-packages\spyder_kernels\py3compat.py", line 356, in compat_exec
    exec(code, globals, locals)

  File "c:\users\zhaox\documents\下载\hmmlearn-main\examples\plot_casino.py", line 33, in <module>
    gen_model = hmm.CategoricalHMM(n_components=2, random_state=99)

AttributeError: module 'hmmlearn.hmm' has no attribute 'CategoricalHMM'
```
my environment is win10+python3.8+hmm0.2.7

**Comment by jamesYu365** [comment]
Wait a minute, I have checked the original code in the hmmlearn package. Why there is only three HMM models? 
```python
__all__ = ["GMMHMM", "GaussianHMM", "MultinomialHMM"]
```

**Comment by blckmaxima** [comment]
If you take the latest code from GitHub, you'll have a CategoricalHMM.  We
probably just need to make a release.

**Comment by anntzer** [comment]
Sorry I got a bit behind with that, I'll try to do it in a few days.

**Comment by jamesYu365** [comment]
I see and thank for you guys' work

**Comment by anntzer** [comment]
0.2.8 has been released.
