### ISSUE TITLE
error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/

### ISSUE THREAD

**Issue by NOOR-JAMALUDEEN** [hmmlearn/hmmlearn#488]
I am trying to install the last version of the package directly from GitHub but I am getting the following error. I do have the visual studio installed.
Here is the error text below:

Collecting git+https://github.com/hmmlearn/hmmlearn
  Cloning https://github.com/hmmlearn/hmmlearn to c:\users\a-jamalude\appdata\local\temp\pip-req-build-2qixc3dh
  Running command git clone --filter=blob:none --quiet https://github.com/hmmlearn/hmmlearn 'C:\Users\a-jamalude\AppData\Local\Temp\pip-req-build-2qixc3dh'
  Resolved https://github.com/hmmlearn/hmmlearn to commit d16c7c851b60e934729eb40ce5ef01164e13a813
  Preparing metadata (setup.py) ... done
Requirement already satisfied: numpy>=1.10 in c:\users\a-jamalude\documents\lin\2ndproject_intracategorycausality\venv\lib\site-packages (from hmmlearn==0.2.7.post20+gd16c7c8) (1.23.3)
Requirement already satisfied: scikit-learn>=0.16 in c:\users\a-jamalude\documents\lin\2ndproject_intracategorycausality\venv\lib\site-packages (from hmmlearn==0.2.7.post20+gd16c7c8) (1.1.2)
Requirement already satisfied: scipy>=0.19 in c:\users\a-jamalude\documents\lin\2ndproject_intracategorycausality\venv\lib\site-packages (from hmmlearn==0.2.7.post20+gd16c7c8) (1.9.1)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\users\a-jamalude\documents\lin\2ndproject_intracategorycausality\venv\lib\site-packages (from scikit-learn>=0.16->hmmlearn==0.2.7.post20+gd16c7c8) (3.1.0)
Requirement already satisfied: joblib>=1.0.0 in c:\users\a-jamalude\documents\lin\2ndproject_intracategorycausality\venv\lib\site-packages (from scikit-learn>=0.16->hmmlearn==0.2.7.post20+gd16c7c8) (1.1.0)
Building wheels for collected packages: hmmlearn
  Building wheel for hmmlearn (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [28 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-3.9
      creating build\lib.win-amd64-3.9\hmmlearn
      copying lib\hmmlearn\base.py -> build\lib.win-amd64-3.9\hmmlearn
      copying lib\hmmlearn\hmm.py -> build\lib.win-amd64-3.9\hmmlearn
      copying lib\hmmlearn\stats.py -> build\lib.win-amd64-3.9\hmmlearn
      copying lib\hmmlearn\utils.py -> build\lib.win-amd64-3.9\hmmlearn
      copying lib\hmmlearn\_utils.py -> build\lib.win-amd64-3.9\hmmlearn
      copying lib\hmmlearn\_version.py -> build\lib.win-amd64-3.9\hmmlearn
      copying lib\hmmlearn\__init__.py -> build\lib.win-amd64-3.9\hmmlearn
      creating build\lib.win-amd64-3.9\hmmlearn\tests
      copying lib\hmmlearn\tests\conftest.py -> build\lib.win-amd64-3.9\hmmlearn\tests
      copying lib\hmmlearn\tests\test_base.py -> build\lib.win-amd64-3.9\hmmlearn\tests
      copying lib\hmmlearn\tests\test_categorical_hmm.py -> build\lib.win-amd64-3.9\hmmlearn\tests
      copying lib\hmmlearn\tests\test_gaussian_hmm.py -> build\lib.win-amd64-3.9\hmmlearn\tests
      copying lib\hmmlearn\tests\test_gmm_hmm.py -> build\lib.win-amd64-3.9\hmmlearn\tests
      copying lib\hmmlearn\tests\test_gmm_hmm_multisequence.py -> build\lib.win-amd64-3.9\hmmlearn\tests
      copying lib\hmmlearn\tests\test_gmm_hmm_new.py -> build\lib.win-amd64-3.9\hmmlearn\tests
      copying lib\hmmlearn\tests\test_multinomial_hmm.py -> build\lib.win-amd64-3.9\hmmlearn\tests
      copying lib\hmmlearn\tests\test_poisson_hmm.py -> build\lib.win-amd64-3.9\hmmlearn\tests
      copying lib\hmmlearn\tests\test_utils.py -> build\lib.win-amd64-3.9\hmmlearn\tests
      copying lib\hmmlearn\tests\__init__.py -> build\lib.win-amd64-3.9\hmmlearn\tests
      running build_ext
      building 'hmmlearn._hmmc' extension
      error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for hmmlearn
  Running setup.py clean for hmmlearn
Failed to build hmmlearn
Installing collected packages: hmmlearn
  Attempting uninstall: hmmlearn
    Found existing installation: hmmlearn 0.2.7
    Uninstalling hmmlearn-0.2.7:
      Successfully uninstalled hmmlearn-0.2.7
  Running setup.py install for hmmlearn ... error
  error: subprocess-exited-with-error

  × Running setup.py install for hmmlearn did not run successfully.
  │ exit code: 1
  ╰─> [28 lines of output]
      running install
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-3.9
      creating build\lib.win-amd64-3.9\hmmlearn
      copying lib\hmmlearn\base.py -> build\lib.win-amd64-3.9\hmmlearn
      copying lib\hmmlearn\hmm.py -> build\lib.win-amd64-3.9\hmmlearn
      copying lib\hmmlearn\stats.py -> build\lib.win-amd64-3.9\hmmlearn
      copying lib\hmmlearn\utils.py -> build\lib.win-amd64-3.9\hmmlearn
      copying lib\hmmlearn\_utils.py -> build\lib.win-amd64-3.9\hmmlearn
      copying lib\hmmlearn\_version.py -> build\lib.win-amd64-3.9\hmmlearn
      copying lib\hmmlearn\__init__.py -> build\lib.win-amd64-3.9\hmmlearn
      creating build\lib.win-amd64-3.9\hmmlearn\tests
      copying lib\hmmlearn\tests\conftest.py -> build\lib.win-amd64-3.9\hmmlearn\tests
      copying lib\hmmlearn\tests\test_base.py -> build\lib.win-amd64-3.9\hmmlearn\tests
      copying lib\hmmlearn\tests\test_categorical_hmm.py -> build\lib.win-amd64-3.9\hmmlearn\tests
      copying lib\hmmlearn\tests\test_gaussian_hmm.py -> build\lib.win-amd64-3.9\hmmlearn\tests
      copying lib\hmmlearn\tests\test_gmm_hmm.py -> build\lib.win-amd64-3.9\hmmlearn\tests
      copying lib\hmmlearn\tests\test_gmm_hmm_multisequence.py -> build\lib.win-amd64-3.9\hmmlearn\tests
      copying lib\hmmlearn\tests\test_gmm_hmm_new.py -> build\lib.win-amd64-3.9\hmmlearn\tests
      copying lib\hmmlearn\tests\test_multinomial_hmm.py -> build\lib.win-amd64-3.9\hmmlearn\tests
      copying lib\hmmlearn\tests\test_poisson_hmm.py -> build\lib.win-amd64-3.9\hmmlearn\tests
      copying lib\hmmlearn\tests\test_utils.py -> build\lib.win-amd64-3.9\hmmlearn\tests
      copying lib\hmmlearn\tests\__init__.py -> build\lib.win-amd64-3.9\hmmlearn\tests
      running build_ext
      building 'hmmlearn._hmmc' extension
      error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  Rolling back uninstall of hmmlearn
  Moving to c:\users\a-jamalude\documents\lin\2ndproject_intracategorycausality\venv\lib\site-packages\hmmlearn-0.2.7.dist-info\
   from C:\Users\a-jamalude\Documents\LIN\2ndProject_IntraCategoryCausality\venv\Lib\site-packages\~mmlearn-0.2.7.dist-info
  Moving to c:\users\a-jamalude\documents\lin\2ndproject_intracategorycausality\venv\lib\site-packages\hmmlearn\
   from C:\Users\a-jamalude\Documents\LIN\2ndProject_IntraCategoryCausality\venv\Lib\site-packages\~mmlearn
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> hmmlearn

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

**Comment by anntzer** [comment]
That's what it says on the box: you need msvc++ to install from source.
