### ISSUE TITLE
Getting non-deterministic results with python 3.10

### ISSUE THREAD

**Issue by siliwangCMT** [hmmlearn/hmmlearn#490]
## I have a question

Our in-production system uses` hmmlearn = "~=0.2.4"`; it is generating non-deterministic results with Python 3.10. Are you aware of such issues and would the latest release fix the non-deterministic part?

Thanks

**Comment by anntzer** [comment]
Are you setting random_state?  If you do and still see nondeterminism, please provide an example.

**Comment by anntzer** [comment]
Closing due to the lack of reproducible example, which makes this non-actionable.  Feel free to re-ping with a reproduction.
