### ISSUE TITLE
Nondeterministic results when convergence = True

### ISSUE THREAD

**Issue by ethan-skinner99** [hmmlearn/hmmlearn#491]
## I am reporting a bug
- Release 0.2.8
I was getting nondeterministic solutions using the hmmlearn.hmm.GMMHMM in version 0.2.8 so I switched back to 0.2.7 and had no issues so must be in the 0.2.8 update.

I wanted to see if it was the new Dirichlet distribution initialization for the start_prob and transmat_prior so I carried on presetting these values in the initialization of the model (See code below). However, when changing the random_state while keeping the start_prob and transmat_prior constant the inconsistent state prediction persisted. 

I went through the previous commits and found moving the forward-backward algorithm from python to C++ might be the issue. (I am not 100% sure). The commit was this one 
->Begin to simplify python/C++ interface. (https://github.com/hmmlearn/hmmlearn/pull/478)

_model = hmmlearn.hmm.GMMHMM(n_components=3, n_mix=1, covariance_type="full", random_state = i,tol=0.0001,n_iter=100,
        startprob_prior = np.array([0.06558334, 0.5608788,  0.37353786]),transmat_prior = np.array([[0.0054153,  0.68176292, 0.31282178],[0.00194156, 0.52703759, 0.47102085], [0.13210196, 0.3981238,  0.46977423]]),algorithm = 'viterbi'). 
  _model.fit(np.array(df.iloc[:,1:]))
  #_model.fit_log(np.array(df.iloc[:,1:]))
  df['state'] = _model.predict(np.array(df.iloc[:,1:]))

Run this same line of code to reproduce the issue while changing the random_state. Using a time series with about 40,000 data points. Sample of data below.

![Capture](https://user-images.githubusercontent.com/60528528/204036224-c8a4f278-c96c-4d55-88d1-136acbddec1c.PNG)

**Comment by anntzer** [comment]
1) This is not a minimal reproducible example: I cannot reproduce the problem without the contents of df.
2) If you change random_state it is *expected* that the results will change (that's the point of that parameter).

**Comment by ethan-skinner99** [comment]
1. Attached the dataframe (.csv)  ~ 40,000 
2.  This issue is about stability issues from V0.27 to V0.28. The same input data will converge to the same solution regardless of the random_state in V0.27 and fail to do so in V0.28. 
[HMMdataInput.csv](https://github.com/hmmlearn/hmmlearn/files/10107823/HMMdataInput.csv)

Unsure why this was closed before we were both clear on the problem. Will open another one with the reproducible example. So, you will be able to see as well.

**Comment by anntzer** [comment]
I would have reopened the issue with the reproduction information.  In any case this is now tracked at #492.

**Comment by ethan-skinner99** [comment]
was unaware you can reopen cases.
