### ISSUE TITLE
Result stability issues from V0.27 to V0.28 

### ISSUE THREAD

**Issue by ethan-skinner99** [hmmlearn/hmmlearn#492]
Release 0.2.8
I was getting nondeterministic solutions using the hmmlearn.hmm.GMMHMM in version 0.2.8 so I switched back to 0.2.7 and had no issues so must be in the 0.2.8 update.

This issue is about stability issues from V0.27 to V0.28. The same input data will converge to the same solution regardless of the random_state in V0.27 and fail to do so in V0.28.

I wanted to see if it was the new Dirichlet distribution initialization for the start_prob and transmat_prior so I carried on presetting these values in the initialization of the model (See code below). However, when changing the random_state while keeping the start_prob and transmat_prior constant the inconsistent state prediction persisted.

I went through the previous commits and found moving the forward-backward algorithm from python to C++ might be the issue. (I am not 100% sure). The commit was this one
->Begin to simplify python/C++ interface. (https://github.com/hmmlearn/hmmlearn/pull/478)

_model = hmmlearn.hmm.GMMHMM(n_components=3, n_mix=1, covariance_type="full", random_state = i,tol=0.0001,n_iter=100,
startprob_prior = np.array([0.06558334, 0.5608788, 0.37353786]),transmat_prior = np.array([[0.0054153, 0.68176292, 0.31282178],[0.00194156, 0.52703759, 0.47102085], [0.13210196, 0.3981238, 0.46977423]]),algorithm = 'viterbi').
_model.fit(np.array(df.iloc[:,1:]))
#_model.fit_log(np.array(df.iloc[:,1:]))
df['state'] = _model.predict(np.array(df.iloc[:,1:]))

Attached the dataframe (.csv) ~ 40,000

[HMMdataInput.csv](https://github.com/hmmlearn/hmmlearn/files/10107844/HMMdataInput.csv)

**Comment by blckmaxima** [comment]
In your example, you are setting `random_state=i` ?  What is the value of `i`?  

If you pass the same value to `random_state`, are the solutions identical?

**Comment by ethan-skinner99** [comment]
values of i vary. Some values cause it to converge to a solution similar to V0.27 while other values of i cause a completely different result.

**Comment by blckmaxima** [comment]
I ran a git bisect, and the changes are due to the new Dirichlet distribution initialization.
I started with 0.2.7 release as "good",
I set the 0.2.8 release as "bad"
It stopped on:
commit 6d3900db813528d22149fcc5d3d2a0f4bdfcb9e8 (refs/bisect/bad)
Author: Alex Rockhill <aprockhill@mailbox.org>
Date:   Mon May 23 10:47:35 2022 -0700

    [ENH, MRG] Add Dirichlet random initialization of priors on startprob and transmat (#466)


If you set `init_params=""`, and manually setup `startprob_` and `transmat_` then you will recover the 0.2.7 release behavior.
```
### Sample Script ### 
import hmmlearn.hmm
import numpy as np
import pandas as pd

df = pd.read_csv("HMMdataInput.csv", index_col=0)

_model = hmmlearn.hmm.GMMHMM(
    n_components=3,
    n_mix=1,
    covariance_type="full",
    random_state = 0,
    tol=0.0001,
    n_iter=100,
    init_params="e",
    startprob_prior = np.array([0.06558334, 0.5608788, 0.37353786]),
    transmat_prior = np.array([[0.0054153, 0.68176292, 0.31282178],[0.00194156, 0.52703759, 0.47102085], [0.13210196, 0.3981238, 0.46977423]]),
    algorithm = 'viterbi',
    verbose=True
)
_model.startprob_ = np.full(_model.n_components, 1 /_model.n_components)
_model.transmat_ = np.full((_model.n_components, _model.n_components), 1 /_model.n_components)
_model.fit(np.array(df.values))
#_model.fit_log(np.array(df.iloc[:,1:]))
df['state'] = _model.predict(np.array(df.iloc[:,1:]))
```

**Comment by anntzer** [comment]
Thanks for doing the investigation :)

**Comment by blckmaxima** [comment]
Need to pull my weight! :)
