### ISSUE TITLE
Problem with Multinomial when setting both n_trials and lengths

### ISSUE THREAD

**Issue by evd995** [hmmlearn/hmmlearn#495]
When running the following example

```python
import numpy as np
from hmmlearn import hmm

X = [[1, 2], [2, 0], [1, 2], [2, 0]]

model = hmm.MultinomialHMM(n_components=2, n_trials=[3,2,3,2])
model.fit(X, lengths=np.array([2, 2]))
```

I get the following error
<img width="808" alt="Screen Shot 2022-12-22 at 10 54 48" src="https://user-images.githubusercontent.com/17606121/209149221-2fae0d29-bf82-4b74-aeed-5cf82ccfa10d.png">

The problem is not present when setting only n_trials or lengths.

**Comment by anntzer** [comment]
Thanks for the report; this should be now fixed as of master (by e438907).
