### ISSUE TITLE
predict() looks into the future

### ISSUE THREAD

**Issue by localcreator** [hmmlearn/hmmlearn#496]
hmmlearn==0.2.8. HMM arranges hidden states "retroactively". It is easy to check this if we compare the predicted states (let there be 2 of them) and the real last ones, if we follow the observations with a "sliding window" and take the last predicted state.

The first column is predict() on out of sample. The second column is what happens if we don't know the future.
It is clearly seen that the predict() method looks one step into the future. How to turn off looking into the future? Perhaps this is planned to be fixed in a future version? How can I disable overwriting of the last value in hidden states?

model = hmm.GaussianHMM(n_components=2, covariance_type="diag", n_iter=100, random_state=11).fit(X)
model.predict(Y)

0 0
0 0
1 0
1 1
1 1
1 0
1 1
1 1
1 1
1 1
0 1
0 0
0 0

**Comment by anntzer** [comment]
This is standard behavior, see e.g. the referenced articles at https://hmmlearn.readthedocs.io/en/latest/tutorial.html.  As you noted yourself you can use a sliding window to hide the future.
