### ISSUE TITLE
HMM isn't converging

### ISSUE THREAD

**Issue by Lila14** [hmmlearn/hmmlearn#50]
I'm trying to fit a GMMHMM with 3 components to a series of numbers ("dirIndices").  Here's an example of  the first few lines of dirIndices: 

0
0.5
1.66666666667
-0.0833333333333
0.1
-0.75
0
-0.125
0.5
0.736363636364
0.242424242424
0.166666666667
0
0
11.2015503876
57.9074588477

Here's my code: 

```
model = GMMHMM(n_components=3, covariance_type="diag", n_iter=1000).fit(dirIndices)
domain_states = model.predict(dirIndices)
logprob, posteriors = model.score_samples(dirIndices)
```

For every line, the posterior probabilities are:
[ 0.33333333  0.33333333  0.33333333]

So it's clear that the HMM didn't converge.  In general, what problems with data can cause an HMM to not converge?

**Comment by superbobry** [comment]
Hello @Lila14, what version of `hmmlearn` are you using? If it happens to be the `master` version, can you please post the output of:

```python
print(model.monitor_.history)
```

**Comment by superbobry** [comment]
This is caused by #78.
