### ISSUE TITLE
Wrong output from predict and decode methods

### ISSUE THREAD

**Issue by dave-shore** [hmmlearn/hmmlearn#504]
Dear all,
I am using hmmlearn in its development version and I noticed that calling `predict` or `decode` methods on an array of shape (n_samples, n_features) doesn't return a state sequence of length n_samples as written in the docs, but of length n_samples*n_features. Is there a way to correct it?

**Comment by dave-shore** [comment]
Here is a toy example to clarify my point:

```
from hmmlearn import vhmm
import numpy as np

# Initializing model
model = vhmm.VariationalCategoricalHMM(n_components = 9, n_iter = 10, init_params = "ste")

# Generating data
X = np.random.randint(0, 3, (30,10))
seq_ids = sorted(np.random.randint(0, 5, 30))
seq_lengths = np.unique(seq_ids, return_counts = True)[1]
assert sum(seq_lengths) == 30

# Fitting the model
model.fit(X, seq_lengths)

# Predicting the best sequence
p, predicted_seq = model.decode(X, algorithm = "viterbi") # same output using model.predict
predicted_seq.shape
```

According to the docs, coherent to the theory, the final shape of the predicted sequence should be 30, while here it's 300. 
Thank you again for your attention!

**Comment by anntzer** [comment]
@blckmaxima as this appears to concern vhmms.

**Comment by blckmaxima** [comment]
Thanks, I'll take a peek hopefully this afternoon.

**Comment by blckmaxima** [comment]
A couple of things:

1. Don't forget to pass lengths to `decode()`, though that isn't the issue.
2. `hmm.CategoricalHMM()` behaves the same way.
3. I'm not sure if X is setup the way you want as an array of shape `(30, 10)` [with values 0, 1, and 2].  I would be more familiar with categorical data having the second dimension having a value of `1` at most.  If you go and look at the model learned, it has `n_features=3` and the `emission_prob_` attributes has shape (9, 3).  If this is all the case, then the Categorical HMMs should enforce a constraint on the shape of `X`, as the output from decode is indeed surprising, and wrong.

**Comment by anntzer** [comment]
Ah, good catch, sorry for the misping.  This is indeed due to Categorical flattening `X` (via np.concatenate), a behavior I've always thought slightly ungainly and should probably be deprecated.

**Comment by blckmaxima** [comment]
Let's do it.

**Comment by anntzer** [comment]
OK, done and pushed.
