### ISSUE TITLE
Problem with installing version 0.2.8 

### ISSUE THREAD

**Issue by Varanasi-Anirudh** [hmmlearn/hmmlearn#505]
Hello, I have installed 'hmmlearn' package in Python using the command "conda install -c conda-forge hmmlearn". (https://anaconda.org/conda-forge/hmmlearn)

However, it onlys installs version 0.2.7 and not the latest version 0.2.8. When I try to install package using the command "conda install -c conda-forge hmmlearn==0.2.8", this is the message I received. (conda started examining conflicts for 5 hours and then got stuck)

<img width="433" alt="hmmlearn 0 2 8 installation problem" src="https://user-images.githubusercontent.com/122984221/213526128-7094990a-b35b-4d3f-9e86-a8fc68eb09b8.png">

How can I solve this problem? 
Thank you very much in advance.

**Comment by anntzer** [comment]
We don't manage the conda-forge packages; you'll have to see directly with the packagers.
