### ISSUE TITLE
Cannot find aic of Gaussian HMM,

### ISSUE THREAD

**Issue by Simply-Adi** [hmmlearn/hmmlearn#513]
Hi,
I have hmmlearn  0.2.8. I tried running the tutorial given [here](https://hmmlearn.readthedocs.io/en/latest/auto_examples/plot_gaussian_model_selection.html#sphx-glr-auto-examples-plot-gaussian-model-selection-py). It throws AttributeError: 'GaussianHMM' object has no attribute 'aic'.

**Comment by blckmaxima** [comment]
Hello!  Please use the latest in GitHub on the main branch for this method.

**Comment by anntzer** [comment]
Let's close this as it will be fixed by the next release.
