### ISSUE TITLE
TypeError: GaussianHMM.__init__() got an unexpected keyword argument 'n_init'

### ISSUE THREAD

**Issue by xmTR007** [hmmlearn/hmmlearn#518]
I am using hmmlearn 0.2.7. 

When I initialized a new hmm model by 
`hmm.GaussianHMM(n_components=n_components, covariance_type="full")`
an warning message was prompt, "FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of`n_init` explicitly to suppress the warning warnings.warn("

But after I specify the value of n_init in the model using:
`model = hmm.GaussianHMM(n_components=n_components, covariance_type="full", n_init=10)`

an error was prompted: TypeError: GaussianHMM.__init__() got an unexpected keyword argument 'n_init'

**Comment by xmTR007** [comment]
Also, would like to check if AIC and BIC calculation is still available.

**Comment by blckmaxima** [comment]
Two answers:
* The warning about `n_init` behavior change is coming from scikit-learn,
and our use of KMeans for initializing the model.  You do not pass this
parameter to the GaussianHMM instance, and for now I would recommend
ignoring this parameter.
* AIC / BIC is available if you install the latest code from github.

**Comment by anntzer** [comment]
This will be fixed by the next release, which is tracked by #514.
