### ISSUE TITLE
transmat initialization

### ISSUE THREAD

**Issue by anntzer** [hmmlearn/hmmlearn#52]
It used to be possible to pass a `transmat` kwarg to GaussianHMM (still mentioned in the ![docs](http://hmmlearn.github.io/hmmlearn/generated/hmmlearn.hmm.GaussianHMM.html#hmmlearn.hmm.GaussianHMM)) to set a starting point for Viterbi, but this seems to no longer be the case.
It would be nice if this possibility was restored, or at least if an alternative was mentioned in the docs.

**Comment by superbobry** [comment]
Hello. The new way (currently unreleased) of fixing `transmat` is by directly setting the corresponding attribute on the `GaussianHMM` instance:

```python
hmm = GaussianHMM(...)
hmm.transmat_ = ...
```

**Comment by anntzer** [comment]
Actually, does that *fix* transmat (so EM would just fit the emission probabilities), or does that simply provide a starting point for the EM?  The latter is what I want to keep.

**Comment by superbobry** [comment]
Yes, this provides a starting point for EM, if you pass `init_params="smc"` to the constructor.

**Comment by anntzer** [comment]
I still think that it makes sense for `transmat` to be settable as a kwarg (why couldn't it, when the priors are?), but am not going to fight for it either.

**Comment by anntzer** [comment]
Actually, this doesn't provide a starting point for EM as of today's HEAD, see `base.py`:
```
        if 't' in params or not hasattr(self, "transmat_"): # <= overwritten here.
            self.transmat_ = np.full((self.n_components, self.n_components),
                                     init)
```

**Comment by superbobry** [comment]
> I still think that it makes sense for transmat to be settable as a kwarg [...]

It was settable as a kwarg in the previous version of `hmmlearn`, but I've decided to go after `scikit-learn` here and require estimated params to be set manually via attribute assignment, see e.g. [`GMM`](http://scikit-learn.org/stable/modules/generated/sklearn.mixture.GMM.html).

> Actually, this doesn't provide a starting point for EM as of today's HEAD [...]

It does. Sorry if the docs weren't clear enough on this. See comment on `init_params` in #62.

**Comment by superbobry** [comment]
I've added a note on `params` and `init_params` to the [tutorial](http://hmmlearn.readthedocs.org/en/latest/tutorial.html#building-hmm-and-generating-samples).
