### ISSUE TITLE
Matrix sparsification

### ISSUE THREAD

**Issue by liyifan20010515** [hmmlearn/hmmlearn#524]
## Matrix sparsification

I have a large (15000x30000) matrix as an emission matrix. I would like to sparse it to save memory usage. So I would like to know if the package now has the capability to handle sparse matrices.

**Comment by blckmaxima** [comment]
No, we don't yet support sparse matrices.

**Comment by liyifan20010515** [comment]
您好，邮件已收到~

**Comment by liyifan20010515** [comment]
您好，邮件已收到~
