### ISSUE TITLE
Create a tag for the 0.3.0 release

### ISSUE THREAD

**Issue by jakecyr** [hmmlearn/hmmlearn#526]
## I am requesting a new feature

Would it be possible to create a tag for the 0.3.0 release? It looks like 0.3.0 was released on commit:
13b56b2731716acf33fb13087fb0469c5558b320. 

The company I work at only allows using package versions that have a corresponding tag.

@anntzer

**Comment by anntzer** [comment]
Done.

**Comment by jakecyr** [comment]
> Done.

Thank you so much!
