### ISSUE TITLE
GMMHMM Error: Mixture not positive definite when n_mix > 1 

### ISSUE THREAD

**Issue by user529481** [hmmlearn/hmmlearn#528]
Hi,

Thank you for creating and maintaining this project. I tried running GMMHMM and the `fit` function throws an error if I specify n_mix for any number greater than 1. My code is below, and I've included a CSV of the data I called `fit()` on [google drive](https://drive.google.com/file/d/1-Dn6KqinfYxuPb5FrPHqeAITRgTewRi7/view?usp=sharing)

```py
train = <See google drive link above for CSV> # dataframe of size (48855, 16)

for idx in range(10): 
        try:
            model = hmm.GMMHMM(n_components=4, n_mix=2, covariance_type="full", random_state=idx, n_iter=10)
            model.fit(train)
            print(f'Score: {scores[-1]}')
        except Exception as e:
            print(e)
            continue
```

This is the error I'm getting:
```
Covariance of state #1, mixture #0 is not positive definite
```

**Comment by blckmaxima** [comment]
Thank you!  Can you provide a sample set of data that reproduces the error
with the code you provided?
