### ISSUE TITLE
Question about "map" algorithm

### ISSUE THREAD

**Issue by ValerianRey** [hmmlearn/hmmlearn#532]
Hey, I just wanted to make sure that the `map` algorithm for decoding is equivalent to the "forward-backward" algorithm.
If so, it would be nice to make it explicit from the documentation of the parameter.

**Comment by blckmaxima** [comment]
Hello, yes map decoding is equivalent to using the forward-backward
algorithm. We could definitely make that explicit.  If you propose a
documentation improvement, I can make sure it gets included.

Best,
Matthew
