### ISSUE TITLE
Sample code complains about hmm not being fitted

### ISSUE THREAD

**Issue by zoohair** [hmmlearn/hmmlearn#54]
Using this sample code provided in the docs (http://hmmlearn.github.io/hmmlearn/hmm.html#building-hmm-and-generating-samples)

```
>>> import numpy as np
>>> from hmmlearn import hmm

>>> startprob = np.array([0.6, 0.3, 0.1])
>>> transmat = np.array([[0.7, 0.2, 0.1], [0.3, 0.5, 0.2], [0.3, 0.3, 0.4]])
>>> means = np.array([[0.0, 0.0], [3.0, -3.0], [5.0, 10.0]])
>>> covars = np.tile(np.identity(2), (3, 1, 1))
>>> model = hmm.GaussianHMM(3, "full", startprob, transmat)
>>> model.means_ = means
>>> model.covars_ = covars
>>> X, Z = model.sample(100)
```
generates this error:

```
NotFittedError: This GaussianHMM instance is not fitted yet. Call 'fit' with appropriate arguments before using this method.
```

Version info:
```
In [4]: hmmlearn.__version__
Out[4]: '0.2.0'
```

git info:
```
commit d6dbe8c855cfebe3431f1b0d87e31de47535ea3e
Author: Sergei Lebedev <superbobry@gmail.com>
Date:   Thu Oct 15 01:34:49 2015 +0300
```

**Comment by zoohair** [comment]
I checked out the 0.1.1 tag and it seems to work. Where is the documentation for 0.2.0, or is it not recommended to use that?

**Comment by superbobry** [comment]
Hello, @zoohair. I know this is confusing, but the API docs are for the latest stable release which is `0.1.1`. There's no development documentation on the moment, but I'm working on making it available via ReadTheDocs.

**Comment by zoohair** [comment]
@superbobry: thanks for confirming that.

May I suggest making the default branch for the project to be 0.1.1 as long as the 0.2.0 documentation is not yet available, especially that the project page points to the 0.1.1 documentation.

**Comment by superbobry** [comment]
Yes. That makes sense, thank you.

**Comment by superbobry** [comment]
The docs for 0.2.0 are now available on [RTD](hmmlearn.readthedocs.org).

**Comment by nekovolta** [comment]
I have the same problem:

hmmlearn.__version__ is '0.2.1'

How can I solve this problem? Is it related to the hmmlearn version?

**Comment by rubyzhang1** [comment]
I have the same problem:
hmmlearn version is 0.2.2

**Comment by rubyzhang1** [comment]
> I have the same problem:
> hmmlearn version is 0.2.2

https://hmmlearn.readthedocs.io/en/latest/tutorial.html
