### ISSUE TITLE
Request a minor version update

### ISSUE THREAD

**Issue by taoliu** [hmmlearn/hmmlearn#546]
Hello! I am a developer in the MACS3 project, and we are using `hmmlearn` to build an HMM for detecting open chromatin regions from ATAC-seq data. Without the PR #545, we can't reproduce our results from an earlier sklearn (<1.3) -- related to https://github.com/macs3-project/MACS/pull/620 when members of Debian-med team tried to build deb packages for `macs` and `hmmlearn`. Is it possible to release a minor version update of `hmmlearn` to include this change? Currently, I implemented a simple workaround https://github.com/macs3-project/MACS/blob/bd5d7a33eba20a93374189f9e7a615536b6435df/MACS3/Signal/HMMR_HMM.pyx#L54-L80 But ideally, we'd like to use `hmmlearn` directly. Thank you!

**Comment by blckmaxima** [comment]
Thanks, let me see what I can do in the next two weeks.

**Comment by blckmaxima** [comment]
Just to understand, no code changes are necessary, just a new release?  IE, the work we did for test-stability takes care of the issue you were seeing.

**Comment by taoliu** [comment]
@blckmaxima You are right! No extra code changes. Just a new release with #545 -- test-stability-- on the file [lib/hmmlearn/hmm.py]( https://github.com/blckmaxima/hmmlearn/blob/ba2bab6b731044bbccd0a36024ae6ebe50ce80d7/lib/hmmlearn/hmm.py#L313)

**Comment by blckmaxima** [comment]
@taoliu I've tagged 0.3.2, and will be updating the packages on pypi later tonight.
