### ISSUE TITLE
Missing dependencies in README.rst

### ISSUE THREAD

**Issue by soupault** [hmmlearn/hmmlearn#55]
Trying to build `html` documentation on Win64 I've faced couple of errors on missing dependencies. They are: `sphinx-gallery`, `sphinx_rtd_theme`. With these packages installed the documentation is being built flawlessly.

So, I suggest to substitute

    $ pip install Pillow matplotlib Sphinx numpydoc

with 

    $ pip install Pillow matplotlib Sphinx sphinx-gallery sphinx_rtd_theme numpydoc

**Comment by superbobry** [comment]
Thanks. A PR would be perfect.

**Comment by soupault** [comment]
Verified that same packages are needed on Archlinux and they are supplied as separate.
