### ISSUE TITLE
Numpy's 2.0 release seems to break hmmlearn.

### ISSUE THREAD

**Issue by tobemo** [hmmlearn/hmmlearn#560]
Models no longer seem to learn in numpy 2.x. 
I was playing around with a `VariationalGaussianHMM` but I couldn't get it to learn anything. It kept predicting a single regime for all data points.

@Pinjhih, in #557, mentioned downgrading numpy to 1.26.4 (the last 1.x. version) which fixed the issue.

Adapting the [Using a Hidden Markov Model with Poisson Emissions to Understand Earthquakes](https://hmmlearn.readthedocs.io/en/latest/auto_examples/plot_poisson_hmm.html#using-a-hidden-markov-model-with-poisson-emissions-to-understand-earthquakes) example:

```py
import numpy as np
from hmmlearn import hmm

# earthquake data from http://earthquake.usgs.gov/
earthquakes = np.array([
    13, 14, 8, 10, 16, 26, 32, 27, 18, 32, 36, 24, 22, 23, 22, 18,
    25, 21, 21, 14, 8, 11, 14, 23, 18, 17, 19, 20, 22, 19, 13, 26,
    13, 14, 22, 24, 21, 22, 26, 21, 23, 24, 27, 41, 31, 27, 35, 26,
    28, 36, 39, 21, 17, 22, 17, 19, 15, 34, 10, 15, 22, 18, 15, 20,
    15, 22, 19, 16, 30, 27, 29, 23, 20, 16, 21, 21, 25, 16, 18, 15,
    18, 14, 10, 15, 8, 15, 6, 11, 8, 7, 18, 16, 13, 12, 13, 20,
    15, 16, 12, 18, 15, 16, 13, 15, 16, 11, 11])


n_components = 4 # best number of components per example
model = hmm.PoissonHMM(n_components=n_components, n_iter=10)
model.fit(earthquakes[:, None])
print(
    model.predict(earthquakes[:, None])
)
```
outputs:
```
Model is not converging.  Current: -340.8221635313274 is not greater than -340.7840696350969. Delta is -0.03809389623052084
[2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2]   
```

libraries installed:
```
hmmlearn==0.3.2
joblib==1.4.2
numpy==2.0.0
scikit-learn==1.5.1
scipy==1.14.1
threadpoolctl==3.5.0
```

#558 seems related.

**Comment by hezhenqi77** [comment]
Great！I'm worrying about it.

**Comment by anntzer** [comment]
This is likely because the wheels of the latest release were compiled against numpy<2; a fresh compilation should be the only thing required.  @tobemo @hezhenqi77 can either of you install from the git repository and confirm that it works for you?  If so we can probably arrange to tag a new release quickly.

**Comment by tobemo** [comment]
Yes, this works.
Using `pip install git+https://github.com/hmmlearn/hmmlearn` in a new venv, and without chaging any of the code, now outputs:
```
[0 2 0 2 0 3 3 3 3 3 3 1 1 1 1 1 1 1 1 0 2 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 3 3 3 3 3 3 3 3 3 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 3 3 3 1 1 1
 1 1 1 1 1 1 1 0 2 0 2 0 2 0 2 0 2 0 2 0 2 0 2 0 2 0 2 0 2 0 2 0 2]
```
and without any warnings about the model not converging.

**Comment by tobemo** [comment]
Do we close this now or wait for the new release?

**Comment by hezhenqi77** [comment]
It's up to you.



---- Replied Message ----
| From | Tomás ***@***.***> |
| Date | 09/09/2024 18:03 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [hmmlearn/hmmlearn] Numpy's 2.0 release seems to break hmmlearn. (Issue #560) |

Do we close this now or wait for the new release?

**Comment by anntzer** [comment]
@blckmaxima Let me know if you have any objections against me merging #561 & #562 and making a new release to fix the bad wheels.

**Comment by blckmaxima** [comment]
merge away!
