### ISSUE TITLE
GaussianHMM getting reproducible/consistent results

### ISSUE THREAD

**Issue by erexer** [hmmlearn/hmmlearn#567]
## I have a question

Hi! I'm running into the same issue as this: Changes in Fitting of Viterbi Sequence Based on Package Version #520 

In the [changelog for v0.2.8](https://hmmlearn.readthedocs.io/en/latest/changelog.html#version-0-2-8) you say

> `startmat_` and `transmat_` will both be initialized with random variables drawn from a Dirichlet distribution, to maintain the old behavior, these must be initialized as `1 / n_components`.

You say in issue #520 to change `startprob_` and `transmat_`, but in the changelog to change `startmat_` and `transmat_`, which is correct?

**Comment by anntzer** [comment]
It's startprob_.  I fixed the typo.
