### ISSUE TITLE
Please clarify the format of priors

### ISSUE THREAD

**Issue by anntzer** [hmmlearn/hmmlearn#58]
`GaussianHMM` provides the `startprob_prior` and `transmat_prior` kwargs, but it isn't clear to me how I'd use them to specify that (in a two state model) I have a prior e.g. of `a_11,a_12~Dirichlet(0.5)` or something else.

Also, is it possible to specify priors for the means and variances?

Thanks.

**Comment by superbobry** [comment]
Hello. Currently `hmmlearn` implement HMMs in a frequentist way, so the (slightly misleading) name *prior* simply means regularizer. I'm not sure if it corresponds to Dirichlet distribution mean.

Similar "priors" exist for means and variances, but I think I forgot to mention them in the docs, so please take a look at the [constructor signature](https://github.com/hmmlearn/hmmlearn/blob/master/hmmlearn/hmm.py#L116).

**Comment by anntzer** [comment]
Thanks you.  I would guess that this indeed corresponds to the Dirichlet prior for starting and transition probabilities.  I need to stare longer at the formulas for regularizing the means and variances to figure out what prior they correspond to -- can you help me there?

**Comment by jan-matthis** [comment]
The prior on the transition matrix/starting probability is indeed a Dirichlet (you can think of it as specifying pseudocounts).

To have a prior on the mean and covariance of a multivariate Gaussian, you would use a normal(-inverse) Wishart distribution. The M-step in `GaussianHMM` is based on this, however, you do not specify the parameters of the prior distribution but rather the variables `covars_prior`, `covars_weight`, `means_prior`, and `means_weight`.  If you want to know how these are related to the parameters of the normal(-inverse) Wishart, you can go about it by deriving the MAP solution and  relating it to the parametrization in the package. 

You might find it helpful to look at: _Maximum A Posteriori Estimation for Multivariate Gaussian Mixture Observations of Markov Chains_ by Gauvain and Lee (1993).

**Comment by anntzer** [comment]
Thanks for the reference.

**Comment by jexner** [comment]
@jan-matthis  This sounds like `startprob_prior` etc. only concern the MAP algorithm, but from the code it looks like it also affects the viterbi algorithm. Are there any other reference on this topic? What would be a typical value range for `startprob_prior`? (I guess it's  not a probability, since then `startprob_` might become negative, see https://github.com/hmmlearn/hmmlearn/blob/master/hmmlearn/base.py#L643.)

**Comment by jexner** [comment]
In the [initial commit](https://github.com/hmmlearn/hmmlearn/blob/14b3a8c35631ec2daf3fe8e9c3c0a1f4034d2472/hmmlearn/hmm.py#L549), there's a reference to [Huang, Acero, Hon, "Spoken Language Processing", p. 443 - 445](https://www.lrde.epita.fr/~reda/cours/speech/PH%20Spoken%20Language%20Processing%20-%20A%20Guide%20to%20Theory,%20Algorithm%20and%20System%20Development%20(2001)/chapter9.pdf#page=31). I'm just leaving this here for reference.
