### ISSUE TITLE
clarify meaning of `covariance_type` for GaussianHMM

### ISSUE THREAD

**Issue by anntzer** [hmmlearn/hmmlearn#60]
Perhaps something like
```
    covariance_type : string
        String describing the type of covariance parameters to use.  Must be
        one of 'spherical' (each state has its own single variance that applies
        for all components), 'tied' (the same general covariance matrix applies
        to all states), 'diag' (the same diagonal covariance matrix applies to
        all states), 'full' (each state has its own general covariance matrix).
        Defaults to 'diag'.
```
(I'm not even sure I got this correctly.)

**Comment by superbobry** [comment]
Thanks! 

I think `sklearn.mixture.GMM` might benefit from a similar comment. There's an ongoing effort on improving `GMM` and related classes in scikit-learn/scikit-learn#4802.

**Comment by anntzer** [comment]
Feel free to copy-paste my comment there in whatever suitable form, the thread there looks quite lengthy and I have a few other things on my plate...

**Comment by superbobry** [comment]
Done, thanks.
