### ISSUE TITLE
GaussianHMM cannot take a starting point for fitting means and covariances

### ISSUE THREAD

**Issue by anntzer** [hmmlearn/hmmlearn#62]
Of course you can set `means_` and `covars_`, but if we plan to fit the means and variances then they always get overwritten:
```
        if 'm' in params or not hasattr(self, "means_"): # <= oops
            kmeans = cluster.KMeans(n_clusters=self.n_components)
            kmeans.fit(X)
            self.means_ = kmeans.cluster_centers_
        if 'c' in params or not hasattr(self, "covars_"): # <= oops
            cv = np.cov(X.T)
            if not cv.shape:
                cv.shape = (1, 1)
            self._covars_ = distribute_covar_matrix_to_match_covariance_type(
                cv, self.covariance_type, self.n_components)
            self._covars_ = self._covars_.copy()
            if self._covars_.any() == 0:
                self._covars_[self._covars_ == 0] = 1e-5
```

**Comment by superbobry** [comment]
`GaussianHMM` accepts `init_params`, which is a string indicating which parameters should be initialized automatically. Just omit `"m"` and `"c"` and you won't have means and covariances overwritten:

```python
h = hmm.GaussianHMM(n_components=2, init_params="st")
h.means_ = [...]
h.covars_ = [...]
h.fit()

**Comment by anntzer** [comment]
Ah, I see, I didn't realize that there were both `params` and `init_params` that are independently settable.  Thanks.

**Comment by nesdolya** [comment]
Hi there, 
I have a question expanding on this. I am using the GaussianHMM for binary classification and I am trying to set the means prior, but I would like the covariances to be updated. Essentially, I want to shift my Gaussian curve for state 1 closer to zero. Is this possible?
Thanks!
