### ISSUE TITLE
ImportError: cannot import name 'logsumexp'

### ISSUE THREAD

**Issue by ckemere** [hmmlearn/hmmlearn#63]
I just recently switched from version 0.1.1 to the newest on master branch, and I'm getting an error when loading the library.

Here's my code:
import numpy as np
import matplotlib.pyplot as plt
from hmmlearn import hmm

Here's the error:

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-ad7d23e5821e> in <module>()
      2 import matplotlib.pyplot as plt
      3 
----> 4 from hmmlearn import hmm
      5 

/Users/ckemere/Anaconda3/lib/python3.4/site-packages/hmmlearn-0.2.0-py3.4-macosx-10.5-x86_64.egg/hmmlearn/hmm.py in <module>()
     18 from sklearn.utils import check_random_state
     19 
---> 20 from .base import _BaseHMM
     21 from .utils import iter_from_X_lengths, normalize
     22 

/Users/ckemere/Anaconda3/lib/python3.4/site-packages/hmmlearn-0.2.0-py3.4-macosx-10.5-x86_64.egg/hmmlearn/base.py in <module>()
     11 
     12 from . import _hmmc
---> 13 from .utils import normalize, logsumexp, iter_from_X_lengths, \
     14     log_mask_zero, exp_mask_zero
     15 

ImportError: cannot import name 'logsumexp'

**Comment by superbobry** [comment]
Interesting. Can you please make sure the file 

```
/Users/ckemere/Anaconda3/lib/python3.4/site-packages/hmmlearn-0.2.0-py3.4-macosx-10.5-x86_64.egg/hmmlearn/utils.py
```

is present and contains `def logsumexp`?

**Comment by ckemere** [comment]
Yes and yes. (That was the first thing I checked.)

**Comment by ckemere** [comment]
Purging my complete anaconda installation and reinstalling (without ever enabling the 0.1.1 branch) seems to have solved my problem. Is it possible that setup.py has some sort of misconfiguration?

**Comment by superbobry** [comment]
It is possible, but if so, the bug is very had to catch --- we run `setup.py` on both Travis and AppVeyor on each commit.
