### ISSUE TITLE
Is numerical stability an issue?

### ISSUE THREAD

**Issue by moooeeeep** [hmmlearn/hmmlearn#66]
In the earliest version that was committed here, a note was to be found in a docstring that warned of known numerical stability issues. 

The note was removed in this commit, without going into detail about it: https://github.com/hmmlearn/hmmlearn/commit/b378e1135819697f6249434d1429e2bb9268ff18

As I've seen, internally logarithms of probabilities are being used for computations. 

So, is numerical stability actually a non-issue? But why was the note originally present?

**Comment by superbobry** [comment]
I'm not sure what issue the note was referring to (#2 maybe?). 

As far as the current implementation is being concerned, I'm not aware of any existing issues (except #2) with numerical stability.
