### ISSUE TITLE
Clarification on  log-likelihood

### ISSUE THREAD

**Issue by alexander-james-gamino** [hmmlearn/hmmlearn#69]
I'm fairly new to hmms, so forgive me if I sound ignorant.

Essentially, I'm creating input features by sampling from 3 normal distributions, all centred at 5.0, with a standard deviations of 0.0000001. I train the HMM using these observations, and then use the **sample** method to generate samples from my HMM. Then I use the **score** method to get an idea of the probability of this sequence in the model. 

Here's the code I am using:

```python
import math
import numpy as np
from hmmlearn import hmm

m, s = 5.0,0.0000001

g1 = np.random.normal(m, s, 1000)
g2 = np.random.normal(m, s, 1000)
g3 = np.random.normal(m, s, 1000)

X = np.column_stack([g1, g2, g3])
HMM = hmm.GaussianHMM(n_components=3, n_iter=1000)
HMM.fit(X)

for i in range(0,100):
    sample, _ = HMM.sample(1)
    print sample
    prob = HMM.score(sample)
    print 'log-like: ', prob, '   prob: ', math.exp(prob) 
```
I'm getting output that looks something like this:

    [[ 5.00143565  4.9991442   4.99118425]]
    log-like:  11.5169454308    prob:  100402.805676
    [[ 4.99956099  4.98920739  5.00099388]]
    log-like:  10.8780507602    prob:  53000.1890873
    [[ 5.01013709  5.00566525  4.99596563]]
    log-like:  10.3069876345    prob:  29941.1070975
    [[ 5.00540697  4.99297579  5.00257765]]
    log-like:  11.4357086287    prob:  92568.9108846
    [[ 4.99881746  4.99839775  5.0034536 ]]
    log-like:  12.6393340166    prob:  308455.85503

Am I interpreting this log-likelyhood correctly? I assume that the value returned from **score** is ln(p) where p is the probability I'm looking for, thus e^ln(p) should be equal to p, which is what I am attempting to do in the code.

However the number's I am getting are rather strange, I would expect them to be between 0.0 and 1.0, but rather they tend to be huge. Can anyone shed some light on why this is? 

Thanks.

**Comment by ambushed** [comment]
I am very new to HMM but it looks like you are feeding a observations into the HMM that are very close to being constant.  Standard deviation of 0.0000001 is basically no std.dev at all.  If you increase the value to at least 1.0, then the score function will start returning negative log-probabilities.

**Comment by superbobry** [comment]
Hello. I think @ambushed is right. You fit an HMM to (effectively) unimodal data with rather small SD. This might not be what you want. 

> However the number's I am getting are rather strange, I would expect them to be between 0.0 and 1.0, but rather they tend to be huge.

The p.d.f. is not constrained to [0, 1], see e.g. [this](http://blog.stata.com/2011/02/16/positive-log-likelihood-values-happen/) link, which uses normal distribution with small standard deviation to illustrate the point.

```
>>> stats.norm.pdf(0, 0, 1e-1)
3.9894228040143269
>>> stats.norm.pdf(0, 0, 1e-2)
39.894228040143268
>>> stats.norm.pdf(0, 0, 1e-8)
39894228.040143266
```
