### ISSUE TITLE
ImportError: cannot import name hmm

### ISSUE THREAD

**Issue by metterlein** [hmmlearn/hmmlearn#7]
Hi,

I used the hmm module from sklearn and tried to replace it by the hmmlearn module. Unfortunately I could not import it to my notebook. 

`from hmmlearn import hmm`
`---------------------------------------------------------------------------`
`ImportError                               Traceback (most recent call last)`
`<ipython-input-7-8b8c029fb053> in <module>()`
`----> 1 from hmmlearn import hmm`

`ImportError: cannot import name hmm`

I tried first 
`pip-3.3 install git+https://github.com/hmmlearn/hmmlearn.git`

As this didn't work I cloned the project and run the setup.py (with python 3.3) but I still get an import error.

If I try to import 

`import hmmlearn.hmm`

I get another error

`ImportError                               Traceback (most recent call last)`
`<ipython-input-8-8dbb2cfe75b2> in <module>()`
`----> 1 import hmmlearn.hmm`

`/home/ipython/python/lib/python3.3/site-packages/hmmlearn/hmm.py in <module>()`
`22 from sklearn import cluster`
`23`
`---> 24 from .utils.fixes import log_multivariate_normal_density`
`25`
`26 from . import _hmmc`

`ImportError: No module named 'hmmlearn.utils'`

What did I do wrong?

Cheers, Evelyn

**Comment by alicia1** [comment]
Hi, I've just installed hmmlearn and am having the same issue. I don't have any configuration function in my setup.py file. What should I do? 

This is the error:

`from hmmlearn import hmm
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "build/bdist.macosx-10.11-intel/egg/hmmlearn/hmm.py", line 14, in <module>
  ImportError: No module named sklearn`

**Comment by superbobry** [comment]
It looks like you don't have `scikit-learn` installed, try running

```bash
pip install scikit-learn
```

or, if you're using conda,

```bash
conda install scikit-learn
```

**Comment by khronosplus** [comment]
@superbobry  hi, I've the same question and have seen your answer before, but I don't know how to do. What exactly should I do?

This is the error:
Traceback (most recent call last):
  File "/media/khronos/新加卷/py_project/hmmlearn-master/hmmlearn/tests/test_gmm_hmm.py", line 8, in <module>
    from hmmlearn import hmm
  File "/media/khronos/新加卷/py_project/hmmlearn-master/hmmlearn/hmm.py", line 22, in <module>
    from .base import _BaseHMM
  File "/media/khronos/新加卷/py_project/hmmlearn-master/hmmlearn/base.py", line 13, in <module>
    from . import _hmmc
ImportError: cannot import name '_hmmc'

**Comment by superbobry** [comment]
Hi @khronosplus, from the error it seems you're trying to import `hmmlearn` from the repo root. To do this you need to manually compile the C extension first:

```bash
$ python setup.py build_ext --inplace
```

Otherwise, I'd recommend to install it via

```
$ pip install .
```

**Comment by khronosplus** [comment]
@superbobry Thanks for your help.
firstly,I manually compile the C extension with the command:
`python setup.py build_ext --inplace`
but failed
`creating build
creating build/temp.linux-x86_64-2.7
creating build/temp.linux-x86_64-2.7/hmmlearn
compile options: '-I/usr/lib/python2.7/dist-packages/numpy/core/include -I/usr/include/python2.7 -c'
extra options: '-O3'
x86_64-linux-gnu-gcc: hmmlearn/_hmmc.c
Assembler messages:
Fatal error: can't create build/temp.linux-x86_64-2.7/hmmlearn/_hmmc.o: 没有那个文件或目录
Assembler messages:
Fatal error: can't create build/temp.linux-x86_64-2.7/hmmlearn/_hmmc.o: 没有那个文件或目录
error: Command "x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/lib/python2.7/dist-packages/numpy/core/include -I/usr/include/python2.7 -c hmmlearn/_hmmc.c -o build/temp.linux-x86_64-2.7/hmmlearn/_hmmc.o -O3" failed with exit status 1
`
secondly,I installed hmmlearn using  sudo pip3 install hmmlearn,
`Requirement already satisfied (use --upgrade to upgrade): hmmlearn in /home/khronos/.local/lib/python3.4/site-packages
`
but I can't access to /home/khronos/.local/lib/python3.4/site-packages
`bash: cd: /home/khronos/.local/lib/python3.4/site-packages: 权限不够
`

**Comment by superbobry** [comment]
According to the error message, you don't have permissions to access `site-packages`. Could you do `ls ~/.local/lib/python3.4/site-packages`?

**Comment by khronosplus** [comment]
@superbobry I have deleted the old hmmlearn in` ~/.local/lib/python3.4/site-packages`,and installed hmmlearn with pip3.
Now, I can successfully use hmmlearn  with import toolkit, and run hmm-master successfully.
Thank you very much for your patience

**Comment by apr1** [comment]
Hello @superbobry and @khronosplus, I am having a similar issue in running this module with jupyter, 
I am getting the error - 
```
[---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-1a818208e4fd> in <module>()
----> 1 from sklearn.hmm import GaussianHMM
      2 
      3 
      4 def fit_hmm(depth_normed,  # normalised coverage array 
      5             transition_probability,  # probability of state transition

ImportError: No module named hmm](url)
```
I tried uninstalling and installed hmmlearn with pip3 but I am getting same error again and again.

**Comment by superbobry** [comment]
Hi @apr, you have to do `from hmmlearn.hmm import `GaussianHMM`. `hmmlearn` does not user scikit-learn namespace.

**Comment by ldesmetepm** [comment]
Hi everybody,

I am new in Python and I have issues when I try to import this library.
Hope guys you could help me ?

I am currently working on Windows 10, with Anaconda and Spyder. I am using Python 3.6.3 and sc learn 0.19

Well the issue is quite simple, when I start the script with : 
from sklearn import hmm

There is this error : 
ImportError: cannot import name hmm

Do you hqve any clue to help me out ?

Thanks everyone

**Comment by GaelVaroquaux** [comment]
You need to install hmmlearn and import from hmmlearn.

**Comment by ldesmetepm** [comment]
Thanks Gael,

Using :  conda install -c omnia hmmlearn works perfectly now ! But I don't get it, is it from sk learn library ? Because the syntax is exactly the same.

Thank's again :)

**Comment by danodonovan** [comment]
From the the github repository description:
> Hidden Markov Models in Python, with scikit-learn like API http://hmmlearn.readthedocs.org

**Comment by ldesmetepm** [comment]
Thanks ;)

**Comment by manitadayon** [comment]
I am receiving the same error as
 cannot import name '_hmmc'

Above you explained that I should change the setup file, Can you elaborate what lines I should change ?
where should I add them? thanks

**Comment by Lena-1994** [comment]
Hi @superbobry,
could you please help me. I have a weird problem. I have installed hmm learn via "python3 -m pip install --user git+https://github.com/hmmlearn/hmmlearn" and I can import it in either terminal or visual studio. However, when I import it in Jupiter Notebook I get this error"

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
/var/folders/5_/4m4077hn793440lp0f95cjtr0000gp/T/ipykernel_18578/4049620608.py in <module>
     14 import scipy
     15 from pandas.plotting import register_matplotlib_converters
---> 16 from hmmlearn import hmm
     17 from hmmlearn.hmm import GaussianHMM

ModuleNotFoundError: No module named 'hmmlearn'

What should I do in this case?
