### ISSUE TITLE
simple multinomial example

### ISSUE THREAD

**Issue by ambushed** [hmmlearn/hmmlearn#70]
Hi there!

Using the latest master of hmmlearn, I tried running a simple MultinomialHMM example (code below) that results in the following error:

> >  File "build/bdist.macosx-10.5-x86_64/egg/hmmlearn/base.py", line 307, in decode
> > ValueError: could not broadcast input array from shape (6) into shape (1)

Could you please tell me what i am doing wrong?  My expectation is that applying Viterbi should give me the most probable hidden sequence.  However passing a list of observation doesn't work unlike passing a single value which does.

Thanks!

Vlad

``` python
from __future__ import division
import numpy as np
from hmmlearn import hmm

states = ["Rainy", "Sunny"]
n_states = len(states)

observations = ["walk", "shop", "clean"]
n_observations = len(observations)

start_probability = np.array([0.6, 0.4])

transition_probability = np.array([
  [0.7, 0.3],
  [0.4, 0.6]
])

emission_probability = np.array([
  [0.1, 0.4, 0.5],
  [0.6, 0.3, 0.1]
])

model = hmm.MultinomialHMM(n_components=n_states)
model.startprob=start_probability
model.transmat=transition_probability
model.emissionprob=emission_probability

# predict a sequence of hidden states based on visible states
bob_says = [0, 2, 1, 1, 2, 0]
model = model.fit(bob_says)
logprob, alice_hears = model.decode(bob_says, algorithm="viterbi")
print "Bob says:", ", ".join(map(lambda x: observations[x], bob_says))
print "Alice hears:", ", ".join(map(lambda x: states[x], alice_hears))
```

**Comment by soupault** [comment]
Hi!
You need to pass both features (for fitting) and observations (for decode) in 2D numpy-arrays, where the observation index is used as a first dimension one.

Here is the change that fixes your code:

    bob_says = np.array([[0, 2, 1, 1, 2, 0]]).T

Output:

    Bob says: walk, clean, shop, shop, clean, walk
    Alice hears: Rainy, Sunny, Sunny, Sunny, Sunny, Rainy

**Comment by ambushed** [comment]
Thanks a lot!  It helped!

**Comment by soupault** [comment]
Meaningful example, yes. There are already some of them added.
Please, check actual documentation beforce you proceed - https://hmmlearn.readthedocs.org/en/latest/index.html .

If issue is resolved, could you, please, close it?

**Comment by piyushchauhan2011** [comment]
👍  Works perfectly. I was hoping if someone have answer to this warning message ?

`//anaconda/lib/python3.5/site-packages/ipykernel/__main__.py:33: DeprecationWarning: converting an array with ndim > 0 to an index will result in an error in the future`

**Comment by superbobry** [comment]
Could you attach the code causing the warning or does it happen when you run the tutorial code?

**Comment by piyushchauhan2011** [comment]
Here is the full code @superbobry :

```python
from __future__ import division
import numpy as np
from hmmlearn import hmm

states = ["Rainy", "Sunny"]
n_states = len(states)

observations = ["walk", "shop", "clean"]
n_observations = len(observations)

start_probability = np.array([0.6, 0.4])

transition_probability = np.array([
  [0.7, 0.3],
  [0.4, 0.6]
])

emission_probability = np.array([
  [0.1, 0.4, 0.5],
  [0.6, 0.3, 0.1]
])

model = hmm.MultinomialHMM(n_components=n_states)
model.startprob=start_probability
model.transmat=transition_probability
model.emissionprob=emission_probability

# predict a sequence of hidden states based on visible states
bob_says = np.array([[0, 2, 1, 1, 2, 0]]).T

model = model.fit(bob_says)
logprob, alice_hears = model.decode(bob_says, algorithm="viterbi")
print("Bob says:", ", ".join(map(lambda x: observations[x], bob_says)))
print("Alice hears:", ", ".join(map(lambda x: states[x], alice_hears)))
```

**Comment by gallupliu** [comment]
hi all ，
   I use this example，but，why the model parameter（startprob，transmat,and
 emisiionprob）is unchanged?

**Comment by gallupliu** [comment]
I has solve it ,But I encountered such a mistake：“ expected a sample from a Multinomial distribution”，My data formate  as fellow：
tom_says = np.array([[-0.19718082,0.08098814,-0.05390872,-0.42958553,0.09095274,-0.46553826,
  0.14951585,0.06249087,-0.12556805],
[0.12566081,-0.25735795,0.06026819,0.22645027,0.11658830,0.53303989,
  0.28749026,0.11135886,0.10657429],
[0.11706524,0.2314521,0.09253231,-0.02948833,0.13897765,-0.08485895,
  0.45912256,0.40540203,-0.01244893]])

**Comment by dimitargnikolov** [comment]
I also tried this example with some modifications, but the model didn't change (transmat, emissionprob and startprob remain the same). This is the code.

```python
from __future__ import division
import numpy as np, random
from hmmlearn import hmm

states = ["Rainy", "Sunny"]
n_states = len(states)

observations = ["walk", "shop", "clean"]
n_observations = len(observations)

start_probability = np.array([0.6, 0.4])

transition_probability = np.array([
    [0.7, 0.3],
    [0.4, 0.6]
])

emission_probability = np.array([
    [0.1, 0.4, 0.5],
    [0.6, 0.3, 0.1]
])

model = hmm.MultinomialHMM(n_components=n_states, n_iter=1000)
model.startprob=start_probability
model.transmat=transition_probability
model.emissionprob=emission_probability

print model.transmat
print model.emissionprob
print model.startprob
print

# predict a sequence of hidden states based on visible states                                                                                                                                                    
seq = []
lengths = []
for _ in range(100):
    length = random.randint(5, 10)
    lengths.append(length)
    for _ in range(length):
        r = random.random()
        if r < .2:
            seq.append(0)
        elif r < .6:
            seq.append(1)
        else:
            seq.append(2)
seq = np.array([seq]).T
model = model.fit(seq, lengths)


print model.transmat
print model.emissionprob
print model.startprob
print

bob_says = np.array([[0, 2, 1, 1, 2, 0]]).T
logprob, alice_hears = model.decode(bob_says, algorithm="viterbi")
print "Bob says:", ", ".join(map(lambda x: observations[x], bob_says.T[0]))
print "Alice hears:", ", ".join(map(lambda x: states[x], alice_hears))
```

@gallupliu, your input sequence makes sense for a continuous emission function, but not a discrete one. For a multinomial HMM as used in the example, I would think you'd need a discrete set of values for the observations.

**Comment by dimitargnikolov** [comment]
OK, the issue with the examples here that causes the model parameters not to change when the model is trained is that the correct attribute names are `transmat_`, `startprob_` and `emissionprob_`, with underscores. So changing these three lines in the examples 

```python
model.startprob=start_probability
model.transmat=transition_probability
model.emissionprob=emission_probability
```

to 

```python
model.startprob_=start_probability
model.transmat_=transition_probability
model.emissionprob_=emission_probability
```

solves the issue.

Also, @piyushchauhan2011 and @superbobry, the issue with the exception is this line from the original example:

```python
print "Bob says:", ", ".join(map(lambda x: observations[x], bob_says))
```

It assumes the old input format for `bob_says`. Changing it as follows gets rid of the warning.

```python
print "Bob says:", ", ".join(map(lambda x: observations[x], bob_says.T[0]))
```

**Comment by f-rumblefish** [comment]
Dear All:

This example is great, but the output is somewhat confusing. I run the program five times and get different results as follow. It seems to me that Alice cannot get the correct state or just get a state with some probability. How do we explain the outputs or maybe display the corresponding probability?

`C:\Users\Frank\Desktop\mypython>python hello_hmm_001.py
Bob says: walk, clean, shop, shop, clean, walk
Alice hears: Rainy, Sunny, Sunny, Sunny, Sunny, Rainy

C:\Users\Frank\Desktop\mypython>python hello_hmm_001.py
Bob says: walk, clean, shop, shop, clean, walk
Alice hears: Rainy, Sunny, Sunny, Rainy, Sunny, Rainy

C:\Users\Frank\Desktop\mypython>python hello_hmm_001.py
Bob says: walk, clean, shop, shop, clean, walk
Alice hears: Rainy, Sunny, Sunny, Rainy, Sunny, Rainy

C:\Users\Frank\Desktop\mypython>python hello_hmm_001.py
Bob says: walk, clean, shop, shop, clean, walk
Alice hears: Sunny, Rainy, Sunny, Rainy, Rainy, Sunny

C:\Users\Frank\Desktop\mypython>python hello_hmm_001.py
Bob says: walk, clean, shop, shop, clean, walk
Alice hears: Sunny, Rainy, Sunny, Rainy, Rainy, Sunny`

**Comment by superbobry** [comment]
Hi, the variability in the outputs has to do with parameter initialization. In the current implementation emission probabilities are initialized randomly, which makes the learning converge to slightly different results.

Another issue is that initial parameters are unused, because a) they are missing _ suffix and b) `init_param` is missing from the constructor call. Here's the corrected version:

```python
import numpy as np
from hmmlearn import hmm

states = ["Rainy", "Sunny"]
n_states = len(states)

observations = ["walk", "shop", "clean"]
n_observations = len(observations)

model = hmm.MultinomialHMM(n_components=n_states, init_params="")
model.startprob_ = np.array([0.6, 0.4])
model.transprob_ = np.array([
  [0.7, 0.3],
  [0.4, 0.6]
])
model.emissionprob_ = np.array([
  [0.1, 0.4, 0.5],
  [0.6, 0.3, 0.1]
])

# predict a sequence of hidden states based on visible states
bob_says = np.array([[0, 2, 1, 1, 2, 0]]).T

model = model.fit(bob_says)
logprob, alice_hears = model.decode(bob_says, algorithm="viterbi")
print("Bob says:", ", ".join(map(lambda x: observations[x], bob_says)))
print("Alice hears:", ", ".join(map(lambda x: states[x], alice_hears)))
```

**Comment by f-rumblefish** [comment]
Thanks for the comments. Using the new version, I can get consistent results now. But, it seems to me that random results provide more interesting points about identifying the corresponding states.

**Comment by superbobry** [comment]
Yep, random init is often used with EM-type algorithms to workaround (in an ad-hoc way) the issue of local optima. The strategy is to run the learning multiple times and them pick the model with the best log-likelihood.

**Comment by f-rumblefish** [comment]
Got it. Thanks.

**Comment by himat** [comment]
@soupault You said there were already examples in the documentation, but there are none like this which use a discrete HMM. I think it should be added

**Comment by saroyogi3** [comment]
Hi,

I am working on Named entity recognition using HMM.
state = ['PERSON', 'O', 'LOCATION']
The states are Person, Others and Location similar to sunny and rainy

The start probability, transmat probability and emission probability are calculated
I get random values for each iteration. 
If i set init_params=""  to avoid random values

model.startprob_ , model.transmat_, model.emissionprob_ becomes NAN
As a result
logprob, alice_hears = model.decode(bob_says, algorithm="viterbi")
throws error.

If i set init_params="ste"  then 
model.startprob_ , model.transmat_, model.emissionprob_ 
parameters gets calculated but with random values.

please suggest where things are wrong



my code is as given below

model = hmm.MultinomialHMM(n_components=n_state, init_params="ste")
model.startprob_ = np.array(start_valuelist)
model.transmat_ = np.array(tras_valuelist)
model.emissionprob_ = np.array(emis_valuelist)

# Predict the optimal sequence of internal hidden state
bob_says = np.array([[0, 2, 1, 1, 2, 0]]).T
model = model.fit(bob_says)
print model

print model.startprob_  (NAN if init_params="" as suggested in the previous posts)
print model.transmat_  (NAN if init_params="" as suggested in the previous posts)
print model.emissionprob_ (NAN if init_params="" as suggested in the previous posts)


logprob, alice_hears = model.decode(bob_says, algorithm="viterbi")


print("Bob says:", ", ".join(map(lambda x: observations[x], [item for sublist in bob_says for item in sublist])))
print("Alice hears:", ", ".join(map(lambda x: states[x], alice_hears)))

**Comment by MichaelPolla** [comment]
Hi,
When trying to use the samples below (e.g. @superbobry's one), the last two lines (print) give me a TypeError : only integer scalar arrays can be converted to a scalar index.

Could someone help me to get it working ?

**Comment by johnomics** [comment]
@MichaelPolla I just hit the same problem. It can be fixed by converting x to an integer before using it as an index:

```python
print("Bob says:", ", ".join(map(lambda x: observations[int(x)], bob_says)))
print("Alice hears:", ", ".join(map(lambda x: states[int(x)], alice_hears)))
```

**Comment by frozflame** [comment]
I don't understand why passing `model.fit` and then `model.decode` the same data (`bob_says `)?

**Comment by alexrockhill** [comment]
See this PR https://github.com/hmmlearn/hmmlearn/pull/458, I think that this addresses this issue.

**Comment by danielwei0214** [comment]
Hi !
Using the hmmlearn, I tried running a simple MultinomialHMM example (code below) that results in the following error:
### 
Traceback (most recent call last):
  File "C:\Users\danie\Desktop\hmm1.py", line 34, in <module>
    model.fit(X)
  File "C:\Users\danie\AppData\Local\Programs\Python\Python310\lib\site-packages\hmmlearn\base.py", line 497, in fit
    self._init(X)
  File "C:\Users\danie\AppData\Local\Programs\Python\Python310\lib\site-packages\hmmlearn\hmm.py", line 441, in _init
    self._check_and_set_multinomial_n_features_n_trials(X)
  File "C:\Users\danie\AppData\Local\Programs\Python\Python310\lib\site-packages\hmmlearn\hmm.py", line 437, in _check_and_set_multinomial_n_features_n_trials
    raise ValueError("Total count for each sample should add up to "
**ValueError: Total count for each sample should add up to the number of trials**_
Could you please tell me what i am doing wrong?


import numpy as np
from hmmlearn import hmm

states = ['Rainy', 'Sunny']
n_states = len(states)  

observations = ['walk', 'shop', 'clean']
n_observations = len(observations)

start_probability = np.array([0.6, 0.4])

transition_probability = np.array([
    [0.7, 0.3],
    [0.4, 0.6]
])

emission_probability = np.array([
    [0.1, 0.4, 0.5],
    [0.6, 0.3, 0.1]
])

model = hmm.MultinomialHMM(n_components=n_states,n_iter=100, tol=0.01) 
X = np.array([[2, 0, 1, 1, 2, 0], [0, 0, 1, 1, 2, 0], [2, 1, 2, 1, 2, 0]])
model.fit(X)
print('startprob: \n',model.startprob_)
print('transmat:\n',model.transmat_)
print('emissionprob:\n',model.emissionprob_)

**Comment by yafeng-Soong** [comment]
> ```python
> from __future__ import division
> import numpy as np
> from hmmlearn import hmm
> 
> states = ["Rainy", "Sunny"]
> n_states = len(states)
> 
> observations = ["walk", "shop", "clean"]
> n_observations = len(observations)
> 
> start_probability = np.array([0.6, 0.4])
> 
> transition_probability = np.array([
>   [0.7, 0.3],
>   [0.4, 0.6]
> ])
> 
> emission_probability = np.array([
>   [0.1, 0.4, 0.5],
>   [0.6, 0.3, 0.1]
> ])
> 
> model = hmm.MultinomialHMM(n_components=n_states)
> model.startprob=start_probability
> model.transmat=transition_probability
> model.emissionprob=emission_probability
> 
> # predict a sequence of hidden states based on visible states
> bob_says = np.array([[0, 2, 1, 1, 2, 0]]).T
> 
> model = model.fit(bob_says)
> logprob, alice_hears = model.decode(bob_says, algorithm="viterbi")
> print("Bob says:", ", ".join(map(lambda x: observations[x], bob_says)))
> print("Alice hears:", ", ".join(map(lambda x: states[x], alice_hears)))
> ```

I have same problem

**Comment by anntzer** [comment]
@danielwei0214 Your issue is fixed as of master.
@yafeng-Soong The attribute names end with an underscore.

**Comment by yafeng-Soong** [comment]
> @danielwei0214 Your issue is fixed as of master. @yafeng-Soong The attribute names end with an underscore.

Thanks, I solved this problem by checking the official documents. 
![image](https://user-images.githubusercontent.com/35646388/211235812-73186f11-366d-44e3-bd5b-64162d13fb86.png)
What I really want to call should be the ```CategoricalHMM```
