### ISSUE TITLE
multinomial HMM training long sequences

### ISSUE THREAD

**Issue by waterblas** [hmmlearn/hmmlearn#72]
Hi,  I want to use MultinomialHMM to train a long sequences that can't load in RAM once. It seems that the MultinomialHMM `fit` method only access whole sequences once, is that right?       
If right, is there any api that support to train slice of long sequences each time?

**Comment by superbobry** [comment]
No, there's no API for out-of-core learning at the moment.

Can you please elaborate on the use-case you have? It is possible that we can come up with a reasonable API.
