### ISSUE TITLE
Too small number of iterations in fit() method

### ISSUE THREAD

**Issue by michcio1234** [hmmlearn/hmmlearn#73]
Hi

It seems that `ConvergenceMonitor` stops HMM fitting 1 iteration too early. For a given HMM, its `monitor_` is initialized as:

    class ConvergenceMonitor(object):
        def __init__(self, tol, n_iter, verbose):
            (...)
            self.iter = 1

`self.iter` is incremented only in `report()` function, which is called _between_ E and M steps during fitting. Right after it, convergence is checked:

    def fit(self, X, lengths=None):
            (...)  # E step here
            self.monitor_.report(curr_logprob)  # monitor_.iter is incremented
            if self.monitor_.converged:
                break
            (...)  # M step here

So, during `n'th` iteration, `monitor_.iter` is being set to `n` before performing M step. Therefore, during 1-before-last iteration, convergence check reports that iterations number limit was reached... 

    @property
    def converged(self):
        """``True`` if the EM-algorithm converged and ``False`` otherwise."""
        return (self.iter == self.n_iter or  # THIS CONDITION STOPS FITTING
                (len(self.history) == 2 and
                 self.history[1] - self.history[0] < self.tol))

...and fitting is stopped.

Maybe `monitor_` should be initialized with `self.iter = 0`?

Regards
Michał

**Comment by superbobry** [comment]
Hello, Michael. Thank you for a detailed bug report.

Setting `self.iter` to 0 is indeed the correct way to solve this. I've pushed a patch to `master`.
