### ISSUE TITLE
ConvergenceMonitor works only for 2'nd iteration

### ISSUE THREAD

**Issue by michcio1234** [hmmlearn/hmmlearn#75]
Thanks, @superbobry, for publishing the patch to #73.
BUT. ;)
I didn't realize that the second condition in convergence check is also improper. It works only in 2'nd iteration.

    @property
    def converged(self):
        """``True`` if the EM algorithm converged and ``False`` otherwise."""
        # XXX we might want to check that ``logprob`` is non-decreasing.
        return (self.iter == self.n_iter or
                (len(self.history) == 2 and  # ONLY IF WE'RE IN 2'nd ITERATION
                 self.history[1] - self.history[0] < self.tol))  # ONLY IF WE'RE IN 2'nd ITERATION

Also, you added a note that "*we might want to check that ``logprob`` is non-decreasing*". Indeed, we do it already (negative difference in history is less then `self.tol`, 'cause `self.tol` should be >0), but it works only for 2'nd iteration.

The last issue I want to mention is that `ConvergenceMonitor` does not `report()` anything during 1'st (actually 0'th) iteration, because `self.history` is empty. This may be misleading, since if we set a number of iteration to N, we observe reports with numbers 1:N-1, so one may think that N-1 iterations were performed.

**Comment by superbobry** [comment]
> I didn't realize that the second condition in convergence check is also improper. It works only in 2'nd iteration.

Well, there's not much we can do if we only have one `logprob` value. How would you define *convergence* in this case?

> Indeed, we do it already  (negative difference in history is less then `self.tol`, 'cause `self.tol` should be >0), but it works only for 2'nd iteration.

You're right. However, the comment is for an explicit check with an informative error message, which we don't have atm.

> The last issue I want to mention is that `ConvergenceMonitor` does not `report()` anything during 1'st (actually 0'th) iteration, because `self.history` is empty.

This is a valid point. We could use a separate message for this case, e.g.

```
{iter:>10d} {logprob:>16.4f}
```

**Comment by michcio1234** [comment]
>> I didn't realize that the second condition in convergence check is also improper. It works only in 2'nd iteration.

>Well, there's not much we can do if we only have one logprob value. How would you define convergence in this case?

You actually answer this particular question in your last sentence:

>We could use a separate message for this case, e.g. `{iter:>10d} {logprob:>16.4f}`

Of course *convergence* cannot be defined with only 1 `logprob`.

But what I'm saying is that `ConvergenceMonitor` doesn't work for 3'rd, 4'th iteration and so on! :)
I think it should be like this:
```
    @property
    def converged(self):
        """``True`` if the EM algorithm converged and ``False`` otherwise."""
        # XXX we might want to check that ``logprob`` is non-decreasing.
        return (self.iter == self.n_iter or
                (len(self.history) >= 2 and
                 self.history[-1] - self.history[-2] < self.tol))
```
although I did not test it.

**Comment by superbobry** [comment]
> But what I'm saying is that `ConvergenceMonitor` doesn't work for 3'rd, 4'th iteration and so on! :)

`self.history` is a bounded deque, so it's length never exceeds 2, that's why we have `==` there.

**Comment by michcio1234** [comment]
Aww, sorry for that. :/ So, it's up to you whether to close this issue. Thanks for your responses. And I'll probably disturb you in the near future again. ;)

**Comment by superbobry** [comment]
No problem. I'll add the `iter = 0` message and close the issue after that.

> And I'll probably disturb you in the near future again. ;)

You're more than welcome. It's always good to have more than one pair of eyes on the code.
