### ISSUE TITLE
Transmat normalization leads to incorrect adaptation (left-right HMMs)

### ISSUE THREAD

**Issue by michcio1234** [hmmlearn/hmmlearn#77]
Hello again

It seems to me that the problem related to #33 and #65 still exists. Transmat adaptation in left-right HMMs results in ergodic topology (zero probabilities are raised to non-zero).

in `base.py` we have:

    def _do_mstep(self, stats):
        (...)
        # The ``np.where`` calls guard against updating forbidden states
        # or transitions in e.g. a left-right HMM.
        (...)
        if 't' in self.params:
            transmat_ = self.transmat_prior - 1.0 + stats['trans']
            self.transmat_ = np.where(self.transmat_ == 0.0,
                                      self.transmat_, transmat_)
            ############################
            normalize(self.transmat_, axis=1)  # WE NORMALIZE AFTER CHECKING FOR ZEROS
            ############################

And in `utils.py` we have:
```
def normalize(a, axis=None):
    (...)
    ####################
    a += np.finfo(float).eps  # AND HERE WE LOOSE OUR "GUARD"
    ####################

    a_sum = a.sum(axis)
    if axis and a.ndim > 1:
        # Make sure we don't divide by zero.
        a_sum[a_sum == 0] = 1
        shape = list(a.shape)
        shape[axis] = 1
        a_sum.shape = shape

    a /= a_sum

    # TODO: should return nothing, since the operation is inplace.
    return a
```

**Comment by superbobry** [comment]
Thank you. Sometimes OK tests give a (misleading) feeling of correctness :)
