### ISSUE TITLE
Why you guys not do more work about the tutorial?

### ISSUE THREAD

**Issue by regzhuce** [hmmlearn/hmmlearn#79]
Excellent job!
BUT Your current tutorial tell very very little information about how to use it.
I have to read through the code to get the usage, what a headache!
Would you please just give more detail? That helps lots.
Thanks.

**Comment by superbobry** [comment]
Hi, it's true, the tutorial isn't very informative at the moment. Can you list the things you missed there?

**Comment by mimouncadosch** [comment]
Hi, thanks for taking input. 

Would you mind giving a sample matrix X that would go into the remodel.fit(X) method?

Thanks

**Comment by regzhuce** [comment]
For example, just as mimouncadosch mentioned, is there any sample for training data X?

To show more detail. If I have lots of sequences like:
[There is a cat]
[Smelly cat]
[Soft cat]
[Why does she go home]
...

Every line is a sequence, and every word is an observation.
Then, what steps should I take to do an unsupervised training?
And, what steps should I take to infer, what will be the observation after the sub-sequence [What's a pity]?

Thanks a lot.

**Comment by mimouncadosch** [comment]
Actually, I was able to figure out a sample matrix from their tutorial example with the stock prices.

The sample matrix _X_ is a numpy array with _n_ rows and 2 columns. The first column corresponds to the observation values, and the second column corresponds to the length of each observation. 

So for example if the states possible are {A, B, C} and your sequence is A, A, A, B, B, C, A, C, C then _X_ is:
A 3
B 2
C 1
A 1
C 2

@superbobry might want to confirm this though

**Comment by superbobry** [comment]
> The sample matrix X is a numpy array with n rows and 2 columns. The first column corresponds to the observation values, and the second column corresponds to the length of each observation.

X is a NumPy array (or an array like object) with `n_samples` rows and `n_features` columns. 

For the stock prices example `n_features` is indeed 2: 
* the first column contains the differences of the consecutive *close* values (described [here](parse_yahoo_historical)), and 
* the second column contains *volume* values.

It is possible to train an HMM over multiple sequences by passing a second argument `lengths` to the `.fit` or `.predict` methods. This is the format implemented in a similar [`seqlearn`](https://github.com/larsmans/seqlearn) library by @larsmans. 

I'll try to illustrate it with an example. Consider the following two 1D sequences

```
X1 = [1, 2, 0, 1, 1]
X2 = [42, 42]
```

To pass both of the to the `.fit` method we need to a) concatenate them into a single array and b) compute an array of lengths

```
X = np.append(X1, X2)
lengths = [len(X1), len(X2)]
```

Hope this clears things up a bit.

**Comment by superbobry** [comment]
> To show more detail. If I have lots of sequences like:
> [There is a cat]
> [Smelly cat]
> [Soft cat]
> [Why does she go home]
> ...
> 
> Every line is a sequence, and every word is an observation.
> Then, what steps should I take to do an unsupervised training? 

1. You need to transform sentences into numeric vectors using e.g. [`CountVectorizer`](http://scikit-learn.org/stable/modules/generated/sklearn.feature_extraction.text.CountVectorizer.html) from scikit-learn. 
2. Construct `X` and `lengths` as described in the previous comment and 
3. pass both to `MultinomialHMM.fit`. 

Of course you also need to decide on the number of components for an HMM, but for this it's hard to give a specific advice without more context.

**Comment by regzhuce** [comment]
OK. Got it, thanks.
But why not offer an API with a 2D array:
X1 = [1, 2, 0, 1, 1]
X2 = [42, 42]
X = [X1, X2] = [[1, 2, 0, 1, 1], [42, 42]]

It's more convenient.

Another question. Are there APIs for saving and loading model, from file?

**Comment by superbobry** [comment]
> But why not offer an API with a 2D array

Because it is incompatible with scikit-learn [`Pipeline`](http://scikit-learn.org/stable/modules/generated/sklearn.pipeline.Pipeline.html), see discussion in #29.

> Are there APIs for saving and loading model, from file?

No, but `pickle` should work.

**Comment by GaelVaroquaux** [comment]
> No, but pickle should work.

joblib.dump/joblib.save will be faster and more efficient.

**Comment by superbobry** [comment]
> joblib.dump/joblib.save will be faster and more efficient.

Good point. This also deserves a mention in the tutorial.
