### ISSUE TITLE
how to install the package

### ISSUE THREAD

**Issue by emigmo** [hmmlearn/hmmlearn#80]
When I try to install the hmmlearn 
 -->py.test --doctest-modules hmmlearn

ImportError: cannot import name check_array

then I don't know how to deal.

**Comment by superbobry** [comment]
Hi, 

I think you might be using an older version of scikit-learn, [`check_array`](http://scikit-learn.org/0.16/developers/utilities.html) was introduced in 0.16.

**Comment by tarlen5** [comment]
Hello,

I can confirm that this is the problem. I got the same error, but it was because I was using version `0.14.1` and when upgrading to the latest version (`0.17`), the problem was solved.

**Comment by superbobry** [comment]
I'll make the version requirements explicit in `setup.py`. Thank you for letting me know.
