### ISSUE TITLE
indexerror in plot_hmm_stock_analysis.py

### ISSUE THREAD

**Issue by PacoSpike** [hmmlearn/hmmlearn#84]
![lqssu7t oi f3p9 4 oo 1](https://cloud.githubusercontent.com/assets/16490664/12450296/c9c087f2-bfbd-11e5-828a-2b54a9b6f524.jpg)

**Comment by michcio1234** [comment]
What about #83?

**Comment by PacoSpike** [comment]
Thanks!

**Comment by PacoSpike** [comment]
i use 'pip' to install it, and the version was old.
