### ISSUE TITLE
OS X El Capitan - plot_hmm_stock_analysis.py - Issue

### ISSUE THREAD

**Issue by lettergram** [hmmlearn/hmmlearn#85]
I just wanted to share that the example plot_hmm_stock_analysis.py does not appear to work on OS X El Capitan. It's just a plotting issue, but figured I would submit an issue.

It's actually an issue with matplotlib: https://github.com/matplotlib/matplotlib/issues/1852

However, here is a solution, change the bottom lines from plot_hmm_stock_analysis.py:

    fig.tight_layout()                                                                                       
    fig.autofmt_xdate()                                                                                      
    fig.show()

To:

    plt.show()
    
At least, there is then something being displayed :)

Original Error:

    /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/matplotlib/tight_layout.py:225: UserWarning: tight_layout : falling back to Agg renderer 
    warnings.warn("tight_layout : falling back to Agg renderer")
     Traceback (most recent call last):
       File "plot_hmm_stock_analysis.py", line 91, in <module>
         fig.show()
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/matplotlib/figure.py", line 360, in show
    "created by pyplot.figure()." % err)
    AttributeError: 'FigureCanvasAgg' object has no attribute 'manager'
     Figure.show works only for figures managed by pyplot, normally created by pyplot.figure().

**Comment by superbobry** [comment]
Hi, Austin. Thank you for reporting this. I believe a fix (see PR #81) has already been submitted, so this'll be fixed in `master` as well soon.
