### ISSUE TITLE
How to find best Optima?

### ISSUE THREAD

**Issue by adywp** [hmmlearn/hmmlearn#86]
Hi all,

I have created a small Multinomial-HMM try-out:

```
from hmmlearn.hmm import MultinomialHMM

inp = [[0,1,2,3,4], [5,6,7,8,9], [5,6,7,8,9]]
model = MultinomialHMM(n_components=3, n_iter=1000).fit(inp,[len(inp)])

#print("model = ",model.emissionprob_)

test1 = [[0,1,2,3,4]]
lprob1= model.score(test1,[len(test1)])
print("logprob1 = ",lprob1)
test2 = [[5,6,7,8,9]]
lprob2= model.score(test2,[len(test2)])
print("logprob2 = ",lprob2)
test3 = [[0,1,2,3,9]]
lprob3= model.score(test3,[len(test3)])
print("logprob3 = ",lprob3)
```
the results over several execution:
```
logprob1 =  -6.30359599219
logprob2 =  -42.8713174117
logprob3 =  -7.40190037113
```
```
logprob1 =  -10.0939129778
logprob2 =  -41.6434051794
logprob3 =  -35.9943911389
```
```
logprob1 =  -8.95881612525
logprob2 =  -6.18622270857
logprob3 =  -44.0216323571
```
obviously the intended result would be something like the last one.

I have little knowledge on HMM detailed work, but I guess those difference results was caused by local optimas. Please correct me if I am wrong.

My question is can somebody suggest me how should I proceed to find the best optima? my real modelling problem is using bigger data set (lot of sequence), so repeated modelling is quite ‘expensive’.
Or did I implement the problem above wrongly?

Thank you in advance…

**Comment by superbobry** [comment]
Hi,

> I have little knowledge on HMM detailed work, but I guess those difference results was caused by local optimas. Please correct me if I am wrong.

EM is indeed susceptible to local optima, but I think in your case the behaviour of the algorithm is better explained by the lack of data. Starting from initial random probabilities EM simply doesn't have enough data to move away from it. 

> My question is can somebody suggest me how should I proceed to find the best optima?

Unfortunately, I'm not aware of a good solution for the case of unsupervised HMMs. A more practical version of the usual "run it N times" trick is to limit the number of iterations for each of the randomized runs. This allows you to try a lot of starting points and then pick current best one and proceed until convergence. 

For instance you could do the three runs above with `n_iter=100` and then fit the best scoring model with `n_iter=1000`. 

IIRC this modificatioin is called small EM but I don't have a reference atm.

**Comment by adywp** [comment]
Hi Sergei, thank you for your information,

In respond to your reply, I modified the script a bit:
```
from hmmlearn.hmm import MultinomialHMM

#inp = [[0,1,2,3,4],[5,6,7,8,9],[5,6,7,8,9]]
inp = [[0,1,2,3,4]*100 + [5,6,7,8,9]*200]
model = MultinomialHMM(n_components=2, n_iter=1000).fit(inp,[len(inp)])

#print("model = ",model.emissionprob_)

test1 = [[0,1,2,3,4]]
lprob1= model.score(test1,[len(test1)])
print("logprob1 = ",lprob1)
test2 = [[5,6,7,8,9]]
lprob2= model.score(test2,[len(test2)])
print("logprob2 = ",lprob2)
test3 = [[0,1,2,3,9]]
lprob3= model.score(test3,[len(test3)])
print("logprob3 = ",lprob3)
```
results of first three attempts:
```
logprob1 =  -13.0852563936
logprob2 =  -11.2105063632
logprob3 =  -12.3922054095
```
```
logprob1 =  -11.6787157115
logprob2 =  -8.2129782912
logprob3 =  -10.9855685309
```
```
logprob1 =  -10.9838995664
logprob2 =  -27.2778606427
logprob3 =  -10.2907523858
```
Are there some 'rule of thumb' on how many training data should I prepare?

> This allows you to try a lot of starting points and then pick current best one and proceed until convergence.

Is it sufficient to check `model.monitor_.converged` to check whether the model created has converged?
Some of the model I created only use `n_iter=2` and `tol=0.001` and `print("System converged?",model.monitor_.converged)` returns `True`

Thank you for your kind response

**Comment by superbobry** [comment]
I think I have another explanation for the behaviour you observed. 

The data in `inp` clearly comes from a unimodal distribution. The HMM on the other hand is bimodal (`n_components` is 2). As a result, the estimated emission probabilities are distributed between the two components, where if `emissionprob_[0, f]` has a relatively high probability then `emissionprob_[1, f]` tends to be zero. Again this process heavily depends on the initialization which is random.

Here's a couple of runs:
```ipython
In [36]: inp = [[0,1]*100 + [2]*200]

In [37]: MultinomialHMM(n_components=2, n_iter=1000).fit(inp).emissionprob_
Out[37]:
array([[  5.00000001e-01,   4.99999999e-01,   2.96075281e-10],
       [  2.93811078e-22,   2.34890265e-09,   9.99999998e-01]])

In [38]: MultinomialHMM(n_components=2, n_iter=1000).fit(inp).emissionprob_
Out[38]:
array([[  7.24880673e-23,   1.58055473e-09,   9.99999998e-01],
       [  5.00000001e-01,   4.99999999e-01,   2.11231690e-10]])
```

If you try to fit a bimodal HMM to a bimodal sample (e.g. a sample from a known HMM) things tend to get a bit more stable:
```ipython
In [56]: model = MultinomialHMM(n_components=2, n_iter=1000)

In [57]: model.startprob_ = np.full(2, .5)

In [58]: model.transmat_ = np.full((2, 2), .5)

In [59]: model.emissionprob_ = np.array([[.5, .3, .2], [.1, .85, .05]])

In [60]: inp, _Z = model.sample(1000)

In [61]: MultinomialHMM(n_components=2, n_iter=1000).fit(inp).emissionprob_
Out[61]:
array([[ 0.24883943,  0.64340111,  0.10775947],
       [ 0.38345166,  0.50429809,  0.11225024]])

In [62]: MultinomialHMM(n_components=2, n_iter=1000).fit(inp).emissionprob_
Out[62]:
array([[ 0.37920094,  0.49343163,  0.12736743],
       [ 0.25473053,  0.65210614,  0.09316333]])
```

> Are there some 'rule of thumb' on how many training data should I prepare?

I don't think I know any, but in general the more data you have the better.

> Is it sufficient to check `model.monitor_.converged` to check whether the model created has converged?

It should be sufficient, yes. However, we implement a slightly abused notion of convergence here. `converged` is `True` if the maximum number of iterations is reached **or** the increase in log-likelihood is below `tol`.

You can check that the convergence was due to the stabilized log-likelihood using the `monitor_.history` attribute:

```python
truly_converged = monitor.history[1] - monitor.history[0] < monitor.tol
```

**Comment by adywp** [comment]
Thank you Sergei
