### ISSUE TITLE
Docstring of GaussianHMM's constructor is missing a few arguments

### ISSUE THREAD

**Issue by anntzer** [hmmlearn/hmmlearn#88]
... namely covars_prior, means_weight, covars_weight.

In an unrelated question, any chance for a future release of 0.2.0?  There's been quite a few API changes since 0.1.1.

**Comment by superbobry** [comment]
Yeah, this is already covered in #58. 

0.2.0 is almost there, I plan to fix #58 and #78 and then do a release.
