### ISSUE TITLE
[TEST]: hmmlearn/hmm.py:609: TypeError

### ISSUE THREAD

**Issue by aubreyli** [hmmlearn/hmmlearn#90]
running test encountered 12 failures. The errors are exactly the same.
$py.test --doctest-modules hmmlearn

I snipped one below:

self = GMMHMM(algorithm='viterbi', covariance_type='diag', covars_prior=1.0,
    init...ate=None, startprob_prior=1.0, tol=0.01, transmat_prior=1.0,
    verbose=False)
..........
>                   cvnorm.shape = shape
E                   TypeError: 'numpy.float64' object cannot be interpreted as an index

hmmlearn/hmm.py:609: TypeError

**Comment by superbobry** [comment]
Hi there, this looks interesting. Are you using a 32bit OS by any chance?

**Comment by aubreyli** [comment]
I'm using 64bit debian

$ uname -m
x86_64

**Comment by aubreyli** [comment]
The default return array of np.ones() is numpy.float64. 
The following patch made all of the tests passed, not sure if the semantic is correct here though

diff --git a/hmmlearn/hmm.py b/hmmlearn/hmm.py
index 00bcf33..d39c618 100644
--- a/hmmlearn/hmm.py
+++ b/hmmlearn/hmm.py
@@ -604,7 +604,7 @@ class GMMHMM(_BaseHMM):
                     stats['covars'][state] += tmp_gmm.covars_ * norm.sum()
                 else:
                     cvnorm = np.copy(norm)
-                    shape = np.ones(tmp_gmm.covars_.ndim)
+                    shape = np.ones(tmp_gmm.covars_.ndim, dtype=np.int)
                     shape[0] = np.shape(tmp_gmm.covars_)[0]
                     cvnorm.shape = shape
                     stats['covars'][state] += (tmp_gmm.covars_
@@ -630,7 +630,7 @@ class GMMHMM(_BaseHMM):
                                  / norm.sum())
                 else:
                     cvnorm = np.copy(norm)
-                    shape = np.ones(g.covars_.ndim)
+                    shape = np.ones(g.covars_.ndim, dtype=np.int)
                     shape[0] = np.shape(g.covars_)[0]
                     cvnorm.shape = shape
                     if g.covariance_type in ['spherical', 'diag']:

**Comment by heyanyun** [comment]
can it been used in w7  64 and python 2.7 32 ?

**Comment by superbobry** [comment]
@aubreyli thanks, I'll incorporate your patch as soon as I get the `GMMHMM` working.

> can it been used in w7 64 and python 2.7 32 ?

Yep, I don't see why not.

**Comment by aubreyli** [comment]
Thanks @superbobry , I made a pull request to make the patch merge easier for you.

**Comment by superbobry** [comment]
Cool, I'll close the issue then.
