### ISSUE TITLE
the predict reault what can do?

### ISSUE THREAD

**Issue by heyanyun** [hmmlearn/hmmlearn#92]
the result from sample plot_hmm_sampling.py file
hidden_states can"t help low buy and high sell

```
diff hidden_states
-0.01 1
0.02 1
0.04 1
0.04 3
0.03 3
...
```

**Comment by superbobry** [comment]
Hi, can you please clarify your question? `plot_hmm_sampling.py` gives an example of how to sample from an HMM, not much else.

Also, please do not add long outputs directly to the issue, upload these to Gist or pastebin instead and provide a link.
