### ISSUE TITLE
 probability would approach to 0 after several EM iterations

### ISSUE THREAD

**Issue by PacoSpike** [hmmlearn/hmmlearn#93]
When I used GaussianHMM().fit() to train HMM, there is a RuntimeWarning: divide by zero encountered in log. Then I found  that the start probability would approach to 0 after several EM iterations. 
My question is how to avoid probability approaching to 0 ?

**Comment by aubreyli** [comment]
@PacoSpike , which version of hmmlearn are you using?

**Comment by PacoSpike** [comment]
The latest, 0.2

**Comment by PacoSpike** [comment]
@aubreyli

**Comment by aubreyli** [comment]
@PacoSpike , I previously encountered divide by zero error when I was using 0.1.1.
The problem is gone after I upgrade to latest repo.

So, I think it should be helpful if you place your data onto somewhere and provide a link here.

**Comment by superbobry** [comment]
Zero starting probabilities can happen if you have few training sequences or the most likely starting state for each sequence is the same.

**Comment by PacoSpike** [comment]
@aubreyli This is a sample.
[sample.txt](https://github.com/hmmlearn/hmmlearn/files/139453/sample.txt)

**Comment by aubreyli** [comment]
@PacoSpike , I didn't encounter divide by zero error. please check the attachment.

[sample_log.txt](https://github.com/hmmlearn/hmmlearn/files/139526/sample_log.txt)
![sample](https://cloud.githubusercontent.com/assets/7411812/13201792/f49254a4-d8ba-11e5-9437-f710156f76b6.JPG)

**Comment by PacoSpike** [comment]
@aubreyli Thank you very much. I have examined the sample and  your result is the same as mine. However, the warning is real. So I repeat my data and select 2 new samples. When I use the 2 samples to train HMM
[new_sample_2.txt](https://github.com/hmmlearn/hmmlearn/files/139583/new_sample_2.txt)
[new_sample_1.txt](https://github.com/hmmlearn/hmmlearn/files/139584/new_sample_1.txt)

, I notice the warning occurs randomly.
Thanks again.

**Comment by aubreyli** [comment]
@PacoSpike , I can replicate the warning by new_sample_1.txt now.

I believe the warning occurs randomly, which is because Clustering kmeans algorithm is initialized randomly.

For a temporary workaround and a quick check, can you please do the following change in hmm.py?

Change
`kmeans = cluster.KMeans(n_clusters=self.n_components)`

To
`kmeans = cluster.KMeans(n_clusters=self.n_components, random_state = 1)`

Don't forget to install the change into python lib in order to make it take effect.

This is an expected behavior in my mind. we should pass random_state parameter into clustering KMeans initialization, so that we can tune random_state to avoid this case.

**Comment by PacoSpike** [comment]
@aubreyli Thank you for your help. I will assign random_state parameter..

**Comment by aubreyli** [comment]
@superbobry , does it make sense to make a patch to pass model random_state parameter into the base mode.fit method to initialize Clustering KMeans method? instead of letting Kmeans method use random_state = None forever?

**Comment by PacoSpike** [comment]
@aubreyli I have changed the code,but there is still a warning.I think there is a possible case: because of PYTHON, sum of matrix is not equal to 1.
[new_sample_3.txt](https://github.com/hmmlearn/hmmlearn/files/139701/new_sample_3.txt)

**Comment by aubreyli** [comment]
@PacoSpike , please report as a different issue if the warning is different and attach the detailed log.

**Comment by superbobry** [comment]
> does it make sense to make a patch to pass model random_state parameter into the base mode.fit method to initialize Clustering KMeans method? instead of letting Kmeans method use random_state = None forever?

Yes, this makes sense. Please go ahead with the patch.

**Comment by PacoSpike** [comment]
@aubreyli The issue is the same one.The possible case I mentioned is one possible reason for this issue.

**Comment by aubreyli** [comment]
@PacoSpike , I can't replicate the warning with new_sample_3.txt. Can you please turn verbose on for both GaussianHMM and Kmeans call and attach your log?

As I explained above, if one encounters an error, you may need to change another random_state.

**Comment by aubreyli** [comment]
@PacoSpike , an alternative way is trying to capture RuntimeWarning and run model fit() again.
code example below:

`import warnings`
`warnings.filterwarnings("error")`

`n_try = 10`
`for i in range(n_timesout):`
`    try:`
`        model.fit(X)`
`    except RuntimeWarning:`
`        print("\n\n\nI got a warning, try to fit model again\n\n\n")`
`    else:`
`        break`

you can increase 'n_try' if 10 is not enough in your case.
Hope this helps.

**Comment by naghmehghanooni** [comment]
Hello,

I wanted to report that I have this problem too. I have a lot of sequences and I want to cluster them using hmmlearn but after fitting the model sometimes I got the RuntimeWarning: divide by zero encountered in log.
My start probability is the same for all the states and sometimes my sequences are not that large. 
I am using version 0.2.1 and I also changed random_state = 1 instead of random_state = self.random_state. But the problem still occurs. 
Does anyone has any other idea of what I could do to fix it? 

Thank you very much in advance,

**Comment by superbobry** [comment]
Do you also experience the issue with zero starting probabilities?

Could you please attach full warning messages including the file name and line number?

**Comment by naghmehghanooni** [comment]
No, I don't have issues with zero starting probabilities. 
My starting probability matrix is this: 
startProb = [1.0/70] * 70
I have 70 states and all have equal probability of 1/70. 
And in the GaussianHMM I give starting probability to params and init_params. 
But when I fit the data I get this warning: 

/usr/local/lib/python2.7/dist-packages/hmmlearn-0.2.0-py2.7-linux-x86_64.egg/hmmlearn/base.py:459: RuntimeWarning: divide by zero encountered in log
/usr/local/lib/python2.7/dist-packages/hmmlearn-0.2.0-py2.7-linux-x86_64.egg/hmmlearn/base.py:468: RuntimeWarning: divide by zero encountered in log
/usr/local/lib/python2.7/dist-packages/hmmlearn-0.2.0-py2.7-linux-x86_64.egg/hmmlearn/base.py:451: RuntimeWarning: divide by zero encountered in log

**Comment by aubreyli** [comment]
@naghmehghanooni , I guess the runtime warning at base.py:459 means during the model fitting, you have zero starting probabilities as well. Is it possible to attach your sample data?
