### ISSUE TITLE
Predicting performance of baseball players

### ISSUE THREAD

**Issue by Randyjp** [hmmlearn/hmmlearn#95]
This is a question, not any issue. I'm new dealing with HMM and I'm still confused with the predictive power capabilities of the algorithm and I would really appreciate if someone can point me in the right direction.

I have the statistics describing the performance of baseball players for the last 5 seasons(2011-2015), The data consists of the name of the player(string), season(only year), and several other columns with continuous values. 

Is it possible with this algorithm to model the data and predict a players performance in the coming season? In other word predict those continuous values mentioned before .If the answer is yes I would appreciate any material that could help me understand  this subject.

**Comment by superbobry** [comment]
Hi Randy,

There're at least two ways to approach this: theoretical (or rather rhetorical) and practical. From the theoretical point of view HMMs are parameteric models, in a sense that they make very specific assumptions about the way data is distributed:

* the distribution of the observations at time `t` is completely determined by the (unobserved) hidden state at time `t`,
* the sequence of hidden states forms a first-order Markov chain. 

The former also implies that you have to fix the family of distributions before doing inference. For instance, if you have reasons to believe that the continuous variables are normally distributed you need a `GaussianHMM`. Any other family (e.g. Gamma or Beta distributions) would give rise to a different HMM. Of course none of these assumptions hold perfectly for real-world data, so if you aren't sure, just go with Gaussians. 

This brings us to the practical approach, which is simply to go ahead and try the available models on your data. In general I wouldn't expect to much from HMMs, but they're still worth a try.

Another thing you'll probably need to decide on is the "meaning" of hidden states. I think for your type of problem you could go with two states: "good" and "poor" performance. Alternatively, you can introduce a number of intermediate states to differentiation between the varieties of the two. 

Hope this helps.

**Comment by Randyjp** [comment]
Thank you very much, it sure helps a lot!
